.\" Copyright (c) 2007 Joseph Koshy.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" This software is provided by Joseph Koshy ``as is'' and
.\" any express or implied warranties, including, but not limited to, the
.\" implied warranties of merchantability and fitness for a particular purpose
.\" are disclaimed.  in no event shall Joseph Koshy be liable
.\" for any direct, indirect, incidental, special, exemplary, or consequential
.\" damages (including, but not limited to, procurement of substitute goods
.\" or services; loss of use, data, or profits; or business interruption)
.\" however caused and on any theory of liability, whether in contract, strict
.\" liability, or tort (including negligence or otherwise) arising in any way
.\" out of the use of this software, even if advised of the possibility of
.\" such damage.
.\"
.\" FRDP path ./usr.bin/ar/ar.1
.\" FRDP githash fa9896e082a1046ff4fbc75fcba4d18d1f2efc19
.\" FRDP hash256 fb5ffffe7f5140c6d67ab920cd77bec28da263a1a3bf3f7700f189aa73a9156a
.Dd 29 декабря 2021
.Dt AR 1
.Os
.Sh ИМЯ
.Nm ar ,
.Nm ranlib
.Nd управление архивами
.Sh СИНТАКСИС
.Nm
.Fl d
.Op Fl T
.Op Fl f
.Op Fl j
.Op Fl v
.Op Fl z
.Ar архив
.Ar
.Nm
.Fl m
.Op Fl T
.Op Fl a Ar позиция-после
.Op Fl b Ar позиция-перед
.Op Fl f
.Op Fl i Ar позиция-перед
.Op Fl j
.Op Fl s | Fl S
.Op Fl z
.Ar архив
.Ar
.Nm
.Fl p
.Op Fl T
.Op Fl f
.Op Fl v
.Ar архив
.Op Ar
.Nm
.Fl q
.Op Fl T
.Op Fl c
.Op Fl D
.Op Fl f
.Op Fl s | Fl S
.Op Fl U
.Op Fl v
.Op Fl z
.Ar архив
.Ar
.Nm
.Fl r
.Op Fl T
.Op Fl a Ar позиция-после
.Op Fl b Ar позиция-перед
.Op Fl c
.Op Fl D
.Op Fl f
.Op Fl i Ar позиция-перед
.Op Fl j
.Op Fl s | Fl S
.Op Fl u
.Op Fl U
.Op Fl v
.Op Fl z
.Ar архив
.Ar
.Nm
.Fl s
.Op Fl j
.Op Fl z
.Ar архив
.Nm
.Fl t
.Op Fl f
.Op Fl T
.Op Fl v
.Ar архив
.Op Ar
.Nm
.Fl x
.Op Fl C
.Op Fl T
.Op Fl f
.Op Fl o
.Op Fl u
.Op Fl v
.Ar архив
.Op Ar
.Nm
.Fl M
.Nm ranlib
.Op Fl D
.Op Fl U
.Ar архив ...
.Sh ОПИСАНИЕ
Утилита
.Nm
создает и обслуживает группы файлов, объединенных в
архив.
После создания архива в него можно добавлять новые файлы, а
существующие файлы можно извлекать, удалять или заменять.
.Pp
Файлы именуются в архиве по последнему компоненту их имени,
поэтому если файл, на который ссылается путь, содержащий
.Dq / ,
архивируется, он будет назван последним компонентом пути.
Аналогично, при сопоставлении путей, перечисленных в командной строке, с
именами файлов, хранящимися в архиве, будет сравниваться только последний компонент
пути.
.Pp
Обычное использование
.Nm
— это создание и обслуживание библиотек, подходящих для использования
с редактором связей
.Xr ld 1 ,
хотя она не ограничивается этой целью.
Утилита
.Nm
может создавать и управлять таблицей символов архива (см.
.Xr ar 5 ),
используемой для ускорения операций редактирования связей.
Если таблица символов присутствует в архиве, она будет
поддерживаться в актуальном состоянии последующими операциями над архивом.
.Pp
Утилита
.Nm ranlib
используется для добавления таблицы символов архива
в существующий архив.
.Sh ПАРАМЕТРЫ
Утилита
.Nm
поддерживает следующие параметры:
.Bl -tag -width indent
.It Fl a Ar элемент-после
При использовании с параметром
.Fl m
этот параметр указывает, что элементы архива, указанные аргументами
.Ar ,
перемещаются после элемента архива, указанного аргументом
.Ar элемент-после .
При использовании с параметром
.Fl r
этот параметр указывает, что файлы, указанные аргументами
.Ar ,
добавляются после элемента архива, указанного аргументом
.Ar элемент-после .
.It Fl b Ar элемент-перед
При использовании с параметром
.Fl m
этот параметр указывает, что элементы архива, указанные аргументами
.Ar ,
перемещаются перед элементом архива, указанным аргументом
.Ar элемент-перед .
При использовании с параметром
.Fl r
этот параметр указывает, что файлы, указанные аргументами
.Ar ,
добавляются перед элементом архива, указанным аргументом
.Ar элемент-перед .
.It Fl c
Подавлять информационное сообщение, выводимое при создании нового архива с помощью параметров
.Fl r
и
.Fl q .
.It Fl C
Предотвращать замену одноименных файлов
в файловой системе при извлечении.
.It Fl d
Удалить элементы, указанные аргументами
.Ar ,
из архива, указанного аргументом
.Ar архив .
Таблица символов архива, если она присутствует, обновляется в соответствии с
новым содержимым архива.
.It Fl D
При использовании в комбинации с параметрами
.Fl r
или
.Fl q ,
с параметром
.Fl s
без других опций или при вызове как
.Nm ranlib ,
вставлять нули вместо реальных значений mtime, uid и gid
и 0644 вместо режима файла из элементов, указанных аргументами
.Ar .
Это гарантирует, что контрольные суммы результирующих архивов воспроизводимы,
когда содержимое элементов идентично.
Этот параметр включен по умолчанию.
Если несколько параметров
.Fl D
и
.Fl U
указаны в командной строке, последний имеет приоритет.
.It Fl f
Использовать только первые пятнадцать символов имени элемента архива или
аргумента имени файла в командной строке при именовании элементов архива.
.It Fl i Ar элемент-перед
Синоним параметра
.Fl b .
.It Fl j
Этот параметр принимается, но игнорируется.
.It Fl l
Этот параметр принимается для совместимости с GNU
.Xr ar 1 ,
но игнорируется.
.It Fl m
Переместить элементы архива, указанные аргументами
.Ar ,
внутри архива.
Если позиция была указана одним из параметров
.Fl a ,
.Fl b
или
.Fl i ,
элементы перемещаются до или после указанной
позиции.
Если позиция не указана, указанные элементы перемещаются
в конец архива.
Если в архиве есть таблица символов, она обновляется в соответствии с
новым содержимым архива.
.It Fl M
Читать и выполнять команды библиотекаря MRI из стандартного ввода.
Команды, понимаемые утилитой
.Nm ,
описаны в разделе
.It Fl o
Сохранять исходные времена модификации элементов при их извлечении.
.It Fl p
Записать содержимое указанных элементов архива, указанных аргументами
.Ar ,
в стандартный вывод.
Если элементы не указаны, содержимое всех файлов в
архиве записывается в порядке их появления в архиве.
.It Fl q
Добавить файлы, указанные аргументами
.Ar ,
в архив, указанный аргументом
.Ar архив ,
без проверки, существуют ли файлы уже в архиве.
Таблица символов архива будет обновлена по мере необходимости.
Если файл, указанный аргументом
.Ar архив ,
еще не существует, будет создан новый архив.
.It Fl r
Заменить (добавить) файлы, указанные аргументами
.Ar ,
в архиве, указанном аргументом
.Ar архив ,
создав архив при необходимости.
Замена существующих элементов не изменит порядок элементов в
архиве.
Если файл, указанный в аргументах
.Ar ,
не существует, существующие элементы в архиве, соответствующие этому
имени, не изменяются.
Новые файлы добавляются в конец архива, если не указан один из
параметров позиционирования
.Fl a ,
.Fl b
или
.Fl i .
Таблица символов архива, если она существует, обновляется в соответствии с
новым состоянием архива.
.It Fl s
Добавить таблицу символов архива (см.
.Xr ar 5 )
в архив, указанный аргументом
.Ar архив .
Вызов
.Nm
с параметром
.Fl s
сам по себе эквивалентен вызову
.Nm ranlib .
.It Fl S
Не генерировать таблицу символов архива.
.It Fl t
Вывести список файлов, указанных аргументами
.Ar ,
в порядке их появления в архиве, по одному в строке.
Если файлы не указаны, выводятся все файлы в архиве.
.It Fl T
Устаревший алиас для
.Fl f .
В других реализациях
.Nm ,
.Fl T
.It Fl u
Условно обновить архив или извлечь элементы.
При использовании с параметром
.Fl r
файлы, указанные аргументами
.Ar ,
будут заменены в архиве, если они новее их
архивных версий.
При использовании с параметром
.Fl x
элементы, указанные аргументами
.Ar ,
будут извлечены только если они новее соответствующих
файлов в файловой системе.
.It Fl U
При использовании в комбинации с параметрами
.Fl r
или
.Fl q ,
вставлять реальные значения mtime, uid и gid, а также режима файла
из элементов, указанных аргументами
.Ar .
Если несколько параметров
.Fl D
и
.Fl U
указаны в командной строке, последний имеет приоритет.
.It Fl v
Предоставлять подробный вывод.
При использовании с параметрами
.Fl d ,
.Fl m ,
.Fl q
или
.Fl x ,
.Nm
дает описание изменения архива по файлам, которое состоит из трех полей,
разделенных пробелами:
буква параметра, дефис
и имя файла.
При использовании с параметром
.Fl r ,
.Nm
отображает описание, как указано выше, но начальная буква —
.Dq a ,
если файл добавлен в архив, или
.Dq r ,
если файл заменяет файл, уже находящийся в архиве.
При использовании с параметром
.Fl p
имя файла, заключенное в символы
.Dq <
и
.Dq > ,
записывается в стандартный вывод, предваренное одним символом новой строки
и за которым следуют два символа новой строки.
Содержимое указанного файла следует за именем файла.
При использовании с параметром
.Fl t ,
.Nm
отображает восемь полей, разделенных пробелами:
права доступа к файлу, как отображаемые
.Xr strmode 3 ,
десятичные идентификаторы пользователя и группы, разделенные косой чертой (
.Dq / Ns ) ,
размер файла в байтах, время модификации файла в формате
.Xr strftime 3
и имя файла.
.It Fl V
Вывести строку версии и выйти.
.It Fl x
Извлечь элементы архива, указанные аргументами
.Ar ,
в текущий каталог.
Если элементы не указаны, извлекаются все элементы архива.
Если файл, соответствующий извлеченному элементу, не существует, он
будет создан.
Если файл, соответствующий извлеченному элементу, существует, его владелец
и группа не будут изменены, в то время как его содержимое будет перезаписано,
а его разрешения будут установлены в соответствии с архивом.
Время доступа и модификации файла будет соответствовать времени
извлечения, если не указан параметр
.Fl o .
.It Fl z
Этот параметр принимается, но игнорируется.
.El
Если указан параметр
.Fl M ,
утилита
.Nm
будет читать и выполнять команды из своего стандартного ввода.
Если стандартный ввод является терминалом, утилита
.Nm
будет отображать приглашение
перед чтением строки и продолжит работу даже при возникновении ошибок.
Если стандартный ввод не является терминалом, утилита
.Nm
не будет отображать приглашение и завершит выполнение при
возникновении ошибки.
.Pp
Каждая входная строка содержит одну команду.
Слова во входной строке разделяются символами пробела.
Первое слово строки — это команда, остальные слова —
аргументы команды.
Слово команды может быть указано в любом регистре.
Аргументы могут разделяться запятыми или пробелами.
.Pp
Пустые строки разрешены и игнорируются.
Длинные строки продолжаются путем их завершения символом
.Dq Li + .
.Pp
Символы
.Dq Li *
и
начинают комментарий.
Комментарии продолжаются до конца строки.
.Pp
При выполнении скрипта библиотекаря MRI утилита
.Nm
работает с временной копией архива.
Изменения в копии сохраняются с помощью команды
.Ic save .
.Pp
Команды, понимаемые утилитой
.Nm :
.Bl -tag -width indent
.It Ic addlib Ar архив | Ic addlib Ar архив Pq Ar элемент Oo Li , Ar элемент Oc Ns ...
Добавить содержимое архива с именем, указанным аргументом
.Ar архив ,
в текущий архив.
Если указаны конкретные элементы с помощью аргументов
.Ar элемент ,
то эти элементы добавляются в текущий архив.
Если элементы не указаны, все содержимое архива
добавляется в текущий архив.
.It Ic addmod Ar элемент Oo Li , Ar элемент Oc Ns ...
Добавить файлы с именами, указанными аргументами
.Ar элемент ,
в текущий архив.
.It Ic clear
Отбросить все содержимое текущего архива.
.It Ic create Ar архив
Создать новый архив с именем, указанным аргументом
.Ar архив ,
и сделать его текущим архивом.
Если именованный архив уже существует, он будет перезаписан
при выполнении команды
.Ic save .
.It Ic delete Ar модуль Oo Li , Ar элемент Oc Ns ...
Удалить модули с именами, указанными аргументами
.Ar элемент ,
из текущего архива.
.It Ic directory Ar архив Po Ar элемент Oo Li , Ar элемент Oc Ns ... Pc Op Ar выходной-файл
Вывести список каждого именованного модуля в архиве.
Формат вывода зависит от настройки подробности, установленной с помощью
команды
.Ic verbose .
Вывод отправляется в стандартный вывод или в файл, указанный аргументом
.Ar выходной-файл .
.It Ic end
Успешно выйти из утилиты
.Nm .
Любые несохраненные изменения текущего архива будут отброшены.
.It Ic extract Ar элемент Oo Li , Ar элемент Oc Ns ...
Извлечь элементы с именами, указанными аргументами
.Ar элемент ,
из текущего архива.
.It Ic list
Отобразить содержимое текущего архива в подробном стиле.
.It Ic open Ar архив
Открыть архив с именем, указанным аргументом
.Ar архив ,
и сделать его текущим архивом.
.It Ic replace Ar элемент Oo Li , Ar элемент Oc Ns ...
Заменить именованные элементы в текущем архиве файлами, указанными
аргументами
.Ar элемент .
Файлы должны присутствовать в текущем каталоге, а именованные
модули уже должны существовать в текущем архиве.
.It Ic save
Применить все изменения к текущему архиву.
.It Ic verbose
Переключить подробность вывода команды
.Ic directory .
.El
.Sh ПРИМЕРЫ
Чтобы создать новый архив
.Pa ex.a ,
содержащий три файла
.Pa ex1.o ,
.Pa ex2.o
и
.Pa ex3.o ,
используйте:
.Pp
Чтобы добавить таблицу символов архива в существующий архив
.Pa ex.a ,
используйте:
.Pp
Чтобы удалить файл
.Pa ex1.o
из архива
.Pa ex.a ,
используйте:
.Pp
Чтобы подробно вывести содержимое архива
.Pa ex.a ,
используйте:
.Pp
Чтобы создать новый архив
.Pa ex.a ,
содержащий файлы
.Pa ex1.o
и
.Pa ex2.o ,
используя команды библиотекаря MRI, используйте следующий скрипт:
.Bd -literal -offset indent
create ex.a		 * указать выходной архив
addmod ex1.o ex2.o	 * добавить модули
save			 * сохранить ожидающие изменения
end			 * выйти из утилиты
.Ed
.Sh ДИАГНОСТИКА
.Ex -std
.Sh СМ. ТАКЖЕ
.Xr ld 1 ,
.Xr archive 3 ,
.Xr elf 3 ,
.Xr strftime 3 ,
.Xr strmode 3 ,
.Xr ar 5
.Sh СООТВЕТСТВИЕ СТАНДАРТАМ
Считается, что поддержка утилитой
.Nm
параметров
.Fl a ,
.Fl b ,
.Fl c ,
.Fl i ,
.Fl m ,
.Fl p ,
.Fl q ,
.Fl r ,
.Fl s ,
.Fl t ,
.Fl u ,
.Fl v ,
.Fl C
и
.Fl T
соответствует
.St -p1003.2 .
.Sh ИСТОРИЯ
Команда
.Nm
впервые появилась в AT&T UNIX Version 1.
В
.Fx 8.0 ,
.An Кай Ван Aq Mt kaiw@FreeBSD.org
перереализовал
.Nm
и
.Nm ranlib
с использованием
.Lb libarchive
и
.Lb libelf .
