.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" Copyright (c) 2003-2007 Tim Kientzle
.\" Copyright (c) 2017 Martin Matuska
.\" All rights reserved.
.\"
.\" FRDP path ./contrib/libarchive/tar/bsdtar.1
.\" FRDP githash 2e113ef82465598b8c26e0ca415fbe90677fbd47
.\" FRDP hash256 afb9681646f7691480b2d265859daf8f38d1c121121ed6bc126a5a37528af95c
.Dd April 23, 2024
.Dt TAR 1
.Os
.Sh ИМЯ
.Nm tar
.Nd работа с архивами на магнитных лентах
.Sh СИНТАКСИС
.Nm
.Op Ar объединённые-флаги Ao аргументы Ac
.Op Ao Ar файл Ac | Ao Ar шаблон Ac ...
.Nm
.Brq Fl c
.Op Ar опции
.Op Ar файлы | Ar каталоги
.Nm
.Brq Fl r | Fl u
.Fl f Ar архив-файл
.Op Ar опции
.Op Ar файлы | Ar каталоги
.Nm
.Brq Fl t | Fl x
.Op Ar опции
.Op Ar шаблоны
.Sh ОПИСАНИЕ
.Nm
создаёт и обрабатывает потоковые архивные файлы.
Эта реализация может извлекать из архивов tar, pax, cpio, zip, jar, ar, xar,
rar, rpm, 7-zip и образов CDROM ISO 9660, а также создавать архивы tar, pax,
cpio, ar, zip, 7-zip и shar.
.Pp
Первая форма синтаксиса показывает
.Dq объединённое
слово опций.
Это использование предоставлено для совместимости с историческими реализациями.
Подробности см.
.Sx СОВМЕСТИМОСТЬ
ниже.
.Pp
Другие формы синтаксиса показывают предпочтительное использование.
Первая опция для
.Nm
это индикатор режима из следующего списка:
.Pp
.Bl -tag -compact -width indent
.It Fl c
Создать новый архив, содержащий указанные элементы.
Длинная форма опции:
.Fl Fl create .
.It Fl r
Как
.Fl c ,
но новые записи добавляются в архив.
Обратите внимание, что это работает только с несжатыми архивами, хранящимися в обычных файлах.
Опция
.Fl f
обязательна.
Длинная форма опции:
.Fl Fl append .
.It Fl t
Вывести список содержимого архива на стандартный вывод.
Длинная форма опции:
.Fl Fl list .
.It Fl u
Как
.Fl r ,
но новые записи добавляются только если их дата модификации
новее соответствующей записи в архиве.
Обратите внимание, что это работает только с несжатыми архивами, хранящимися в обычных файлах.
Опция
.Fl f
обязательна.
Длинная форма:
.Fl Fl update .
.It Fl x
Извлечь на диск из архива.
Если файл с тем же именем появляется в архиве более одного раза,
каждая копия будет извлечена, причём поздние копии перезаписывают (заменяют)
более ранние копии.
Длинная форма опции:
.Fl Fl extract .
.El
.Pp
В режимах
.Fl c ,
.Fl r ,
или
.Fl u ,
каждый указанный файл или каталог добавляется в
архив в порядке, указанном в командной строке.
По умолчанию содержимое каждого каталога также архивируется.
.Pp
В режиме извлечения или списка вся командная строка
читается и анализируется до открытия архива.
Пути или шаблоны в командной строке указывают,
какие элементы в архиве должны быть обработаны.
Шаблоны — это шаблоны подстановки в стиле shell, как
документировано в
.Xr tcsh 1 .
.Sh ОПЦИИ
Если не указано иное, опции применимы во
всех режимах работы.
.Bl -tag -width indent
.It Cm @ Ns Pa архив
(только режимы c и r)
Указанный архив открывается, и записи
из него будут добавлены к текущему архиву.
В качестве простого примера,
.Pp
.Dl Nm Fl c Fl f Pa - Pa новыйфайл Cm @ Ns Pa исходный.tar
.Pp
записывает новый архив на стандартный вывод, содержащий файл
.Pa новыйфайл
и все записи из
.Pa исходный.tar .
В отличие от этого,
.Pp
.Dl Nm Fl c Fl f Pa - Pa новыйфайл Pa исходный.tar
.Pp
создаёт новый архив только с двумя записями.
Аналогично,
.Pp
.Dl Nm Fl czf Pa - Fl Fl format Cm pax Cm @ Ns Pa -
.Pp
читает архив со стандартного ввода (чей формат будет определён
автоматически) и преобразует его в архив формата pax,
сжатый gzip, на стандартный вывод.
Таким образом,
.Nm
может использоваться для преобразования архивов из одного формата в другой.
.It Fl a , Fl Fl auto-compress
(только режим c)
Использовать суффикс архива для определения набора формата и
сжатия.
В качестве простого примера,
.Pp
.Dl Nm Fl a Fl cf Pa архив.tgz исходный.c исходный.h
.Pp
создаёт новый архив с ограниченным форматом pax и сжатием gzip,
.Pp
.Dl Nm Fl a Fl cf Pa архив.tar.bz2.uu исходный.c исходный.h
.Pp
создаёт новый архив с ограниченным форматом pax и сжатием bzip2
и сжатием uuencode,
.Pp
.Dl Nm Fl a Fl cf Pa архив.zip исходный.c исходный.h
.Pp
создаёт новый архив с форматом zip,
.Pp
.Dl Nm Fl a Fl jcf Pa архив.tgz исходный.c исходный.h
.Pp
игнорирует опцию
.Dq -j
и создаёт новый архив с ограниченным форматом pax
и сжатием gzip,
.Pp
.Dl Nm Fl a Fl jcf Pa архив.xxx исходный.c исходный.h
.Pp
если суффикс неизвестен или отсутствует, создаёт новый архив с
ограниченным форматом pax и сжатием bzip2.
.It Fl Fl acls
(только режимы c, r, u, x)
Архивировать или извлекать ACL POSIX.1e или NFSv4.
Это противоположность
.Fl Fl no-acls
и поведение по умолчанию в режимах c, r и u (кроме Mac OS X) или если
.Nm
запущен в режиме x от имени root.
На Mac OS X эта опция преобразует расширенные ACL в ACL NFSv4.
Для хранения расширенных ACL предпочтительнее опция
.Fl Fl mac-metadata .
.It Fl B , Fl Fl read-full-blocks
Игнорируется для совместимости с другими
реализациями
.Xr tar 1 .
.It Fl b Ar размер-блока , Fl Fl block-size Ar размер-блока
Указать размер блока в записях по 512 байт для ввода-вывода на ленточный накопитель.
Как правило, этот аргумент нужен только при чтении или записи
на ленточные накопители, и обычно даже тогда, поскольку размер блока по умолчанию
в 20 записей (10240 байт) очень распространён.
.It Fl C Ar каталог , Fl Fl cd Ar каталог , Fl Fl directory Ar каталог
В режимах c и r это изменяет каталог перед добавлением
следующих файлов.
В режиме x изменить каталоги после открытия архива,
но перед извлечением записей из архива.
.It Fl Fl chroot
(только режим x)
.Fn chroot
в текущий каталог после обработки любых
опций
.Fl C
и перед извлечением любых файлов.
.It Fl Fl clamp-mtime
(использовать с
.Fl Fl mtime )
Устанавливать время модификации только если файл новее даты, указанной в
.Fl Fl mtime .
.It Fl Fl clear-nochange-fflags
(только режим x)
Перед удалением объектов файловой системы для их замены очистить специфичные для платформы
атрибуты файлов или флаги файлов, которые могут помешать удалению.
.It Fl Fl exclude Ar шаблон
Не обрабатывать файлы или каталоги, соответствующие
указанному шаблону.
Обратите внимание, что исключения имеют приоритет над шаблонами или именами файлов,
указанными в командной строке.
.It Fl Fl exclude-vcs
Не обрабатывать файлы или каталоги, внутренне используемые
системами контроля версий
.Sq Arch ,
.Sq Bazaar ,
.Sq CVS ,
.Sq Darcs ,
.Sq Mercurial ,
.Sq RCS ,
.Sq SCCS ,
.Sq SVN
и
.Sq git .
.It Fl Fl fflags
(только режимы c, r, u, x)
Архивировать или извлекать специфичные для платформы атрибуты файлов или флаги файлов.
Это противоположность
.Fl Fl no-fflags
и поведение по умолчанию в режимах c, r и u или если
.Nm
запущен в режиме x от имени root.
.It Fl Fl format Ar формат
(только режимы c, r, u)
Использовать указанный формат для создаваемого архива.
Поддерживаемые форматы включают
.Dq cpio ,
.Dq pax ,
.Dq shar ,
и
.Dq ustar .
Другие форматы также могут поддерживаться; см.
.Xr libarchive-formats 5
для получения дополнительной информации о текущих поддерживаемых форматах.
В режимах r и u при расширении существующего архива формат, указанный
здесь, должен быть совместим с форматом существующего архива на диске.
.It Fl f Ar файл , Fl Fl file Ar файл
Читать архив из или записывать архив в указанный файл.
Имя файла может быть
.Pa -
для стандартного ввода или стандартного вывода.
По умолчанию зависит от системы;
на
.Fx ,
по умолчанию
.Pa /dev/sa0 ;
на Linux, по умолчанию
.Pa /dev/st0 .
.It Fl Fl gid Ar id
Использовать предоставленный номер идентификатора группы.
При извлечении это переопределяет идентификатор группы в архиве;
имя группы в архиве будет проигнорировано.
При создании это переопределяет идентификатор группы, прочитанный с диска;
если
.Fl Fl gname
не указано, имя группы будет установлено в
соответствие с идентификатором группы.
.It Fl Fl gname Ar имя
Использовать предоставленное имя группы.
При извлечении это переопределяет имя группы в архиве;
если предоставленное имя группы не существует в системе,
будет использован идентификатор группы
(из архива или из опции
.Fl Fl gid ) .
При создании это устанавливает имя группы, которое будет сохранено
в архиве;
имя не будет проверяться против системной базы данных групп.
.It Fl Fl group Ar имя Ns Op : Ns Ar gid
Использовать предоставленную группу, если
.Ar gid
не предоставлен,
.Ar имя
может быть либо именем группы, либо числовым идентификатором.
Подробности см. в опции
.Fl Fl gname .
.It Fl H
(только режимы c и r)
Символические ссылки, указанные в командной строке, будут разыменованы;
цель ссылки будет заархивирована, а не сама ссылка.
.It Fl h
(только режимы c и r)
Синоним для
.Fl L .
.It Fl I
Синоним для
.Fl T .
.It Fl Fl help
Показать справку по использованию.
.It Fl Fl hfsCompression
(только режим x)
Специфично для Mac OS X (v10.6 или позднее). Сжимать извлечённые обычные файлы сжатием HFS+.
.It Fl Fl ignore-zeros
Псевдоним
.Fl Fl options Cm read_concatenated_archives
для совместимости с GNU tar.
.It Fl Fl include Ar шаблон
Обрабатывать только файлы или каталоги, соответствующие указанному шаблону.
Обратите внимание, что исключения, указанные с помощью
.Fl Fl exclude ,
имеют приоритет над включениями.
Если включения не указаны явно, по умолчанию обрабатываются все записи.
Опция
.Fl Fl include
особенно полезна при фильтрации архивов.
Например, команда
.Pp
.Dl Nm Fl c Fl f Pa новый.tar Fl Fl include='*foo*' Cm @ Ns Pa старый.tgz
.Pp
создаёт новый архив
.Pa новый.tar ,
содержащий только записи из
.Pa старый.tgz ,
содержащие строку
.Sq foo .
.It Fl J , Fl Fl xz
(только режим c)
Сжать результирующий архив с помощью
.Xr xz 1 .
В режимах извлечения или списка эта опция игнорируется.
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие XZ при чтении архивов.
.It Fl j , Fl Fl bzip , Fl Fl bzip2 , Fl Fl bunzip2
(только режим c)
Сжать результирующий архив с помощью
.Xr bzip2 1 .
В режимах извлечения или списка эта опция игнорируется.
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие bzip2 при чтении архивов.
.It Fl k , Fl Fl keep-old-files
(только режим x)
Не перезаписывать существующие файлы.
В частности, если файл появляется в архиве более одного раза,
поздние копии не будут перезаписывать более ранние копии.
.It Fl Fl keep-newer-files
(только режим x)
Не перезаписывать существующие файлы, которые новее, чем
версии, появляющиеся в извлекаемом архиве.
.It Fl L , Fl Fl dereference
(только режимы c и r)
Все символические ссылки будут разыменованы.
Обычно символические ссылки архивируются как таковые.
С этой опцией вместо ссылки будет заархивирована её цель.
.It Fl l , Fl Fl check-links
(только режимы c и r)
Выдавать предупреждение, если не все ссылки на каждый файл заархивированы.
.It Fl Fl lrzip
(только режим c)
Сжать результирующий архив с помощью
.Xr lrzip 1 .
В режимах извлечения или списка эта опция игнорируется.
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие lrzip при чтении архивов.
.It Fl Fl lz4
(только режим c)
Сжать архив совместимым с lz4 сжатием перед записью.
В режимах извлечения или списка эта опция игнорируется.
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие lz4 при чтении архивов.
.It Fl Fl zstd
(только режим c)
Сжать архив совместимым с zstd сжатием перед записью.
В режимах извлечения или списка эта опция игнорируется.
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие zstd при чтении архивов.
.It Fl Fl lzma
(только режим c) Сжать результирующий архив оригинальным алгоритмом LZMA.
В режимах извлечения или списка эта опция игнорируется.
Использование этой опции не рекомендуется, и новые архивы следует создавать с помощью
.Fl Fl xz .
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие LZMA при чтении архивов.
.It Fl Fl lzop
(только режим c)
Сжать результирующий архив с помощью
.Xr lzop 1 .
В режимах извлечения или списка эта опция игнорируется.
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие LZO при чтении архивов.
.It Fl m , Fl Fl modification-time
(только режим x)
Не извлекать время модификации.
По умолчанию время модификации устанавливается на время, хранящееся в архиве.
.It Fl Fl mac-metadata
(только режимы c, r, u и x)
Специфично для Mac OS X.
Архивировать или извлекать расширенные ACL и расширенные атрибуты файлов
с использованием
.Xr copyfile 3
в формате AppleDouble.
Это противоположность
.Fl Fl no-mac-metadata .
и поведение по умолчанию в режимах c, r и u или если
.Nm
запущен в режиме x от имени root.
В настоящее время поддерживается только для форматов pax
.Nm bsdtar Pc
.It Fl Fl mtime Ar дата
(только режимы c, r, u)
Установить время модификации добавляемых файлов на указанную дату.
.It Fl n , Fl Fl norecurse , Fl Fl no-recursion
Не работать рекурсивно с содержимым каталогов.
.It Fl Fl newer Ar дата
(только режимы c, r, u)
Включать только файлы и каталоги новее указанной даты.
Это сравнивает записи ctime.
.It Fl Fl newer-mtime Ar дата
(только режимы c, r, u)
Как
.Fl Fl newer ,
за исключением того, что сравнивает записи mtime вместо записей ctime.
.It Fl Fl newer-than Pa файл
(только режимы c, r, u)
Включать только файлы и каталоги новее указанного файла.
Это сравнивает записи ctime.
.It Fl Fl newer-mtime-than Pa файл
(только режимы c, r, u)
Как
.Fl Fl newer-than ,
за исключением того, что сравнивает записи mtime вместо записей ctime.
.It Fl Fl nodump
(только режимы c и r)
Соблюдать флаг файла nodump, пропуская этот файл.
.It Fl Fl nopreserveHFSCompression
(только режим x)
Специфично для Mac OS X (v10.6 или позднее). Не сжимать извлечённые обычные файлы,
которые были сжаты сжатием HFS+ перед архивацией.
По умолчанию сжимать обычные файлы снова сжатием HFS+.
.It Fl Fl null
(использовать с
.Fl I
или
.Fl T )
Имена файлов или шаблоны разделяются нулевыми символами,
а не символами новой строки.
Это часто используется для чтения имён файлов, выводимых опцией
.Fl print0
в
.Xr find 1 .
.It Fl Fl no-acls
(только режимы c, r, u, x)
Не архивировать или извлекать ACL POSIX.1e или NFSv4.
Это противоположность
.Fl Fl acls
и поведение по умолчанию, если
.Nm
запущен не от root в режиме x (на Mac OS X как любой пользователь в режимах c, r, u и x).
.It Fl Fl no-fflags
(только режимы c, r, u, x)
Не архивировать или извлекать атрибуты файлов или флаги файлов.
Это противоположность
.Fl Fl fflags
и поведение по умолчанию, если
.Nm
запущен не от root в режиме x.
.It Fl Fl no-mac-metadata
(только режимы c, r, u и x)
Специфично для Mac OS X.
Не архивировать или извлекать ACL и расширенные атрибуты файлов
с использованием
.Xr copyfile 3
в формате AppleDouble.
Это противоположность
.Fl Fl mac-metadata .
и поведение по умолчанию, если
.Nm
запущен не от root в режиме x.
.It Fl Fl no-read-sparse
(только режимы c, r, u)
Не читать информацию о разреженных файлах с диска.
Это противоположность
.Fl Fl read-sparse .
.It Fl Fl no-safe-writes
(только режим x)
Не создавать временные файлы и использовать
.Xr rename 2
для замены оригинальных.
Это противоположность
.Fl Fl safe-writes .
.It Fl Fl no-same-owner
(только режим x)
Не извлекать идентификаторы владельца и группы.
Это противоположность
.Fl Fl same-owner
и поведение по умолчанию, если
.Nm
запущен не от root.
.It Fl Fl no-same-permissions
(только режим x)
Не извлекать полные права доступа (SGID, SUID, sticky bit,
атрибуты файлов или флаги файлов, расширенные атрибуты файлов и ACL).
Это противоположность
.Fl p
и поведение по умолчанию, если
.Nm
запущен не от root.
.It Fl Fl no-xattrs
(только режимы c, r, u, x)
Не архивировать или извлекать расширенные атрибуты файлов.
Это противоположность
.Fl Fl xattrs
и поведение по умолчанию, если
.Nm
запущен не от root в режиме x.
.It Fl Fl numeric-owner
Это эквивалентно
.Fl Fl uname
.Qq
.Fl Fl gname
.Qq .
При извлечении это приводит к тому, что имена пользователей и групп в архиве
игнорируются в пользу числовых идентификаторов пользователя и группы.
При создании это приводит к тому, что имена пользователей и групп не сохраняются
в архиве.
.It Fl O , Fl Fl to-stdout
(только режимы x, t)
В режиме извлечения (-x) файлы будут записаны на стандартный вывод, а не
извлечены на диск.
В режиме списка (-t) список файлов будет записан на stderr, а не
на обычный stdout.
.It Fl o
(режим x)
Использовать пользователя и группу пользователя, запускающего программу, а не
указанные в архиве.
Обратите внимание, что это не имеет значения, если не указана
.Fl p ,
и программа запущена от имени пользователя root.
В этом случае режимы файлов и флаги из
архива будут восстановлены, но ACL или информация о владельце в
архиве будет отброшена.
.It Fl o
(режимы c, r, u)
Синоним для
.Fl Fl format Ar ustar
.It Fl Fl older Ar дата
(только режимы c, r, u)
Включать только файлы и каталоги старше указанной даты.
Это сравнивает записи ctime.
.It Fl Fl older-mtime Ar дата
(только режимы c, r, u)
Как
.Fl Fl older ,
за исключением того, что сравнивает записи mtime вместо записей ctime.
.It Fl Fl older-than Pa файл
(только режимы c, r, u)
Включать только файлы и каталоги старше указанного файла.
Это сравнивает записи ctime.
.It Fl Fl older-mtime-than Pa файл
(только режимы c, r, u)
Как
.Fl Fl older-than ,
за исключением того, что сравнивает записи mtime вместо записей ctime.
.It Fl Fl one-file-system
(режимы c, r и u)
Не пересекать точки монтирования.
.It Fl Fl options Ar опции
Выбрать дополнительные поведения для определённых модулей.
Аргумент — это текстовая строка, содержащая разделённые запятыми
ключевые слова и значения.
Они передаются модулям, которые обрабатывают определённые
форматы, чтобы контролировать поведение этих форматов.
Каждая опция имеет одну из следующих форм:
.Pp
.Bl -tag -compact -width indent
.It Ar ключ=значение
Ключ будет установлен в указанное значение в каждом модуле, который его поддерживает.
Модули, которые не поддерживают этот ключ, проигнорируют его.
.It Ar ключ
Ключ будет включён в каждом модуле, который его поддерживает.
Это эквивалентно
.Ar ключ Ns Cm =1 .
.It Ar !ключ
Ключ будет отключён в каждом модуле, который его поддерживает.
.It Ar модуль:ключ=значение , Ar модуль:ключ , Ar модуль:!ключ
Как выше, но соответствующий ключ и значение будут предоставлены
только модулям, чьё имя совпадает с
.Ar модуль .
.El
.Pp
Полный список поддерживаемых модулей и ключей
для режимов создания и добавления находится в
.Xr archive_write_set_options 3
и для режимов извлечения и списка в
.Xr archive_read_set_options 3 .
.Pp
Примеры поддерживаемых опций:
.Pp
.Bl -tag -compact -width indent
.It Cm iso9660:joliet
Поддерживать расширения Joliet.
Это включено по умолчанию, используйте
.Cm !joliet
или
.Cm iso9660:!joliet
для отключения.
.It Cm iso9660:rockridge
Поддерживать расширения Rock Ridge.
Это включено по умолчанию, используйте
.Cm !rockridge
или
.Cm iso9660:!rockridge
для отключения.
.It Cm gzip:compression-level
Десятичное целое число от 1 до 9, указывающее уровень сжатия gzip.
.It Cm gzip:timestamp
Сохранять временную метку.
Это включено по умолчанию, используйте
.Cm !timestamp
или
.Cm gzip:!timestamp
для отключения.
.It Cm lrzip:compression Ns = Ns Ar тип
Использовать
.Ar тип
как метод сжатия.
Поддерживаемые значения: bzip2, gzip, lzo (ультра быстрый),
и zpaq (лучший, чрезвычайно медленный).
.It Cm lrzip:compression-level
Десятичное целое число от 1 до 9, указывающее уровень сжатия lrzip.
.It Cm lz4:compression-level
Десятичное целое число от 1 до 9, указывающее уровень сжатия lzop.
.It Cm lz4:stream-checksum
Включить проверку потока.
Это по умолчанию, используйте
.Cm lz4:!stream-checksum
для отключения.
.It Cm lz4:block-checksum
Включить проверку блока (отключено по умолчанию).
.It Cm lz4:block-size
Десятичное целое число от 4 до 7, указывающее размер блока сжатия lz4
(по умолчанию установлено 7).
.It Cm lz4:block-dependence
Использовать предыдущий блок сжимаемого блока для
словаря сжатия, чтобы улучшить коэффициент сжатия.
.It Cm zstd:compression-level Ns = Ns Ar N
Десятичное целое число, указывающее уровень сжатия zstd.
Поддерживаемые значения зависят
от версии библиотеки, общие значения от 1 до 22.
.It Cm zstd:threads Ns = Ns Ar N
Указать количество рабочих потоков для использования, или 0 для использования
столько потоков, сколько ядер CPU в системе.
.It Cm zstd:frame-per-file
Начать новый кадр сжатия в начале каждого файла в
архиве.
.It Cm zstd:min-frame-in Ns = Ns Ar N
В сочетании с
.Cm zstd:frame-per-file ,
не начинать новый кадр сжатия, если несжатый размер
текущего кадра меньше
.Ar N
байт.
Число может сопровождаться
.Li k / Li kB ,
.Li M / Li MB ,
или
.Li G / Li GB
для указания килобайт, мегабайт или гигабайт соответственно.
.It Cm zstd:min-frame-out Ns = Ns Ar N , Cm zstd:min-frame-size Ns = Ns Ar N
В сочетании с
.Cm zstd:frame-per-file ,
не начинать новый кадр сжатия, если сжатый размер
текущего кадра меньше
.Ar N
байт.
Число может сопровождаться
.Li k / Li kB ,
.Li M / Li MB ,
или
.Li G / Li GB
для указания килобайт, мегабайт или гигабайт соответственно.
.It Cm zstd:max-frame-in Ns = Ns Ar N , Cm zstd:max-frame-size Ns = Ns Ar N
Начать новый кадр сжатия как можно скорее после того, как
несжатый размер текущего кадра превысит
.Ar N
байт.
Число может сопровождаться
.Li k / Li kB ,
.Li M / Li MB ,
или
.Li G / Li GB
для указания килобайт, мегабайт или гигабайт соответственно.
Значения меньше 1,024 будут отвергнуты.
.It Cm zstd:max-frame-out Ns = Ns Ar N
Начать новый кадр сжатия как можно скорее после того, как сжатый
размер текущего кадра превысит
.Ar N
байт.
Число может сопровождаться
.Li k / Li kB ,
.Li M / Li MB ,
или
.Li G / Li GB
для указания килобайт, мегабайт или гигабайт соответственно.
Значения меньше 1,024 будут отвергнуты.
.It Cm lzop:compression-level
Десятичное целое число от 1 до 9, указывающее уровень сжатия lzop.
.It Cm xz:compression-level
Десятичное целое число от 0 до 9, указывающее уровень сжатия xz.
.It Cm xz:threads
Указать количество рабочих потоков для использования.
Установка потоков в специальное значение 0 заставляет
.Xr xz 1
использовать столько потоков, сколько ядер CPU в системе.
.It Cm mtree: Ns Ar ключевое-слово
Модуль записи mtree позволяет указать, какие ключевые слова mtree
будут включены в вывод.
Поддерживаемые ключевые слова включают:
.Cm cksum , Cm device , Cm flags , Cm gid , Cm gname , Cm indent ,
.Cm link , Cm md5 , Cm mode , Cm nlink , Cm rmd160 , Cm sha1 , Cm sha256 ,
.Cm sha384 , Cm sha512 , Cm size , Cm time , Cm uid , Cm uname .
По умолчанию эквивалентно:
.Dq device, flags, gid, gname, link, mode, nlink, size, time, type, uid, uname .
.It Cm mtree:all
Включает все вышеуказанные ключевые слова.
Вы также можете использовать
.Cm mtree:!all
для отключения всех ключевых слов.
.It Cm mtree:use-set
Включить генерацию строк
.Cm /set
в выводе.
.It Cm mtree:indent
Создавать удобочитаемый вывод, делая отступы для опций и разделяя строки
так, чтобы они помещались в 80 столбцов.
.It Cm zip:compression Ns = Ns Ar тип
Использовать
.Ar тип
как метод сжатия.
Поддерживаемые значения: store (несжатый) и deflate (алгоритм gzip).
.It Cm zip:encryption
Включить шифрование с использованием традиционного шифрования zip.
.It Cm zip:encryption Ns = Ns Ar тип
Использовать
.Ar тип
как тип шифрования.
Поддерживаемые значения: zipcrypt (традиционное шифрование zip),
aes128 (шифрование WinZip AES-128) и aes256 (шифрование WinZip AES-256).
.It Cm read_concatenated_archives
Игнорировать нулевые блоки в архиве, что происходит, когда несколько tar архивов
были объединены вместе.
Без этой опции только содержимое
первого объединённого архива будет прочитано.
Эта опция сравнима с опцией
.Fl i , Fl Fl ignore-zeros
GNU tar.
.El
.Pp
Если предоставленная опция не поддерживается никаким модулем, это
фатальная ошибка.
.It Fl P , Fl Fl absolute-paths
Сохранять пути.
По умолчанию абсолютные пути (те, которые начинаются с символа /)
имеют ведущий слэш удалённым как при создании архивов,
так и при извлечении из них.
Также,
.Nm
откажется извлекать записи архива, чьи пути содержат
.Pa ..
или чья целевая директория будет изменена симлинком.
Эта опция подавляет такое поведение.
.It Fl p , Fl Fl insecure , Fl Fl preserve-permissions
(только режим x)
Сохранять права доступа к файлам.
Пытаться восстановить полные права доступа, включая режимы файлов, атрибуты файлов
или флаги файлов, расширенные атрибуты файлов и ACL, если доступно, для каждого элемента,
извлекаемого из архива.
Это противоположность
.Fl Fl no-same-permissions
и поведение по умолчанию, если
.Nm
запущен от имени root.
Это может быть частично переопределено также указанием
.Fl Fl no-acls ,
.Fl Fl no-fflags ,
.Fl Fl no-mac-metadata
или
.Fl Fl no-xattrs .
.It Fl Fl passphrase Ar парольная-фраза
.Pa Парольная-фраза
используется для извлечения или создания зашифрованного архива.
В настоящее время zip — единственный поддерживаемый формат, который поддерживает шифрование.
Вы не должны использовать эту опцию, если не понимаете, насколько небезопасно
её использование.
.It Fl Fl posix
(только режимы c, r, u)
Синоним для
.Fl Fl format Ar pax
.It Fl q , Fl Fl fast-read
(только режимы x и t)
Извлекать или перечислять только первую запись архива, соответствующую каждому шаблону
или операнду имени файла.
Завершать работу, как только каждый указанный шаблон или имя файла был сопоставлен.
По умолчанию архив всегда читается до самого конца, поскольку
может быть несколько записей с одинаковым именем и, по соглашению,
поздние записи перезаписывают более ранние записи.
Эта опция предоставлена как оптимизация производительности.
.It Fl Fl read-sparse
(только режимы c, r, u)
Читать информацию о разреженных файлах с диска.
Это противоположность
.Fl Fl no-read-sparse
и поведение по умолчанию.
.It Fl S
(только режим x)
Извлекать файлы как разреженные файлы.
Для каждого блока на диске сначала проверять, содержит ли он только NULL-байты, и пропускать
его в противном случае.
Это работает аналогично опции conv=sparse у dd.
.It Fl s Ar шаблон
Изменять имена файлов или членов архива согласно
.Pa шаблону .
Шаблон имеет формат
.Ar /старый/новый/ Ns Op bghHprRsS
где
.Ar старый
это базовое регулярное выражение,
.Ar новый
это строка замены совпавшей части,
и необязательные завершающие буквы изменяют
способ выполнения замены.
Если
.Ar старый
не совпадает, шаблон пропускается.
Внутри
.Ar новый ,
~ заменяется на совпадение, \e1 до \e9 на содержимое
соответствующей захваченной группы.
Необязательная завершающая g указывает, что сопоставление должно продолжаться
после совпавшей части и останавливаться на первом несовпавшем шаблоне.
Необязательная завершающая s указывает, что шаблон применяется к значению
символических ссылок.
Необязательная завершающая p указывает, что после успешной замены
оригинальное имя пути и новое имя пути должны быть выведены на
стандартную ошибку.
Необязательная завершающая b указывает, что замена должна быть
сопоставлена с начала строки, а не справа после
позиции, на которой закончилась предыдущая совпавшая замена.
Необязательные завершающие символы H, R или S подавляют замены
для целей жёстких ссылок, обычных имён файлов или целей симлинков,
соответственно.
Необязательные завершающие символы h, r или s включают замены
для целей жёстких ссылок, обычных имён файлов или целей симлинков,
соответственно.
По умолчанию
.Ar hrs
что применяет замены ко всем именам.
В частности, никогда не нужно указывать h, r или s.
.It Fl Fl safe-writes
(только режим x)
Извлекать файлы атомарно.
По умолчанию
.Nm
отсоединяет оригинальный файл с тем же именем, что и извлекаемый файл (если он
существует), а затем немедленно создаёт его под тем же именем и записывает в
него.
В течение короткого периода времени приложения, пытающиеся получить доступ к файлу, могут
не найти его или увидеть неполные результаты.
Если
.Fl Fl safe-writes
включена,
.Nm
сначала создаёт уникальный временный файл, затем записывает новое содержимое в
временный файл и, наконец, переименовывает временный файл в его окончательное
имя атомарно с использованием
.Xr rename 2 .
Это гарантирует, что приложение, обращающееся к файлу, будет видеть
либо старое содержимое, либо новое содержимое в любое время.
.It Fl Fl same-owner
(только режим x)
Извлекать идентификаторы владельца и группы.
Это противоположность
.Fl Fl no-same-owner
и поведение по умолчанию, если
.Nm
запущен от имени root.
.It Fl Fl strip-components Ar количество
Удалить указанное количество ведущих элементов пути.
Пути с меньшим количеством элементов будут тихо пропущены.
Обратите внимание, что имя пути редактируется после проверки шаблонов включения/исключения,
но перед проверками безопасности.
.It Fl T Ar имя-файла , Fl Fl files-from Ar имя-файла
В режиме x или t,
.Nm
будет читать список имён для извлечения из
.Pa имя-файла .
В режиме c,
.Nm
будет читать имена для архивации из
.Pa имя-файла .
Специальное имя
.Dq -C
на отдельной строке заставит текущий каталог измениться на
каталог, указанный на следующей строке.
Имена завершаются символами новой строки, если не указана
.Fl Fl null .
Обратите внимание, что
.Fl Fl null
также отключает специальную обработку строк, содержащих
.Dq -C .
Примечание: Если вы генерируете списки файлов с помощью
.Xr find 1 ,
вам, вероятно, также понадобится использовать
.Fl n .
.It Fl Fl totals
(только режимы c, r, u)
После архивации всех файлов вывести сводку на stderr.
.It Fl U , Fl Fl unlink , Fl Fl unlink-first
(только режим x)
Отсоединять файлы перед их созданием.
Это может быть небольшой оптимизацией производительности, если большинство файлов
уже существуют, но может замедлить работу, если большинство файлов
ещё не существуют.
Этот флаг также заставляет
.Nm
удалять промежуточные символические ссылки каталогов вместо
сообщения об ошибке.
Подробности см. в разделе
.Sx БЕЗОПАСНОСТЬ
ниже.
.It Fl Fl uid Ar id
Использовать предоставленный номер идентификатора пользователя и игнорировать имя
пользователя из архива.
При создании, если
.Fl Fl uname
не указано, имя пользователя будет установлено в
соответствие с идентификатором пользователя.
.It Fl Fl uname Ar имя
Использовать предоставленное имя пользователя.
При извлечении это переопределяет имя пользователя в архиве;
если предоставленное имя пользователя не существует в системе,
оно будет проигнорировано, и будет использован идентификатор пользователя
(из архива или из опции
.Fl Fl uid ) .
При создании это устанавливает имя пользователя, которое будет сохранено
в архиве;
имя не проверяется против системной базы данных пользователей.
.It Fl Fl use-compress-program Ar программа
Пропускать ввод (в режиме x или t) или вывод (в режиме c) через
.Pa программу
вместо использования встроенной поддержки сжатия.
.It Fl Fl owner Ar имя Ns Op : Ns Ar uid
Использовать предоставленного пользователя, если
.Ar uid
не предоставлен,
.Ar имя
может быть либо именем пользователя, либо числовым идентификатором.
Подробности см. в опции
.Fl Fl uname .
.It Fl v , Fl Fl verbose
Выводить подробный вывод.
В режимах создания и извлечения,
.Nm
будет перечислять каждое имя файла по мере чтения из или записи в
архив.
В режиме списка,
.Nm
будет выводить информацию, подобную
.Xr ls 1 .
Дополнительная опция
.Fl v
также предоставит подробности, подобные ls, в режиме создания и извлечения.
.It Fl Fl version
Вывести версию
.Nm
и
.Nm libarchive ,
и завершить работу.
.It Fl w , Fl Fl confirmation , Fl Fl interactive
Запрашивать подтверждение для каждого действия.
.It Fl X Ar имя-файла , Fl Fl exclude-from Ar имя-файла
Читать список шаблонов исключения из указанного файла.
См.
.Fl Fl exclude
для получения дополнительной информации об обработке исключений.
.It Fl Fl xattrs
(только режимы c, r, u, x)
Архивировать или извлекать расширенные атрибуты файлов.
Это противоположность
.Fl Fl no-xattrs
и поведение по умолчанию в режимах c, r и u или если
.Nm
запущен в режиме x от имени root.
.It Fl y
(только режим c)
Сжать результирующий архив с помощью
.Xr bzip2 1 .
В режимах извлечения или списка эта опция игнорируется.
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие bzip2 при чтении архивов.
.It Fl Z , Fl Fl compress , Fl Fl uncompress
(только режим c)
Сжать результирующий архив с помощью
.Xr compress 1 .
В режимах извлечения или списка эта опция игнорируется.
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие compress при чтении архивов.
.It Fl z , Fl Fl gunzip , Fl Fl gzip
(только режим c)
Сжать результирующий архив с помощью
.Xr gzip 1 .
В режимах извлечения или списка эта опция игнорируется.
Обратите внимание, что эта реализация
.Nm tar
автоматически распознаёт сжатие gzip при чтении архивов.
.El
.Sh ОКРУЖЕНИЕ
Следующие переменные окружения влияют на выполнение
.Nm :
.Bl -tag -width indent
.It Ev TAR_READER_OPTIONS
Опции по умолчанию для модулей чтения форматов и сжатия.
Опция
.Fl Fl options
переопределяет это.
.It Ev TAR_WRITER_OPTIONS
Опции по умолчанию для модулей записи форматов и сжатия.
Опция
.Fl Fl options
переопределяет это.
.It Ev LANG
Используемая локаль.
См.
.Xr environ 7
для получения дополнительной информации.
.It Ev TAPE
Устройство по умолчанию.
Опция
.Fl f
переопределяет это.
Пожалуйста, см. описание опции
.Fl f
выше для получения дополнительных подробностей.
.It Ev TZ
Часовой пояс для использования при отображении дат.
См.
.Xr environ 7
для получения дополнительной информации.
.El
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
Следующая команда создаёт новый архив
под названием
.Ar файл.tar.gz ,
который содержит два файла
.Ar исходный.c
и
.Ar исходный.h :
.Pp
.Dl Nm Fl czf Pa файл.tar.gz Pa исходный.c Pa исходный.h
.Pp
Чтобы просмотреть подробную таблицу содержимого этого
архива:
.Pp
.Dl Nm Fl tvf Pa файл.tar.gz
.Pp
Чтобы извлечь все записи из архива на
ленточном накопителе по умолчанию:
.Pp
.Dl Nm Fl x
.Pp
Чтобы изучить содержимое образа CDROM ISO 9660:
.Pp
.Dl Nm Fl tf Pa образ.iso
.Pp
Чтобы переместить иерархии файлов, вызовите
.Nm
как
.Pp
.Dl Nm Fl cf Pa - Fl C Pa исходный-каталог \&. | Nm Fl xpf Pa - Fl C Pa целевой-каталог
.Pp
или более традиционно
.Pp
.Dl cd исходный-каталог \&; Nm Fl cf Pa - \&. | ( cd целевой-каталог \&; Nm Fl xpf Pa - )
.Pp
В режиме создания список файлов и каталогов для архивации
также может включать инструкции смены каталога вида
.Cm -C Ns Pa foo/baz
и включения архивов вида
.Cm @ Ns Pa архив-файл .
Например, командная строка
.Pp
.Dl Nm Fl c Fl f Pa новый.tar Pa foo1 Cm @ Ns Pa старый.tgz Cm -C Ns Pa /tmp Pa foo2
.Pp
создаст новый архив
.Pa новый.tar .
.Nm
прочитает файл
.Pa foo1
из текущего каталога и добавит его в выходной архив.
Затем он прочитает каждую запись из
.Pa старый.tgz
и добавит эти записи в выходной архив.
Наконец, он переключится в каталог
.Pa /tmp
и добавит
.Pa foo2
в выходной архив.
.Pp
Входной файл в формате
.Xr mtree 5
может использоваться для создания выходного архива с произвольными владельцами,
правами доступа или именами, отличающимися от существующих данных на диске:
.Bd -literal -offset indent
$ cat входной.mtree
#mtree
usr/bin uid=0 gid=0 mode=0755 type=dir
usr/bin/ls uid=0 gid=0 mode=0755 type=file content=myls
$ tar -cvf выходной.tar @входной.mtree
.Ed
.Pp
Переключатели
.Fl Fl newer
и
.Fl Fl newer-mtime
принимают различные общие спецификации даты и времени, включая
.Dq 12 Mar 2005 7:14:29pm ,
.Dq 2005-03-12 19:14 ,
.Dq 5 minutes ago ,
и
.Dq 19:14 PST May 1 .
.Pp
Аргумент
.Fl Fl options
может использоваться для контроля различных деталей генерации
или чтения архива.
Например, вы можете сгенерировать вывод mtree, который содержит только
ключевые слова
.Cm type , Cm time ,
и
.Cm uid :
.Pp
.Dl Nm Fl cf Pa файл.tar Fl Fl format=mtree Fl Fl options='!all,type,time,uid' Pa каталог
.Pp
или вы можете установить уровень сжатия, используемый сжатием gzip или xz:
.Pp
.Dl Nm Fl czf Pa файл.tar Fl Fl options='compression-level=9' .
.Pp
Для получения дополнительных подробностей см. объяснение
вызовов API
.Fn archive_read_set_options
и
.Fn archive_write_set_options ,
которые описаны в
.Xr archive_read 3
и
.Xr archive_write 3 .
.Sh СОВМЕСТИМОСТЬ
Формат объединённых аргументов поддерживается для совместимости
с историческими реализациями.
Он состоит из начального слова (без ведущего символа -), в котором
каждый символ указывает опцию.
Аргументы следуют как отдельные слова.
Порядок аргументов должен соответствовать порядку
соответствующих символов в объединённом командном слове.
Например,
.Pp
.Dl Nm Cm tbf 32 Pa файл.tar
.Pp
указывает три флага
.Cm t ,
.Cm b ,
и
.Cm f .
Флаги
.Cm b
и
.Cm f
оба требуют аргументов,
поэтому в командной строке должно быть два дополнительных элемента.
.Ar 32
это аргумент для флага
.Cm b ,
и
.Ar файл.tar
это аргумент для флага
.Cm f .
.Pp
Опции режимов c, r, t, u и x и опции
b, f, l, m, o, v и w соответствуют SUSv2.
.Pp
Для максимальной переносимости скрипты, вызывающие
.Nm tar ,
должны использовать формат объединённых аргументов выше, должны ограничиваться
режимами
.Cm c ,
.Cm t ,
и
.Cm x ,
и опциями
.Cm b ,
.Cm f ,
.Cm m ,
.Cm v ,
и
.Cm w .
.Pp
Дополнительные длинные опции предоставлены для улучшения совместимости с другими
реализациями tar.
.Sh БЕЗОПАСНОСТЬ
Определённые проблемы безопасности общи для многих архивирующих программ, включая
.Nm .
В частности, тщательно созданные архивы могут запросить, чтобы
.Nm
извлекал файлы в места вне целевого каталога.
Это потенциально может использоваться для того, чтобы заставить неосторожных пользователей перезаписать
файлы, которые они не собирались перезаписывать.
Если архив извлекается суперпользователем, любой файл
в системе потенциально может быть перезаписан.
Есть три способа, как это может произойти.
Хотя
.Nm
имеет механизмы защиты от каждого из них,
осведомлённые пользователи должны понимать последствия:
.Bl -bullet -width indent
.It
Записи архива могут иметь абсолютные пути.
По умолчанию,
.Nm
удаляет ведущий символ
.Pa /
из имён файлов перед восстановлением, чтобы защититься от этой проблемы.
.It
Записи архива могут иметь пути, включающие
компоненты
.Pa .. .
По умолчанию,
.Nm
не будет извлекать файлы, содержащие
компоненты
.Pa ..
в их пути.
.It
Записи архива могут использовать символические ссылки для восстановления
файлов в другие каталоги.
Архив может восстановить символическую ссылку в другой каталог,
затем использовать эту ссылку для восстановления файла в этот каталог.
Для защиты от этого,
.Nm
проверяет каждый извлекаемый путь на наличие симлинков.
Если конечный элемент пути является симлинком, он будет удалён
и заменён записью архива.
Если указана
.Fl U ,
любой промежуточный симлинк также будет безусловно удалён.
Если ни
.Fl U ,
ни
.Fl P
не указаны,
.Nm
откажется извлекать запись.
.El
.Pp
Чтобы защитить себя, вы должны быть осторожны с любыми архивами, которые
приходят из ненадёжных источников.
Вы должны изучить содержимое архива с помощью
.Pp
.Dl Nm Fl tf Pa имя-файла
.Pp
перед извлечением.
Вы должны использовать опцию
.Fl k
чтобы гарантировать, что
.Nm
не перезапишет никакие существующие файлы, или опцию
.Fl U
чтобы удалить любые предсуществующие файлы.
Как правило, не следует извлекать архивы, работая с привилегиями суперпользователя.
Обратите внимание, что опция
.Fl P
в
.Nm
отключает проверки безопасности выше и позволяет вам извлекать
архив, сохраняя любые абсолютные пути,
компоненты
.Pa .. ,
или симлинки в другие каталоги.
.Sh СМ. ТАКЖЕ
.Xr bzip2 1 ,
.Xr compress 1 ,
.Xr cpio 1 ,
.Xr gzip 1 ,
.Xr mt 1 ,
.Xr pax 1 ,
.Xr shar 1 ,
.Xr xz 1 ,
.Xr libarchive 3 ,
.Xr libarchive-formats 5 ,
.Xr tar 5
.Sh СТАНДАРТЫ
В настоящее время нет стандарта POSIX для команды tar; она появилась
в
.St -p1003.1-96
но была удалена из
.St -p1003.1-2001 .
Опции, поддерживаемые этой реализацией, были разработаны путём изучения
ряда существующих реализаций tar, а также старой спецификации POSIX
для tar и текущей спецификации POSIX для pax.
.Pp
Форматы файлов обмена ustar и pax определены в
.St -p1003.1-2001
для команды pax.
.Sh ИСТОРИЯ
Команда
.Nm tar
появилась в Seventh Edition Unix, который был выпущен в январе 1979 года.
Было множество других реализаций,
многие из которых расширяли формат файла.
Публичная реализация
.Sy pdtar
Джона Гилмора (около ноября 1987 года)
была весьма влиятельной и легла в основу GNU tar.
GNU tar была включена как стандартная системная tar
в
.Fx
начиная с
.Fx 1.0 .
.Pp
Это полная перереализация на основе библиотеки
.Xr libarchive 3 .
Она была впервые выпущена с
.Fx 5.4
в мае 2005 года.
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Эта программа следует
.St -p1003.1-96
для определения опции
.Fl l .
Обратите внимание, что GNU tar до версии 1.15 трактовала
.Fl l
как синоним опции
.Fl Fl one-file-system .
.Pp
Опция
.Fl C Pa каталог
может отличаться от исторических реализаций.
.Pp
Весь вывод архива записывается в блоки правильного размера, даже
если вывод сжимается.
Будет ли последний выходной блок дополнен до полного
размера блока, зависит от формата и
устройства вывода.
Для форматов tar и cpio последний блок вывода дополняется
до полного размера блока, если вывод
записывается на стандартный вывод или на символьное или блочное устройство, такое как
ленточный накопитель.
Если вывод записывается в обычный файл, последний блок
не будет дополнен.
Многие компрессоры, включая
.Xr gzip 1
и
.Xr bzip2 1 ,
жалуются на нулевое дополнение при распаковке архива, созданного
.Nm ,
хотя они всё равно извлекают его правильно.
.Pp
Сжатие и распаковка реализованы внутренне, поэтому
могут быть незначительные различия между сжатым выводом,
сгенерированным командой
.Pp
.Dl Nm Fl czf Pa - файл
.Pp
и выводом, сгенерированным командой
.Pp
.Dl Nm Fl cf Pa - файл | Nm gzip
.Pp
По умолчанию следует читать и писать архивы на стандартные пути ввода-вывода,
но традиция (и POSIX) диктует иное.
.Pp
Режимы
.Cm r
и
.Cm u
требуют, чтобы архив был несжатым
и находился в обычном файле на диске.
Другие архивы могут быть изменены с помощью
режима
.Cm c
с расширением
.Pa @архив-файл .
.Pp
Чтобы заархивировать файл с именем
.Pa @foo
или
.Pa -foo ,
вы должны указать его как
.Pa ./@foo
или
.Pa ./-foo ,
соответственно.
.Pp
В режиме создания ведущий
.Pa ./
всегда удаляется.
Ведущий
.Pa /
удаляется, если не указана опция
.Fl P .
.Pp
Необходима лучшая поддержка выбора файлов как при создании,
так и при извлечении.
.Pp
Пока нет поддержки многотомных архивов.
.Pp
Преобразование между различными форматами архивов (такими как tar и cpio) с использованием
соглашения
.Cm @ Ns Pa -
может привести к потере информации о жёстких ссылках.
Это следствие несовместимых способов хранения информации о жёстких ссылках
разными форматами архивов.
