.\" Licensed under the OpenIB.org BSD license (FreeBSD Variant) - See COPYING.md
.\" FRDP path ./contrib/ofed/libibverbs/man/ibv_xsrq_pingpong.1
.\" FRDP githash d6b92ffa990dc57d8a969a98e3ca4e25ba39cbb2
.\" FRDP hash256 6c3d2cd33877f360d2a1e578b3860bfce0249fbb8c564efef07bc9710756c6e6
.SH ИМЯ
ibv_xsrq_pingpong \- простой тест разделяемой очереди приёма InfiniBand

.SH СИНТАКСИС
.B ibv_xsrq_pingpong
[\-p порт] [\-d устройство] [\-i ib порт] [\-s размер] [\-m mtu] [\-c клиенты]
[\-n число_тестов] [\-l sl] [\-e] [\-g индекс gid] \fBИМЯ_ХОСТА\fR

.B ibv_xsrq_pingpong
[\-p порт] [\-d устройство] [\-i ib порт] [\-s размер] [\-m mtu] [\-c клиенты]
[\-n число_тестов] [\-l sl] [\-e] [\-g индекс gid]

.SH ОПИСАНИЕ
.PP
Запускает простой пинг-понг тест через InfiniBand с использованием расширенного надёжного
соединённого (XRC) транспортного сервиса и разделяемой очереди приёма (SRQ).

.SH ПАРАМЕТРЫ

.PP
.TP
\fB\-p\fR, \fB\-\-port\fR=\fIПОРТ\fR
использовать TCP порт \fIПОРТ\fR для начальной синхронизации (по умолчанию 18515)
.TP
\fB\-d\fR, \fB\-\-ib\-dev\fR=\fIУСТРОЙСТВО\fR
использовать устройство IB \fIУСТРОЙСТВО\fR (по умолчанию первое найденное устройство)
.TP
\fB\-i\fR, \fB\-\-ib\-port\fR=\fIПОРТ\fR
использовать порт IB \fIПОРТ\fR (по умолчанию порт 1)
.TP
\fB\-s\fR, \fB\-\-size\fR=\fIРАЗМЕР\fR
размер сообщений для пинг-понга \fIРАЗМЕР\fR (по умолчанию 4096)
.TP
\fB\-m\fR, \fB\-\-mtu\fR=\fIMTU\fR
использовать MTU пути размером \fIMTU\fR (по умолчанию 2048)
.TP
\fB\-c\fR, \fB\-\-clients\fR=\fIКЛИЕНТЫ\fR
количество клиентов \fIКЛИЕНТЫ\fR (только на сервере, по умолчанию 1)
.TP
\fB\-n\fR, \fB\-\-num\-tests\fR=\fIЧИСЛО_ТЕСТОВ\fR
выполнить \fIЧИСЛО_ТЕСТОВ\fR тестов на клиента (по умолчанию 5)
.TP
\fB\-l\fR, \fB\-\-sl\fR=\fISL\fR
использовать \fISL\fR в качестве значения уровня обслуживания (по умолчанию 0)
.TP
\fB\-e\fR, \fB\-\-events\fR
ожидать событий завершения работы в режиме сна (по умолчанию опрос завершений)
.TP
\fB\-g\fR, \fB\-\-gid-idx\fR=\fIИНДЕКС_GID\fR
локальный порт \fIИНДЕКС_GID\fR

.SH СМ. ТАКЖЕ
.BR ibv_rc_pingpong (1),
.BR ibv_uc_pingpong (1),
.BR ibv_ud_pingpong (1)
.BR ibv_srq_pingpong (1)

.SH АВТОРЫ
.TP
Roland Dreier
.RI < roland@purestorage.com >
.TP
Jarod Wilson
.RI < jarod@redhat.com >

.SH ИЗВЕСТНЫЕ ОШИБКИ
Сетевая синхронизация между экземплярами клиента и сервера
ненадёжна и не предотвращает использование несовместимых параметров в
двух экземплярах. Метод получения завершений работы не является
строго корректным, и состояния гонки могут вызывать сбои на некоторых
системах.
