.\" Licensed under the OpenIB.org BSD license (FreeBSD Variant) - See COPYING.md
.\" FRDP path ./contrib/ofed/libibverbs/man/ibv_devices.1
.\" FRDP githash d6b92ffa990dc57d8a969a98e3ca4e25ba39cbb2
.\" FRDP hash256 7b643648ee18843e7ffd2c13922d1943656e2bffbb5ad72024df8ae0086506cc
.SH ИМЯ
ibv_devices \- список устройств RDMA

.SH СИНТАКСИС
.B ibv_devices

.SH ОПИСАНИЕ
.PP
Выводит список устройств RDMA, доступных для использования из пользовательского пространства.

.SH СМ. ТАКЖЕ
.BR ibv_devinfo (1)

.SH АВТОРЫ
.TP
Roland Dreier
.RI < rolandd@cisco.com >
