.\" FRDP path ./contrib/ldns/packaging/ldns-config.1
.\" FRDP githash 986ba33c7a3bc8f5ba13c7a9d6512602f6e32c61
.\" FRDP hash256 b82dd1cbe46d436502d8197773bf93615bc184975912579ccf1038c66d368390
.SH ИМЯ
ldns-config \- отображение флагов компилятора и компоновщика для использования ldns.
.SH СИНТАКСИС
.B ldns-config
[
.IR ОПЦИИ
]

.SH ОПИСАНИЕ
При написании программ с использованием ldns необходимо указывать компилятору,
где искать включаемые файлы и какие библиотеки из какого расположения
использовать при компоновке. \fBldns-config\fR позволяет определить,
какие флаги следует использовать с компилятором C и компоновщиком.

.SH ОПЦИИ
.TP
\fB--cflags\fR
Показать флаги компилятора C, необходимые для компиляции с ldns.

.TP
\fB--libs\fR
Показать флаги, используемые для компоновки с ldns.

.TP
\fB--version\fR
Показать версию установленной библиотеки ldns.

.TP
\fB--libversion\fR
Показать версию двоичного API установленной библиотеки ldns.

.TP
\fB--help\fR
Показать описание использования \fBldns-config\fR.

.SH АВТОРЫ
Написано командой разработчиков ldns.

.SH СООБЩЕНИЕ ОБ ОШИБКАХ
Сообщения об ошибках отправлять по адресу <ldns-team@nlnetlabs.nl>.

.SH АВТОРСКИЕ ПРАВА
Авторские права (C) 2011 NLnet Labs. Это свободное программное обеспечение.
НИКАКИХ ГАРАНТИЙ НЕ ПРЕДОСТАВЛЯЕТСЯ, даже на ПРИГОДНОСТЬ ДЛЯ КОНКРЕТНОЙ ЦЕЛИ.
