.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)logname.1	8.1 (Berkeley) 6/9/93
.\"
.\" FRDP path ./usr.bin/logname/logname.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 0dc06e92e0c4710c1311f4e500a6e1a65a47730841e01f3bbc701d1913428451
.Dd 9 июня 1993
.Dt LOGNAME 1
.Os
.Sh ИМЯ
.Nm logname
.Nd отобразить имя входа пользователя
.Sh СИНТАКСИС
.Nm
.Sh ОПИСАНИЕ
Утилита
.Nm
записывает имя входа пользователя в стандартный вывод,
за которым следует символ новой строки.
.Pp
Утилита
.Nm
явно игнорирует переменные окружения
.Ev LOGNAME
и
.Ev USER,
поскольку окружению нельзя доверять.
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh СМ. ТАКЖЕ
.Xr who 1 ,
.Xr whoami 1 ,
.Xr getlogin 2
.Sh СТАНДАРТЫ
Ожидается, что утилита
.Nm
соответствует
.St -p1003.2 .
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Bx 4.4 .
