.\"
.\" FRDP path ./share/examples/ipfilter/mkfilters.1
.\" FRDP githash b2c76c41be32f904179efed29c0ca04d53f3996c
.\" FRDP hash256 5870d60dd4a97a5307c7627419c0bf58ecb777eb0c16735aecd72254916241df
.TH MKFILTERS 1
.SH ИМЯ
mkfilters \- создание минимального набора правил межсетевого экрана для ipfilter
.SH СИНТАКСИС
.B mkfilters
.SH ФАЙЛЫ
/usr/share/examples/ipfilter/mkfilters
.SH ОПИСАНИЕ
.PP
\fBmkfilters\fP \- это perl-скрипт, который создаёт минимальный набор правил фильтрации для использования с \fBipfilter\fP путём анализа вывода команды \fBifconfig\fP.
.DT
.SH СМ. ТАКЖЕ
ipf(8), ipf(5), ipfilter(5), ifconfig(8)
