.\" $Id$
.\"
.\" FRDP path ./crypto/heimdal/appl/rcp/rcp.1
.\" FRDP githash ae77177087c655fc883075af4f425b37e032cd05
.\" FRDP hash256 76a8df714686f571bf9a833ea5f6a2c50892588e613a865a89a4edd9c7ac3f40
.Dd 16 апреля 2003
.Dt RCP 1
.Os HEIMDAL
.Sh ИМЯ
.Nm rcp
.Nd копирование файлов на удалённые машины и с них
.Sh СИНТАКСИС
.Nm rcp
.Op Fl 45FKpxz
.Op Fl P Ar порт
.Ar файл1 файл2
.Nm rcp
.Op Fl 45FKprxz
.Op Fl P Ar порт
.Ar файл... каталог
.Sh ОПИСАНИЕ
.Nm rcp
копирует файлы между машинами. Каждый аргумент файла является либо удалённым именем файла вида
.Dq имя@хост:путь
либо локальным файлом (не содержащим двоеточия или содержащим слэш перед первым двоеточием).
.Pp
Поддерживаемые опции:
.Bl -tag -width Ds
.It Xo
.Fl 4 ,
.Fl 5 ,
.Fl K ,
.Fl F ,
.Fl x ,
.Fl z
.Xc
Эти опции передаются в
.Xr rsh 1 .
.It Fl P Ar порт
Эта опция передаст параметр
.Fl p Ar порт
в
.Xr rsh 1 .
.It Fl p
Сохранять права доступа к файлам.
.It Fl r
Рекурсивное копирование исходных каталогов.
.El
.Sh ДИАГНОСТИКА
.Nm rcp
реализован как протокол поверх
.Xr rsh 1 ,
и поэтому требует работоспособного rsh. Если планируется использовать аутентификацию Kerberos, rsh должен поддерживать Kerberos, иначе могут появиться дополнительные
.Sh ИСТОРИЯ
Утилита
.Nm rcp
впервые появилась в 4.2BSD. Данная версия основана на 4.3BSD-Reno.
