.\" Licensed under the OpenIB.org BSD license (FreeBSD Variant) - See COPYING.md
.\" FRDP path ./contrib/ofed/librdmacm/man/rdma_client.1
.\" FRDP githash d6b92ffa990dc57d8a969a98e3ca4e25ba39cbb2
.\" FRDP hash256 69566b0554f571272e597f16d77ad28018bdcc2fe76d66dd0d50a46b900e7563
.SH ИМЯ
rdma_client \- простой тест соединения RDMA CM и пинг-понг.
.SH СИНТАКСИС
.sp
.nf
\fIrdma_client\fR [-s адрес_сервера] [-p порт_сервера]
.fi
Использует синхронные вызовы librdmam для установки RDMA соединения между
двумя узлами. Этот пример предназначен для предоставления очень простого
кодового примера использования RDMA.
.TP
\-s адрес_сервера
Указывает адрес системы, на которой запущен rdma_server.
По умолчанию клиент попытается подключиться к серверу, используя
127.0.0.1.
.TP
\-p порт_сервера
Указывает номер порта, который прослушивает сервер. По умолчанию сервер
прослушивает порт 7471.
Основное использование: запустить rdma_server, затем подключиться к серверу с помощью
программы rdma_client.
.P
Поскольку этот тест отображает ресурсы RDMA в пользовательское пространство, пользователи должны убедиться,
что у них есть доступные системные ресурсы и разрешения. Дополнительные детали см. в
файле README libibverbs.
rdma_cm(7), udaddy(1), mckey(1), rping(1), rdma_server(1)
