.\" FRDP path sbin/fsck/fsck.8
.\" FRDP githash fa9896e082a1046ff4fbc75fcba4d18d1f2efc19
.\" FRDP hash256 0f5ac6ffa47a746bab421225143d91827768f730448ab0971cf6b5129761a9f2
.Dd March 5, 2019
.Dt FSCK 8
.Os
.Sh ИМЯ
.Nm fsck
.Nd проверка целостности файловой системы и интерактивное восстановление
.Sh СИНТАКСИС
.Nm
.Op Fl Cdfnpvy
.Op Fl B | F
.Op Fl T Ar fstype : Ns Ar fsoptions
.Op Fl t Ar fstype
.Op Fl c Ar fstab
.Oo Ar special | node Oc ...
.Sh ОПИСАНИЕ
Утилита
.Nm
вызывает программы, специфичные для файловых систем, для проверки
специальных устройств, перечисленных в файле
.Xr fstab 5
или в командной строке, на целостность.
.Pp
Обычно она используется в сценарии
.Pa /etc/rc
во время автоматической перезагрузки.
Традиционно
.Nm
вызывается до монтирования файловых систем,
и все проверки выполняются до завершения в это время.
Если доступна фоновая проверка,
.Nm
вызывается дважды.
Сначала она вызывается в традиционное время,
до монтирования файловых систем, с
флагом
.Fl F
для проверки всех файловых систем,
которые не могут выполнять фоновую проверку.
Затем она вызывается второй раз,
после того как система завершила переход в многопользовательский режим, с
флагом
.Fl B
для проверки всех файловых систем,
которые могут выполнять фоновую проверку.
В отличие от проверки на переднем плане,
фоновая проверка запускается асинхронно,
чтобы другая системная активность могла продолжаться
даже на файловых системах, которые проверяются.
.Pp
Если файловые системы не указаны,
.Nm
читает таблицу
.Pa /etc/fstab
для определения, какие файловые системы проверять.
Проверяются только разделы в
.Pa /etc/fstab ,
которые смонтированы как
.Dq rw ,
.Dq rq
или
.Dq ro
и имеют ненулевой номер прохода.
Файловые системы с номером прохода 1 (обычно только корневая файловая система)
всегда проверяются по одной за раз.
.Pp
Если не в режиме preen, остальные записи проверяются в порядке
возрастания номера прохода по одной за раз.
Это необходимо, когда требуется взаимодействие с
.Nm .
.Pp
В режиме preen, после завершения прохода 1, все остальные файловые системы проверяются
в порядке номеров проходов, запуская по одному процессу на дисковод параллельно для каждого
номера прохода в возрастающем порядке.
.Pp
Другими словами: в режиме preen все разделы прохода 1 проверяются последовательно.
Затем все разделы прохода 2 проверяются параллельно, по одному процессу на дисковод.
Затем все разделы прохода 3 проверяются параллельно, по одному процессу на дисковод.
и т. д.
.Pp
Дисковод, содержащий каждую файловую систему, выводится из кратчайшего префикса
имени устройства, заканчивающегося цифрой; остальные символы считаются
обозначениями раздела и слайса.
.Pp
Если флаги
.Fl t
или
.Fl T
не указаны,
.Nm
попытается определить тип файловой системы и вызвать
соответствующую утилиту проверки файловой системы.
Неудача в определении типа файловой системы заставит
.Nm
завершиться с ошибкой и сообщением, что раздел имеет неизвестный тип файловой системы.
.Pp
Параметры следующие:
.Bl -tag -width indent
.It Fl C
Проверить, установлен ли флаг
.Dq clean
в суперблоке, и пропустить проверки файловой системы, если файловая система была
правильно размонтирована и помечена как чистая.
.It Fl c Ar fstab
Указать файл
.Pa fstab
для использования.
.It Fl d
Режим отладки.
Просто выводить команды, не выполняя их.
Доступно
только если
.Nm
скомпилирована с поддержкой этого.
.It Fl f
Принудительная проверка файловых систем.
Запуск
.Dq Li fsck -f
игнорирует журнал и выполняет полную
проверку целостности диска, поэтому найдёт и исправит ошибки, о которых
журнал не знает.
.It Fl n
Заставляет
.Nm
.It Fl p
Войти в режим preen.
В режиме preen исправляется только ограниченный класс безобидных
несоответствий файловой системы.
Если встречаются неожиданные несоответствия, вызванные отказами аппаратного или
программного обеспечения, программа проверки
завершится с ошибкой.
См. страницы руководства для отдельных программ проверки,
чтобы получить список типов отказов, которые они исправляют
при работе в режиме preen.
.It Fl F
Запуск в режиме переднего плана.
Программа проверки для каждой файловой системы вызывается с
флагом
.Fl F ,
чтобы определить, желает ли она выполняться как часть
последовательности загрузки,
или она способна выполнять свою работу в фоне после того, как
система загружена и работает.
Ненулевой код выхода указывает, что она хочет работать на переднем плане,
и программа проверки вызывается.
Нулевой код выхода указывает, что она способна работать позже в фоне,
и просто выводится отложенное сообщение.
.It Fl B
Запуск в фоновом режиме.
Программа проверки для каждой файловой системы вызывается с
флагом
.Fl F ,
чтобы определить, желает ли она выполняться как часть
последовательности загрузки,
или она способна выполнять свою работу в фоне после того, как
система загружена и работает.
Ненулевой код выхода указывает, что она хотела работать на переднем плане,
что, как предполагается, уже было сделано, поэтому файловая система пропускается.
Нулевой код выхода указывает, что она способна работать в фоне,
поэтому программа проверки вызывается с
флагом
.Fl B ,
чтобы указать, что должна быть выполнена проверка активной файловой системы.
При работе в фоновом режиме
проверяется только одна файловая система за раз.
Обратите внимание, что фоновая
.Nm
ограничена проверкой только наиболее часто встречающихся
аномалий файловой системы.
При определённых обстоятельствах
некоторые ошибки могут ускользнуть от фоновой
.Nm .
Рекомендуется периодически выполнять проверку на переднем плане
.Nm
на ваших системах и всякий раз, когда вы сталкиваетесь
с паниками, связанными с файловой системой.
.It Fl t Ar fstype
Вызывать
.Nm
только для разделённого запятыми списка типов файловых систем.
Если
список начинается с
.Dq no ,
то вызывать
.Nm
для типов файловых систем, не указанных в списке.
.It Fl v
Выводить команды перед их выполнением.
.It Fl y
Заставляет
.Nm
предполагать «да»
как ответ на все вопросы оператора.
.It Fl T Ar fstype : Ns Ar fsoptions
Список разделённых запятыми параметров, специфичных для файловой системы указанного
типа, в том же формате, что и
.Xr mount 8 .
.El
.Sh ФАЙЛЫ
.Bl -tag -width /etc/fstab -compact
.It Pa /etc/fstab
таблица файловых систем
.El
.Sh СМ. ТАКЖЕ
.Xr fstab 5 ,
.Xr fsck_ffs 8 ,
.Xr fsck_msdosfs 8 ,
.Xr mount 8
.Sh ИСТОРИЯ
Утилита
.Nm
появилась в
.Bx 4.0 .
Она была переписана как независимая от файловой системы обёртка в
.Nx 1.3
и впервые появилась в
.Fx 5.0 .
Исходная утилита, специфичная для файловой системы, стала
.Xr fsck_ffs 8
в этот момент.
