.\" FRDP path sys/contrib/openzfs/man/man8/fsck.zfs.8
.\" FRDP githash 22649d4dba730d46244fd2dff4fd174903c8379f
.\" FRDP hash256 9099685c991ba5b3ffeec904a656f2bb2d4ef11a145fd0a6b54327b22330df75
.Dd May 26, 2021
.Dt FSCK.ZFS 8
.Os
.
.Sh ИМЯ
.Nm fsck.zfs
.Nd фиктивная программа проверки файловой системы ZFS
.Sh СИНТАКСИС
.Nm
.Op Ar options
.Ar dataset Ns No …
.
.Sh ОПИСАНИЕ
.Nm
— это тонкая обёртка-скрипт оболочки, которая в лучшем случае проверяет состояние
пула-контейнера набора данных.
Она устанавливается OpenZFS, потому что некоторые дистрибутивы Linux
ожидают наличие помощника fsck для всех файловых систем.
.Pp
Если указано более одного
.Ar dataset ,
каждый проверяется по очереди, а результаты объединяются побитовым ИЛИ.
.
.Sh ПАРАМЕТРЫ
Игнорируются.
.
.Sh ПРИМЕЧАНИЯ
Наборы данных ZFS проверяются запуском
.Nm zpool Cm scrub
на содержащем пуле.
Отдельный набор данных ZFS никогда не проверяется независимо от его пула,
что отличается от обычной файловой системы.
.Pp
Однако интерфейс
.Xr fsck 8
всё же позволяет ей сообщать о некоторых ошибках: если
.Ar dataset
находится в деградировавшем пуле, то
.Nm
вернёт код выхода
.Sy 4 ,
указывая на неисправленную ошибку файловой системы.
.Pp
Аналогично, если
.Ar dataset
находится в отказавшем пуле и имеет устаревшую запись в
.Pa /etc/fstab ,
то
.Nm
вернёт код выхода
.Sy 8 ,
указывая на фатальную операционную ошибку.
.Sh СМ. ТАКЖЕ
.Xr fstab 5 ,
.Xr fsck 8 ,
.Xr zpool-scrub 8
