.\" FRDP path contrib/atf/atf-sh/atf-check.1
.\" FRDP githash 952231086100bed7130212b5425e44ffd732913b
.\" FRDP hash256 12facaa870b2a0f443ccf93000f6e1d51bc79c1d5090a2ad636bd7a4684ee941
.Dd August 13, 2026
.Dt ATF-CHECK 1
.Os
.Sh ИМЯ
.Nm atf-check
.Nd выполняет команду и анализирует её результаты
.Sh СИНТАКСИС
.Nm
.Op Fl s Ar qual:значение
.Op Fl o Ar действие:аргумент ...
.Op Fl e Ar действие:аргумент ...
.Op Fl x
.Op Fl r Ar таймаут[:интервал]
.Ar команда
.Sh ОПИСАНИЕ
.Nm
выполняет заданную команду и анализирует её результаты, включая
код выхода, stdout и stderr.
.Pp
.Bf Em
Тестовые случаи должны использовать
.Xr atf-sh 3 Ns ' Ns s
.Nm atf_check
встроенную функцию вместо прямого вызова этой утилиты.
.Ef
.Pp
.Nm
выполнит предоставленную команду и применит проверки, указанные
аргументами.
По умолчанию
.Nm
ведёт себя так, как если бы был запущен с
.Fl s
.Ar exit:0
.Fl o
.Ar empty
.Fl e
.Ar empty .
.Pp
.Fl o
.Ar empty
и
.Fl e
.Ar empty
могут быть указаны несколько раз.
Если они указаны несколько раз, проверки будут применяться к
соответствующему потоку в том порядке, в котором они были заданы.
.Pp
Доступны следующие параметры:
.Bl -tag  -width XqualXvalueXX
.It Fl s Ar qual:значение
Анализирует статус завершения.
Допустимые значения:
.Bl -tag -width signal:<value> -compact
.It Ar exit:<значение>
проверяет, что программа завершилась нормально и что её статус выхода равен
.Va значение .
Код выхода можно вообще опустить, и в этом случае принимается любое
нормальное завершение.
.It Ar ignore
игнорирует проверку завершения.
.It Ar signal:<значение>
проверяет, что программа завершилась из-за сигнала, и (необязательно) что
сигнал, завершивший процесс, равен
.Va значение .
Сигнал можно задать числом, именем или вообще опустить
(в этом случае принимается любой сигнал).
.El
.Pp
Большинство этих проверок можно предварить строкой
.Sq not-
, что фактически инвертирует проверку.
.It Fl o Ar действие:аргумент
Анализирует стандартный вывод.
Допустимые значения:
.Bl -tag -width inline:<value> -compact
.It Ar empty
проверяет, что stdout пуст
.It Ar ignore
игнорирует stdout
.It Ar file:<путь>
сравнивает stdout с заданным файлом
.It Ar inline:<значение>
сравнивает stdout со встроенным значением
.It Ar match:<regexp>
ищет регулярное выражение в stdout
.It Ar save:<путь>
сохраняет stdout в заданный файл
.El
.Pp
Большинство этих проверок можно предварить строкой
.Sq not-
, что фактически инвертирует проверку.
.It Fl e Ar действие:аргумент
Анализирует стандартный поток ошибок.
Использование идентично
.Fl o .
.It Fl x
Выполняет
.Ar команда
как командную строку оболочки, запуская её с помощью системной оболочки, определённой в
.Va ATF_SHELL .
Следует по возможности избегать использования этого флага, чтобы предотвратить
проблемы с экранированием в оболочке.
.It Fl r Ar таймаут[:интервал]
Повторяет неудачные проверки, пока не истечёт
.Ar таймаут
(в секундах).
Если не указан, по умолчанию
.Ar интервал
(в миллисекундах) равен 50 мс.
Это можно использовать для ожидания предполагаемого обновления содержимого файла.
.El
.Sh ОКРУЖЕНИЕ
.Bl -tag -width ATFXSHELLXX -compact
.It Va ATF_SHELL
Путь к системной оболочке, используемой, когда
.Fl x
задан для запуска команд.
.El
.Sh СТАТУС ВЫХОДА
.Nm
завершается с кодом 0 при успехе и другим (неопределённым) значением при неудаче.
.Sh ПРИМЕРЫ
Ниже приведены примеры вызовов из тестового случая.
Обратите внимание, что мы используем функцию
.Nm atf_check
предоставляемую
.Xr atf-sh 3
вместо прямого выполнения
.Nm
:
.Bd -literal -offset indent
# Код выхода 0, ничего в stdout/stderr
atf_check true

# Типичное использование, если ожидается сбой
atf_check -s not-exit:0 false

# Проверка stdout/stderr
echo foobar >expout

# Проверка на аварийное завершение
atf_check -s signal:sigsegv my_program

# Комбинированные проверки
atf_check -o match:foo -o not-match:bar echo foo baz

# Ожидание 5 секунд появления строки в файле
atf-check -o ignore -e ignore -s exit:0 -r 5 \e
.Ed
.Sh СМ. ТАКЖЕ
.Xr atf-sh 1
