.\" FRDP path contrib/one-true-awk/awk.1
.\" FRDP githash eb690a0576e8cf5412124477eace3bb765068c3d
.\" FRDP hash256 743dee3c3bba4847553c70c344237305d3b6276b53d6fdf92eb112b79fb334a1
.de EX
.nf
.ft CW
..
.de EE
.br
.fi
.ft 1
..
.de TF
.PD 0
..
.TH AWK 1
.CT 1 files prog_other
.SH ИМЯ
awk \- язык сканирования и обработки с управлением по шаблонам
.SH СИНТАКСИС
.B awk
[
.BI \-F
.I fs
|
.B \-\^\-csv
]
[
.BI \-v
.I var=value
]
[
.I 'prog'
|
.BI \-f
.I progfile
]
[
.I file ...
]
.SH ОПИСАНИЕ
.I Awk
сканирует каждый входной
.I file
в поисках строк, соответствующих любому из набора шаблонов, заданных буквально в
.I prog
или в одном либо нескольких файлах,
указанных как
.B \-f
.IR progfile .
С каждым шаблоном
может быть связано действие, которое будет выполнено,
когда строка
.I file
соответствует шаблону.
Каждая строка сопоставляется с
частью-шаблоном каждого оператора шаблон-действие;
связанное действие выполняется для каждого совпавшего шаблона.
Имя файла
.B \-
означает стандартный ввод.
Любой
.I file
вида
.I var=value
рассматривается как присваивание, а не как имя файла,
и выполняется в тот момент, когда он был бы открыт, если бы был именем файла.
Параметр
.B \-v
с последующим
.I var=value
— это присваивание, которое нужно выполнить до
выполнения
.I prog ;
может присутствовать любое количество
параметров
.B \-v .
Параметр
.B \-F
.I fs
определяет разделитель полей ввода как регулярное выражение
.IR fs .
Параметр
.B \-\^\-csv
заставляет
.I awk
обрабатывать записи, используя (более или менее) стандартный формат
значений, разделённых запятыми (CSV).
.PP
Входная строка обычно состоит из полей, разделённых пробельными символами
или регулярным выражением
.BR FS .
Поля обозначаются
.BR $1 ,
.BR $2 ,
\&..., тогда как
.B $0
относится ко всей строке.
Если
.BR FS
пусто, входная строка разбивается на одно поле на символ.
.PP
Оператор шаблон-действие имеет форму:
.IP
.PP
Отсутствующее
означает вывести строку;
отсутствующий шаблон всегда соответствует.
Операторы шаблон-действие разделяются символами новой строки или точками с запятой.
.PP
Действие — это последовательность операторов.
Оператор может быть одним из следующих:
.PP
.EX
.ta \w'\f(CWdelete array[expression]\fR'u
.RS
.nf
.ft CW
if(\fI expression \fP)\fI statement \fP\fR[ \fPelse\fI statement \fP\fR]\fP
while(\fI expression \fP)\fI statement\fP
for(\fI expression \fP;\fI expression \fP;\fI expression \fP)\fI statement\fP
for(\fI var \fPin\fI array \fP)\fI statement\fP
do\fI statement \fPwhile(\fI expression \fP)
break
continue
{\fR [\fP\fI statement ... \fP\fR] \fP}
\fIexpression\fP	#\fR commonly\fP\fI var = expression\fP
print\fR [ \fP\fIexpression-list \fP\fR] \fP\fR[ \fP>\fI expression \fP\fR]\fP
printf\fI format \fP\fR[ \fP,\fI expression-list \fP\fR] \fP\fR[ \fP>\fI expression \fP\fR]\fP
return\fR [ \fP\fIexpression \fP\fR]\fP
next	#\fR skip remaining patterns on this input line\fP
nextfile	#\fR skip rest of this file, open next, start at top\fP
delete\fI array\fP[\fI expression \fP]	#\fR delete an array element\fP
delete\fI array\fP	#\fR delete all elements of array\fP
exit\fR [ \fP\fIexpression \fP\fR]\fP	#\fR exit immediately; status is \fP\fIexpression\fP
.fi
.RE
.EE
.DT
.PP
Операторы завершаются
точками с запятой, символами новой строки или правыми фигурными скобками.
Пустой
.I expression-list
означает
.BR $0 .
с обычными escape-последовательностями C, распознаваемыми внутри.
Выражения принимают строковые или числовые значения по обстоятельствам
и строятся с использованием операторов
.B + \- * / % ^
(возведение в степень) и конкатенации (обозначаемой пробельным символом).
Операторы
.B
! ++ \-\- += \-= *= /= %= ^= > >= < <= == != ?:
также доступны в выражениях.
Переменные могут быть скалярами, элементами массива
(обозначаемыми
.IB x  [ i ] \fR)
или полями.
Переменные инициализируются пустой строкой.
Индексы массива могут быть любой строкой,
не обязательно числовой;
это допускает форму ассоциативной памяти.
Множественные индексы, такие как
.B [i,j,k]
допускаются; составляющие конкатенируются,
разделяясь значением
.BR SUBSEP .
.PP
Оператор
.B print
выводит свои аргументы в стандартный вывод
(или в файл, если
или
присутствует, или в конвейер, если
присутствует), разделяя их текущим разделителем полей вывода
и завершая их разделителем записей вывода.
.I file
и
.I cmd
могут быть буквальными именами или выражениями в скобках;
идентичные строковые значения в разных операторах обозначают
один и тот же открытый файл.
Оператор
.B printf
форматирует свой список выражений согласно
.I format
(см.
.IR printf (3)).
Встроенная функция
.BI close( expr )
закрывает файл или конвейер
.IR expr .
Встроенная функция
.BI fflush( expr )
сбрасывает любой буферизованный вывод для файла или конвейера
.IR expr .
.PP
Математические функции
.BR atan2 ,
.BR cos ,
.BR exp ,
.BR log ,
.BR sin
и
.B sqrt
являются встроенными.
Другие встроенные функции:
.TP
\fBlength(\fR[\fIv\^\fR]\fB)\fR
длина её аргумента,
взятого как строка,
количество элементов в массиве для аргумента-массива
или длина
.B $0
при отсутствии аргумента.
.TP
.B rand()
случайное число на [0,1).
.TP
\fBsrand(\fR[\fIs\^\fR]\fB)\fR
устанавливает начальное значение для
.B rand
и возвращает предыдущее начальное значение.
.TP
.BI int( x\^ )
усекает до целого значения.
.TP
\fBsubstr(\fIs\fB, \fIm\fR [\fB, \fIn\^\fR]\fB)\fR
подстрока из
.IR n -символов
строки
.I s
начиная с позиции
.I m
считая от 1.
Если
.IR n
не указано, использовать остаток строки.
.TP
позиция в
.I s
где встречается строка
.I t
или 0, если она не встречается.
.TP
позиция в
.I s
где встречается регулярное выражение
.I r
или 0, если оно не встречается.
Переменные
.B RSTART
и
.B RLENGTH
устанавливаются в позицию и длину совпавшей строки.
.TP
\fBsplit(\fIs\fB, \fIa \fR[\fB, \fIfs\^\fR]\fB)\fR
разбивает строку
.I s
на элементы массива
.IB a [1] \fR,
.IB a [2] \fR,
\&...,
.IB a [ n ] \fR
и возвращает
.IR n .
Разделение выполняется с помощью регулярного выражения
.I fs
или с помощью разделителя полей
.B FS ,
если
.I fs
не задано.
Пустая строка в качестве разделителя полей разбивает строку
на один элемент массива на символ.
.TP
\fBsub(\fIr\fB, \fIt \fR[, \fIs\^\fR]\fB)
заменяет
.I t
на первое вхождение регулярного выражения
.I r
в строке
.IR s .
Если
.I s
не задано,
используется
.B $0 .
.TP
\fBgsub(\fIr\fB, \fIt \fR[, \fIs\^\fR]\fB)
то же, что и
.B sub ,
за исключением того, что заменяются все вхождения регулярного выражения;
.B sub
и
.B gsub
возвращают количество замен.
.TP
\fBgensub(\fIpat\fB, \fIrepl\fB, \fIhow\fR [\fB, \fItarget\fR]\fB)\fR
заменяет вхождения
.I pat
в
.I target
на
.IR repl .
Если
.I how
.I how
— это число, указывающее, какое вхождение заменить. Если нет
.IR target ,
использовать
.BR $0 .
Вернуть результирующую строку;
.I target
не изменяется.
.TP
строка, полученная в результате форматирования
.I expr ...
согласно формату
.IR printf (3)
.IR fmt .
.TP
.B systime()
возвращает текущую дату и время как стандартное
значение ``секунды с начала эпохи''.
.TP
форматирует
.I timestamp
(значение в секундах с начала эпохи)
согласно
.IR fmt ,
которая является строкой формата, поддерживаемой
.IR strftime (3).
Как
.I timestamp ,
так и
.I fmt
могут быть опущены; если нет
.IR timestamp ,
используется текущее время суток, а если нет
.IR fmt ,
.TP
.BI system( cmd )
выполняет
.I cmd
и возвращает её статус выхода. Это будет \-1 при ошибке,
статус выхода
.IR cmd
при нормальном завершении,
256 +
.I sig
при смерти от сигнала, где
.I sig
— номер убивающего сигнала,
или 512 +
.I sig
если был дамп ядра.
.TP
.BI tolower( str )
возвращает копию
.I str
со всеми символами верхнего регистра, переведёнными в их
соответствующие эквиваленты нижнего регистра.
.TP
.BI toupper( str )
возвращает копию
.I str
со всеми символами нижнего регистра, переведёнными в их
соответствующие эквиваленты верхнего регистра.
.PD
.PP
``Функция''
.B getline
устанавливает
.B $0
в следующую входную запись из текущего входного файла;
.B getline
устанавливает
.B $0
в следующую запись из
.IR file .
.B getline
.I x
вместо этого устанавливает переменную
.I x .
Наконец,
направляет вывод
.I cmd
в
.BR getline ;
каждый вызов
.B getline
возвращает следующую строку вывода из
.IR cmd .
Во всех случаях
.B getline
возвращает 1 при успешном вводе,
0 при конце файла и \-1 при ошибке.
.PP
Функции
.BR compl ,
.BR and ,
.BR or ,
.BR xor ,
.BR lshift
и
.B rshift
выполняют соответствующие побитовые операции над своими
операндами, которые сначала усекаются до целых.
.PP
Шаблоны — это произвольные булевы комбинации
(с
регулярных выражений и
реляционных выражений.
Регулярные выражения такие же, как в
.IR egrep ;
см.
.IR grep (1).
Изолированные регулярные выражения
в шаблоне применяются ко всей строке.
Регулярные выражения также могут встречаться в
реляционных выражениях с использованием операторов
.B ~
и
.BR !~ .
.BI / re /
— это константное регулярное выражение;
любая строка (константа или переменная) может использоваться
как регулярное выражение, кроме позиции изолированного регулярного выражения
в шаблоне.
.PP
Шаблон может состоять из двух шаблонов, разделённых запятой;
в этом случае действие выполняется для всех строк
от вхождения первого шаблона
до вхождения второго, включительно.
.PP
Реляционное выражение — это одно из следующих:
.IP
.I expression matchop regular-expression
.br
.I expression relop expression
.br
.br
.PP
где
.I relop
— любой из шести реляционных операторов в C,
а
.I matchop
— либо
.B ~
(соответствует),
либо
.B !~
(не соответствует).
Условие — это арифметическое выражение,
реляционное выражение
или булева комбинация
из них.
.PP
Специальные шаблоны
.B BEGIN
и
.B END
можно использовать для захвата управления до чтения первой входной строки
и после последней.
.B BEGIN
и
.B END
не комбинируются с другими шаблонами.
Они могут появляться в программе несколько раз и выполняются
в том порядке, в котором они прочитаны
.IR awk .
.PP
Имена переменных со специальными значениями:
.TF FILENAME
.TP
.B ARGC
количество аргументов, присваиваемое.
.TP
.B ARGV
массив аргументов, присваиваемый;
непустые члены принимаются как имена файлов.
.TP
.B CONVFMT
формат преобразования, используемый при преобразовании чисел
(по умолчанию
.TP
.B ENVIRON
массив переменных окружения; индексы — это имена.
.TP
.B FILENAME
имя текущего входного файла.
.TP
.B FNR
порядковый номер текущей записи в текущем файле.
.TP
.B FS
регулярное выражение, используемое для разделения полей; также задаётся
параметром
.BI \-F fs\fR.
.TP
.BR NF
количество полей в текущей записи.
.TP
.B NR
порядковый номер текущей записи.
.TP
.B OFMT
формат вывода для чисел (по умолчанию
.TP
.B OFS
разделитель полей вывода (по умолчанию пробел).
.TP
.B ORS
разделитель записей вывода (по умолчанию символ новой строки).
.TP
.B RLENGTH
длина строки, совпавшей с
.BR match .
.TP
.B RS
разделитель входных записей (по умолчанию символ новой строки).
Если пусто, пустые строки разделяют записи.
Если длиной более одного символа,
.B RS
рассматривается как регулярное выражение, и записи
разделяются текстом, соответствующим выражению.
.TP
.B RSTART
начальная позиция строки, совпавшей с
.BR match .
.TP
.B SUBSEP
разделяет множественные индексы (по умолчанию 034).
.PD
.PP
Функции могут быть определены (в позиции оператора шаблон-действие) так:
.IP
.B
function foo(a, b, c) { ... }
.PP
Параметры передаются по значению, если скаляр, и по ссылке, если имя массива;
функции могут вызываться рекурсивно.
Параметры локальны для функции; все остальные переменные глобальны.
Таким образом, локальные переменные можно создать, указав избыточные параметры в
определении функции.
.SH ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
Если
.B POSIXLY_CORRECT
установлена в окружении, то
.I awk
следует правилам POSIX для
.B sub
и
.B gsub
в отношении последовательных обратных косых черт и амперсандов.
.SH ПРИМЕРЫ
.TP
.EX
length($0) > 72
.EE
Вывести строки длиннее 72 символов.
.TP
.EX
{ print $2, $1 }
.EE
Вывести первые два поля в обратном порядке.
.PP
.EX
      { print $2, $1 }
.EE
.ns
.IP
То же, с полями ввода, разделёнными запятой и/или пробелами и табуляциями.
.PP
.EX
.nf
	{ s += $1 }
.fi
.EE
.ns
.IP
Сложить первый столбец, вывести сумму и среднее.
.TP
.EX
/start/, /stop/
.EE
Вывести все строки между парами start/stop.
.PP
.EX
.nf
BEGIN	{	# Simulate echo(1)
	exit }
.fi
.EE
.SH СМ. ТАКЖЕ
.IR grep (1),
.IR lex (1),
.IR sed (1)
.br
A. V. Aho, B. W. Kernighan, P. J. Weinberger,
Addison-Wesley, 2024.  ISBN 978-0-13-826972-2, 0-13-826972-6.
.SH ИЗВЕСТНЫЕ ОШИБКИ
Нет явных преобразований между числами и строками.
Чтобы заставить выражение рассматриваться как число, добавьте к нему 0;
чтобы заставить его рассматриваться как строка, конкатенируйте
.PP
Правила области видимости для переменных в функциях — это мешанина;
синтаксис ещё хуже.
.PP
Ожидается, что ввод закодирован в UTF-8. Другие многобайтовые
наборы символов не обрабатываются.
Однако в восьмибитных локалях
.I awk
обрабатывает каждый входной байт как отдельный символ.
.SH НЕОБЫЧНЫЕ ЗНАЧЕНИЯ С ПЛАВАЮЩЕЙ ТОЧКОЙ
.I Awk
был разработан до того, как арифметика IEEE 754 определила значения
Not-A-Number (NaN) и бесконечности, которые поддерживаются всем современным оборудованием
с плавающей точкой.
.PP
Поскольку
.I awk
использует
.IR strtod (3)
и
.IR atof (3)
для преобразования строковых значений в значения с плавающей точкой двойной точности,
современные библиотеки C также преобразуют строки, начинающиеся с
.B inf
и
.B nan ,
в бесконечность и NaN соответственно. Это привело к странным результатам,
например таким:
.PP
.EX
.nf
echo nancy | awk '{ print $1 + 0 }'
.fi
.EE
.PP
выводит
.B nan
вместо нуля.
.PP
.I Awk
теперь следует GNU AWK и предварительно фильтрует строковые значения перед попыткой
преобразовать их в числа следующим образом:
.TP
Шестнадцатеричные значения (разрешённые с C99) преобразуются в ноль, как это было
до C99.
.TP
Две строки
.B +nan
и
.B \-nan
(независимо от регистра) преобразуются в NaN. Никакие другие — нет.
(NaN могут иметь знаки.)
.TP
Две строки
.B +inf
и
.B \-inf
(независимо от регистра) преобразуются в положительную и отрицательную бесконечность соответственно.
Никакие другие — нет.
