.\" FRDP path usr.bin/compress/compress.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 e1bc78d1d33cc3a593993e558a5d46cea0f77687e2b304b6aa8da3dd0236cc67
.Dd March 4, 2021
.Dt COMPRESS 1
.Os
.Sh ИМЯ
.Nm compress ,
.Nm uncompress
.Nd сжимать и разворачивать данные
.Sh СИНТАКСИС
.Nm
.Op Fl fv
.Op Fl b Ar bits
.Op Ar
.Nm
.Fl c
.Op Fl b Ar bits
.Op Ar file
.Nm uncompress
.Op Fl f
.Op Ar
.Nm uncompress
.Fl c
.Op Ar file
.Sh ОПИСАНИЕ
Утилита
.Nm
уменьшает размер файлов, используя адаптивное кодирование Лемпеля-Зива.
Каждый
.Ar file
переименовывается в то же имя с добавлением расширения
.Pa .Z .
Аргумент
.Ar file
с расширением
.Pa .Z
будет проигнорирован, за исключением того, что это вызовет
аварийное завершение после обработки остальных аргументов.
Если сжатие не уменьшило бы размер
.Ar file ,
файл игнорируется.
.Pp
Утилита
.Nm uncompress
восстанавливает сжатые файлы в их исходную форму, переименовывая
файлы путём удаления расширений
.Pa .Z .
В спецификации файла не обязательно указывать расширение
.Pa .Z
файла.
Если имя файла в его файловой системе не имеет
расширения
.Pa .Z ,
он не будет развёрнут, и это вызовет
аварийное завершение после обработки остальных аргументов.
.Pp
Если переименование файлов привело бы к перезаписи файлов, а стандартное
устройство ввода является терминалом, пользователю выводится запрос (в стандартный поток ошибок)
на подтверждение.
Если запрос невозможен или подтверждение не получено, файлы
не перезаписываются.
.Pp
Насколько позволяют права доступа, в новом файле сохраняются время модификации,
время доступа, флаги файла, режим файла,
идентификатор пользователя и идентификатор группы.
.Pp
Если файлы не указаны или аргумент
.Ar file
представляет собой одиночное тире
.Pq Sq Fl ,
стандартный ввод сжимается или разворачивается в стандартный вывод.
Если входной или выходной файлы не являются обычными файлами, проверки на
уменьшение размера и перезапись файла не выполняются, входной файл
не удаляется, а атрибуты входного файла не сохраняются
в выходном файле.
.Pp
Параметры следующие:
.It Fl b Ar bits
Размер кода (см. ниже) ограничивается значением
.Ar bits ,
которое должно находиться в диапазоне 9..16.
По умолчанию — 16.
.It Fl c
Сжатый или развёрнутый вывод записывается в стандартный вывод.
Никакие файлы не изменяются.
Параметр
.Fl v
игнорируется.
Сжатие выполняется, даже если результаты окажутся больше
исходных данных.
.It Fl f
Файлы перезаписываются без запроса подтверждения.
Кроме того, для
.Nm compress ,
файлы сжимаются, даже если их размер фактически не уменьшается.
.It Fl v
Выводить процент уменьшения для каждого файла.
Игнорируется командой
.Nm uncompress
или если также используется параметр
.Fl c .
.El
.Pp
Утилита
.Nm
использует модифицированный алгоритм Лемпеля-Зива.
Общие подстроки в файле сначала заменяются 9-битными кодами, начиная с 257.
Когда достигается код 512, алгоритм переключается на 10-битные коды и
продолжает использовать больше битов, пока не будет достигнут
предел, указанный параметром
.Fl b
или его значением по умолчанию.
.Pp
После достижения предела
.Nm
периодически проверяет коэффициент сжатия.
Если он увеличивается,
.Nm
продолжает использовать существующий словарь кодов.
Однако если коэффициент сжатия уменьшается,
.Nm
отбрасывает таблицу подстрок и строит её заново с нуля.
Это позволяет
.Pp
Параметр
.Fl b
недоступен для
.Nm uncompress ,
поскольку параметр
.Ar bits ,
указанный при сжатии,
закодирован в выводе вместе с
магическим числом, чтобы гарантировать, что не будет предпринята
попытка ни развёртывания случайных данных, ни
повторного сжатия сжатых данных.
.Pp
Степень сжатия зависит от размера
входных данных, количества
.Ar bits
на код и распределения общих подстрок.
Как правило, текст, такой как исходный код или английский текст, уменьшается на 50\-60%.
Сжатие, как правило, намного лучше, чем достигаемое кодированием Хаффмана
(как использовалось в исторической команде pack), или адаптивным кодированием Хаффмана
(как использовалось в исторической команде compact), и требует меньше
времени на вычисление.
.Pp
Если
.Ar file
является мягкой или жёсткой ссылкой,
.Nm
заменит её сжатой копией файла, на который указывает ссылка.
Целевой файл ссылки остаётся несжатым.
.Sh СТАТУС ВЫХОДА
.Ex -std compress uncompress
.Pp
Утилита
.Nm compress
завершается с кодом 2, если попытка сжать файл не уменьшила бы его размер,
а параметр
.Fl f
не был указан, и если не произошло других ошибок.
.Sh ПРИМЕРЫ
Создать файл
.Pa test_file
с одной строкой текста:
.Bd -literal -offset indent
.Ed
.Pp
Попытаться уменьшить размер файла, используя 10-битный код, и показать статус выхода:
.Bd -literal -offset indent
$ compress -b 10 test_file
$ echo $?
2
.Ed
.Pp
Попытаться сжать файл и показать процент сжатия:
.Bd -literal -offset indent
$ compress -v test_file
test_file: file would grow; left unmodified
.Ed
.Pp
То же, что и выше, но с принудительным сжатием:
.Bd -literal -offset indent
$ compress -f -v test_file
test_file.Z: 79% expansion
.Ed
.Pp
Сжать и развернуть строку
.Ql hello
на лету:
.Bd -literal -offset indent
hello
.Ed
.Sh СМ. ТАКЖЕ
.Xr gunzip 1 ,
.Xr gzexe 1 ,
.Xr gzip 1 ,
.Xr zcat 1 ,
.Xr zmore 1 ,
.Xr znew 1
.Rs
.%A Welch, Terry A.
.%D June, 1984
.%V 17:6
.%P pp. 8-19
.Re
.Sh СТАНДАРТЫ
Утилиты
.Nm compress
и
.Nm uncompress
соответствуют
.St -p1003.1-2001 .
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Bx 4.3 .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Программа плохо обрабатывает ссылки и не имеет параметров для работы со ссылками.
.Pp
Некоторые из них можно считать иначе недокументированными особенностями.
.Pp
.Nm compress :
Если утилита не сжимает файл, потому что это не уменьшило бы
его размер, и существует файл с тем же именем, но с
расширением
.Pa .Z ,
указанный файл на самом деле не игнорируется, как сказано выше;
это вызывает запрос на подтверждение перезаписи файла с расширением.
Если операция подтверждена, этот файл удаляется.
.Pp
.Nm uncompress :
Если пустой файл сжимается (с использованием
.Fl f ) ,
полученный
.Pa .Z
файл также пуст.
Это кажется правильным, но если затем
.Nm uncompress
используется для этого файла, возникнет ошибка.
.Pp
Обе утилиты: Если используется аргумент
.Sq Fl
и утилита запрашивает пользователя, стандартный ввод
принимается как ответ пользователя на запрос.
.Pp
Обе утилиты:
Если указанный файл не существует, но существует аналогично названный файл с (для
.Nm compress )
или без (для
.Nm uncompress )
расширения
.Pa .Z ,
утилита потратит время пользователя, не
выдавая немедленно сообщение об ошибке об отсутствующем файле и
продолжая работу.
Вместо этого она сначала запрашивает подтверждение перезаписи
существующего файла, а затем не перезаписывает его.
