.\" FRDP path bin/cp/cp.1
.\" FRDP githash 5dc400ff452b0259f0c50474255ebe6e5e02edb9
.\" FRDP hash256 52aaeb5317a9a7fdebaf55a093aef2a2b23d7ecddc660ab4cf65fcb651d579bf
.Dd July 22, 2026
.Dt CP 1
.Os
.Sh ИМЯ
.Nm cp
.Nd копировать файлы
.Sh СИНТАКСИС
.Nm
.Oo
.Fl R
.Op Fl H | Fl L | Fl P
.Oc
.Op Fl f | i | n
.Op Fl alNpsvx
.Ar исходный_файл целевой_файл
.Nm
.Oo
.Fl R
.Op Fl H | Fl L | Fl P
.Oc
.Op Fl f | i | n
.Op Fl alNpsvx
.Ar исходный_файл ... целевой_каталог
.Nm
.Op Fl f | i | n
.Op Fl alNPpsvx
.Ar исходный_файл целевой_файл
.Nm
.Op Fl f | i | n
.Op Fl alNPpsvx
.Ar исходный_файл ... целевой_каталог
.Sh ОПИСАНИЕ
В первой форме синтаксиса утилита
.Nm
копирует содержимое
.Ar исходного_файла
в
.Ar целевой_файл .
Во второй форме синтаксиса
содержимое каждого указанного
.Ar исходного_файла
копируется в
.Ar целевой_каталог .
Имена самих файлов не изменяются.
Если
.Nm
обнаруживает попытку скопировать файл в себя, копирование завершится неудачей.
.Pp
Доступны следующие параметры:
.Bl -tag -width flag
.It Fl H
Если указан параметр
.Fl R ,
символические ссылки в командной строке отслеживаются.
(Символические ссылки, встречающиеся при обходе дерева, не отслеживаются.)
.It Fl L , Fl -dereference
Если указан параметр
.Fl R ,
отслеживаются все символические ссылки.
.It Fl P , Fl -no-dereference
Символические ссылки не отслеживаются.
Это значение по умолчанию, если указан параметр
.Fl R .
.It Fl R , Fl -recursive
Если
.Ar исходный_файл
обозначает каталог,
.Nm
копирует каталог и всё поддерево, связанное с этой точкой.
Если
.Ar исходный_файл
оканчивается на
.Pa / ,
копируется содержимое каталога, а не сам каталог.
Этот параметр также приводит к копированию символических ссылок, а не
к переходу по ним, и к тому, что
.Nm
создаёт специальные файлы, а не копирует их как обычные файлы.
Созданные каталоги имеют тот же режим, что и соответствующий исходный
каталог, без изменений, вносимых umask процесса.
.Pp
Обратите внимание, что
.Nm
копирует жёстко связанные файлы как отдельные файлы.
Если вам нужно сохранить жёсткие ссылки, рассмотрите использование
.Xr tar 1 ,
.Xr cpio 1
или
.Xr pax 1
вместо этого.
.It Fl a , Fl -archive
Режим архивации.
То же, что
.Fl RpP .
.It Fl f , Fl -force
Для каждого существующего пути назначения удалить его и
создать новый файл, не запрашивая подтверждение,
независимо от его прав.
(Параметр
.Fl f
переопределяет любые предыдущие параметры
.Fl i
или
.Fl n .)
.It Fl i , Fl -interactive
Вывести приглашение в стандартный поток ошибок перед копированием файла,
который перезаписал бы существующий файл.
Если ответ из стандартного ввода начинается с символа
.Sq Li y
или
.Sq Li Y ,
предпринимается попытка копирования файла.
(Параметр
.Fl i
переопределяет любые предыдущие параметры
.Fl f
или
.Fl n .)
.It Fl l , Fl -link
Создавать жёсткие ссылки на обычные файлы в иерархии вместо копирования.
.It Fl N
При использовании с
.Fl p
подавлять копирование флагов файлов.
.It Fl n , Fl -no-clobber
Не перезаписывать существующий файл.
(Параметр
.Fl n
переопределяет любые предыдущие параметры
.Fl f
или
.Fl i .)
.It Fl p
Сохранять следующие атрибуты каждого исходного
файла в копии: время модификации, время доступа,
флаги файлов, режим файла, ACL, идентификатор пользователя и идентификатор группы, насколько это позволяют права.
.Pp
Если идентификатор пользователя и идентификатор группы невозможно сохранить, сообщение об ошибке
не выводится и значение выхода не изменяется.
.Pp
Если у исходного файла установлен бит set-user-ID и идентификатор пользователя невозможно
сохранить, бит set-user-ID не сохраняется
в правах копии.
Если у исходного файла установлен бит set-group-ID и идентификатор группы невозможно
сохранить, бит set-group-ID не сохраняется
в правах копии.
Если у исходного файла установлены оба бита set-user-ID и set-group-ID,
и либо идентификатор пользователя, либо идентификатор группы невозможно сохранить,
ни бит set-user-ID, ни бит set-group-ID не сохраняются в правах копии.
.It Fl -sort
Посещать и обходить источники в (нелокализованном) лексикографическом порядке.
Обычно
.Nm
посещает источники в порядке их перечисления в командной строке,
а при рекурсивном обходе обходит их содержимое в том порядке, в котором
его вернуло ядро, — это может быть порядок создания, лексикографический порядок или что-то совсем иное.
С
.Fl -sort
источники и посещаются, и обходятся в лексикографическом порядке.
Это в основном полезно для тестирования.
.It Fl s , Fl -symbolic-link
Создавать символические ссылки на обычные файлы в иерархии вместо копирования.
.It Fl v , Fl -verbose
Быть подробным, показывая как исходный, так и целевой путь каждого файла
по мере копирования.
.It Fl x , Fl -one-file-system
Не обходить точки монтирования файловых систем.
.El
.Pp
Для каждого целевого файла, который уже существует, его содержимое
перезаписывается, если позволяют права.
Его режим, идентификатор пользователя и идентификатор группы
не изменяются, если только не был указан параметр
.Fl p .
.Pp
Во второй форме синтаксиса
.Ar целевой_каталог
должен существовать, если только не указан один
.Ar исходный_файл ,
который является каталогом, и указан флаг
.Fl R .
.Pp
Если целевой файл не существует, используется режим исходного файла
с изменениями, внесёнными маской создания режима файла
.Pf ( Ic umask ,
см.
.Xr csh 1 ) .
Если у исходного файла установлен бит set-user-ID, этот бит удаляется,
если только исходный файл и целевой файл не принадлежат
одному и тому же пользователю.
Если у исходного файла установлен бит set-group-ID, этот бит удаляется,
если только исходный файл и целевой файл не находятся в одной
группе и пользователь не является членом этой группы.
Если установлены оба бита set-user-ID и set-group-ID, все вышеуказанные
условия должны быть выполнены, иначе оба бита удаляются.
.Pp
Для создания или перезаписи файлов требуются соответствующие права.
.Pp
Символические ссылки всегда отслеживаются, если не установлен флаг
.Fl R ,
и в этом случае символические ссылки по умолчанию не отслеживаются.
Флаги
.Fl H
или
.Fl L
(в сочетании с флагом
.Fl R )
заставляют символические ссылки отслеживаться, как описано выше.
Параметры
.Fl H
и
.Fl L
игнорируются, если не указан параметр
.Fl R .
Параметр
.Fl P
можно использовать с
.Fl R
или без него.
Эти параметры переопределяют друг друга, и
действия команды определяются последним указанным.
.Pp
Если
.Nm
получает сигнал
.Dv SIGINFO
(см. аргумент
.Cm status
для
.Xr stty 1 ) ,
текущий входной и выходной файл и процент завершения
будут записаны в стандартный поток ошибок.
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
Создать копию файла
.Pa foo
с именем
.Pa bar :
.Pp
.Dl $ cp foo bar
.Pp
Скопировать группу файлов в каталог
.Pa /tmp :
.Pp
.Dl $ cp *.txt /tmp
.Pp
Скопировать каталог
.Pa junk
и всё его содержимое (включая любые подкаталоги) в каталог
.Pa /tmp :
.Pp
.Dl $ cp -R junk /tmp
.Sh СОВМЕСТИМОСТЬ
Исторические версии утилиты
.Nm
имели параметр
.Fl r .
Эта реализация поддерживает этот параметр, однако его поведение
отличается от исторического поведения
.Fx .
Использование этого параметра
настоятельно не рекомендуется, поскольку поведение зависит от реализации.
В
.Fx ,
.Fl r
является синонимом
.Fl RL
и работает так же, если не изменён другими флагами.
Исторические реализации
.Fl r
отличаются тем, что копируют специальные файлы как обычные
файлы, одновременно воссоздавая иерархию.
.Pp
Параметры
.Fl a ,
.Fl l ,
.Fl N ,
.Fl n ,
.Fl s ,
.Fl v ,
и
.Fl x
являются нестандартными, и их использование в скриптах не рекомендуется.
.Sh СМ. ТАКЖЕ
.Xr mv 1 ,
.Xr umask 2 ,
.Xr fts 3 ,
.Xr symlink 7
.Sh СТАНДАРТЫ
Ожидается, что команда
.Nm
совместима с
.St -p1003.2 .
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v1 .
