.\" FRDP path cddl/usr.bin/ctfmerge/ctfmerge.1
.\" FRDP githash 4f293e32e4529617dd05bd64fd3c22a57a56a355
.\" FRDP hash256 577e9b96741553d0a4ac3fe5d3241aa13cdd7c83ae0db8b4e829475ee7a78161
.Dd June 30, 2026
.Dt CTFMERGE 1
.Os
.Sh ИМЯ
.Nm ctfmerge
.Nd "объединить несколько секций данных CTF в одну"
.Sh СИНТАКСИС
.Nm
.Op Fl fgstv
.Fl l Ar метка
.Fl L Ar имя_переменной_окружения
.Fl o Ar выходной_файл
файл ...
.Nm
.Op Fl fgstv
.Fl l Ar метка
.Fl L Ar имя_переменной_окружения
.Fl o Ar выходной_файл
.Fl d Ar файл_уникализации
.Op Fl g
.Op Fl D Ar метка_уникализации
файл ...
.Nm
.Op Fl fgstv
.Fl l Ar метка
.Fl L Ar имя_переменной_окружения
.Fl o Ar выходной_файл
.Fl w Ar файл_слияния
файл ...
.Nm
.Op Fl g
.Fl c Ar исходный_файл
.Ar конечный_файл
.Sh ОПИСАНИЕ
Утилита
.Nm
объединяет несколько секций данных CTF (Compact C Type Format) из нескольких
файлов в один выходной файл, унифицируя общие данные.
.Pp
Доступны следующие параметры:
.Bl -tag -width indent
.It Fl f
Сопоставлять глобальные символы с глобальными данными CTF.
.It Fl g
Не удалять исходные отладочные секции.
.It Fl s
Использовать секцию ELF .dynsym вместо секции ELF .symtab.
.It Fl t
Убедиться, что все объектные файлы имеют секцию CTF.
.It Fl v
Включить подробный режим.
.It Fl l Ar метка
Устанавливает метку как
.Ar метка .
.It Fl L Ar имя_переменной_окружения
Предписывает
.Nm
прочитать метку из переменной окружения
.Ar имя_переменной_окружения .
.It Fl o Ar выходной_файл
Использовать
.Ar выходной_файл
для сохранения объединённых данных CTF.
.It Fl d Ar файл_уникализации
Уникализировать относительно
.Ar файл_уникализации .
.It Fl D Ar метка_уникализации
Уникализировать относительно метки
.Ar метка_уникализации .
.It Fl w Ar файл_слияния
Аддитивное слияние с
.Ar файл_слияния .
.It Fl c Ar исходный_файл Ar конечный_файл
Копировать данные CTF из
.Ar исходный_файл
в
.Ar конечный_файл .
.El
.Sh ОКРУЖЕНИЕ
Следующие переменные окружения используются программой
.Nm :
.Bl -tag -width indent
.It Ev CTFMERGE_DEBUG_LEVEL
Увеличить подробность отладки
.Pq максимум 3 .
.It Ev CTFMERGE_INPUT_THROTTLE
Максимальный размер очереди для постановки в очередь
.Pq по умолчанию 10 .
.It Ev CTFMERGE_PHASE1_BATCH_SIZE
Количество файлов в слоте, необходимое до начала обработки
.Pq по умолчанию 8 .
.It Ev CTFMERGE_MAX_SLOTS
Количество слотов циклического перебора во входной очереди, которые обрабатываются
рабочими потоками.
Каждый слот представляет пакет файлов
.Pq по умолчанию 5 .
.It Ev CTFMERGE_TERMINATE_NO_UNLINK
Не удалять временные файлы при завершении,
чтобы их можно было исследовать для отладки.
.El
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh СМ. ТАКЖЕ
.Xr ctfconvert 1 ,
.Xr ctfdump 1 ,
.Xr ctf 5
.Sh ИСТОРИЯ
Утилита
.Nm
впервые появилась в
.Fx 7.0 .
.Sh АВТОРЫ
Утилиты CTF взяты из OpenSolaris.
