.\" FRDP path bin/date/date.1
.\" FRDP githash 38839c872e7af6a1424009bf07d6b4450e9ca61d
.\" FRDP hash256 9d4e89c12e2ff7d6d75b94d553beab23d942b13ce888e28e4ff54aa8dfd60a7b
.Dd November 10, 2025
.Dt DATE 1
.Os
.Sh ИМЯ
.Nm date
.Nd "отобразить или установить дату и время"
.Sh СИНТАКСИС
.Nm
.Op Fl nRu
.Op Fl z Ar зона_вывода
.Op Fl I Ns Op Ar FMT
.Op Fl r Ar имя_файла
.Op Fl r Ar секунды
.Oo
.Sm off
.Fl v
.Op Cm + | -
.Ar значение Op Cm y | m | w | d | H | M | S
.Sm on
.Oc
.Op Cm + Ns Ar выходной_формат
.Nm
.Op Fl jnRu
.Op Fl z Ar зона_вывода
.Op Fl I Ns Op Ar FMT
.Oo
.Sm off
.Fl v
.Op Cm + | -
.Ar значение Op Cm y | m | w | d | H | M | S
.Sm on
.Oc
.Sm off
.Oo Oo Oo Oo Oo
.Ar cc Oc
.Ar yy Oc
.Ar mm Oc
.Ar dd Oc
.Ar HH
.Oc Ar MM Op Cm \&. Ar SS
.Sm on
.Op Cm + Ns Ar выходной_формат
.Nm
.Op Fl jnRu
.Op Fl z Ar зона_вывода
.Op Fl I Ns Op Ar FMT
.Oo
.Sm off
.Fl v
.Op Cm + | -
.Ar значение Op Cm y | m | w | d | H | M | S
.Sm on
.Oc
.Fl f Ar входной_формат
.Ar новая_дата
.Op Cm + Ns Ar выходной_формат
.Sh ОПИСАНИЕ
При запуске без аргументов
.Nm
выводит текущую дату и время.
В противном случае, в зависимости от указанных параметров,
.Nm
установит дату и время или выведет их в определяемом пользователем формате.
.Pp
Утилита
.Nm
выводит дату и время, считанные из часов ядра.
При использовании для установки даты и времени
обновляются как часы ядра, так и аппаратные часы.
.Pp
Только суперпользователь может устанавливать дату,
и если системный уровень безопасности (см.
.Xr securelevel 7 )
больше 1,
время нельзя изменять более чем на 1 секунду.
.Pp
Параметры следующие:
.Bl -tag -width Ds
.It Fl f Ar входной_формат
Использовать
.Ar входной_формат
как строку формата для разбора предоставленной
.Ar новая_дата
вместо использования формата по умолчанию
.Sm off
.Oo Oo Oo Oo Oo
.Ar cc Oc
.Ar yy Oc
.Ar mm Oc
.Ar dd Oc
.Ar HH
.Oc Ar MM Op Cm \&. Ar SS
.Sm on
.
Разбор выполняется с помощью
.Xr strptime 3 .
.It Fl I Ns Op Ar FMT
Использовать расширенный
.St -iso8601
формат вывода.
.Ar FMT
можно опустить, в этом случае по умолчанию используется
.Cm date .
Допустимые
.Ar FMT
значения:
.Cm date ,
.Cm hours ,
.Cm minutes ,
.Cm seconds
и
.Cm ns
.Pq для наносекунд .
Дата и время форматируются с указанной точностью.
Когда
.Ar FMT
равно
.Cm hours
.Po или более точным
.Cm minutes ,
.Cm seconds
или
.Cm ns Pc ,
расширенный
.St -iso8601
формат включает смещение часового пояса.
.It Fl j
Не пытаться установить дату.
Это позволяет использовать
.Fl f
вместе с
.Cm +
для преобразования одного формата даты в другой.
Обратите внимание, что любые компоненты даты или времени, не указанные в
.Fl f
строке формата, берут значения из текущего времени.
.It Fl n
Устаревший флаг; принимается и игнорируется для совместимости.
.It Fl R
Использовать формат вывода даты и времени RFC 2822.
Это эквивалентно использованию
.Ql %a, %d %b %Y \&%T %z
как
.Ar выходной_формат
при установленной
.Ev LC_TIME
в
.Dq C
локаль .
.It Fl r Ar секунды
Вывести дату и время, представленные
.Ar секунды ,
где
.Ar секунды
— число секунд с начала эпохи Unix
(00:00:00 UTC, 1 января 1970 г.;
см.
.Xr time 3 ) ,
и может быть указано в десятичном, восьмеричном или шестнадцатеричном виде.
.It Fl r Ar имя_файла
Вывести дату и время последнего изменения
.Ar имя_файла .
.It Fl u
Отображать или устанавливать дату по UTC (всемирное координированное время).
По умолчанию
.Nm
отображает время в часовом поясе, описанном в
.Pa /etc/localtime
или переменной окружения
.Ev TZ .
.It Fl z Ar зона_вывода
Непосредственно перед выводом времени переключиться на указанный часовой пояс;
см. описание
.Ev TZ
ниже.
Это можно использовать с
.Fl j
для простого преобразования времени из одного пояса в другой.
.It Xo
.Fl v
.Sm off
.Op Cm + | -
.Ar значение Op Cm y | m | w | d | H | M | S
.Sm on
.Xc
Скорректировать (т.е. взять текущую дату и отобразить результат
корректировки; фактически не устанавливать дату) секунды, минуты, часы, день
месяца, день недели, месяц или год согласно
.Ar значение .
Если
.Ar значение
предваряется знаком плюс или минус,
дата корректируется вперёд или назад в соответствии с оставшейся строкой,
иначе соответствующая часть даты устанавливается.
Дату можно корректировать столько раз, сколько требуется, используя эти флаги.
Флаги обрабатываются в заданном порядке.
.Pp
При установке значений
(а не их корректировке)
секунды находятся в диапазоне 0-59, минуты — в диапазоне 0-59, часы —
в диапазоне 0-23, дни месяца — в диапазоне 1-31, дни недели — в
диапазоне 0-6 (вс-сб),
месяцы — в диапазоне 1-12 (янв-дек),
а годы — в ограниченном диапазоне в зависимости от платформы.
.Pp
На i386 годы находятся в диапазоне 69-38, представляющем 1969-2038.
На всех других платформах принимаются годы 0-68, представляющие 2000-2068, и
69-99, представляющие 1969-1999.
В обоих случаях принимаются годы с 100 по 1900 (включительно) и
интерпретируются как относительные к 1900 году григорианского календаря с ограничением 138 на
i386 и гораздо более высоким ограничением на всех других платформах.
Также принимаются годы начиная с 1901 и интерпретируются как абсолютные годы.
.Pp
Если
.Ar значение
является числовым, необходимо использовать один из
.Cm y ,
.Cm m ,
.Cm w ,
.Cm d ,
.Cm H ,
.Cm M
или
.Cm S
чтобы указать, какую часть даты нужно скорректировать.
.Pp
День недели или месяц можно указать с помощью имени, а не
числа.
Если имя используется со знаком плюс
(или минус),
дата будет перенесена вперёд
(или назад)
к следующей
(предыдущей)
дате, соответствующей заданному дню недели или месяцу.
Дата не будет скорректирована,
если заданный день недели или месяц совпадает с текущим.
.Pp
Когда дата корректируется до конкретного значения или в единицах больше часов,
соображения перехода на летнее время игнорируются.
Корректировки в единицах часов или меньше учитывают переход на летнее время.
Так, если текущая дата — 26 марта, 0:30 и переход на летнее время
означает, что часы переводятся вперёд с 01:00 на 02:00, использование
.Fl v No +1H
скорректирует дату на 26 марта, 2:30.
Аналогично, если дата — 29 октября, 0:30 и переход на летнее время
означает, что часы переводятся назад с 02:00 на 01:00, потребуется использовать
.Fl v No +3H
чтобы достичь 29 октября, 2:30.
.Pp
Когда дата корректируется до конкретного значения, которое фактически не существует
(например, 26 марта, 1:30 BST 2000 в часовом поясе Europe/London),
дата будет молча сдвигаться вперёд с шагом в один час, пока не
достигнет допустимого времени.
Когда дата корректируется до конкретного значения, которое встречается дважды
(например, 29 октября, 1:30 2000),
итоговый часовой пояс будет установлен так, чтобы дата соответствовала более раннему из
двух времён.
.Pp
Невозможно скорректировать дату до недопустимого абсолютного дня, поэтому использование
параметров
.Fl v No 31d Fl v No 12m
просто не сработает в течение пяти месяцев года.
Поэтому обычно сначала устанавливают месяц, а затем день; использование
.Fl v No 12m Fl v No 31d
всегда работает.
.Pp
Корректировка даты на месяцы по своей сути неоднозначна, потому что
месяц — это единица переменной длины, зависящая от текущей даты.
Этот вид корректировки даты применяется наиболее интуитивным способом.
Прежде всего,
.Nm
пытается сохранить день месяца.
Если это невозможно, потому что целевой месяц короче текущего,
результатом будет последний день целевого месяца.
Например, использование
.Fl v No +1m
31 мая скорректирует дату на 30 июня, а использование того же параметра
30 января приведёт к корректировке даты на последний день февраля.
Также считается, что этот подход наиболее разумен для сценариев оболочки.
Тем не менее, учтите, что переход вперёд и назад на одинаковое число
месяцев может привести к другой дате.
.Pp
Дополнительные сведения см. в примерах ниже.
.El
.Pp
Операнд с ведущим знаком плюс
.Pq Sq +
задаёт определяемую пользователем строку формата,
которая указывает формат отображения даты и времени.
Строка формата может содержать любые спецификации преобразования,
описанные в
.Xr strftime 3
руководстве, а также произвольный текст.
.Pp
Поддерживаются следующие расширения обычного
.Xr strftime 3
синтаксиса:
.Bl -tag -width Ds
.It Cm \&% Ns Ar n Ns Cm N
Заменяется на
.Ar n Ns
-значную дробную часть числа секунд с начала эпохи Unix.
Если
.Ar n
опущено или равно нулю, используется значение по умолчанию 9, что даёт
число с наносекундным разрешением (отсюда выбор буквы
.Sq N
для этого преобразования).
Обратите внимание, что лежащие в основе часы могут не обязательно поддерживать
наносекундное разрешение.
.It Cm \&%-N
Как выше, но автоматически выбирается точность на основе сообщаемого
разрешения лежащих в основе часов.
Если был указан параметр
.Fl r ,
используется точность по умолчанию в 9 цифр.
.El
.Pp
Символ новой строки
.Pq Ql \en
всегда выводится после символов, указанных
строкой формата.
Строка формата для отображения по умолчанию —
.Dq %+ .
.Pp
Если операнд не имеет ведущего знака плюс, он интерпретируется как
значение для установки системного представления текущей даты и времени.
Каноническое представление для установки даты и времени:
.Pp
.Bl -tag -width Ds -compact -offset indent
.It Ar cc
Век
(19 или 20)
перед сокращённым годом.
.It Ar yy
Год в сокращённой форме
(например, 89 для 1989, 06 для 2006).
.It Ar mm
Числовой месяц, число от 1 до 12.
.It Ar dd
День, число от 1 до 31.
.It Ar HH
Час, число от 0 до 23.
.It Ar MM
Минуты, число от 0 до 59.
.It Ar SS
Секунды, число от 0 до 60
(59 плюс возможная високосная секунда).
.El
.Pp
Всё, кроме минут, необязательно.
.Pp
.Nm
понимает определения часовых поясов из базы данных часовых поясов IANA,
.Sy tzdata ,
расположенной в
.Pa /usr/share/zoneinfo .
Изменения времени для перехода на летнее время, стандартного времени, високосных секунд
и високосных лет обрабатываются автоматически.
.Pp
Есть два способа указать часовой пояс:
.Pp
Если файл или символическая ссылка
.Pa /etc/localtime
существует, она интерпретируется как файл определения часового пояса, обычно в
иерархии каталогов
.Pa /usr/share/zoneinfo ,
которая содержит определения часовых поясов из
.Sy tzdata .
.Pp
Если переменная окружения
.Ev TZ
установлена, её значение интерпретируется как имя файла определения часового пояса,
либо абсолютный путь, либо относительный путь к определению часового пояса
в
.Pa /usr/share/zoneinfo .
Переменная
.Ev TZ
переопределяет
.Pa /etc/localtime .
.Pp
Если файл определения часового пояса недействителен,
.Nm
молча возвращается к UTC.
.Pp
В предыдущих версиях
.Nm
были параметры
.Fl d
(установить флаг летнего времени) и
.Fl t
(установить отрицательное смещение часового пояса), но теперь эти детали
обрабатываются автоматически с помощью
.Sy tzdata .
Современные смещения положительны для часовых поясов впереди UTC и отрицательны
для часовых поясов позади UTC, но, как и устаревший параметр
.Fl t ,
файлы
.Sy tzdata
в подкаталоге
.Pa /usr/share/zoneinfo/Etc
всё ещё используют старое соглашение, где время впереди UTC считается
отрицательным.
.Sh ОКРУЖЕНИЕ
Следующая переменная окружения влияет на выполнение
.Nm :
.Bl -tag -width Ds
.It Ev TZ
Часовой пояс, используемый при отображении дат.
Обычный формат — путь относительно
.Pa /usr/share/zoneinfo .
Например, команда
.Dq TZ=America/Los_Angeles date
отображает текущее время в Калифорнии.
Переменная также может задавать абсолютный путь.
См.
.Xr environ 7
для получения дополнительной информации.
.El
.Sh ФАЙЛЫ
.Bl -tag -width /var/log/messages -compact
.It Pa /etc/localtime
Файл информации о часовом поясе для системного часового пояса по умолчанию.
Может отсутствовать, в этом случае часовой пояс по умолчанию — UTC.
.It Pa /usr/share/zoneinfo
Каталог, содержащий файлы информации о часовых поясах.
.It Pa /var/log/messages
Запись о пользователе, устанавливающем время.
.It Pa /var/log/utx.log
Запись о сбросах даты и изменениях времени.
.El
.Sh СТАТУС ВЫХОДА
Утилита
.Nm
завершается с кодом 0 при успехе, 1 если не удалось установить дату, и 2
если удалось установить локальную дату, но не удалось установить её глобально.
.Sh ПРИМЕРЫ
Команда
.Pp
.Pp
выведет время, прошедшее с начала эпохи Unix, с точностью до миллисекунд.
.Pp
Команда:
.Pp
.Pp
выведет:
.Bd -literal -offset indent
DATE: 1987-11-21
TIME: 13:36:16
.Ed
.Pp
В часовом поясе Europe/London команда:
.Pp
.Pp
выведет:
.Pp
.Pp
где сейчас
.Pp
Команда:
.Pp
.Pp
выведет последний день февраля 2000 года:
.Pp
.Pp
Так же и команда:
.Pp
.Pp
потому что не существует такой даты, как 30 февраля.
.Pp
Команда:
.Pp
.Pp
выведет последнюю пятницу месяца:
.Pp
.Pp
где сейчас
.Pp
Команда:
.Pp
.Pp
устанавливает дату в
.Pp
.Pp
может использоваться на одной машине для вывода даты,
подходящей для установки на другой.
.Po Используйте
с GNU date в
Linux .
.Pc
.Pp
Команда:
.Pp
.Pp
устанавливает время в
без изменения даты.
.Pp
Команда
.Pp
.Pp
выведет
.Pp
.Pp
Команда:
.Pp
.Pp
может использоваться для разбора вывода
.Nm
и выражения его во времени эпохи.
.Pp
Наконец, команда
.Pp
.Pp
выведет время в часовом поясе
.Dq Europe/Paris
когда в часовом поясе
.Dq America/Los_Angeles
9:00.
.Sh ДИАГНОСТИКА
Недопустимо сочетать флаг
.Fl I
с
.Fl R
или операндом формата вывода
.Dq ( + Ns ... )
.
Если это произойдёт,
.Nm
выведет:
.Ql multiple output formats specified
и завершится со статусом 1.
.Sh СМ. ТАКЖЕ
.Xr locale 1 ,
.Xr clock_gettime 2 ,
.Xr gettimeofday 2 ,
.Xr getutxent 3 ,
.Xr strftime 3 ,
.Xr strptime 3 ,
.Xr tzset 3 ,
.Xr adjkerntz 8 ,
.Xr ntpd 8 ,
.Xr tzsetup 8
.Rs
.%A R. Gusella
.%A S. Zatti
.Re
.Rs
.%U https://iana.org/time-zones
.%T Time Zone Database
.Re
.Sh СТАНДАРТЫ
Утилита
.Nm
должна быть совместима с
.St -p1003.2 .
За исключением параметра
.Fl u ,
все параметры являются расширениями стандарта.
.Pp
Формат, выбираемый флагом
.Fl I ,
совместим с
.St -iso8601 .
.Pp
Спецификация преобразования
.Ql \&%N
для наносекунд является нестандартным расширением.
Она совместима с
.Ql \&%N
в GNU date.
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v1 .
.Pp
Ряд параметров был добавлен и затем снова удалён, включая
.Fl d
(установить флаг летнего времени) и
.Fl t
(установить отрицательное смещение часового пояса).
Теперь часовые пояса обрабатываются кодом, поставляемым с
.Sy tzdata .
.Pp
Флаг
.Fl I
был добавлен в
.Fx 12.0 .
.Pp
Спецификация преобразования
.Ql \&%N
была добавлена в
.Fx 14.1 .
Поддержка вариантов
.Ql \&% Ns Ar n Ns Cm N
и
.Ql \&%-N
была добавлена в
.Fx 15.1 .
