.\" FRDP path contrib/mandoc/demandoc.1
.\" FRDP githash c1c95add8c80843ba15d784f95c361d795b1f593
.\" FRDP hash256 51d0b383346f0719e349c736518903aef61b9cfa9d07d2f318eb9728ec84d6d6
.Dd $Mdocdate: March 20 2022 $
.Dt DEMANDOC 1
.Os
.Sh ИМЯ
.Nm demandoc
.Nd "выводить только текст руководств UNIX"
.Sh СИНТАКСИС
.Nm demandoc
.Op Fl w
.Op Ar
.Sh ОПИСАНИЕ
Утилита
.Nm
выводит только текстовые части корректно сформированных
.Xr mdoc 7
и
.Xr man 7
.Ux
файлов руководств.
.Pp
По умолчанию
.Nm
разбирает стандартный ввод и выводит только текстовые узлы, сохраняя
позиции строк и столбцов.
Управляющие последовательности исключаются из вывода.
.Pp
Её аргументы таковы:
.Bl -tag -width Ds
.It Fl w
Выводить список слов.
При этом каждое слово текста выводится на отдельной строке.
.Qq слово ,
в этом случае относится к терминам, разделённым пробельными символами,
начинающимся по крайней мере с двух букв и не состоящим из каких-либо
управляющих последовательностей.
Начальная и конечная пунктуация слов
.Pq двойные кавычки, знаки конца предложения и т.п.
удаляется.
.It Ar
Входные файлы.
.El
.Pp
Если документ не является корректно сформированным, он пропускается.
.Pp
Флаги
.Fl i ,
.Fl k ,
.Fl m
и
.Fl p
молча отбрасываются для совместимости вызова с
исторической deroff.
.Sh СТАТУС ВЫХОДА
Утилита
.Nm
завершается с одним из следующих значений:
.Pp
.Bl -tag -width Ds -compact
.It 0
Ошибок не произошло.
.It 6
Произошла ошибка операционной системы, например исчерпание памяти или
ошибка доступа к входным файлам.
Такие ошибки заставляют
.Nm
немедленно завершиться, возможно, в середине разбора или форматирования файла.
.El
.Sh ПРИМЕРЫ
Традиционное использование
.Nm
предназначено для проверки орфографии руководств в
.Bx .
Это делается следующим образом (предполагается британское правописание):
.Pp
.Dl $ demandoc -w file.1 | spell -b
.Sh СМ. ТАКЖЕ
.Xr mandoc 1 ,
.Xr man 7 ,
.Xr mdoc 7
.Sh ИСТОРИЯ
.Nm
заменяет историческую утилиту deroff для обработки современных
.Xr man 7
и
.Xr mdoc 7
документов.
.Sh АВТОРЫ
Утилита
.Nm
была написана
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv .
