.\" FRDP path bin/domainname/domainname.1
.\" FRDP githash 90405e1d63ff919705422745f19a8b56a37f5ac0
.\" FRDP hash256 2ed2c94c6b381869ba6573aa1c445b7d990f0558ceec25268b63059393c4d267
.Dd April 22, 2013
.Dt DOMAINNAME 1
.Os
.Sh ИМЯ
.Nm domainname
.Nd установить или вывести имя текущего домена YP/NIS
.Sh СИНТАКСИС
.Nm
.Op Ar домен_YP
.Sh ОПИСАНИЕ
Утилита
.Nm
выводит имя текущего домена YP/NIS.
Суперпользователь может
задать доменное имя, указав аргумент; обычно это делается с помощью
.Va nisdomainname
в файле
.Pa /etc/rc.conf ,
как правило, во время загрузки.
.Sh ПРИМЕЧАНИЯ
Имя домена YP/NIS (ранее ``Yellow Pages'', но переименованного по юридическим причинам)
не обязательно имеет какое-либо отношение к имени домена Domain
Name System, хотя их часто устанавливают одинаковыми для удобства
администрирования.
.Sh СМ. ТАКЖЕ
.Xr getdomainname 3 ,
.Xr rc.conf 5
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Fx 1.1 ,
основанная на аналогичной команде в
.Tn SunOS .
