.\" FRDP path usr.bin/dtc/dtc.1
.\" FRDP githash fa9896e082a1046ff4fbc75fcba4d18d1f2efc19
.\" FRDP hash256 3881423736a2a31303ca3b30e02fb9a8dd542c17a606e7730e686dfc0ca22bbd
.Dd February 26, 2022
.Dt DTC 1
.Os
.Sh ИМЯ
.Nm dtc
.Nd компилятор дерева устройств
.Sh СИНТАКСИС
.Nm
.Op Fl @fhsv
.Op Fl b Ar boot_cpu_id
.Op Fl d Ar dependency_file
.Op Fl i Ar include_path
.Op Fl E Ar [no-]checker_name
.Op Fl H Ar phandle_format
.Op Fl I Ar input_format
.Op Fl O Ar output_format
.Op Fl o Ar output_file
.Op Fl R Ar entries
.Op Fl S Ar bytes
.Op Fl p Ar bytes
.Op Fl V Ar blob_version
.Op Fl W Ar [no-]checker_name
.Op Fl P Ar predefined_properties
.Ar input_file
.Sh ОПИСАНИЕ
Утилита
.Nm
преобразует между представлениями плоского дерева устройств (FDT).
Чаще всего она используется для генерации блобов дерева устройств (DTB), двоичного
представления FDT, из исходников дерева устройств (DTS), ASCII-текстового исходного
представления.
.Pp
Двоичные данные могут быть записаны в двух форматах: двоичном и ассемблерном.
Двоичный идентичен представлению в памяти и может использоваться
непосредственно прошивкой, загрузчиками и так далее.
Ассемблерный формат, описанный в
, при ассемблировании даст тот же двоичный формат, но также включает некоторые
глобальные переменные, ссылающиеся на части таблицы.
Этот формат чаще всего используется для создания ядра, специфичного для устройства,
со встроенным блобом дерева устройств.
.Pp
Параметры следующие:
.Bl -tag -width indent
.It Fl d Ar dependency_file
Записывает файл зависимостей, понятный make, в указанный файл.
Этот файл можно включить в Makefile, и он обеспечит, что выходной файл
зависит от входного файла и любых включаемых им файлов.
Этот аргумент полезен только когда входные данные — DTS, так как только исходный формат
имеет понятие включений.
.It Fl i Ar include_path
Добавляет путь для поиска включаемых файлов.
.It Fl E Ar [no-]checker_name
Включает или отключает указанную проверку.
Аргумент — имя проверки.
Полный список проверок приведён в
.Sx ПРОВЕРКИ .
.It Fl @
Создаёт узел __symbols__, позволяющий загружать плагины.
.It Fl f
Заставляет инструмент попытаться сгенерировать вывод, даже если входные данные содержали ошибки.
.It Fl h
Показать текст справки и выйти.
.It Fl H Ar phandle_format
Указывает тип узлов phandle для генерации в выводе.
Допустимые значения:
.Pp
.Bl -tag -width indent -compact
.It Ar linux
Генерировать устаревшие узлы linux,phandle, ожидаемые старыми системами.
.It Ar epapr
Генерировать узлы phandle, как описано в спецификации ePAPR.
Это наиболее разумный вариант для деревьев устройств, используемых с
.Fx .
.It Ar both
Генерировать оба, для максимальной совместимости.
.El
.It Fl I Ar input_format
Указывает входной формат.
Допустимые значения:
.Pp
.Bl -tag -width indent -compact
.It Ar dtb
Блоб дерева устройств.
Двоичное представление FDT.
.It Ar dts
Исходник дерева устройств.
ASCII-представление FDT.
Это значение по умолчанию, если входной формат явно не указан.
.El
.It Fl O Ar output_format
Указывает выходной формат.
Допустимые значения:
.Pp
.Bl -tag -width indent -compact
.It Ar asm
Ассемблерный исходник для генерации блоба дерева устройств, как описано в
.It Ar dtb
Блоб дерева устройств.
Двоичное представление FDT.
Это значение по умолчанию, если выходной формат явно не указан.
.It Ar dts
Исходник дерева устройств.
ASCII-представление FDT.
.El
.It Fl o Ar output_file
Файл, в который записывать вывод.
.It Fl P Ar predefined_macro
Определяет макрос в форме
.Ar name=value
или
.Ar name
для использования в исходных файлах дерева устройств, содержащих условные компоненты.
Этот инструмент поддерживает два расширения стандарта для поддержки условной
компиляции деревьев устройств.
Первое — директива
, разрешённая в начале файла и включающая указанный файл только если указанное свойство передано с этим флагом.
Второе — формат
.Ar $NAME
для значений свойств.
Они позволяют задавать значение свойства в командной строке.
.It Fl R Ar entries
Количество пустых записей таблицы резервирования для дополнения таблицы.
Это полезно, если вы генерируете блоб дерева устройств для загрузчика или
чего-то подобного, что должно зарезервировать память перед передачей управления
операционной системе.
.It Fl S Ar bytes
Минимальный размер блоба в байтах.
Блоб будет дополнен после таблицы строк, чтобы гарантировать нужный
размер.
Это полезно для сред, где блоб дерева устройств должен изменяться на
месте.
.It Fl p Ar bytes
Количество байтов дополнения, добавляемых к блобу.
Блоб будет дополнен после таблицы строк, чтобы гарантировать нужный
размер.
Это полезно для сред, где блоб дерева устройств должен изменяться на
месте.
.It Fl W Ar [no-]checker_name
Включает или отключает указанную проверку.
Это псевдоним для
.Fl E .
.It Fl s
Сортирует свойства и узлы в дереве.
Это в основном полезно при использовании таких инструментов, как
.Xr diff 1 ,
для сравнения двух исходников деревьев устройств.
.It Fl V Ar output_version
Версия формата для вывода.
Это имеет значение только для двоичного вывода, и в настоящее время поддерживается
только значение 17.
.It Fl v
Показать версию инструмента и выйти.
.It Ar input_file
Исходный файл.
.El
Ассемблерный формат определяет несколько глобальных переменных, на которые можно
ссылаться из других единиц компиляции, в дополнение к любым меткам, указанным в исходнике.
Это:
.Pp
.It dt_blob_start
начало блоба дерева устройств.
.It dt_header
начало заголовка, обычно совпадает с началом блоба.
.It dt_reserve_map
начало карты резервирования.
.It dt_struct_start
начало таблицы структуры.
.It dt_struct_end
конец таблицы структуры.
.It dt_strings_start
начало таблицы строк.
.It dt_strings_end
конец таблицы строк.
.It dt_blob_end
конец блоба дерева устройств.
.El
.Sh ПРОВЕРКИ
Утилита выполняет ряд семантических проверок корректности
дерева.
Их можно отключить с помощью флага
.Fl W .
Например,
.Fl W Ar no-type-phandle
отключит проверку типа phandle.
Поддерживаемые проверки:
.Pp
.It type-compatible
Проверяет тип свойства
.Va compatible .
.It type-model
Проверяет тип свойства
.Va model .
.It type-compatible
Проверяет тип свойства
.Va compatible .
.It cells-attributes
Проверяет, что все узлы с дочерними элементами имеют свойства
.Va #address-cells
и
.Va #size-cells .
.It deleted-nodes
Проверяет, что все инструкции
.Va /delete-node/
ссылаются на узлы, которые объединены.
.El
.Sh НАЛОЖЕНИЯ
Утилита поддерживает генерацию наложений, также известных как плагины.
Наложения — это метод исправления базового дерева устройств, скомпилированного с
флагом
.Fl @ ,
с некоторой ограниченной поддержкой исправления деревьев устройств, не скомпилированных
с флагом
.Fl @ .
.Pp
Чтобы обозначить, что DTS предназначен для использования в качестве наложения,
в заголовок следует включить
.Va /plugin/\&;
после любого применимого тега
.Va /dts-v1/\&; .
.Pp
Обычные наложения создаются путём создания
узлов
.Va fragment
в корне.
Каждый узел fragment должен иметь либо свойство
.Va target ,
установленное в ссылку на метку, либо строковое свойство
.Va target-path ,
установленное в путь.
Затем он должен иметь дочерний узел
.Va __overlay__ ,
свойства и дочерние узлы которого объединяются в базовое дерево
устройств при применении наложения.
.Pp
Гораздо более простой синтаксический сахар был позже изобретён для упрощения генерации наложений.
Вместо ручного создания целевых фрагментов можно создать корневой
узел, нацеленный на метку в базовом FDT, используя синтаксис
.Va &label ,
поддерживаемый в обычных DTS.
Это укажет, что для узла должен быть сгенерирован фрагмент, с данной
.Va label
в качестве цели, а свойства и дочерние узлы будут использованы как
__overlay__.
.Pp
Кроме того, поддерживается основанная на путях версия этого синтаксического сахара.
Корневой узел может нацеливаться на путь в базовом FDT, используя имя вида
.Va &{/path} .
Для узла будет сгенерирован фрагмент, как в случае
.Va &label ,
за исключением того, что свойство
.Va target-path
будет установлено в
.Va /path ,
а
.Va target
установлен не будет.
.Pp
Поддерживаются как обычные наложения, так и добавленный позже синтаксический сахар.
.Pp
Блобы наложений можно применять во время загрузки, установив
.Va fdt_overlays
в
.Xr loader.conf 5 .
Можно указать несколько наложений, и они будут применены в указанном порядке.
.Sh ПРОПУСК УЗЛОВ
Эта утилита поддерживает инструкцию
.Va /omit-if-no-ref/
для пометки узлов для пропуска, если на них в конечном итоге нигде не ссылаются
в дереве устройств.
Это может использоваться в средах с более ограниченным пространством для удаления узлов, которые могут
не применяться к конкретному устройству, для которого компилируется дерево.
.Pp
Когда используется флаг
.Fl @
для записи символов, узлы с метками будут считаться referenced
и не будут удалены из дерева.
.Sh ПРИМЕРЫ
Команда:
.Pp
.Pp
сгенерирует файл
.Pa blob.S
из исходника дерева устройств
.Pa device.dts
и выведет ошибки, если они возникнут во время разбора или проверки свойств.
Полученный файл можно ассемблировать и скомпоновать в двоичный файл.
.Pp
Команда:
.Pp
.Pp
запишет исходник дерева устройств для блоба дерева устройств
.Pa device.dtb
в стандартный вывод.
Это полезно при отладке деревьев устройств.
.Pp
Команда:
.Pp
.Pp
сгенерирует файл
.Pa device.dtb
из исходника дерева устройств
.Pa device.dts
с включённым узлом __symbols__, чтобы к нему можно было применять наложения.
.Pp
Команда:
.Pp
.Pp
сгенерирует файл
.Pa device_overlay.dtbo ,
используя стандартное расширение для наложения дерева устройств, из исходника
дерева устройств
.Pa device_overlay.dts .
Будет включён узел __symbols__, чтобы к нему можно было применять наложения.
Наличие директивы
.Va /plugin/\&;
в
.Pa device_overlay.dts
укажет утилите, что она также должна сгенерировать базовые
метаданные, требуемые в наложениях.
.Sh СОВМЕСТИМОСТЬ
Эта утилита предназначена для совместимости с компилятором дерева устройств,
предоставляемым elinux.org.
В настоящее время она реализует подмножество функций,
необходимых для сборки
.Fx ,
и другие, запрошенные разработчиками
.Fx .
.Pp
Входной формат
.Ar fs
не поддерживается.
Он строит дерево из Linux
.Pa  /proc/device-tree ,
иерархии файловой системы, отсутствующей в
.Fx ,
которая вместо этого предоставляет DTB напрямую через sysctl.
.Pp
Предупреждения и ошибки, поддерживаемые инструментом elinux.org, не документированы.
Этот инструмент поддерживает предупреждения, описанные в разделе
.Sx ПРОВЕРКИ .
.Sh СМ. ТАКЖЕ
.Xr fdt 4
.Sh СТАНДАРТЫ
Форматы дерева устройств, понимаемые этим инструментом, соответствуют Power.org
Standard for Embedded Power Architecture Platform Requirements
.Pq Vt ePAPR ,
за исключением отмеченного в разделе
.Sx ИЗВЕСТНЫЕ ОШИБКИ
и со следующими исключениями для совместимости с инструментом elinux.org:
.Pp
.Bl -bullet -compact
.It
Цель перекрёстных ссылок определена в спецификации как имя узла,
но фактически является меткой.
.El
.Pp
Директива /include/ не является частью стандарта, однако она реализована
с семантикой, совместимой с инструментом elinux.org.
Она должна находиться на верхнем уровне файла и импортирует новое определение корня.
Если файл вместе со всеми его включениями содержит несколько корней, то они
объединяются.
Все узлы, присутствующие во втором, но не в первом, импортируются.
Любые, присутствующие в обоих, рекурсивно объединяются, при этом свойства из второго
заменяют свойства из первого, а дочерние узлы свойств рекурсивно
объединяются.
.Sh ИСТОРИЯ
Инструмент dtc впервые появился в
.Fx 9.0 .
Эта версия инструмента впервые появилась в
.Fx 10.0 .
.Sh АВТОРЫ
.Nm
был написан
.An David T. Chisnall .
Некоторые функции были позже добавлены
.An Kyle Evans .
.Pp
Примечание: тот факт, что инструмент и автор имеют одинаковые инициалы, является полностью
случайным совпадением.
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Компилятор дерева устройств пока не поддерживает следующие функции:
.Pp
.Bl -bullet -compact
.It
Метки в середине значений свойств.
Это полезно только в ассемблерном выводе, и то лишь отчасти, поэтому
вряд ли будет добавлено в ближайшее время.
.It
Полные пути, а не метки, в качестве целей для phandle.
Это не очень сложно добавить, но, вероятно, не будет добавлено, пока что-то
действительно в этом не нуждается.
.El
.Pp
Текущая версия выполняет очень ограниченный набор семантических проверок дерева.
Это будет улучшено в будущих версиях.
