.\" FRDP path bin/ed/ed.1
.\" FRDP githash 84886bf93ae96ee4d19cd7f31696ba368cabddae
.\" FRDP hash256 17fc06379b651da1330490dded3c250507dfb8fe06ed5c28182dade910ae87b7
.Dd April 9, 2021
.Dt ED 1
.Os
.Sh ИМЯ
.Nm ed ,
.Nm red
.Nd текстовый редактор
.Sh СИНТАКСИС
.Nm
.Op Fl
.Op Fl s
.Op Fl p Ar строка
.Op Ar файл
.Nm red
.Op Fl
.Op Fl s
.Op Fl p Ar строка
.Op Ar файл
.Sh ОПИСАНИЕ
Утилита
.Nm
— построчный текстовый редактор.
Она используется для создания, просмотра, изменения и иной обработки текстовых
файлов.
При вызове как
.Nm red ,
редактор работает в
.Qq ограниченном
режиме, в котором единственное отличие состоит в том, что редактор ограничивает
использование имён файлов, начинающихся с
.Ql \&!
(интерпретируемых как команды оболочки в
.Nm )
или содержащих
.Ql \&/ .
Заметьте, что редактирование вне текущего каталога запрещено только
если у пользователя нет прав на запись в текущий каталог.
Если у пользователя есть права на запись в текущий каталог, то символические
ссылки могут быть созданы в текущем каталоге, и в этом случае
.Nm red
не помешает пользователю редактировать файл, на который указывает символическая
ссылка.
.Pp
Если указан аргумент
.Ar файл ,
то копия
.Ar файл
читается в буфер редактора.
Изменения вносятся в эту копию, а не непосредственно в
.Ar файл .
При выходе из
.Nm ,
все изменения, явно не сохранённые командой
.Em w ,
теряются.
.Pp
Редактирование выполняется в двух различных режимах:
.Em команда
и
.Em ввод .
При первом запуске
.Nm
находится в режиме команд.
В этом режиме команды читаются из стандартного ввода и
выполняются для изменения содержимого буфера редактора.
Типичная команда может выглядеть так:
.Pp
.Sm off
.Cm ,s No / Em old Xo
.No / Em new
.No / Cm g
.Xc
.Sm on
.Pp
что заменяет все вхождения строки
.Em old
на
.Em new .
.Pp
Когда задаётся команда ввода, такая как
.Em a
(добавить),
.Em i
(вставить) или
.Em c
(изменить),
.Nm
переходит в режим ввода.
Это основной способ
добавления текста в файл.
В этом режиме команды недоступны;
вместо этого стандартный ввод записывается
непосредственно в буфер редактора.
Строки состоят из текста до
символа
.Em новой строки
включительно.
Режим ввода завершается
вводом одной точки
.Pq Em .\&
в строке.
.Pp
Все команды
.Nm
работают с целыми строками или диапазонами строк; например,
команда
.Em d
удаляет строки; команда
.Em m
перемещает строки, и так далее.
Можно изменить только часть строки с помощью замены,
как в примере выше.
Однако даже здесь команда
.Em s
применяется сразу к целым строкам.
.Pp
В общем, команды
.Nm
состоят из нуля или более адресов строк, за которыми следует односимвольная
команда и, возможно, дополнительные параметры; т.е.
команды имеют структуру:
.Pp
.Sm off
.Xo
.Op Ar адрес Op , Ar адрес
.Ar команда Op Ar параметры
.Xc
.Sm on
.Pp
Адрес(а) указывают строку или диапазон строк, к которым применяется
команда.
Если указано меньше адресов, чем принимает команда, то
подставляются адреса по умолчанию.
.Sh ОПЦИИ
Доступны следующие опции:
.Bl -tag -width indent
.It Fl s
Подавить диагностику.
Это следует использовать, если
стандартный ввод
.Nm Ns 's
поступает из сценария.
.It Fl p Ar строка
Задать приглашение командной строки.
Это можно включать и выключать командой
.Em P .
.It Ar файл
Задать имя файла для чтения.
Если
.Ar файл
начинается с
bang (!), то он интерпретируется как команда оболочки.
В этом случае
читается
стандартный вывод
.Ar файл ,
выполняемого через
.Xr sh 1 .
Чтобы прочитать файл, имя которого начинается с bang, предварите
имя обратной косой чертой (\e).
Имя файла по умолчанию устанавливается в
.Ar файл
только если оно не начинается с bang.
.El
.Sh АДРЕСАЦИЯ СТРОК
Адрес представляет собой номер строки в буфере.
Утилита
.Nm
поддерживает
.Em текущий адрес ,
который
обычно подставляется командам как адрес по умолчанию, если адрес не указан.
Когда файл впервые читается, текущий адрес устанавливается на последнюю строку
файла.
В общем, текущий адрес устанавливается на последнюю строку,
затронутую командой.
.Pp
Адрес строки
строится из одного из базовых элементов в приведённом ниже списке, за которым необязательно
следует числовое смещение.
Смещение может включать любую комбинацию
цифр, операторов (т.е.
.Em + ,
.Em -
и
.Em ^ )
и пробельных символов.
Адреса читаются слева направо, и их значения вычисляются
относительно текущего адреса.
.Pp
Одно исключение из правила, что адреса представляют номера строк, — это
адрес
.Em 0
(ноль).
и он допустим везде, где имеет смысл.
.Pp
Диапазон адресов — это два адреса, разделённые запятой или
точкой с запятой.
Значение первого адреса в диапазоне не может превышать
значение второго.
Если в диапазоне указан только один адрес, то
второй адрес устанавливается равным указанному адресу.
Если дан
.Em n Ns -кортеж
адресов, где
тогда соответствующий диапазон определяется последними двумя адресами в
.Em n Ns -кортеже .
Если ожидается только один адрес, то используется последний адрес.
.Pp
Каждый адрес в диапазоне, разделённом запятыми, интерпретируется относительно
текущего адреса.
В диапазоне, разделённом точкой с запятой, первый адрес
используется для установки текущего адреса, а второй адрес интерпретируется
относительно первого.
.Pp
Распознаются следующие символы адресов:
.Bl -tag -width indent
.It .
Текущая строка (адрес) в буфере.
.It $
Последняя строка в буфере.
.It n
.Em n Ns -я
строка в буфере,
где
.Em n
— число в диапазоне
.Em [0,$] .
.It - или ^
Предыдущая строка.
Это эквивалентно
.Em -1
и может повторяться с накопительным эффектом.
.It -n или ^n
.Em n Ns -я
предыдущая строка, где
.Em n
— неотрицательное число.
.It +
Следующая строка.
Это эквивалентно
.Em +1
и может повторяться с накопительным эффектом.
.It +n
.Em n Ns -я
следующая строка, где
.Em n
— неотрицательное число.
.It , или %
Первая до последней строки в буфере.
Это эквивалентно
диапазону адресов
.Em 1,$ .
.It ;
Текущая до последней строки в буфере.
Это эквивалентно
диапазону адресов
.Em .,$ .
.It /re/
Следующая строка, содержащая регулярное выражение
.Em re .
Поиск циклически переходит к началу буфера и продолжается вниз до
текущей строки, если необходимо.
// повторяет последний поиск.
.It ?re?
Предыдущая строка, содержащая регулярное выражение
.Em re .
Поиск циклически переходит к концу буфера и продолжается вверх до
текущей строки, если необходимо.
?? повторяет последний поиск.
.It 'lc
Строка,
ранее помеченная командой
.Em k
(mark), где
.Em lc
— строчная буква.
.El
.Sh РЕГУЛЯРНЫЕ ВЫРАЖЕНИЯ
Регулярные выражения — это шаблоны, используемые для выбора текста.
Например, команда:
.Pp
.Sm off
.Cm g No / Em string Xo
.No /
.Xc
.Sm on
.Pp
печатает все строки, содержащие
.Em string .
Регулярные выражения также
используются командой
.Em s
для выбора старого текста, который нужно заменить новым.
.Pp
Помимо задания строковых литералов, регулярные выражения могут
представлять
классы строк.
Говорят, что строки, представленные таким образом, сопоставляются
соответствующему регулярному выражению.
Если регулярное выражение
может сопоставиться с несколькими строками в строке, то выбирается
самое левое самое длинное совпадение.
.Pp
Следующие символы используются при построении регулярных выражений:
.Bl -tag -width indent
.It c
Любой символ
.Em c ,
не перечисленный ниже, включая
.Ql \&{ ,
.Ql \&} ,
.Ql \&( ,
.Ql \&) ,
.Ql <
и
.Ql > ,
совпадает сам с собой.
.It Pf \e c
Любой экранированный обратной косой чертой символ
.Em c ,
кроме
.Ql \&{ ,
.Ql \&} ,
.Ql \&( ,
.Ql \&) ,
.Ql <
и
.Ql > ,
совпадает сам с собой.
.It .
Сопоставить любой одиночный символ.
.It Op char-class
Сопоставить любой одиночный символ из
.Em char-class .
Чтобы включить
.Ql \&]
в
.Em char-class ,
он должен быть первым символом.
Диапазон символов можно задать, разделив конечные символы
диапазона с помощью
.Ql - ,
например,
.Ql a-z
задаёт строчные символы.
Следующие литеральные выражения также можно использовать в
.Em char-class
для задания наборов символов:
.Pp
.Bl -column "[:alnum:]" "[:cntrl:]" "[:lower:]" "[:space:]" -compact
.It [:alnum:] Ta [:cntrl:] Ta [:lower:] Ta [:space:]
.It [:alpha:] Ta [:digit:] Ta [:print:] Ta [:upper:]
.It [:blank:] Ta [:graph:] Ta [:punct:] Ta [:xdigit:]
.El
.Pp
Если
.Ql -
появляется как первый или последний
символ
.Em char-class ,
то он совпадает сам с собой.
Все остальные символы в
.Em char-class
совпадают сами с собой.
.Pp
Шаблоны в
.Em char-class
вида:
.Pp
.Bl -item -compact -offset 2n
.It
.Op \&. Ns Ar col-elm Ns .\&
или,
.It
.Op = Ns Ar col-elm Ns =
.El
.Pp
где
.Ar col-elm
— это
.Em collating element
интерпретируются в соответствии с текущими настройками локали
(в настоящее время не поддерживается).
См.
.Xr regex 3
и
.Xr re_format 7
для объяснения этих конструкций.
.It Op ^char-class
Сопоставить любой одиночный символ, кроме новой строки, не входящий в
.Em char-class .
.Em Char-class
определяется
как выше.
.It ^
Если
.Em ^
— первый символ регулярного выражения, то он
привязывает регулярное выражение к началу строки.
В противном случае он совпадает сам с собой.
.It $
Если
.Em $
— последний символ регулярного выражения, он
привязывает регулярное выражение к концу строки.
В противном случае он совпадает сам с собой.
.It Pf \e <
Привязать регулярное выражение из одного символа или подвыражение,
непосредственно следующее за ним, к началу слова.
(Это может быть недоступно)
.It Pf \e >
Привязать регулярное выражение из одного символа или подвыражение,
непосредственно следующее за ним, к концу слова.
(Это может быть недоступно)
.It Pf \e (re\e)
Определить подвыражение
.Em re .
Подвыражения могут быть вложенными.
Последующая обратная ссылка вида
.Pf \e Em n ,
где
.Em n
— число в диапазоне [1,9], раскрывается в текст, сопоставленный
.Em n Ns -м
подвыражением.
Например, регулярное выражение
.Ql \e(.*\e)\e1
совпадает с любой строкой,
состоящей из одинаковых смежных подстрок.
Подвыражения упорядочены относительно
их левого разделителя.
.It *
Сопоставить регулярное выражение из одного символа или подвыражение,
непосредственно предшествующее ему, ноль или более раз.
Если
.Em *
— первый
символ регулярного выражения или подвыражения, то он совпадает
сам с собой.
Оператор
.Em *
иногда даёт неожиданные результаты.
Например, регулярное выражение
.Ql b*
совпадает с началом
строки
.Ql abbb
(в отличие от подстроки
.Ql bbb ) ,
поскольку пустое совпадение
является единственным самым левым совпадением.
.It \e{n,m\e} или \e{n,\e} или \e{n\e}
Сопоставить регулярное выражение из одного символа или подвыражение,
непосредственно предшествующее ему, по крайней мере
.Em n
и не более
.Em m
раз.
Если
.Em m
опущено, то он совпадает по крайней мере
.Em n
раз.
Если запятая также опущена, то он совпадает ровно
.Em n
раз.
.El
.Pp
Дополнительные операторы регулярных выражений могут быть определены в зависимости от
конкретной реализации
.Xr regex 3 .
.Sh КОМАНДЫ
Все команды
.Nm
состоят из одного символа, хотя некоторые требуют дополнительных параметров.
Если параметры команды занимают несколько строк, то
каждая строка, кроме последней,
должна заканчиваться обратной косой чертой (\e).
.Pp
В общем, на строке допускается не более одной команды.
Однако большинство команд принимают суффикс печати, который может быть любым из
.Em p
(печать),
.Em l
(список)
или
.Em n
(нумеровать),
чтобы напечатать последнюю строку, затронутую командой.
.Pp
Прерывание (обычно ^C) приводит к отмене текущей команды
и возврату редактора в режим команд.
.Pp
Утилита
.Nm
распознаёт следующие команды.
Команды показаны вместе с
адресом или диапазоном адресов по умолчанию, подставляемыми, если ничего не
указано (в скобках).
.Bl -tag -width indent
.It (.)a
Добавить текст в буфер после указанной строки.
Текст вводится в режиме ввода.
Текущий адрес устанавливается на последнюю введённую строку.
.It (.,.)c
Изменить строки в буфере.
Указанные строки удаляются
из буфера, и текст добавляется на их место.
Текст вводится в режиме ввода.
Текущий адрес устанавливается на последнюю введённую строку.
.It (.,.)d
Удалить указанные строки из буфера.
Если после удалённого диапазона есть строка, то текущий адрес устанавливается
на эту строку.
В противном случае текущий адрес устанавливается на строку
перед удалённым диапазоном.
.It e Ar файл
Редактировать
.Ar файл
и установить имя файла по умолчанию.
Если
.Ar файл
не указан, то используется имя файла по умолчанию.
Все строки в буфере удаляются перед
чтением нового файла.
Текущий адрес устанавливается на последнюю прочитанную строку.
.It e Ar !команда
Редактировать стандартный вывод
.Ar !команда ,
(см.
.Ar !команда
ниже).
Имя файла по умолчанию не изменяется.
Все строки в буфере удаляются перед чтением вывода
.Ar команда .
Текущий адрес устанавливается на последнюю прочитанную строку.
.It E Ar файл
Редактировать
.Ar файл
безусловно.
Это аналогично команде
.Em e ,
за исключением того, что несохранённые изменения отбрасываются без предупреждения.
Текущий адрес устанавливается на последнюю прочитанную строку.
.It f Ar файл
Установить имя файла по умолчанию в
.Ar файл .
Если
.Ar файл
не указан, то печатается имя файла по умолчанию без экранирования.
.It (1,$)g/re/список-команд
Применить
.Ar список-команд
к каждой из указанных строк, соответствующих регулярному выражению
.Ar re .
Текущий адрес устанавливается на
строку, сопоставленную в данный момент, перед выполнением
.Ar список-команд .
В конце команды
.Em g
текущий адрес устанавливается на последнюю строку, затронутую
.Ar список-команд .
.Pp
Каждая команда в
.Ar список-команд
должна быть на отдельной строке,
и каждая строка, кроме последней, должна заканчиваться обратной косой чертой
(\e).
Разрешены любые команды, кроме
.Em g ,
.Em G ,
.Em v
и
.Em V .
Одна новая строка в
.Ar список-команд
эквивалентна команде
.Em p .
.It (1,$)G/re/
Интерактивно редактировать указанные строки, соответствующие регулярному выражению
.Ar re .
Для каждой соответствующей строки
строка печатается,
текущий адрес устанавливается,
и пользователю предлагается ввести
.Ar список-команд .
В конце команды
.Em G
текущий адрес
устанавливается на последнюю строку, затронутую (последним)
.Ar список-команд .
.Pp
Формат
.Ar список-команд
такой же, как у команды
.Em g .
Одна новая строка действует как пустой список команд.
Одиночный
.Ql &
повторяет последний непустой список команд.
.It H
Переключать печать объяснений ошибок.
По умолчанию объяснения не печатаются.
Рекомендуется, чтобы сценарии ed начинались с этой команды для
облегчения отладки.
.It h
Напечатать объяснение последней ошибки.
.It (.)i
Вставить текст в буфер перед текущей строкой.
Текст вводится в режиме ввода.
Текущий адрес устанавливается на последнюю введённую строку.
.It (.,.+1)j
Объединить указанные строки.
Указанные строки
удаляются из буфера и заменяются одной
строкой, содержащей их объединённый текст.
Текущий адрес устанавливается на результирующую строку.
.It (.)klc
Пометить строку строчной буквой
.Em lc .
Затем к строке можно обращаться как
.Em 'lc
(т.е. апостроф, за которым следует
.Em lc )
в последующих командах.
Метка не снимается, пока строка не
удалена или иным образом изменена.
.It (.,.)l
Печатать указанные строки однозначно.
Если одна строка занимает больше одного экрана (как может быть,
например, при просмотре двоичного файла),
на последней строке печатается приглашение
.Dq Li --More-- .
Утилита
.Nm
ждёт нажатия клавиши RETURN
перед отображением следующего экрана.
Текущий адрес устанавливается на последнюю напечатанную строку.
.It (.,.)m(.)
Переместить строки в буфере.
Указанные строки перемещаются после
правого адреса назначения, которым может быть адрес
.Em 0
(ноль).
Текущий адрес устанавливается на
последнюю перемещённую строку.
.It (.,.)n
Печатать указанные строки вместе с
их номерами строк.
Текущий адрес устанавливается на последнюю напечатанную
строку.
.It (.,.)p
Печатать указанные строки.
Текущий адрес устанавливается на последнюю напечатанную
строку.
.It P
Переключать приглашение командной строки.
Если приглашение не было задано параметром командной строки
.Fl p Ar строка ,
приглашение командной строки по умолчанию отключено.
.It q
Выйти из
.Nm .
.It Q
Выйти из
.Nm
безусловно.
Это аналогично команде
.Em q ,
за исключением того, что несохранённые изменения отбрасываются без предупреждения.
.It ($)r Ar файл
Читать
.Ar файл
после указанной строки.
Если
.Ar файл
не указан, то используется имя файла по умолчанию.
Если до команды не было имени файла по умолчанию,
то имя файла по умолчанию устанавливается в
.Ar файл .
В противном случае имя файла по умолчанию не изменяется.
Текущий адрес устанавливается на последнюю прочитанную строку.
.It ($)r Ar !команда
Читать
после указанной строки
стандартный вывод
.Ar !команда ,
(см.
.Ar !команда
ниже).
Имя файла по умолчанию не изменяется.
Текущий адрес устанавливается на последнюю прочитанную строку.
.It (.,.)s/re/замена/
.It (.,.)s/re/замена/g
.It (.,.)s/re/замена/n
Заменить текст в указанных строках,
соответствующий регулярному выражению
.Ar re ,
на
.Ar замена .
По умолчанию заменяется только первое совпадение в каждой строке.
Если задан суффикс
.Em g
(global), то заменяются все совпадения.
Суффикс
.Em n ,
где
.Em n
— положительное число, вызывает замену только
.Em n Ns -го
совпадения.
Ошибкой является, если не выполнено ни одной замены ни в одной из указанных
строк.
Текущий адрес устанавливается на последнюю затронутую строку.
.Pp
.Ar \&Re
и
.Ar замена
могут разделяться любым символом, кроме пробела и новой строки
(см. команду
.Em s
ниже).
Если один или два последних разделителя опущены, то печатается последняя
затронутая строка, как если бы был указан суффикс печати
.Em p .
.Pp
Неэкранированный
.Ql &
в
.Ar замена
заменяется текущим сопоставленным текстом.
Последовательность символов
.Em \em ,
где
.Em m
— число в диапазоне [1,9], заменяется
.Em m Ns -м
выражением обратной ссылки сопоставленного текста.
Если
.Ar замена
состоит из одного
.Ql % ,
то используется
.Ar замена
из последней замены.
Новые строки могут быть встроены в
.Ar замена ,
если они экранированы обратной косой чертой (\e).
.It (.,.)s
Повторить последнюю замену.
Эта форма команды
.Em s
принимает суффикс счётчика
.Em n
или любую комбинацию символов
.Em r ,
.Em g
и
.Em p .
Если задан суффикс счётчика
.Em n ,
то заменяется только
.Em n Ns -е
совпадение.
Суффикс
.Em r
вызывает
использование регулярного выражения последнего поиска вместо
регулярного выражения последней замены.
Суффикс
.Em g
переключает глобальный суффикс последней замены.
Суффикс
.Em p
переключает суффикс печати последней замены.
Текущий адрес устанавливается на последнюю затронутую строку.
.It (.,.)t(.)
Копировать (т.е. перенести) указанные строки после правого
адреса назначения, которым может быть адрес
.Em 0
(ноль).
Текущий адрес устанавливается на последнюю
скопированную строку.
.It u
Отменить последнюю команду и восстановить текущий адрес
до того, каким он был перед командой.
Глобальные команды
.Em g ,
.Em G ,
.Em v
и
.Em V .
рассматриваются отменой как одна команда.
.Em u
является обратной самой себе.
.It (1,$)v/re/список-команд
Применить
.Ar список-команд
к каждой из указанных строк, не соответствующих регулярному выражению
.Ar re .
Это аналогично команде
.Em g .
.It (1,$)V/re/
Интерактивно редактировать указанные строки, не соответствующие регулярному выражению
.Ar re .
Это аналогично команде
.Em G .
.It (1,$)w Ar файл
Записать указанные строки в
.Ar файл .
Любое предыдущее содержимое
.Ar файл
теряется без предупреждения.
Если имени файла по умолчанию нет, то имя файла по умолчанию устанавливается в
.Ar файл ,
иначе оно не изменяется.
Если имя файла не указано, то используется имя файла
по умолчанию.
Текущий адрес не изменяется.
.It (1,$)wq Ar файл
Записать указанные строки в
.Ar файл ,
а затем выполнить команду
.Em q .
.It (1,$)w Ar !команда
Записать указанные строки на стандартный ввод
.Ar !команда ,
(см.
.Em !команда
ниже).
Имя файла по умолчанию и текущий адрес не изменяются.
.It (1,$)W Ar файл
Добавить указанные строки в конец
.Ar файл .
Это аналогично команде
.Em w ,
за исключением того, что предыдущее содержимое файла не перезаписывается.
Текущий адрес не изменяется.
.It Pf (.+1)z n
Прокрутить
.Ar n
строк за раз, начиная с указанной строки.
Если
.Ar n
не указано, то используется текущий размер окна.
Текущий адрес устанавливается на последнюю напечатанную строку.
.It !команда
Выполнить
.Ar команда
через
.Xr sh 1 .
Если первый символ
.Ar команда
—
.Ql \&! ,
то он заменяется текстом
предыдущей
.Ar !команда .
Утилита
.Nm
не обрабатывает
.Ar команда
для экранирования обратной косой чертой (\e).
Однако неэкранированный
.Em %
заменяется именем файла по умолчанию.
Когда оболочка возвращается из выполнения, в стандартный вывод
печатается
.Ql \&! .
Текущая строка не изменяется.
.It ($)=
Напечатать номер строки указанного адреса.
.It (.+1)новая строка
Напечатать указанную строку и установить текущий адрес на
эту строку.
.El
.Sh ФАЙЛЫ
.Bl -tag -width /tmp/ed.* -compact
.It Pa /tmp/ed.*
файл буфера
.It Pa ed.hup
файл, в который
.Nm
пытается записать буфер, если терминал отключается
.El
.Sh ДИАГНОСТИКА
При возникновении ошибки
.Nm
печатает
.Ql \&?
и либо возвращается в режим команд,
либо завершается, если его ввод происходит из сценария.
Объяснение последней ошибки можно
напечатать с помощью команды
.Em h
(help).
.Pp
Поскольку команда
.Em g
(global) маскирует любые ошибки от неудачных поисков и замен,
её можно использовать для выполнения условных операций в сценариях; например,
.Pp
.Sm off
.Cm g No / Em old Xo
.No / Cm s
.No // Em new
.No /
.Xc
.Sm on
.Pp
заменяет любые вхождения
.Em old
на
.Em new .
Если команда
.Em u
(undo) встречается в списке глобальных команд, то
список команд выполняется только один раз.
.Pp
Если диагностика не отключена, попытка выйти из
.Nm
или отредактировать другой файл до записи изменённого буфера
приводит к ошибке.
Если команда введена во второй раз, она успешно выполняется,
но любые изменения в буфере теряются.
.Sh СМ. ТАКЖЕ
.Xr sed 1 ,
.Xr sh 1 ,
.Xr vi 1 ,
.Xr regex 3
.Pp
USD:12-13
.Rs
.%A B. W. Kernighan
.%A P. J. Plauger
.%B Software Tools in Pascal
.%O Addison-Wesley
.%D 1981
.Re
.Rs
.%A B. W. Kernighan
.%T A Tutorial Introduction to the UNIX Text Editor
.Re
.Rs
.%A B. W. Kernighan
.%T Advanced Editing on UNIX
.Re
.Sh ОГРАНИЧЕНИЯ
Утилита
.Nm
обрабатывает аргументы
.Ar файл
для экранирования обратной косой чертой, т.е. в имени файла
любые символы, перед которыми стоит обратная косая черта (\e),
интерпретируются буквально.
.Pp
Если текстовый (не двоичный) файл не заканчивается символом новой строки,
то
.Nm
добавляет его при чтении/записи.
В случае двоичного файла
.Nm
не добавляет новую строку при чтении/записи.
.Pp
накладные расходы на строку: 4 ints
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v1 .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Утилита
.Nm
не распознаёт многобайтовые символы.
