.\" FRDP path contrib/bc/manuals/bc/EHN.1
.\" FRDP githash fdc4a7c8012b214986cfa2e2fb6d99731f004b1b
.\" FRDP hash256 666ac2631b97733a83a4ef0b95b7e3f075f9adc97e57c6e33c9c71ef414ee105
.nh
.ad l
.SH ИМЯ
bc \- язык и калькулятор десятичной арифметики произвольной точности
.SH СИНТАКСИС
\f[B]bc\f[R] [\f[B]\-cCghilPqRsvVw\f[R]] [\f[B]\-\-digit\-clamp\f[R]]
[\f[B]\-\-no\-digit\-clamp\f[R]] [\f[B]\-\-global\-stacks\f[R]]
[\f[B]\-\-help\f[R]] [\f[B]\-\-interactive\f[R]] [\f[B]\-\-mathlib\f[R]]
[\f[B]\-\-no\-prompt\f[R]] [\f[B]\-\-no\-read\-prompt\f[R]]
[\f[B]\-\-quiet\f[R]] [\f[B]\-\-standard\f[R]] [\f[B]\-\-warn\f[R]]
[\f[B]\-\-version\f[R]] [\f[B]\-e\f[R] \f[I]expr\f[R]]
[\f[B]\-\-expression\f[R]=\f[I]expr\f[R]\&...]
[\f[B]\-f\f[R] \f[I]file\f[R]\&...]
[\f[B]\-\-file\f[R]=\f[I]file\f[R]\&...]
[\f[I]file\f[R]\&...]
.SH ОПИСАНИЕ
bc(1) — интерактивный процессор для языка, впервые стандартизованного в
1991 году POSIX.
(См. раздел \f[B]СТАНДАРТЫ\f[R].)
Язык предоставляет десятичную арифметику неограниченной точности и
несколько похож на C, но есть различия.
Такие различия отмечены в этом документе.
.PP
После разбора и обработки опций этот bc(1) читает любые файлы, заданные в
командной строке, и выполняет их перед чтением из \f[B]stdin\f[R].
.PP
Этот bc(1) является заменой \f[I]любого\f[R] bc(1), включая
(и особенно) GNU bc(1).
Он также имеет много расширений и дополнительных возможностей по сравнению с другими
реализациями.
.PP
\f[B]Примечание\f[R]: Если запуск этого bc(1) на \f[I]любом\f[R] скрипте, предназначенном для
другого bc(1), даёт ошибку разбора, вероятно, потому что слово, которое этот
bc(1) резервирует как ключевое, используется как имя функции, переменной
или массива.
Чтобы исправить это, используйте опцию командной строки \f[B]\-r\f[R]
\f[I]keyword\f[R], где \f[I]keyword\f[R] — ключевое слово, которое используется
как имя в скрипте.
Для получения дополнительной информации см. раздел \f[B]ОПЦИИ\f[R].
.PP
Если разбор скриптов, предназначенных для других реализаций bc(1), всё ещё не
работает, это ошибка, и о ней следует сообщить.
См. раздел \f[B]ИЗВЕСТНЫЕ ОШИБКИ\f[R].
.SH ОПЦИИ
Далее перечислены опции, которые принимает bc(1).
.TP
\f[B]\-C\f[R], \f[B]\-\-no\-digit\-clamp\f[R]
Отключает ограничение цифр, больших или равных текущему
\f[B]ibase\f[R], при разборе чисел.
.RS
.PP
Это означает, что значение, добавляемое к числу из цифры, всегда равно значению этой
цифры, умноженному на значение ibase, возведённое в степень
позиции цифры, которая начинается с 0 у младшей
значащей цифры.
.PP
Если эта и/или опции \f[B]\-c\f[R] или \f[B]\-\-digit\-clamp\f[R]
заданы несколько раз, используется последняя заданная.
.PP
Эта опция переопределяет переменную окружения \f[B]BC_DIGIT_CLAMP\f[R]
(см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]) и значение по умолчанию, которое
можно узнать с помощью опций \f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-c\f[R], \f[B]\-\-digit\-clamp\f[R]
Включает ограничение цифр, больших или равных текущему
\f[B]ibase\f[R], при разборе чисел.
.RS
.PP
Это означает, что для цифр, значение которых больше или равно ibase,
значение, добавляемое к числу из цифры, равно значению ibase минус 1,
умноженному на значение ibase, возведённое в степень
позиции цифры, которая начинается с 0 у младшей
значащей цифры.
.PP
Если эта и/или опции \f[B]\-C\f[R] или \f[B]\-\-no\-digit\-clamp\f[R]
заданы несколько раз, используется последняя заданная.
.PP
Эта опция переопределяет переменную окружения \f[B]BC_DIGIT_CLAMP\f[R]
(см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]) и значение по умолчанию, которое
можно узнать с помощью опций \f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-e\f[R] \f[I]expr\f[R], \f[B]\-\-expression\f[R]=\f[I]expr\f[R]
Вычисляет \f[I]expr\f[R].
Если задано несколько выражений, они вычисляются по порядку.
Если также заданы файлы (см. опции \f[B]\-f\f[R] и \f[B]\-\-file\f[R]),
выражения и файлы вычисляются в заданном порядке.
Это означает, что если файл задан перед выражением, файл
считывается и вычисляется первым.
.RS
.PP
Если эта опция задана в командной строке (т. е. не в
\f[B]BC_ENV_ARGS\f[R], см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]),
то после обработки всех выражений и файлов bc(1) завершится, если только
\f[B]\-\f[R] (\f[B]stdin\f[R]) не был задан как аргумент хотя бы один раз для
\f[B]\-f\f[R] или \f[B]\-\-file\f[R], в командной строке или в
\f[B]BC_ENV_ARGS\f[R].
Однако если любые другие аргументы \f[B]\-e\f[R], \f[B]\-\-expression\f[R],
\f[B]\-f\f[R] или \f[B]\-\-file\f[R] заданы после
\f[B]\-f\-\f[R] или эквивалента, bc(1) выдаст фатальную ошибку
и завершится.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-f\f[R] \f[I]file\f[R], \f[B]\-\-file\f[R]=\f[I]file\f[R]
Считывает \f[I]file\f[R] и вычисляет его построчно, как будто он
был прочитан через \f[B]stdin\f[R].
Если также заданы выражения (см. опции \f[B]\-e\f[R] и
\f[B]\-\-expression\f[R]), выражения вычисляются в
заданном порядке.
.RS
.PP
Если эта опция задана в командной строке (т. е. не в
\f[B]BC_ENV_ARGS\f[R], см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]),
то после обработки всех выражений и файлов bc(1) завершится, если только
\f[B]\-\f[R] (\f[B]stdin\f[R]) не был задан как аргумент хотя бы один раз для
\f[B]\-f\f[R] или \f[B]\-\-file\f[R].
Однако если любые другие аргументы \f[B]\-e\f[R], \f[B]\-\-expression\f[R],
\f[B]\-f\f[R] или \f[B]\-\-file\f[R] заданы после
\f[B]\-f\-\f[R] или эквивалента, bc(1) выдаст фатальную ошибку
и завершится.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-g\f[R], \f[B]\-\-global\-stacks\f[R]
Превращает глобальные переменные \f[B]ibase\f[R], \f[B]obase\f[R] и \f[B]scale\f[R]
в стеки.
.RS
.PP
Это приводит к тому, что копия текущего значения всех трёх переменных
помещается в стек при каждом вызове функции, а также извлекается при
возврате каждой функции.
Это означает, что функции могут присваивать любые из этих глобальных переменных
без беспокойства о том, что изменение повлияет на другие функции.
Таким образом, гипотетическая функция с именем \f[B]output(x,b)\f[R], которая просто
выводила \f[B]x\f[R] в системе счисления \f[B]b\f[R], могла бы быть написана так:
.IP
.EX
define void output(x, b) {
    obase=b
    x
}
.EE
.PP
вместо так:
.IP
.EX
define void output(x, b) {
    auto c
    c=obase
    obase=b
    x
    obase=c
}
.EE
.PP
Это значительно упрощает написание функций.
.PP
Однако, поскольку использование этого флага означает, что функции не могут задавать
\f[B]ibase\f[R], \f[B]obase\f[R] или \f[B]scale\f[R] глобально, функции,
которые были сделаны для этого, больше не могут работать.
Есть два возможных варианта использования, и для каждого есть решение.
.PP
Во-первых, если функция вызывается при запуске, чтобы превратить bc(1) в конвертер
чисел, можно заменить эту возможность различными псевдонимами оболочки.
Примеры:
.IP
.EX
alias d2o=\[dq]bc \-e ibase=A \-e obase=8\[dq]
alias h2b=\[dq]bc \-e ibase=G \-e obase=2\[dq]
.EE
.PP
Во-вторых, если назначение функции — устанавливать \f[B]ibase\f[R],
\f[B]obase\f[R] или \f[B]scale\f[R] глобально для любых других целей, её
можно разделить на одну-три функции (в зависимости от того, сколько глобальных переменных она
устанавливает), и каждая из этих функций может возвращать желаемое значение для
глобальной переменной.
.PP
Если поведение этой опции желательно при каждом запуске bc(1), то
пользователи могут убедиться, что определена \f[B]BC_ENV_ARGS\f[R], и включить эту
опцию (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R] для получения более
подробной информации).
.PP
Если используются \f[B]\-s\f[R], \f[B]\-w\f[R] или любые эквиваленты, эта
опция игнорируется.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-h\f[R], \f[B]\-\-help\f[R]
Выводит сообщение об использовании и завершает работу.
.TP
\f[B]\-I\f[R] \f[I]ibase\f[R], \f[B]\-\-ibase\f[R]=\f[I]ibase\f[R]
Устанавливает встроенную переменную \f[B]ibase\f[R] в значение \f[I]ibase\f[R],
предполагая, что \f[I]ibase\f[R] задано в системе счисления 10.
Это фатальная ошибка, если \f[I]ibase\f[R] не является допустимым числом.
.RS
.PP
Если задано несколько экземпляров этой опции, используется последний.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-i\f[R], \f[B]\-\-interactive\f[R]
Принудительно включает интерактивный режим.
(См. раздел \f[B]ИНТЕРАКТИВНЫЙ РЕЖИМ\f[R].)
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-L\f[R], \f[B]\-\-no\-line\-length\f[R]
Отключает проверку длины строк и выводит числа без обратных косых черт и
символов новой строки.
Иными словами, эта опция устанавливает \f[B]BC_LINE_LENGTH\f[R] в \f[B]0\f[R]
(см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-l\f[R], \f[B]\-\-mathlib\f[R]
Устанавливает \f[B]scale\f[R] (см. раздел \f[B]СИНТАКСИС\f[R]) в \f[B]20\f[R]
и загружает включённую математическую библиотеку перед выполнением любого кода,
включая любые выражения или файлы, указанные в командной строке.
.RS
.PP
Чтобы узнать, что находится в библиотеке, см. раздел \f[B]БИБЛИОТЕКА\f[R].
.RE
.TP
\f[B]\-O\f[R] \f[I]obase\f[R], \f[B]\-\-obase\f[R]=\f[I]obase\f[R]
Устанавливает встроенную переменную \f[B]obase\f[R] в значение \f[I]obase\f[R],
предполагая, что \f[I]obase\f[R] задано в системе счисления 10.
Это фатальная ошибка, если \f[I]obase\f[R] не является допустимым числом.
.RS
.PP
Если задано несколько экземпляров этой опции, используется последний.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-P\f[R], \f[B]\-\-no\-prompt\f[R]
Отключает приглашение в режиме TTY.
(Приглашение включено только в режиме TTY.
См. раздел \f[B]РЕЖИМ TTY\f[R].)
Это в основном для тех пользователей, которые не хотят приглашения или не привыкли
к ним в bc(1).
Большинство таких пользователей захотят поместить эту опцию в
\f[B]BC_ENV_ARGS\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
.RS
.PP
Эти опции переопределяют переменные окружения \f[B]BC_PROMPT\f[R] и \f[B]BC_TTY_MODE\f[R]
(см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-q\f[R], \f[B]\-\-quiet\f[R]
Эта опция предназначена для совместимости с GNU bc(1)
(https://www.gnu.org/software/bc/); она ничего не делает.
Без этой опции GNU bc(1) выводит заголовок авторских прав.
Этот bc(1) выводит заголовок авторских прав только если задана одна или несколько
опций \f[B]\-v\f[R], \f[B]\-V\f[R] или \f[B]\-\-version\f[R],
если только переменная окружения \f[B]BC_BANNER\f[R] не установлена и не содержит
ненулевое целое число, или если этот bc(1) был собран с заголовком, отображаемым
по умолчанию.
Если \f[I]любое\f[R] из этого имеет место, то эта опция \f[I]действительно\f[R]
не позволяет bc(1) выводить заголовок.
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-R\f[R], \f[B]\-\-no\-read\-prompt\f[R]
Отключает приглашение чтения в режиме TTY.
(Приглашение чтения включено только в режиме TTY.
См. раздел \f[B]РЕЖИМ TTY\f[R].)
Это в основном для тех пользователей, которые не хотят приглашения чтения или не
привыкли к ним в bc(1).
Большинство таких пользователей захотят поместить эту опцию в
\f[B]BC_ENV_ARGS\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
Эта опция также полезна в строках hash bang скриптов bc(1), которые
запрашивают пользовательский ввод.
.RS
.PP
Эта опция не отключает обычное приглашение, потому что приглашение чтения
используется только при вызове встроенной функции \f[B]read()\f[R].
.PP
Эти опции \f[I]действительно\f[R] переопределяют переменные окружения \f[B]BC_PROMPT\f[R] и
\f[B]BC_TTY_MODE\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ
ОКРУЖЕНИЯ\f[R]), но только для приглашения чтения.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-r\f[R] \f[I]keyword\f[R], \f[B]\-\-redefine\f[R]=\f[I]keyword\f[R]
Переопределяет \f[I]keyword\f[R], чтобы позволить использовать его как
имя функции, переменной или массива.
Это полезно, когда этот bc(1) выдаёт ошибки разбора при разборе скриптов,
предназначенных для других реализаций bc(1).
.RS
.PP
Ключевые слова, которые этот bc(1) позволяет переопределять:
.IP \[bu] 2
\f[B]abs\f[R]
.IP \[bu] 2
\f[B]asciify\f[R]
.IP \[bu] 2
\f[B]continue\f[R]
.IP \[bu] 2
\f[B]divmod\f[R]
.IP \[bu] 2
\f[B]else\f[R]
.IP \[bu] 2
\f[B]halt\f[R]
.IP \[bu] 2
\f[B]last\f[R]
.IP \[bu] 2
\f[B]limits\f[R]
.IP \[bu] 2
\f[B]maxibase\f[R]
.IP \[bu] 2
\f[B]maxobase\f[R]
.IP \[bu] 2
\f[B]maxscale\f[R]
.IP \[bu] 2
\f[B]modexp\f[R]
.IP \[bu] 2
\f[B]print\f[R]
.IP \[bu] 2
\f[B]read\f[R]
.IP \[bu] 2
\f[B]stream\f[R]
.PP
Если любое из этих ключевых слов используется как имя функции, переменной или массива
в скрипте, используйте эту опцию с ключевым словом в качестве аргумента.
Если используется несколько, используйте эту опцию для всех них; её можно использовать
несколько раз.
.PP
Ключевые слова \f[I]не\f[R] переопределяются при разборе встроенной математической
библиотеки (см. раздел \f[B]БИБЛИОТЕКА\f[R]).
.PP
Переопределение ключевых слов, требуемых стандартом POSIX
(см. раздел \f[B]СТАНДАРТЫ\f[R]), является фатальной ошибкой.
Попытка переопределить слова, которые этот bc(1) не
резервирует как ключевые, является фатальной ошибкой.
.RE
.TP
\f[B]\-S\f[R] \f[I]scale\f[R], \f[B]\-\-scale\f[R]=\f[I]scale\f[R]
Устанавливает встроенную переменную \f[B]scale\f[R] в значение \f[I]scale\f[R],
предполагая, что \f[I]scale\f[R] задано в системе счисления 10.
Это фатальная ошибка, если \f[I]scale\f[R] не является допустимым числом.
.RS
.PP
Если задано несколько экземпляров этой опции, используется последний.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-s\f[R], \f[B]\-\-standard\f[R]
Обрабатывает точно язык, определённый стандартом (см.
раздел \f[B]СТАНДАРТЫ\f[R]), и выдаёт ошибку, если используются какие-либо расширения.
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-v\f[R], \f[B]\-V\f[R], \f[B]\-\-version\f[R]
Выводит информацию о версии (заголовок авторских прав) и завершает работу.
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-w\f[R], \f[B]\-\-warn\f[R]
Как \f[B]\-s\f[R] и \f[B]\-\-standard\f[R], за исключением того, что для
нестандартных расширений выводятся предупреждения (а не ошибки), и выполнение
продолжается нормально.
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-z\f[R], \f[B]\-\-leading\-zeroes\f[R]
Заставляет bc(1) выводить все числа больше \f[B]\-1\f[R] и меньше
\f[B]1\f[R], и не равные \f[B]0\f[R], с ведущим нулём.
.RS
.PP
Это можно задать для отдельных чисел с помощью функций \f[B]plz(x)\f[R],
\f[B]plznl(x)\f[R], \f[B]pnlz(x)\f[R] и \f[B]pnlznl(x)\f[R]
в расширенной математической библиотеке (см. раздел \f[B]БИБЛИОТЕКА\f[R]).
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.PP
Все длинные опции являются \f[B]непереносимыми расширениями\f[R].
.SH СТАНДАРТНЫЙ ВВОД
Если никакие файлы или выражения не заданы опциями \f[B]\-f\f[R],
\f[B]\-\-file\f[R], \f[B]\-e\f[R] или \f[B]\-\-expression\f[R],
то bc(1) читает из \f[B]stdin\f[R].
.PP
Однако здесь есть несколько оговорок.
.PP
Во-первых, \f[B]stdin\f[R] вычисляется по одной строке за раз.
Единственное исключение — если разбор не может завершиться.
Это означает, что начало строки без её завершения или начало
функции, инструкции \f[B]if\f[R] или цикла без их завершения также
приведёт к тому, что bc(1) не выполнит код.
.PP
Во-вторых, после инструкции \f[B]if\f[R] bc(1) не знает, будет ли
следовать инструкция \f[B]else\f[R], поэтому он не выполняет её, пока не
узнает, что инструкции \f[B]else\f[R] не будет.
.SH СТАНДАРТНЫЙ ВЫВОД
Любой вывод, не являющийся ошибкой, записывается в \f[B]stdout\f[R].
Кроме того, если включены история (см. раздел \f[B]ИСТОРИЯ\f[R]) и
приглашение (см. раздел \f[B]РЕЖИМ TTY\f[R]), оба выводятся
в \f[B]stdout\f[R].
.PP
\f[B]Примечание\f[R]: В отличие от других реализаций bc(1), этот bc(1) выдаёт
фатальную ошибку (см. раздел \f[B]СТАТУС ВЫХОДА\f[R]), если не может
записать в \f[B]stdout\f[R], поэтому если \f[B]stdout\f[R] закрыт, как в
\f[B]bc  >&\-\f[R], он завершится с ошибкой.
Это сделано для того, чтобы bc(1) мог сообщать о проблемах, когда \f[B]stdout\f[R]
перенаправлен в файл.
.PP
Если есть скрипты, зависящие от поведения других реализаций bc(1),
рекомендуется изменить эти скрипты так, чтобы они перенаправляли \f[B]stdout\f[R]
в \f[B]/dev/null\f[R].
.SH СТАНДАРТНЫЙ ВЫВОД ОШИБОК
Любой вывод ошибок записывается в \f[B]stderr\f[R].
.PP
\f[B]Примечание\f[R]: В отличие от других реализаций bc(1), этот bc(1) выдаёт
фатальную ошибку (см. раздел \f[B]СТАТУС ВЫХОДА\f[R]), если не может
записать в \f[B]stderr\f[R], поэтому если \f[B]stderr\f[R] закрыт, как в
\f[B]bc  2>&\-\f[R], он завершится с ошибкой.
Это сделано для того, чтобы bc(1) мог завершиться с кодом ошибки, когда
\f[B]stderr\f[R] перенаправлен в файл.
.PP
Если есть скрипты, зависящие от поведения других реализаций bc(1),
рекомендуется изменить эти скрипты так, чтобы они перенаправляли \f[B]stderr\f[R]
в \f[B]/dev/null\f[R].
.SH СИНТАКСИС
Синтаксис программ bc(1) в основном похож на C, с некоторыми отличиями.
Этот bc(1) следует стандарту POSIX (см. раздел \f[B]СТАНДАРТЫ\f[R]),
который является гораздо более полным источником по языку, принимаемому этим
bc(1).
Этот раздел предназначен для краткого обзора и перечисления всех
расширений стандарта.
.PP
В разделах ниже \f[B]E\f[R] означает выражение, \f[B]S\f[R] означает
инструкцию, а \f[B]I\f[R] означает идентификатор.
.PP
Идентификаторы (\f[B]I\f[R]) начинаются со строчной буквы и могут
содержать любое количество (до \f[B]BC_NAME_MAX\-1\f[R]) строчных
букв (\f[B]a\-z\f[R]), цифр (\f[B]0\-9\f[R]) и подчёркиваний
(\f[B]_\f[R]).
Регулярное выражение: \f[B][a\-z][a\-z0\-9_]*\f[R].
Идентификаторы длиной более одного символа (буквы) являются
\f[B]непереносимым расширением\f[R].
.PP
\f[B]ibase\f[R] — глобальная переменная, определяющая, как интерпретировать
константные числа.
Это основание «ввода», или система счисления, используемая для интерпретации
входных чисел.
Изначально \f[B]ibase\f[R] равно \f[B]10\f[R].
Если флаги \f[B]\-s\f[R] (\f[B]\-\-standard\f[R]) и \f[B]\-w\f[R]
(\f[B]\-\-warn\f[R]) не были заданы в командной строке, максимальное
допустимое значение для \f[B]ibase\f[R] — \f[B]36\f[R].
В противном случае — \f[B]16\f[R].
Минимальное допустимое значение для \f[B]ibase\f[R] — \f[B]2\f[R].
Максимальное допустимое значение для \f[B]ibase\f[R] можно узнать в
программах bc(1) с помощью встроенной функции \f[B]maxibase()\f[R].
.PP
\f[B]obase\f[R] — глобальная переменная, определяющая, как выводить результаты.
Это основание «вывода», или система счисления, используемая для вывода
чисел.
Изначально \f[B]obase\f[R] равно \f[B]10\f[R].
Максимальное допустимое значение для \f[B]obase\f[R] — \f[B]BC_BASE_MAX\f[R], и
его можно узнать в программах bc(1) с помощью встроенной функции
\f[B]maxobase()\f[R].
Минимальное допустимое значение для \f[B]obase\f[R] — \f[B]2\f[R].
Значения выводятся в указанной системе счисления.
.PP
\f[I]scale\f[R] выражения — это количество цифр в
результате выражения справа от десятичной точки, а \f[B]scale\f[R] —
глобальная переменная, задающая точность любых операций, за
исключениями.
Изначально \f[B]scale\f[R] равно \f[B]0\f[R].
\f[B]scale\f[R] не может быть отрицательным.
Максимальное допустимое значение для \f[B]scale\f[R] — \f[B]BC_SCALE_MAX\f[R],
и его можно узнать в программах bc(1) с помощью встроенной функции
\f[B]maxscale()\f[R].
.PP
В bc(1) есть как \f[I]глобальные\f[R], так и \f[I]локальные\f[R] переменные.
Все \f[I]локальные\f[R] переменные локальны для функции; они являются
параметрами или введены в списке \f[B]auto\f[R] функции
(см. раздел \f[B]ФУНКЦИИ\f[R]).
Если происходит доступ к переменной, которая не является параметром или
не указана в списке \f[B]auto\f[R], предполагается, что она \f[I]глобальная\f[R].
Если родительская функция имеет \f[I]локальную\f[R] версию переменной,
которую дочерняя функция считает \f[I]глобальной\f[R], значение этой
\f[I]глобальной\f[R] переменной в дочерней функции — это значение
переменной в родительской функции, а не значение фактической
\f[I]глобальной\f[R] переменной.
.PP
Всё вышесказанное также применимо к массивам.
.PP
Значение инструкции, являющейся выражением (т. е. любого из именованных
выражений или операндов), выводится, если только оператор с наименьшим
приоритетом не является оператором присваивания \f[I]и\f[R] выражение
не окружено скобками.
.PP
Выводимое значение также присваивается специальной переменной
\f[B]last\f[R].
Одиночная точка (\f[B].\f[R]) также может использоваться как синоним
\f[B]last\f[R].
Это \f[B]непереносимые расширения\f[R].
.PP
Инструкции могут разделяться точками с запятой или символами новой строки.
.SS Комментарии
Есть два вида комментариев:
Блочные комментарии заключаются между \f[B]/*\f[R] и \f[B]*/\f[R].
Строчные комментарии начинаются с \f[B]#\f[R] и продолжаются до, не
включая, следующего символа новой строки.
Это \f[B]непереносимое расширение\f[R].
.SS Именованные выражения
В bc(1) именованными выражениями являются следующие:
Переменные: \f[B]I\f[R]
Элементы массива: \f[B]I[E]\f[R]
\f[B]ibase\f[R]
\f[B]obase\f[R]
\f[B]scale\f[R]
\f[B]last\f[R] или одиночная точка (\f[B].\f[R])
.PP
Номер 6 является \f[B]непереносимым расширением\f[R].
.PP
Переменные и массивы не конфликтуют; пользователи могут иметь массивы с
тем же именем, что и переменные.
Это также относится к функциям (см. раздел \f[B]ФУНКЦИИ\f[R]), поэтому
пользователь может иметь переменную, массив и функцию с одинаковым
именем, и они не будут перекрывать друг друга, ни внутри функций,
ни вне них.
.PP
Именованные выражения требуются как операнд операторов
\f[B]инкремента\f[R]/\f[B]декремента\f[R] и как левая часть
операторов \f[B]присваивания\f[R] (см. подраздел \f[I]Операторы\f[R]).
.SS Операнды
В bc(1) допустимы следующие операнды:
Числа (см. подраздел \f[I]Числа\f[R] ниже).
Индексы массива (\f[B]I[E]\f[R]).
\f[B](E)\f[R]: значение \f[B]E\f[R] (используется для изменения приоритета).
\f[B]sqrt(E)\f[R]: квадратный корень из \f[B]E\f[R].
\f[B]E\f[R] должен быть неотрицательным.
\f[B]length(E)\f[R]: количество значащих десятичных цифр в
\f[B]E\f[R].
Возвращает \f[B]1\f[R] для \f[B]0\f[R] без десятичных знаков.
Если передана строка, возвращается длина строки.
Передача строки в \f[B]length(E)\f[R] — это \f[B]непереносимое
расширение\f[R].
\f[B]length(I[])\f[R]: количество элементов в массиве \f[B]I\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]scale(E)\f[R]: \f[I]scale\f[R] для \f[B]E\f[R].
\f[B]abs(E)\f[R]: абсолютное значение \f[B]E\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]is_number(E)\f[R]: \f[B]1\f[R], если данный аргумент — число,
\f[B]0\f[R], если это строка.
Это \f[B]непереносимое расширение\f[R].
\f[B]is_string(E)\f[R]: \f[B]1\f[R], если данный аргумент — строка,
\f[B]0\f[R], если это число.
Это \f[B]непереносимое расширение\f[R].
\f[B]modexp(E, E, E)\f[R]: модульное возведение в степень, где первое
выражение — основание, второе — показатель степени, а третье —
модуль.
Все три значения должны быть целыми.
Второй аргумент должен быть неотрицательным.
Третий аргумент должен быть ненулевым.
Это \f[B]непереносимое расширение\f[R].
\f[B]divmod(E, E, I[])\f[R]: деление и взятие остатка в одной операции.
Это для оптимизации.
Первое выражение — делимое, второе — делитель,
который должен быть ненулевым.
Возвращаемое значение — частное, а остаток сохраняется в индекс
\f[B]0\f[R] предоставленного массива (последнего аргумента).
Это \f[B]непереносимое расширение\f[R].
\f[B]asciify(E)\f[R]: если \f[B]E\f[R] — строка, возвращает строку,
являющуюся первой буквой её аргумента.
Если это число, вычисляет число по модулю \f[B]256\f[R] и возвращает
это число как односимвольную строку.
Это \f[B]непереносимое расширение\f[R].
\f[B]asciify(I[])\f[R]: строка, составленная из символов, которые
получились бы в результате применения \f[B]asciify(E)\f[R] к каждому элементу
массива, указанного аргументом.
Это позволяет создавать многосимвольные строки и сохранять их.
Это \f[B]непереносимое расширение\f[R].
\f[B]I()\f[R], \f[B]I(E)\f[R], \f[B]I(E, E)\f[R] и так далее, где
\f[B]I\f[R] — идентификатор функции, не являющейся \f[B]void\f[R] (см.
подраздел \f[I]Функции void\f[R] раздела \f[B]ФУНКЦИИ\f[R]).
Аргумент(ы) \f[B]E\f[R] также могут быть массивами вида
\f[B]I[]\f[R], которые автоматически превращаются в ссылки на массивы
(см. подраздел \f[I]Ссылки на массивы\f[R] раздела
\f[B]ФУНКЦИИ\f[R]), если соответствующий параметр в
определении функции является ссылкой на массив.
\f[B]read()\f[R]: читает строку из \f[B]stdin\f[R] и использует её как
выражение.
Результат этого выражения — результат операнда \f[B]read()\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]maxibase()\f[R]: максимально допустимое \f[B]ibase\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]maxobase()\f[R]: максимально допустимое \f[B]obase\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]maxscale()\f[R]: максимально допустимое \f[B]scale\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]line_length()\f[R]: длина строки, установленная
\f[B]BC_LINE_LENGTH\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
Это \f[B]непереносимое расширение\f[R].
\f[B]global_stacks()\f[R]: \f[B]0\f[R], если глобальные стеки не включены
опциями \f[B]\-g\f[R] или \f[B]\-\-global\-stacks\f[R],
иначе ненулевое значение.
См. раздел \f[B]ОПЦИИ\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]leading_zero()\f[R]: \f[B]0\f[R], если ведущие нули не включены
опциями \f[B]\-z\f[R] или \f[B]\[en]leading\-zeroes\f[R],
иначе ненулевое значение.
См. раздел \f[B]ОПЦИИ\f[R].
Это \f[B]непереносимое расширение\f[R].
.SS Числа
Числа — это строки, состоящие из цифр, заглавных букв и не более
\f[B]1\f[R] точки для разделения целой и дробной части.
Числа могут содержать до \f[B]BC_NUM_MAX\f[R] цифр.
Заглавные буквы равны \f[B]9\f[R] плюс их позиция в
алфавите, начиная с \f[B]1\f[R] (т. е. \f[B]A\f[R] равно
\f[B]10\f[R], или \f[B]9+1\f[R]).
.PP
Если цифра или буква не имеет смысла при текущем значении
\f[B]ibase\f[R] (т. е. они больше или равны текущему
значению \f[B]ibase\f[R]), то поведение зависит от наличия
опций \f[B]\-c\f[R]/\f[B]\-\-digit\-clamp\f[R] или
\f[B]\-C\f[R]/\f[B]\-\-no\-digit\-clamp\f[R] (см.
раздел \f[B]ОПЦИИ\f[R]), наличия и значения
переменной окружения \f[B]BC_DIGIT_CLAMP\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ
ОКРУЖЕНИЯ\f[R]) или значения по умолчанию, которое можно узнать с помощью
опции \f[B]\-h\f[R]/\f[B]\-\-help\f[R].
.PP
Если ограничение выключено, то цифры или буквы, которые больше или
равны текущему значению \f[B]ibase\f[R], не изменяются.
Вместо этого их заданное значение умножается на соответствующую степень
\f[B]ibase\f[R] и добавляется к числу.
Это означает, что при \f[B]ibase\f[R] равном \f[B]3\f[R], число
\f[B]AB\f[R] равно \f[B]3\[ha]1*A+3\[ha]0*B\f[R], что равно
\f[B]3\f[R] умножить на \f[B]10\f[R] плюс \f[B]11\f[R], или \f[B]41\f[R].
.PP
Если ограничение включено, то цифры или буквы, которые больше или равны
текущему значению \f[B]ibase\f[R], устанавливаются в значение
наибольшей допустимой цифры в \f[B]ibase\f[R] перед умножением на
соответствующую степень \f[B]ibase\f[R] и добавлением к числу.
Это означает, что при \f[B]ibase\f[R] равном \f[B]3\f[R], число
\f[B]AB\f[R] равно \f[B]3\[ha]1*2+3\[ha]0*2\f[R], что равно
\f[B]3\f[R] умножить на \f[B]2\f[R] плюс \f[B]2\f[R], или \f[B]8\f[R].
.PP
Есть одно исключение из ограничения: односимвольные числа (т. е.
только \f[B]A\f[R]).
Такие числа никогда не ограничиваются и всегда принимают значение, которое они имели бы
при наибольшем возможном \f[B]ibase\f[R].
Это означает, что \f[B]A\f[R] отдельно всегда равно десятичному \f[B]10\f[R], а
\f[B]Z\f[R] отдельно всегда равно десятичному \f[B]35\f[R].
Такое поведение требуется стандартом (см. раздел СТАНДАРТЫ)
и предназначено для предоставления простого способа установить текущий \f[B]ibase\f[R]
(с помощью команды \f[B]i\f[R]) независимо от текущего значения
\f[B]ibase\f[R].
.PP
Если ограничение включено и нужно получить ограниченное значение символа,
используйте ведущий ноль, т. е. для \f[B]A\f[R] используйте \f[B]0A\f[R].
.SS Операторы
Можно использовать следующие арифметические и логические операторы.
Они перечислены в порядке убывания приоритета.
Операторы в одной группе имеют одинаковый приоритет.
.TP
\f[B]++\f[R] \f[B]\-\-\f[R]
Тип: префиксный и постфиксный
.RS
.PP
Ассоциативность: нет
.PP
Описание: \f[B]инкремент\f[R], \f[B]декремент\f[R]
.RE
.TP
\f[B]\-\f[R] \f[B]!\f[R]
Тип: префиксный
.RS
.PP
Ассоциативность: нет
.PP
Описание: \f[B]отрицание\f[R], \f[B]логическое не\f[R]
.RE
.TP
\f[B]\[ha]\f[R]
Тип: бинарный
.RS
.PP
Ассоциативность: правая
.PP
Описание: \f[B]возведение в степень\f[R]
.RE
.TP
\f[B]*\f[R] \f[B]/\f[R] \f[B]%\f[R]
Тип: бинарный
.RS
.PP
Ассоциативность: левая
.PP
Описание: \f[B]умножение\f[R], \f[B]деление\f[R], \f[B]остаток\f[R]
.RE
.TP
\f[B]+\f[R] \f[B]\-\f[R]
Тип: бинарный
.RS
.PP
Ассоциативность: левая
.PP
Описание: \f[B]сложение\f[R], \f[B]вычитание\f[R]
.RE
.TP
\f[B]=\f[R] \f[B]+=\f[R] \f[B]\-=\f[R] \f[B]*=\f[R] \f[B]/=\f[R] \f[B]%=\f[R] \f[B]\[ha]=\f[R]
Тип: бинарный
.RS
.PP
Ассоциативность: правая
.PP
Описание: \f[B]присваивание\f[R]
.RE
.TP
\f[B]==\f[R] \f[B]<=\f[R] \f[B]>=\f[R] \f[B]!=\f[R] \f[B]<\f[R] \f[B]>\f[R]
Тип: бинарный
.RS
.PP
Ассоциативность: левая
.PP
Описание: \f[B]отношения\f[R]
.RE
.TP
\f[B]&&\f[R]
Тип: бинарный
.RS
.PP
Ассоциативность: левая
.PP
Описание: \f[B]логическое и\f[R]
.RE
.TP
\f[B]||\f[R]
Тип: бинарный
.RS
.PP
Ассоциативность: левая
.PP
Описание: \f[B]логическое или\f[R]
.RE
.PP
Операторы подробнее описаны ниже.
.TP
\f[B]++\f[R] \f[B]\-\-\f[R]
Префиксные и постфиксные операторы \f[B]инкремента\f[R] и \f[B]декремента\f[R]
ведут себя точно так же, как в C. Они требуют именованное
выражение (см. подраздел \f[I]Именованные выражения\f[R]) в качестве
операнда.
.RS
.PP
Префиксные версии этих операторов более эффективны; используйте их
там, где возможно.
.RE
.TP
\f[B]\-\f[R]
Оператор \f[B]отрицания\f[R] возвращает \f[B]0\f[R], если пользователь пытается
применить отрицание к любому выражению со значением \f[B]0\f[R].
В противном случае возвращается копия выражения с изменённым знаком.
.TP
\f[B]!\f[R]
Оператор \f[B]логического не\f[R] возвращает \f[B]1\f[R], если выражение
равно \f[B]0\f[R], или \f[B]0\f[R] в противном случае.
.RS
.PP
\f[B]Предупреждение\f[R]: этот оператор имеет \f[B]другой приоритет\f[R],
чем эквивалентный оператор в GNU bc(1) и других реализациях bc(1)!
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\[ha]\f[R]
Оператор \f[B]возведения в степень\f[R] (не оператор \f[B]исключающего или\f[R],
как было бы в C) принимает два выражения и возводит первое в
степень значения второго.
\f[I]scale\f[R] результата равен \f[B]scale\f[R].
.RS
.PP
Второе выражение должно быть целым (без \f[I]scale\f[R]), и если оно
отрицательное, первое значение должно быть ненулевым.
.RE
.TP
\f[B]*\f[R]
Оператор \f[B]умножения\f[R] принимает два выражения, умножает их
и возвращает произведение.
Если \f[B]a\f[R] — \f[I]scale\f[R] первого выражения, а
\f[B]b\f[R] — \f[I]scale\f[R] второго выражения, то
\f[I]scale\f[R] результата равен
\f[B]min(a+b,max(scale,a,b))\f[R], где \f[B]min()\f[R] и
\f[B]max()\f[R] возвращают очевидные значения.
.TP
\f[B]/\f[R]
Оператор \f[B]деления\f[R] принимает два выражения, делит их и
возвращает частное.
\f[I]scale\f[R] результата должен быть равен значению \f[B]scale\f[R].
.RS
.PP
Второе выражение должно быть ненулевым.
.RE
.TP
\f[B]%\f[R]
Оператор \f[B]остатка\f[R] принимает два выражения, \f[B]a\f[R] и
\f[B]b\f[R], и вычисляет их так: 1) вычисляет \f[B]a/b\f[R] с текущим
\f[B]scale\f[R] и 2) использует результат шага 1, чтобы вычислить
\f[B]a\-(a/b)*b\f[R] с \f[I]scale\f[R]
\f[B]max(scale+scale(b),scale(a))\f[R].
.RS
.PP
Второе выражение должно быть ненулевым.
.RE
.TP
\f[B]+\f[R]
Оператор \f[B]сложения\f[R] принимает два выражения, \f[B]a\f[R] и
\f[B]b\f[R], и возвращает сумму с \f[I]scale\f[R], равным
максимуму \f[I]scale\f[R] выражений \f[B]a\f[R] и \f[B]b\f[R].
.TP
\f[B]\-\f[R]
Оператор \f[B]вычитания\f[R] принимает два выражения, \f[B]a\f[R] и
\f[B]b\f[R], и возвращает разность с \f[I]scale\f[R], равным
максимуму \f[I]scale\f[R] выражений \f[B]a\f[R] и \f[B]b\f[R].
.TP
\f[B]=\f[R] \f[B]+=\f[R] \f[B]\-=\f[R] \f[B]*=\f[R] \f[B]/=\f[R] \f[B]%=\f[R] \f[B]\[ha]=\f[R]
Операторы \f[B]присваивания\f[R] принимают два выражения, \f[B]a\f[R] и
\f[B]b\f[R], где \f[B]a\f[R] — именованное выражение (см. подраздел \f[I]Именованные
выражения\f[R]).
.RS
.PP
Для \f[B]=\f[R] \f[B]b\f[R] копируется, и результат присваивается
\f[B]a\f[R].
Для всех остальных \f[B]a\f[R] и \f[B]b\f[R] применяются как операнды к
соответствующему арифметическому оператору, и результат присваивается
\f[B]a\f[R].
.RE
.TP
\f[B]==\f[R] \f[B]<=\f[R] \f[B]>=\f[R] \f[B]!=\f[R] \f[B]<\f[R] \f[B]>\f[R]
Операторы \f[B]отношения\f[R] сравнивают два выражения, \f[B]a\f[R]
и \f[B]b\f[R], и если отношение выполняется согласно семантике языка
C, результат равен \f[B]1\f[R].
В противном случае он равен \f[B]0\f[R].
.RS
.PP
Обратите внимание, что в отличие от C эти операторы имеют более низкий приоритет, чем
операторы \f[B]присваивания\f[R], что означает, что \f[B]a=b>c\f[R]
интерпретируется как \f[B](a=b)>c\f[R].
.PP
Кроме того, в отличие от требования стандарта (см. раздел \f[B]СТАНДАРТЫ\f[R]),
эти операторы могут появляться везде, где могут использоваться любые другие выражения.
Это послабление является \f[B]непереносимым расширением\f[R].
.RE
.TP
\f[B]&&\f[R]
Оператор \f[B]логического и\f[R] принимает два выражения и возвращает
\f[B]1\f[R], если оба выражения ненулевые, иначе \f[B]0\f[R].
.RS
.PP
Это \f[I]не\f[R] оператор с сокращённым вычислением.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]||\f[R]
Оператор \f[B]логического или\f[R] принимает два выражения и возвращает
\f[B]1\f[R], если одно из выражений ненулевое, иначе \f[B]0\f[R].
.RS
.PP
Это \f[I]не\f[R] оператор с сокращённым вычислением.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.SS Инструкции
Следующие элементы являются инструкциями:
\f[B]E\f[R]
\f[B]{\f[R] \f[B]S\f[R] \f[B];\f[R] \&...
\f[B];\f[R] \f[B]S\f[R] \f[B]}\f[R]
\f[B]if\f[R] \f[B](\f[R] \f[B]E\f[R] \f[B])\f[R] \f[B]S\f[R]
\f[B]if\f[R] \f[B](\f[R] \f[B]E\f[R] \f[B])\f[R] \f[B]S\f[R]
\f[B]else\f[R] \f[B]S\f[R]
\f[B]while\f[R] \f[B](\f[R] \f[B]E\f[R] \f[B])\f[R] \f[B]S\f[R]
\f[B]for\f[R] \f[B](\f[R] \f[B]E\f[R] \f[B];\f[R] \f[B]E\f[R]
\f[B];\f[R] \f[B]E\f[R] \f[B])\f[R] \f[B]S\f[R]
Пустая инструкция
\f[B]break\f[R]
\f[B]continue\f[R]
\f[B]quit\f[R]
\f[B]halt\f[R]
\f[B]limits\f[R]
Строка символов, заключённая в двойные кавычки
\f[B]print\f[R] \f[B]E\f[R] \f[B],\f[R] \&...
\f[B],\f[R] \f[B]E\f[R]
\f[B]stream\f[R] \f[B]E\f[R] \f[B],\f[R] \&...
\f[B],\f[R] \f[B]E\f[R]
\f[B]I()\f[R], \f[B]I(E)\f[R], \f[B]I(E, E)\f[R] и так далее, где
\f[B]I\f[R] — идентификатор \f[B]void\f[R]-функции (см.
подраздел \f[I]Функции void\f[R] раздела \f[B]ФУНКЦИИ\f[R]).
Аргумент(ы) \f[B]E\f[R] также могут быть массивами вида
\f[B]I[]\f[R], которые автоматически превращаются в ссылки на массивы
(см. подраздел \f[I]Ссылки на массивы\f[R] раздела
\f[B]ФУНКЦИИ\f[R]), если соответствующий параметр в
определении функции является ссылкой на массив.
.PP
Номера 4, 9, 11, 12, 14, 15 и 16 являются \f[B]непереносимыми
расширениями\f[R].
.PP
Кроме того, как \f[B]непереносимое расширение\f[R], любые или все
выражения в заголовке цикла for могут быть опущены.
Если условие (второе выражение) опущено, предполагается, что это
константа \f[B]1\f[R].
.PP
Инструкция \f[B]break\f[R] заставляет цикл прекратить итерации и возобновить
выполнение сразу после цикла.
Это разрешено только в циклах.
.PP
Инструкция \f[B]continue\f[R] заставляет итерацию цикла завершиться досрочно
и возвращает к началу цикла, включая проверку условия
цикла.
Это разрешено только в циклах.
.PP
Инструкция \f[B]if\f[R] \f[B]else\f[R] делает то же самое, что и в C.
.PP
Инструкция \f[B]quit\f[R] заставляет bc(1) завершиться, даже если она находится в
ветви, которая не будет выполнена (это команда времени компиляции).
.PP
\f[B]Предупреждение\f[R]: поведение этого bc(1) при \f[B]quit\f[R]
немного отличается от других реализаций bc(1).
Другие реализации bc(1) завершаются, как только заканчивают разбор
строки, в которой находится команда \f[B]quit\f[R].
Этот bc(1) выполнит все завершённые и исполняемые инструкции, которые
находятся перед инструкцией \f[B]quit\f[R], прежде чем завершиться.
.PP
Иными словами, для приведённого ниже кода bc(1):
.IP
.EX
for (i = 0; i < 3; ++i) i; quit
.EE
.PP
Другие реализации bc(1) ничего не выведут, а этот bc(1) выведет
\f[B]0\f[R], \f[B]1\f[R] и \f[B]2\f[R] на последовательных строках
перед завершением.
.PP
Инструкция \f[B]halt\f[R] заставляет bc(1) завершиться, если она выполняется.
(В отличие от \f[B]quit\f[R], если она находится в ветви инструкции \f[B]if\f[R],
которая не выполняется, bc(1) не завершается.)
.PP
Инструкция \f[B]limits\f[R] выводит ограничения, которым
подчиняется этот bc(1).
Она похожа на инструкцию \f[B]quit\f[R] тем, что является командой времени
компиляции.
.PP
Выражение само по себе вычисляется и выводится, после чего следует символ новой строки.
.SS Строки
Если строки появляются как отдельная инструкция сами по себе, они выводятся без
завершающего символа новой строки.
.PP
Помимо того, что строки могут быть отдельной инструкцией сами по себе, их можно
присваивать переменным и элементам массива.
Их также можно передавать функциям в параметрах-переменных.
.PP
Если любой инструкции, ожидающей строку, передана переменная, которой была
присвоена строка, инструкция действует так, как будто получила
строку.
.PP
Если над строкой или переменной либо элементом массива, которым была
присвоена строка, предпринимается любая математическая операция, возникает ошибка, и bc(1)
выполняет сброс (см. раздел \f[B]СБРОС\f[R]).
.PP
Присваивание строк переменным и элементам массива и передача их
функциям — это \f[B]непереносимые расширения\f[R].
.SS Инструкция print
«Выражения» в инструкции \f[B]print\f[R] также могут быть
строками.
Если это так, есть escape-последовательности с обратной косой чертой, которые
интерпретируются особым образом.
Какие это последовательности и что они вызывают к выводу, показано
ниже:
.PP
\f[B]\[rs]a\f[R]: \f[B]\[rs]a\f[R]
.PP
\f[B]\[rs]b\f[R]: \f[B]\[rs]b\f[R]
.PP
\f[B]\[rs]\[rs]\f[R]: \f[B]\[rs]\f[R]
.PP
\f[B]\[rs]e\f[R]: \f[B]\[rs]\f[R]
.PP
\f[B]\[rs]f\f[R]: \f[B]\[rs]f\f[R]
.PP
\f[B]\[rs]n\f[R]: \f[B]\[rs]n\f[R]
.PP
\f[B]\[rs]q\f[R]: \f[B]\[lq]\f[R]
.PP
\f[B]\[rs]r\f[R]: \f[B]\[rs]r\f[R]
.PP
\f[B]\[rs]t\f[R]: \f[B]\[rs]t\f[R]
.PP
Любой другой символ после обратной косой черты приводит к тому, что обратная косая черта и
символ выводятся как есть.
.PP
Любое нестроковое выражение в инструкции print должно быть присвоено
\f[B]last\f[R], как и любое другое выводимое выражение.
.SS Инструкция stream
Выражения в инструкции \f[B]stream\f[R] также могут быть строками.
.PP
Если инструкции \f[B]stream\f[R] передана строка, она выводит строку
так, как будто строка была отдельной инструкцией.
Иными словами, инструкция \f[B]stream\f[R] выводит строки обычно,
без символа новой строки.
.PP
Если инструкции \f[B]stream\f[R] передано число, его копия
усекается и вычисляется её абсолютное значение.
Затем результат выводится так, как будто \f[B]obase\f[R] равно \f[B]256\f[R],
и каждая цифра интерпретируется как 8-битный символ ASCII, что делает его
потоком байтов.
.SS Порядок вычисления
Все выражения в инструкции вычисляются слева направо, за исключением
необходимости соблюдения порядка операций.
Это означает, например, что при условии, что \f[B]i\f[R] равно
\f[B]0\f[R], в выражении
.IP
.EX
a[i++] = i++
.EE
.PP
первый (или 0-й) элемент \f[B]a\f[R] устанавливается в \f[B]1\f[R], а
\f[B]i\f[R] равно \f[B]2\f[R] в конце выражения.
.PP
Это включает аргументы функций.
Таким образом, если предположить, что \f[B]i\f[R] равно \f[B]0\f[R], это означает, что в
выражении
.IP
.EX
x(i++, i++)
.EE
.PP
первый аргумент, переданный в \f[B]x()\f[R], равен \f[B]0\f[R], а
второй аргумент равен \f[B]1\f[R], при этом \f[B]i\f[R] равно
\f[B]2\f[R] до начала выполнения функции.
.SH ФУНКЦИИ
Определения функций выглядят так:
.IP
.EX
define I(I,...,I){
    auto I,...,I
    S;...;S
    return(E)
}
.EE
.PP
Любой \f[B]I\f[R] в списке параметров или списке \f[B]auto\f[R] может быть
заменён на \f[B]I[]\f[R], чтобы сделать параметр или переменную \f[B]auto\f[R]
массивом, а любой \f[B]I\f[R] в списке параметров может быть заменён на
\f[B]*I[]\f[R], чтобы сделать параметр ссылкой на массив.
Вызывающие функции, принимающие ссылки на массивы, не должны ставить
звёздочку в вызове; их нужно вызывать просто с \f[B]I[]\f[R], как
обычные параметры-массивы, и они будут автоматически преобразованы в
ссылки.
.PP
Как \f[B]непереносимое расширение\f[R], открывающая скобка
инструкции \f[B]define\f[R] может находиться на следующей строке.
.PP
Как \f[B]непереносимое расширение\f[R], инструкция return также может
быть в одной из следующих форм:
\f[B]return\f[R]
\f[B]return\f[R] \f[B](\f[R] \f[B])\f[R]
\f[B]return\f[R] \f[B]E\f[R]
.PP
Первые две формы или отсутствие указания инструкции \f[B]return\f[R]
эквивалентны \f[B]return (0)\f[R], если только функция не является
\f[B]void\f[R]-функцией (см. подраздел \f[I]Функции void\f[R]
ниже).
.SS Функции void
Функции также могут быть \f[B]void\f[R]-функциями, определяемыми так:
.IP
.EX
define void I(I,...,I){
    auto I,...,I
    S;...;S
    return
}
.EE
.PP
Они могут использоваться только как самостоятельные выражения, где такое
выражение было бы выведено отдельно, кроме случая инструкции print.
.PP
Void-функции могут использовать только первые две инструкции \f[B]return\f[R],
перечисленные выше.
Они также могут полностью опускать инструкцию return.
.PP
Слово «void» не рассматривается как ключевое; по-прежнему
можно иметь переменные, массивы и функции с именем \f[B]void\f[R].
Слово «void» обрабатывается особым образом только сразу после
ключевого слова \f[B]define\f[R].
.PP
Это \f[B]непереносимое расширение\f[R].
.SS Ссылки на массивы
Для любого массива в списке параметров, если массив объявлен в
форме
.IP
.EX
*I[]
.EE
.PP
он является \f[B]ссылкой\f[R].
Любые изменения массива в функции отражаются, когда
функция возвращает управление, в массиве, который был передан.
.PP
Кроме этого, все аргументы функций передаются по значению.
.PP
Это \f[B]непереносимое расширение\f[R].
.SH БИБЛИОТЕКА
Все приведённые ниже функции доступны, когда заданы флаги командной строки
\f[B]\-l\f[R] или \f[B]\-\-mathlib\f[R].
.SS Стандартная библиотека
Стандарт (см. раздел \f[B]СТАНДАРТЫ\f[R]) определяет следующие
функции для математической библиотеки:
.TP
\f[B]s(x)\f[R]
Возвращает синус \f[B]x\f[R], который предполагается заданным в радианах.
.RS
.PP
Это трансцендентная функция (см. подраздел \f[I]Трансцендентные
функции\f[R] ниже).
.RE
.TP
\f[B]c(x)\f[R]
Возвращает косинус \f[B]x\f[R], который предполагается заданным в радианах.
.RS
.PP
Это трансцендентная функция (см. подраздел \f[I]Трансцендентные
функции\f[R] ниже).
.RE
.TP
\f[B]a(x)\f[R]
Возвращает арктангенс \f[B]x\f[R], в радианах.
.RS
.PP
Это трансцендентная функция (см. подраздел \f[I]Трансцендентные
функции\f[R] ниже).
.RE
.TP
\f[B]l(x)\f[R]
Возвращает натуральный логарифм \f[B]x\f[R].
.RS
.PP
Это трансцендентная функция (см. подраздел \f[I]Трансцендентные
функции\f[R] ниже).
.RE
.TP
\f[B]e(x)\f[R]
Возвращает математическую константу \f[B]e\f[R], возведённую в степень
\f[B]x\f[R].
.RS
.PP
Это трансцендентная функция (см. подраздел \f[I]Трансцендентные
функции\f[R] ниже).
.RE
.TP
\f[B]j(x, n)\f[R]
Возвращает функцию Бесселя целого порядка \f[B]n\f[R] (усечённого) от \f[B]x\f[R].
.RS
.PP
Это трансцендентная функция (см. подраздел \f[I]Трансцендентные
функции\f[R] ниже).
.RE
.SS Трансцендентные функции
Все трансцендентные функции могут возвращать немного неточные результаты, вплоть
до 1 ULP (https://en.wikipedia.org/wiki/Unit_in_the_last_place).
Это неизбежно, и статья по адресу
https://people.eecs.berkeley.edu/\[ti]wkahan/LOG10HAF.TXT объясняет, почему
невозможно и не нужно вычислять точные результаты для
трансцендентных функций.
.PP
Из-за возможной неточности я рекомендую пользователям вызывать эти
функции с точностью (\f[B]scale\f[R]), установленной как минимум на 1 выше,
чем необходимо.
Если точные результаты \f[I]абсолютно\f[R] необходимы, пользователи могут удвоить
точность (\f[B]scale\f[R]) и затем усечь.
.PP
Трансцендентные функции в стандартной математической библиотеке:
.IP \[bu] 2
\f[B]s(x)\f[R]
.IP \[bu] 2
\f[B]c(x)\f[R]
.IP \[bu] 2
\f[B]a(x)\f[R]
.IP \[bu] 2
\f[B]l(x)\f[R]
.IP \[bu] 2
\f[B]e(x)\f[R]
.IP \[bu] 2
\f[B]j(x, n)\f[R]
.SH СБРОС
Когда bc(1) встречает ошибку или сигнал, для которого у него есть
обработчик, отличный от стандартного, он выполняет сброс.
Это означает, что происходит несколько вещей.
.PP
Во-первых, все выполняющиеся функции останавливаются и снимаются со
стека.
Поведение не отличается от исключений в языках программирования.
Затем точка выполнения устанавливается так, чтобы любой код, ожидающий выполнения
(после возврата всех функций), был пропущен.
.PP
Таким образом, когда bc(1) выполняет сброс, он пропускает любой оставшийся код,
ожидающий выполнения.
Затем, если это интерактивный режим и ошибка не была фатальной
(см. раздел \f[B]СТАТУС ВЫХОДА\f[R]), он запрашивает дополнительный ввод;
в противном случае он завершается с соответствующим кодом возврата.
.PP
Обратите внимание, что это поведение сброса отличается от GNU bc(1), который
пытается начать выполнение инструкции сразу после той, которая
вызвала ошибку.
.SH ПРОИЗВОДИТЕЛЬНОСТЬ
В большинстве реализаций bc(1) используются типы \f[B]char\f[R] для вычисления
значения \f[B]1\f[R] десятичной цифры за раз, но это может быть медленно.
Этот bc(1) делает иначе.
.PP
Он использует большие целые числа для вычисления более чем \f[B]1\f[R] десятичной цифры
за раз.
Если он собран в среде, где \f[B]BC_LONG_BIT\f[R] (см.
раздел \f[B]ОГРАНИЧЕНИЯ\f[R]) равно \f[B]64\f[R], то каждое целое число содержит
\f[B]9\f[R] десятичных цифр.
Если он собран в среде, где \f[B]BC_LONG_BIT\f[R] равно \f[B]32\f[R],
то каждое целое число содержит \f[B]4\f[R] десятичных цифр.
Это значение (количество десятичных цифр на большое целое число) называется
\f[B]BC_BASE_DIGS\f[R].
.PP
Фактические значения \f[B]BC_LONG_BIT\f[R] и \f[B]BC_BASE_DIGS\f[R]
можно узнать с помощью инструкции \f[B]limits\f[R].
.PP
Кроме того, этот bc(1) использует ещё большее целое число для проверки
переполнения.
Этот целочисленный тип зависит от значения \f[B]BC_LONG_BIT\f[R], но
всегда как минимум вдвое больше целочисленного типа, используемого для хранения цифр.
.SH ОГРАНИЧЕНИЯ
Ниже приведены ограничения bc(1):
.TP
\f[B]BC_LONG_BIT\f[R]
Количество битов в типе \f[B]long\f[R] в среде, где
был собран bc(1).
Это определяет, сколько десятичных цифр может храниться в одном большом
целом числе (см. раздел \f[B]ПРОИЗВОДИТЕЛЬНОСТЬ\f[R]).
.TP
\f[B]BC_BASE_DIGS\f[R]
Количество десятичных цифр на большое целое число (см.
раздел \f[B]ПРОИЗВОДИТЕЛЬНОСТЬ\f[R]).
Зависит от \f[B]BC_LONG_BIT\f[R].
.TP
\f[B]BC_BASE_POW\f[R]
Максимальное десятичное число, которое может хранить каждое большое целое число (см.
\f[B]BC_BASE_DIGS\f[R]), плюс \f[B]1\f[R].
Зависит от \f[B]BC_BASE_DIGS\f[R].
.TP
\f[B]BC_OVERFLOW_MAX\f[R]
Максимальное число, которое может хранить тип переполнения (см. раздел
\f[B]ПРОИЗВОДИТЕЛЬНОСТЬ\f[R]).
Зависит от \f[B]BC_LONG_BIT\f[R].
.TP
\f[B]BC_BASE_MAX\f[R]
Максимальное основание вывода.
Установлено в \f[B]BC_BASE_POW\f[R].
.TP
\f[B]BC_DIM_MAX\f[R]
Максимальный размер массивов.
Установлен в \f[B]SIZE_MAX\-1\f[R].
.TP
\f[B]BC_SCALE_MAX\f[R]
Максимальное \f[B]scale\f[R].
Установлено в \f[B]BC_OVERFLOW_MAX\-1\f[R].
.TP
\f[B]BC_STRING_MAX\f[R]
Максимальная длина строк.
Установлена в \f[B]BC_OVERFLOW_MAX\-1\f[R].
.TP
\f[B]BC_NAME_MAX\f[R]
Максимальная длина идентификаторов.
Установлена в \f[B]BC_OVERFLOW_MAX\-1\f[R].
.TP
\f[B]BC_NUM_MAX\f[R]
Максимальная длина числа (в десятичных цифрах), которая включает
цифры после десятичной точки.
Установлена в \f[B]BC_OVERFLOW_MAX\-1\f[R].
.TP
Экспонента
Максимально допустимая экспонента (положительная или отрицательная).
Установлена в \f[B]BC_OVERFLOW_MAX\f[R].
.TP
Количество переменных
Максимальное количество переменных/массивов.
Установлено в \f[B]SIZE_MAX\-1\f[R].
.PP
Фактические значения можно узнать с помощью инструкции \f[B]limits\f[R].
.PP
Эти ограничения задуманы как фактически несуществующие; они
настолько велики (по крайней мере на 64-битных машинах), что не должно быть
момента, когда они станут проблемой.
Фактически, память должна исчерпаться раньше, чем эти ограничения будут достигнуты.
.SH ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
Как \f[B]непереносимые расширения\f[R], bc(1) распознаёт следующие
переменные окружения:
.TP
\f[B]POSIXLY_CORRECT\f[R]
Если эта переменная существует (независимо от содержимого), bc(1) ведёт себя так, как будто
была задана опция \f[B]\-s\f[R].
.TP
\f[B]BC_ENV_ARGS\f[R]
Это ещё один способ передать аргументы командной строки в bc(1).
Они должны быть в том же формате, что и все другие аргументы командной строки.
Они всегда обрабатываются первыми, поэтому любые файлы, заданные в
\f[B]BC_ENV_ARGS\f[R], будут обработаны до аргументов и файлов, заданных
в командной строке.
Это даёт пользователю возможность настроить «стандартные» опции и
файлы, используемые при каждом вызове.
Самое полезное, что могут содержать такие файлы, — это полезные
функции, которые пользователь может хотеть использовать при каждом запуске bc(1).
.RS
.PP
Код, разбирающий \f[B]BC_ENV_ARGS\f[R], корректно обрабатывает аргументы в кавычках,
но не понимает escape-последовательности.
Например, строка \f[B]\[lq]/home/gavin/some bc file.bc\[rq]\f[R]
будет разобрана корректно, а строка \f[B]\[lq]/home/gavin/some
\[dq]bc\[dq] file.bc\[rq]\f[R] включит обратные косые черты.
.PP
Разбор кавычек будет обрабатывать любой вид кавычек, \f[B]\[cq]\f[R] или
\f[B]\[lq]\f[R].
Таким образом, если у вас есть файл с любым количеством одинарных кавычек в имени,
вы можете использовать двойные кавычки как внешние кавычки, как в \f[B]\[lq]some
`bc' file.bc\[rq]\f[R], и наоборот, если у вас есть файл с двойными
кавычками.
Однако обработка файла с обоими видами кавычек в
\f[B]BC_ENV_ARGS\f[R] не поддерживается из-за сложности
разбора, хотя такие файлы по-прежнему поддерживаются в командной строке,
где разбор выполняется оболочкой.
.RE
.TP
\f[B]BC_LINE_LENGTH\f[R]
Если эта переменная окружения существует и содержит целое число,
большее \f[B]1\f[R] и меньшее \f[B]UINT16_MAX\f[R]
(\f[B]2\[ha]16\-1\f[R]), bc(1) будет выводить строки такой длины,
включая обратную косую черту (\f[B]\[rs]\f[R]).
Длина строки по умолчанию — \f[B]70\f[R].
.RS
.PP
Особое значение \f[B]0\f[R] отключает проверку длины строк и
выводит числа без учёта длины строк и без обратных косых черт и
символов новой строки.
.RE
.TP
\f[B]BC_BANNER\f[R]
Если эта переменная окружения существует и содержит целое число, то
ненулевое значение включает баннер авторских прав, когда bc(1) находится в
интерактивном режиме, а ноль отключает его.
.RS
.PP
Если bc(1) не находится в интерактивном режиме (см. раздел \f[B]ИНТЕРАКТИВНЫЙ РЕЖИМ\f[R]),
то эта переменная окружения не действует, потому что bc(1)
не выводит баннер, когда не находится в интерактивном режиме.
.PP
Эта переменная окружения переопределяет значение по умолчанию, которое можно узнать
с помощью опций \f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.RE
.TP
\f[B]BC_SIGINT_RESET\f[R]
Если bc(1) не находится в интерактивном режиме (см. раздел \f[B]ИНТЕРАКТИВНЫЙ РЕЖИМ\f[R]),
то эта переменная окружения не действует, потому что bc(1)
завершается по \f[B]SIGINT\f[R], когда не находится в интерактивном режиме.
.RS
.PP
Однако когда bc(1) находится в интерактивном режиме, если эта переменная
окружения существует и содержит целое число, ненулевое значение заставляет bc(1)
выполнить сброс по \f[B]SIGINT\f[R], а не завершиться, а ноль заставляет bc(1) завершиться.
Если эта переменная окружения существует и \f[I]не\f[R] является целым числом,
то bc(1) завершится по \f[B]SIGINT\f[R].
.PP
Эта переменная окружения переопределяет значение по умолчанию, которое можно узнать
с помощью опций \f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.RE
.TP
\f[B]BC_TTY_MODE\f[R]
Если режим TTY \f[I]не\f[R] доступен (см. раздел \f[B]РЕЖИМ TTY\f[R]),
то эта переменная окружения не действует.
.RS
.PP
Однако когда режим TTY доступен, если эта переменная окружения
существует и содержит целое число, то ненулевое значение заставляет bc(1) использовать
режим TTY, а ноль заставляет bc(1) не использовать режим TTY.
.PP
Эта переменная окружения переопределяет значение по умолчанию, которое можно узнать
с помощью опций \f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.RE
.TP
\f[B]BC_PROMPT\f[R]
Если режим TTY \f[I]не\f[R] доступен (см. раздел \f[B]РЕЖИМ TTY\f[R]),
то эта переменная окружения не действует.
.RS
.PP
Однако когда режим TTY доступен, если эта переменная окружения
существует и содержит целое число, ненулевое значение заставляет bc(1) использовать
приглашение, а ноль или нецелое значение заставляет bc(1) не использовать приглашение.
Если эта переменная окружения не существует, а \f[B]BC_TTY_MODE\f[R]
существует, то используется значение переменной окружения \f[B]BC_TTY_MODE\f[R].
.PP
Эта переменная окружения и переменная окружения \f[B]BC_TTY_MODE\f[R]
переопределяют значение по умолчанию, которое можно узнать с помощью
опций \f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.RE
.TP
\f[B]BC_EXPR_EXIT\f[R]
Если любые выражения или файлы выражений заданы в командной строке
с помощью \f[B]\-e\f[R], \f[B]\-\-expression\f[R], \f[B]\-f\f[R] или
\f[B]\-\-file\f[R], то если эта переменная окружения существует и
содержит целое число, ненулевое значение заставляет bc(1) завершиться после выполнения
выражений и файлов выражений, а нулевое значение заставляет bc(1) не
завершаться.
.RS
.PP
Эта переменная окружения переопределяет значение по умолчанию, которое можно узнать
с помощью опций \f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.RE
.TP
\f[B]BC_DIGIT_CLAMP\f[R]
При разборе чисел, если эта переменная окружения существует и
содержит целое число, ненулевое значение заставляет bc(1) ограничивать цифры,
которые больше или равны текущему \f[B]ibase\f[R], так что все такие
цифры считаются равными \f[B]ibase\f[R] минус 1, а нулевое
значение отключает такое ограничение, так что эти цифры всегда равны
своему значению, которое умножается на степень \f[B]ibase\f[R].
.RS
.PP
Это никогда не применяется к однозначным числам, согласно стандарту (см.
раздел \f[B]СТАНДАРТЫ\f[R]).
.PP
Эта переменная окружения переопределяет значение по умолчанию, которое можно узнать
с помощью опций \f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.RE
.SH СТАТУС ВЫХОДА
bc(1) возвращает следующие статусы выхода:
.TP
\f[B]0\f[R]
Нет ошибки.
.TP
\f[B]1\f[R]
Произошла математическая ошибка.
Это следует стандартной практике использования \f[B]1\f[R] для ожидаемых ошибок,
поскольку математические ошибки случаются в процессе нормального выполнения.
.RS
.PP
Математические ошибки включают деление на \f[B]0\f[R], извлечение квадратного корня из
отрицательного числа, попытку преобразовать отрицательное число в аппаратное
целое, переполнение при преобразовании числа в аппаратное целое,
переполнение при вычислении размера числа и попытку использовать
нецелое там, где требуется целое.
.PP
Преобразование в аппаратное целое происходит для второго операнда
оператора возведения в степень (\f[B]\[ha]\f[R]) и соответствующего оператора
присваивания.
.RE
.TP
\f[B]2\f[R]
Произошла ошибка разбора.
.RS
.PP
Ошибки разбора включают неожиданный \f[B]EOF\f[R], использование недопустимого
символа, невозможность найти конец строки или комментария, использование токена
там, где он недопустим, задание недопустимого выражения, задание недопустимой
инструкции print, задание недопустимого определения функции, попытку
присвоить выражению, которое не является именованным выражением (см.
подраздел \f[I]Именованные выражения\f[R] раздела \f[B]СИНТАКСИС\f[R]),
задание недопустимого списка \f[B]auto\f[R], наличие дублирующегося
\f[B]auto\f[R]/параметра функции, невозможность найти конец блока
кода, попытку вернуть значение из \f[B]void\f[R]-функции,
попытку использовать переменную как ссылку и использование любых расширений,
когда была задана опция \f[B]\-s\f[R] или любые её эквиваленты.
.RE
.TP
\f[B]3\f[R]
Произошла ошибка времени выполнения.
.RS
.PP
Ошибки времени выполнения включают присваивание недопустимого числа любой глобальной
переменной (\f[B]ibase\f[R], \f[B]obase\f[R] или \f[B]scale\f[R]), передачу плохого
выражения в вызов \f[B]read()\f[R], вызов \f[B]read()\f[R] внутри
вызова \f[B]read()\f[R], ошибки типов, передачу неправильного числа
аргументов функциям, попытку вызвать неопределённую функцию и
попытку использовать вызов \f[B]void\f[R]-функции как значение в
выражении.
.RE
.TP
\f[B]4\f[R]
Произошла фатальная ошибка.
.RS
.PP
Фатальные ошибки включают ошибки выделения памяти, ошибки ввода/вывода, невозможность
открыть файлы, попытку использовать файлы, содержащие не только символы ASCII
(bc(1) принимает только символы ASCII), попытку открыть
каталог как файл и задание недопустимых опций командной строки.
.RE
.PP
Статус выхода \f[B]4\f[R] особый; при возникновении фатальной ошибки bc(1)
всегда завершается и возвращает \f[B]4\f[R], независимо от того, в каком режиме находится bc(1).
.PP
Другие статусы возвращаются только когда bc(1) не находится в
интерактивном режиме (см. раздел \f[B]ИНТЕРАКТИВНЫЙ РЕЖИМ\f[R]), поскольку
bc(1) сбрасывает своё состояние (см. раздел \f[B]СБРОС\f[R]) и принимает
дополнительный ввод, когда одна из этих ошибок происходит в интерактивном режиме.
Это также верно, когда интерактивный режим принудительно включён
флагом \f[B]\-i\f[R] или опцией \f[B]\-\-interactive\f[R].
.PP
Эти статусы выхода позволяют использовать bc(1) в сценариях оболочки с
проверкой ошибок, а его нормальное поведение можно принудительно включить, используя
флаг \f[B]\-i\f[R] или опцию \f[B]\-\-interactive\f[R].
.SH ИНТЕРАКТИВНЫЙ РЕЖИМ
Согласно стандарту (см. раздел \f[B]СТАНДАРТЫ\f[R]), bc(1) имеет
интерактивный режим и неинтерактивный режим.
Интерактивный режим автоматически включается, когда и \f[B]stdin\f[R],
и \f[B]stdout\f[R] подключены к терминалу, но флаг \f[B]\-i\f[R]
и опция \f[B]\-\-interactive\f[R] могут включить его в других
ситуациях.
.PP
В интерактивном режиме bc(1) пытается восстановиться после ошибок (см.
раздел \f[B]СБРОС\f[R]) и при нормальном выполнении сбрасывает
\f[B]stdout\f[R] сразу после завершения выполнения текущего ввода.
bc(1) также может выполнить сброс по \f[B]SIGINT\f[R] вместо завершения, в зависимости от
содержимого или значения по умолчанию переменной окружения \f[B]BC_SIGINT_RESET\f[R]
(см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
.SH РЕЖИМ TTY
Если \f[B]stdin\f[R], \f[B]stdout\f[R] и \f[B]stderr\f[R] все
подключены к TTY, то считается, что «режим TTY» доступен,
и, следовательно, bc(1) может включить режим TTY при некоторых
настройках.
.PP
Если в окружении есть переменная \f[B]BC_TTY_MODE\f[R]
(см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]), то если
эта переменная окружения содержит ненулевое целое число, bc(1) включит
режим TTY, когда \f[B]stdin\f[R], \f[B]stdout\f[R] и \f[B]stderr\f[R]
все подключены к TTY.
Если переменная окружения \f[B]BC_TTY_MODE\f[R] существует, но
\f[I]не\f[R] является ненулевым целым числом, то bc(1) не включит режим TTY.
.PP
Если переменная окружения \f[B]BC_TTY_MODE\f[R] \f[I]не\f[R]
существует, используется настройка по умолчанию.
Настройку по умолчанию можно узнать с помощью опций \f[B]\-h\f[R] или
\f[B]\-\-help\f[R].
.PP
Режим TTY отличается от интерактивного режима, потому что интерактивный режим
требуется стандартом bc(1) (см. раздел \f[B]СТАНДАРТЫ\f[R]),
а интерактивный режим требует только \f[B]stdin\f[R] и \f[B]stdout\f[R]
быть подключёнными к терминалу.
.SS Приглашение
Если режим TTY доступен, можно включить приглашение.
Как и сам режим TTY, его можно включить или выключить с помощью переменной
окружения: \f[B]BC_PROMPT\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
.PP
Если переменная окружения \f[B]BC_PROMPT\f[R] существует и является
ненулевым целым числом, то приглашение включается, когда \f[B]stdin\f[R],
\f[B]stdout\f[R] и \f[B]stderr\f[R] подключены к TTY и
опции \f[B]\-P\f[R] и \f[B]\-\-no\-prompt\f[R] не использовались.
Приглашение чтения будет включено при тех же условиях, за исключением того, что
опции \f[B]\-R\f[R] и \f[B]\-\-no\-read\-prompt\f[R] также не должны
использоваться.
.PP
Однако если \f[B]BC_PROMPT\f[R] не существует, приглашение можно
включить или выключить с помощью переменной окружения \f[B]BC_TTY_MODE\f[R],
опций \f[B]\-P\f[R] и \f[B]\-\-no\-prompt\f[R], а также
опций \f[B]\-R\f[R] и \f[B]\-\-no\-read\-prompt\f[R].
См. разделы \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R] и \f[B]ОПЦИИ\f[R]
для получения дополнительных сведений.
.SH ОБРАБОТКА СИГНАЛОВ
Отправка \f[B]SIGINT\f[R] заставит bc(1) сделать одно из двух.
.PP
Если bc(1) не находится в интерактивном режиме (см. раздел \f[B]ИНТЕРАКТИВНЫЙ РЕЖИМ\f[R]),
или переменная окружения \f[B]BC_SIGINT_RESET\f[R] (см.
раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]), или её значение по умолчанию
не является целым числом либо равно нулю, bc(1) завершится.
.PP
Однако если bc(1) находится в интерактивном режиме и
\f[B]BC_SIGINT_RESET\f[R] или её значение по умолчанию является целым и ненулевым,
то bc(1) остановит выполнение текущего ввода и выполнит сброс (см.
раздел \f[B]СБРОС\f[R]) при получении \f[B]SIGINT\f[R].
.PP
Обратите внимание, что «текущий ввод» может означать одно из двух.
Если bc(1) обрабатывает ввод из \f[B]stdin\f[R] в интерактивном режиме,
он запросит дополнительный ввод.
Если bc(1) обрабатывает ввод из файла в интерактивном режиме, он
остановит обработку файла и начнёт обработку следующего файла, если он
существует, или запросит ввод из \f[B]stdin\f[R], если другого файла нет.
.PP
Это означает, что если \f[B]SIGINT\f[R] отправлен bc(1), когда он
выполняет файл, может показаться, что bc(1) не ответил на
сигнал, поскольку он немедленно начнёт выполнять следующий файл.
Это сделано намеренно; большинство файлов, которые пользователи выполняют при взаимодействии с
bc(1), содержат определения функций, которые быстро разбираются.
Если выполнение файла занимает много времени, возможно, в этом файле есть ошибка.
Остальные файлы всё ещё могут быть выполнены без проблем, что позволяет
пользователю продолжить.
.PP
\f[B]SIGTERM\f[R] и \f[B]SIGQUIT\f[R] заставляют bc(1) выполнить очистку и
завершиться, а для всех остальных сигналов он использует стандартный обработчик.
.SH СМ. ТАКЖЕ
dc(1)
.SH СТАНДАРТЫ
bc(1) соответствует спецификации IEEE Std 1003.1\-2017
(«POSIX.1\-2017») по адресу
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/bc.html .
Флаги \f[B]\-efghiqsvVw\f[R], все длинные опции и расширения,
отмеченные выше, являются расширениями к этой спецификации.
.PP
Кроме того, поведение \f[B]quit\f[R] реализует
интерпретацию этой спецификации, отличную от всех известных
реализаций.
Для получения дополнительной информации см. подраздел \f[B]Инструкции\f[R]
раздела \f[B]СИНТАКСИС\f[R].
.PP
Обратите внимание, что спецификация явно указывает, что bc(1) принимает только
числа, использующие точку (\f[B].\f[R]) в качестве десятичного разделителя, независимо от
значения \f[B]LC_NUMERIC\f[R].
.SH ИЗВЕСТНЫЕ ОШИБКИ
До версии \f[B]6.1.0\f[R] этот bc(1) имел неправильное поведение для
инструкции \f[B]quit\f[R].
.PP
Другие ошибки неизвестны.
Сообщайте об ошибках по адресу https://github.com/gavinhoward/bc .
.SH АВТОРЫ
Gavin D. Howard \c
.MT gavin@gavinhoward.com
.ME \c
\ и участники.
