.\" FRDP path usr.bin/enigma/enigma.1
.\" FRDP githash fa9896e082a1046ff4fbc75fcba4d18d1f2efc19
.\" FRDP hash256 8ffdd458e9aaaadb2d2ea0a9cc632f57e2f4a38251987da6173b3f926ff6703f
.Dd May 8, 2018
.Dt ENIGMA 1
.Os
.Sh ИМЯ
.Nm enigma ,
.Nm crypt
.Nd очень простое шифрование файлов
.Sh СИНТАКСИС
.Nm
.Op Fl s
.Op Fl k
.Op Ar password
.Nm crypt
.Op Fl s
.Op Fl k
.Op Ar password
.Sh ОПИСАНИЕ
Утилита
.Nm
, также известная как
.Nm crypt
— это
.Em очень
простая программа шифрования, работающая на основе
.Dq секретного ключа .
Она работает как фильтр, то есть
шифрует или расшифровывает
поток данных из стандартного ввода и записывает результат в стандартный
вывод.
Поскольку её работа полностью симметрична, повторная подача зашифрованного потока
данных через механизм (с использованием того же секретного ключа)
расшифрует его.
.Pp
Есть несколько способов предоставить программе секретный ключ.
По умолчанию программа запрашивает у пользователя ключ на управляющем терминале,
используя
.Xr getpass 3 .
Это единственный безопасный способ его предоставления.
.Pp
В качестве альтернативы ключ можно передать как единственный аргумент командной строки
.Ar password
при запуске программы.
Очевидно, что таким образом ключ легко
заметят другие пользователи, запустившие
.Xr ps 1 .
Ещё одна альтернатива:
.Nm
можно передать параметр
.Fl k ,
и она возьмёт ключ из переменной окружения
.Ev CrYpTkEy .
Хотя на первый взгляд это кажется более безопасным, чем предыдущий
вариант, на самом деле это не так, поскольку переменные окружения также можно
просмотреть с помощью
.Xr ps 1 .
Таким образом, этот параметр в основном предоставлен для совместимости с другими
реализациями
.Nm .
.Pp
При указании параметра
.Fl s
.Nm
модифицирует механизм шифрования так, что это, как предполагается, делает его
немного более безопасным, но несовместимым с другими реализациями.
.Pp
.Ss Предупреждение
Криптографическая ценность
.Nm
довольно мала.
Эта программа предоставлена здесь только для совместимости
с другими операционными системами, которые также предоставляют реализацию
(обычно называемую там
.Xr crypt 1 ) .
Для настоящего шифрования обратитесь к
.Xr openssl 1 ,
или
.Xr gpg 1 Pq Pa ports/security/gnupg1 .
.Sh ОКРУЖЕНИЕ
.It Ev CrYpTkEy
используется для получения секретного ключа, когда был указан параметр
.Fl k
.El
.Sh ПРИМЕРЫ
.Bd -literal -offset indent
man enigma | enigma > encrypted
Enter key: (XXX \(em key not echoed)
.Ed
.Pp
Это создаст зашифрованную форму этой страницы руководства и сохранит её в
файле
.Pa encrypted .
.Bd -literal -offset indent
enigma XXX < encrypted
.Ed
.Pp
Это отобразит ранее созданный файл на терминале.
.Sh СМ. ТАКЖЕ
.Xr gpg 1 Pq Pa ports/security/gnupg1 ,
.Xr openssl 1 ,
.Xr ps 1 ,
.Xr getpass 3
.Sh ИСТОРИЯ
Реализации
.Nm crypt
очень распространены среди
.Ux
операционных систем.
Эта реализация была взята из
.Em Cryptbreakers Workbench ,
которая находится в общественном достоянии.
