.\" FRDP path contrib/libfido2/man/fido2-assert.1
.\" FRDP githash febb0da5bf4bc99828ebede7abcb039514ac367a
.\" FRDP hash256 862471d5f0c92ae11adc09493fee3bff1230b606988df0c92cabbe512c8f242c
.Dd $Mdocdate: July 3 2023 $
.Dt FIDO2-ASSERT 1
.Os
.Sh ИМЯ
.Nm fido2-assert
.Nd получить/проверить утверждение FIDO2
.Sh СИНТАКСИС
.Nm
.Fl G
.Op Fl bdhpruvw
.Op Fl t Ar параметр
.Op Fl i Ar входной_файл
.Op Fl o Ar выходной_файл
.Ar устройство
.Nm
.Fl V
.Op Fl dhpv
.Op Fl i Ar входной_файл
.Ar файл_ключа
.Op Ar тип
.Sh ОПИСАНИЕ
.Nm
получает или проверяет утверждение FIDO2.
.Pp
Вход
.Nm
определяется параметрами утверждения, которое нужно получить/проверить.
См. раздел
.Sx ФОРМАТ ВВОДА
для подробностей.
.Pp
Выход
.Nm
определяется результатом выбранной операции.
См. раздел
.Sx ФОРМАТ ВЫВОДА
для подробностей.
.Pp
Если утверждение успешно получено или проверено,
.Nm
завершается с кодом 0.
В противном случае
.Nm
завершается с кодом 1.
.Pp
Опции следующие:
.Bl -tag -width Ds
.It Fl G
Сообщает
.Nm ,
что нужно получить новое утверждение от
.Ar устройство .
.It Fl V
Сообщает
.Nm ,
что нужно проверить утверждение, используя открытый ключ в кодировке PEM из
.Ar файл_ключа
типа
.Ar тип ,
где
.Ar тип
может быть
.Em es256
(обозначает ECDSA над NIST P-256 с SHA-256),
.Em es384
(обозначает ECDSA над NIST P-384 с SHA-384),
.Em rs256
(обозначает 2048-битный RSA с дополнением PKCS#1.5 и SHA-256), или
.Em eddsa
(обозначает EDDSA над Curve25519 с SHA-512).
Если
.Ar тип
не указан,
предполагается
.Em es256 .
.It Fl b
Запрашивает
.Dq largeBlobKey
учетных данных —
32-байтовый симметричный ключ, связанный с учетными данными, для которых запрашивается утверждение.
.It Fl h
Если утверждение получается, включить расширение FIDO2 hmac-secret.
Если утверждение проверяется, проверить, был ли бит данных расширения подписан аутентификатором.
.It Fl d
Заставляет
.Nm
выводить отладочную информацию в
.Em stderr .
.It Fl i Ar входной_файл
Сообщает
.Nm ,
что нужно читать параметры утверждения из
.Ar входной_файл
вместо
.Em stdin .
.It Fl o Ar выходной_файл
Сообщает
.Nm ,
что нужно записывать вывод в
.Ar выходной_файл
вместо
.Em stdout .
.It Fl p
Если утверждение получается, запросить присутствие пользователя.
Если утверждение проверяется, проверить, был ли бит присутствия пользователя подписан аутентификатором.
.It Fl r
Получить утверждение с использованием резидентных учетных данных.
Если
.Fl r
указан,
.Nm
не будет ожидать идентификатор учетных данных во входных данных и может вывести
несколько утверждений.
Резидентные учетные данные называются
.Dq обнаруживаемые учетные данные
в CTAP 2.1.
.It Fl t Ar параметр
Переключает
.Ar параметр
вида ключ/значение,
где
.Ar параметр
— строка вида
.Dq key=value .
Поддерживаются следующие параметры:
.Bl -tag -width Ds
.It Cm up Ns = Ns Ar true|false
Запрашивает у аутентификатора включение или отключение присутствия пользователя.
.It Cm uv Ns = Ns Ar true|false
Запрашивает у аутентификатора включение или отключение верификации пользователя.
.It Cm pin Ns = Ns Ar true|false
Сообщает
.Nm ,
запрашивать ли PIN и требовать верификацию пользователя.
.El
.Pp
Опцию
.Fl t
можно указывать несколько раз.
.It Fl u
Получить утверждение с использованием U2F.
По умолчанию,
.Nm
будет использовать FIDO2, если он поддерживается аутентификатором, и в противном случае переключится на U2F.
.It Fl v
Если утверждение получается, запросить у пользователя PIN и потребовать от аутентификатора верификацию пользователя.
Если утверждение проверяется, проверить, был ли бит верификации пользователя подписан аутентификатором.
.It Fl w
Сообщает
.Nm ,
что первая строка входных данных при получении утверждения должна интерпретироваться как нехешированные клиентские данные.
Это требуется Windows Hello, который вычисляет хеш клиентских данных внутренне.
.El
.Pp
Если доступен
.Em tty ,
.Nm
будет использовать его для получения PIN.
В противном случае используется
.Em stdin .
.Sh ФОРМАТ ВВОДА
Вход
.Nm
состоит из блоков base64 и строк UTF-8, разделенных символами новой строки ('\\\\n').
.Pp
При получении утверждения
.Nm
ожидает, что его входные данные состоят из:
.Pp
.Bl -enum -offset indent -compact
.It
хеш клиентских данных (блок base64);
.It
идентификатор доверяющей стороны (строка UTF-8);
.It
идентификатор учетных данных, если учетные данные не резидентные (блок base64);
.It
соль hmac, если включено расширение FIDO2 hmac-secret
(блок base64);
.El
.Pp
При проверке утверждения
.Nm
ожидает, что его входные данные состоят из:
.Pp
.Bl -enum -offset indent -compact
.It
хеш клиентских данных (блок base64);
.It
идентификатор доверяющей стороны (строка UTF-8);
.It
данные аутентификатора в кодировке CBOR (блок base64);
.It
подпись утверждения (блок base64);
.El
.Pp
Строки UTF-8, передаваемые в
.Nm ,
не должны содержать внедренных символов новой строки или NUL.
.Sh ФОРМАТ ВЫВОДА
Выход
.Nm
состоит из блоков base64 и строк UTF-8, разделенных символами новой строки ('\\\\n').
.Pp
Для каждого сгенерированного утверждения
.Nm
выводит:
.Pp
.Bl -enum -offset indent -compact
.It
хеш клиентских данных (блок base64);
.It
идентификатор доверяющей стороны (строка UTF-8);
.It
данные аутентификатора в кодировке CBOR (блок base64);
.It
подпись утверждения (блок base64);
.It
идентификатор пользователя, если учетные данные резидентные (блок base64);
.It
секрет hmac, если включено расширение FIDO2 hmac-secret
(блок base64);
.It
связанный с учетными данными 32-байтовый симметричный ключ
.Pq Dq largeBlobKey ,
если запрошено (блок base64).
.El
.Pp
При проверке утверждения
.Nm
не производит вывода.
.Sh ПРИМЕРЫ
Предполагая, что
.Pa cred
содержит учетные данные
.Em es256 ,
созданные в соответствии с шагами, описанными в
.Xr fido2-cred 1 ,
получите утверждение от аутентификатора по адресу
.Pa /dev/hidraw5
и проверьте его:
.Pp
.Dl $ echo assertion challenge | openssl sha256 -binary | base64 > assert_param
.Dl $ echo relying party >> assert_param
.Dl $ head -1 cred >> assert_param
.Dl $ tail -n +2 cred > pubkey
.Dl $ fido2-assert -G -i assert_param /dev/hidraw5 | fido2-assert -V pubkey es256
.Sh СМ. ТАКЖЕ
.Xr fido2-cred 1 ,
.Xr fido2-token 1
