.\" FRDP path contrib/libfido2/man/fido2-cred.1
.\" FRDP githash febb0da5bf4bc99828ebede7abcb039514ac367a
.\" FRDP hash256 2f2a19722e74ec3ca7f320361209410cf93dcf79180bda0dc921a5bbb7e6e7cd
.Dd $Mdocdate: July 3 2023 $
.Dt FIDO2-CRED 1
.Os
.Sh ИМЯ
.Nm fido2-cred
.Nd создать/проверить учетные данные FIDO2
.Sh СИНТАКСИС
.Nm
.Fl M
.Op Fl bdhqruvw
.Op Fl a Ar режим
.Op Fl c Ar cred_protect
.Op Fl i Ar входной_файл
.Op Fl o Ar выходной_файл
.Ar устройство
.Op Ar тип
.Nm
.Fl V
.Op Fl dhv
.Op Fl c Ar cred_protect
.Op Fl i Ar входной_файл
.Op Fl o Ar выходной_файл
.Op Ar тип
.Sh ОПИСАНИЕ
.Nm
создаёт или проверяет учетные данные FIDO2.
.Pp
Учетные данные
.Ar типа
могут быть
.Em es256
(обозначает ECDSA над NIST P-256 с SHA-256),
.Em es384
(обозначает ECDSA над NIST P-384 с SHA-384),
.Em rs256
(обозначает 2048-битный RSA с дополнением PKCS#1.5 и SHA-256) или
.Em eddsa
(обозначает EDDSA над Curve25519 с SHA-512).
Если
.Ar тип
не указан,
предполагается
.Em es256 .
.Pp
При создании учетных данных аутентификатор может потребовать от пользователя
аутентификации с помощью PIN-кода.
Если опция
.Fl q
не указана,
.Nm
запросит у пользователя PIN-код.
Если доступен
.Em tty ,
.Nm
будет использовать его для получения PIN-кода.
В противном случае используется
.Em stdin .
.Pp
Входные данные
.Nm
определяются параметрами создаваемых/проверяемых учетных данных.
Подробности см. в разделе
.Sx ФОРМАТ ВВОДА
.
.Pp
Выходные данные
.Nm
определяются результатом выбранной операции.
Подробности см. в разделе
.Sx ФОРМАТ ВЫВОДА
.
.Pp
Если учетные данные успешно созданы или проверены,
.Nm
завершается с кодом 0.
В противном случае
.Nm
завершается с кодом 1.
.Pp
Опции следующие:
.Bl -tag -width Ds
.It Fl M
Указывает
.Nm
создать новые учетные данные на
.Ar устройстве .
.It Fl V
Указывает
.Nm
проверить учетные данные.
.It Fl b
Запросить
.Dq largeBlobKey
учетных данных,
32-байтовый симметричный ключ, связанный с созданными учетными данными.
.It Fl a Ar режим
При создании учетных данных запросить корпоративную аттестацию.
Обратитесь к
.In fido/param.h
за списком возможных значений.
.It Fl c Ar cred_protect
При создании учетных данных установить уровень защиты учетных данных в
.Ar cred_protect ,
где
.Ar cred_protect
— уровень защиты учетных данных в десятичной нотации.
Обратитесь к
.In fido/param.h
за списком возможных значений.
При проверке учетных данных проверить, был ли уровень защиты учетных данных
подписан аутентификатором как
.Ar cred_protect .
.It Fl d
Заставляет
.Nm
выводить отладочную информацию в
.Em stderr .
.It Fl h
При создании учетных данных включить расширение FIDO2 hmac-secret.
При проверке учетных данных проверить, был ли бит данных расширения
подписан аутентификатором.
.It Fl i Ar входной_файл
Указывает
.Nm
читать параметры учетных данных из
.Ar входной_файл
вместо
.Em stdin .
.It Fl o Ar выходной_файл
Указывает
.Nm
записывать вывод в
.Ar выходной_файл
вместо
.Em stdout .
.It Fl q
Указывает
.Nm
работать тихо.
Если требуется PIN-код и
.Fl q
указана,
.Nm
завершится с ошибкой.
.It Fl r
Создать резидентные учетные данные.
Резидентные учетные данные называются
.Dq обнаруживаемыми учетными данными
в CTAP 2.1.
.It Fl u
Создать учетные данные U2F.
По умолчанию
.Nm
будет использовать FIDO2, если поддерживается аутентификатором, и в противном случае
переключится на U2F.
.It Fl v
При создании учетных данных запросить верификацию пользователя.
При проверке учетных данных проверить, был ли бит верификации пользователя
подписан аутентификатором.
.It Fl w
Указывает
.Nm ,
что первая строка ввода при создании учетных данных должна
интерпретироваться как нехешированные данные клиента.
Это требуется Windows Hello, который вычисляет хеш данных клиента
внутренне.
.El
.Sh ФОРМАТ ВВОДА
Входные данные
.Nm
состоят из base64-блоков и строк UTF-8, разделённых
символами новой строки ('\\\\n').
.Pp
При создании учетных данных
.Nm
ожидает, что его входные данные состоят из:
.Pp
.Bl -enum -offset indent -compact
.It
хеш данных клиента (base64-блок);
.It
идентификатор доверяющей стороны (строка UTF-8);
.It
имя пользователя (строка UTF-8);
.It
идентификатор пользователя (base64-блок).
.El
.Pp
При проверке учетных данных
.Nm
ожидает, что его входные данные состоят из:
.Pp
.Bl -enum -offset indent -compact
.It
хеш данных клиента (base64-блок);
.It
идентификатор доверяющей стороны (строка UTF-8);
.It
формат учетных данных (строка UTF-8);
.It
данные аутентификатора в кодировке CBOR (base64-блок);
.It
идентификатор учетных данных (base64-блок);
.It
подпись аттестации (base64-блок);
.It
сертификат аттестации (необязательно, base64-блок).
.El
.Pp
Строки UTF-8, передаваемые
.Nm
не должны содержать встроенных символов новой строки или NUL.
.Sh ФОРМАТ ВЫВОДА
Выходные данные
.Nm
состоят из base64-блоков, строк UTF-8 и открытых ключей в кодировке PEM,
разделённых символами новой строки ('\\\\n').
.Pp
При успешном создании учетных данных
.Nm
выводит:
.Pp
.Bl -enum -offset indent -compact
.It
хеш данных клиента (base64-блок);
.It
идентификатор доверяющей стороны (строка UTF-8);
.It
формат учетных данных (строка UTF-8);
.It
данные аутентификатора в кодировке CBOR (base64-блок);
.It
идентификатор учетных данных (base64-блок);
.It
подпись аттестации (base64-блок);
.It
сертификат аттестации, если присутствует (base64-блок).
.It
связанный 32-байтовый симметричный ключ учетных данных
.Pq Dq largeBlobKey ,
если присутствует (base64-блок).
.El
.Pp
При успешной проверке учетных данных
.Nm
выводит:
.Pp
.Bl -enum -offset indent -compact
.It
идентификатор учетных данных (base64-блок);
.It
ключ учетных данных в кодировке PEM.
.El
.Sh ПРИМЕРЫ
Создать новые
.Em es256
учетные данные на
.Pa /dev/hidraw5 ,
проверить их и сохранить идентификатор и открытый ключ учетных данных в
.Em cred :
.Pp
.Dl $ echo credential challenge | openssl sha256 -binary | base64 > cred_param
.Dl $ echo relying party >> cred_param
.Dl $ echo user name >> cred_param
.Dl $ dd if=/dev/urandom bs=1 count=32 | base64 >> cred_param
.Dl $ fido2-cred -M -i cred_param /dev/hidraw5 | fido2-cred -V -o cred
.Sh СМ. ТАКЖЕ
.Xr fido2-assert 1 ,
.Xr fido2-token 1
.Sh ПРЕДОСТЕРЕЖЕНИЯ
Обратите внимание, что
.Nm
обрабатывает Basic Attestation и Self Attestation прозрачно.
В случае Basic Attestation действительность сертификата аттестации
аутентификатора
.Em не
проверяется.
