.\" FRDP path bin/freebsd-version/freebsd-version.1
.\" FRDP githash fcc3096f004116d8bb8a753bb2f2181f2949a806
.\" FRDP hash256 f85823a2852b2613a8ce56205eac329c628b103b5d4801e116e4c2a72af2a894
.Dd August 27, 2025
.Dt FREEBSD-VERSION 1
.Os
.Sh ИМЯ
.Nm freebsd-version
.Nd "вывести версию и уровень патчей установленной системы"
.Sh СИНТАКСИС
.Nm
.Op Fl kru
.Op Fl j Ar клетка
.Sh ОПИСАНИЕ
Утилита
.Nm
делает всё возможное, чтобы определить версию и уровень патчей
установленного ядра и/или пользовательского окружения.
.Pp
Доступны следующие параметры:
.Bl -tag -width Fl
.It Fl k
Вывести версию и уровень патчей установленного ядра.
В отличие от
.Xr uname 1 ,
если новое ядро было установлено, но система ещё не перезагружена,
.Nm
выведет версию и уровень патчей нового ядра.
.It Fl r
Вывести версию и уровень патчей работающего ядра.
В отличие от
.Xr uname 1 ,
на это не влияют переменные окружения.
.It Fl u
Вывести версию и уровень патчей установленного пользовательского окружения.
Они жёстко закодированы в
.Nm
во время сборки.
.It Fl j Ar клетка
Вывести версию и уровень патчей установленного пользовательского окружения в
указанной клетке, заданной через
.Va jid
или
.Va name .
Этот параметр можно указывать несколько раз.
.El
.Pp
Если указано несколько из перечисленных выше параметров,
.Nm
выведет сначала версию установленного ядра, затем версию работающего ядра,
далее версию пользовательского окружения и, наконец, версию пользовательского
окружения указанных клеток, каждую на отдельной строке.
Если параметры не указаны, будет выведена только версия пользовательского
окружения.
.Sh ЗАМЕЧАНИЯ ПО РЕАЛИЗАЦИИ
Утилита
.Nm
должна давать правильный ответ в подавляющем большинстве случаев,
в том числе в системах, поддерживаемых в актуальном состоянии с помощью
.Xr freebsd-update 8 ,
которая не обновляет версию ядра, если только последний патч не затрагивал
само ядро.
.Pp
Чтобы определить имя (а следовательно, и расположение) пользовательского
ядра, утилита
.Nm
попытается разобрать
.Pa /boot/defaults/loader.conf
и
.Pa /boot/loader.conf ,
отыскивая определения переменных
.Va kernel
и
.Va bootfile ,
обе из которых по умолчанию имеют значение
.Dq kernel .
Однако она может не найти правильное ядро, если одна или обе эти переменные
определены в нестандартном месте, например в
.Pa /boot/loader.rc .
.Sh ОКРУЖЕНИЕ
.Bl -tag -width ROOT
.It Ev ROOT
Путь к корню файловой системы, в которой следует искать
.Pa loader.conf
и ядро.
.El
.Sh ПРИМЕРЫ
Чтобы определить версию работающего в данный момент пользовательского
окружения:
.Bd -literal -offset indent
/bin/freebsd-version -u
.Ed
.Pp
Чтобы проверить систему, восстанавливаемую с помощью live-системы:
.Bd -literal -offset indent
mount -rt ufs /dev/ada0p2 /mnt
env ROOT=/mnt /mnt/bin/freebsd-version -ku
.Ed
.Sh СМ. ТАКЖЕ
.Xr uname 1 ,
.Xr loader.conf 5
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Fx 10.0 .
.Sh АВТОРЫ
Утилита
.Nm
и эта страница руководства были написаны
.An Dag-Erling Sm\(/orgrav Aq Mt des@FreeBSD.org .
