.\" FRDP path usr.bin/gcore/gcore.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 53c2a1e7d56662b8b261d6753a74980b38e61d755869009ed935a8c21ae9de53
.Dd April 24, 2021
.Dt GCORE 1
.Os
.Sh ИМЯ
.Nm gcore
.Nd получить образы ядра работающего процесса
.Sh СИНТАКСИС
.Nm
.Op Fl f
.Op Fl k
.Op Fl c Ar core
.Op Ar executable
.Ar pid
.Sh ОПИСАНИЕ
Утилита
.Nm
создаёт образ ядра указанного процесса,
пригодный для использования с
.Xr gdb 1 Pq Pa ports/devel/gdb .
По умолчанию ядро записывается в файл
.Dq Pa core.<pid> .
Идентификатор процесса,
.Ar pid ,
должен быть указан в командной строке.
.Pp
Доступны следующие параметры:
.Bl -tag -width indent
.It Fl c
Записать файл ядра в указанный файл вместо
.Dq Pa core.<pid> .
.It Fl f
Сбросить все доступные сегменты, исключая только неправильно сформированные и несохраняемые
сегменты.
В отличие от вызова по умолчанию, этот флаг сбрасывает отображения устройств, которые
могут сделать недействительным состояние транзакций устройства или вызвать другое неожиданное
поведение.
В результате этот флаг следует использовать только тогда, когда поведение
приложения и любых отображённых им устройств полностью понятно, а любые побочные
эффекты можно контролировать или допускать.
.It Fl k
Использовать функцию ядра
.Xr ptrace 2
.Dv PT_COREDUMP
для записи дампа ядра вместо чтения памяти процесса
и построения файла дампа в самом
.Nm .
Это быстрее, и дамп записывается тем же
кодом ядра, который записывает дампы ядра при фатальных сигналах.
.El
.Sh ФАЙЛЫ
.Bl -tag -width /var/log/messages -compact
.It Pa core.<pid>
образ ядра
.El
.Sh ИСТОРИЯ
Утилита
.Nm
появилась в
.Bx 4.2 .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Из-за использования
.Xr ptrace 2
.Nm
может не работать с процессами, которые активно исследуются с помощью
.Xr truss 1
или
.Xr gdb 1 Pq Pa ports/devel/gdb .
Кроме того, прерываемые состояния ожидания могут завершаться с EINTR.
.Pp
Утилита
.Nm
несовместима с оригинальной версией
.Bx 4.2 .
