.\" FRDP path bin/getfacl/getfacl.1
.\" FRDP githash 8bf37c868f45e73345b791f9abc6c5a07a1629db
.\" FRDP hash256 490907499f73d7add81a5c8a54b3835327816001cb9f1a10cbefea4762663db7
.Dd June 19, 2023
.Dt GETFACL 1
.Os
.Sh ИМЯ
.Nm getfacl
.Nd получить информацию о ACL
.Sh СИНТАКСИС
.Nm
.Op Fl dhinqv
.Op Ar
.Sh ОПИСАНИЕ
Утилита
.Nm
записывает информацию дискреционного управления доступом, связанную с
указанными файлами, в стандартный вывод.
Если утилита
.Xr getconf 1
указывает, что
.Brq Va _POSIX_ACL_EXTENDED
не действует для
.Ar файла ,
то стандартные права дискреционного доступа интерпретируются как
ACL, содержащий только обязательные элементы ACL.
.Pp
Доступна следующая опция:
.Bl -tag -width indent
.It Fl d , Fl -default
Операция применяется к ACL по умолчанию каталога, а не к ACL доступа.
Ошибка возникает, если ACL по умолчанию не может быть связан с
.Ar файлом .
Эта опция недопустима для ACL NFSv4.
.It Fl h
Если целью операции является символическая ссылка, вернуть ACL самой
символической ссылки, а не переходить по ссылке.
.It Fl i
Для ACL NFSv4 добавлять числовой идентификатор в конец каждой записи, содержащей
имя пользователя или группы.
Игнорируется для ACL POSIX.1e.
.It Fl n , Fl -numeric
Отображать идентификаторы пользователей и групп численно, а не преобразовывать
в имя пользователя или группы.
Игнорируется для ACL POSIX.1e.
.It Fl q , Fl -omit-header
Не выводить закомментированную информацию об имени файла и владельце.
Это полезно при работе с именами файлов, содержащими непечатаемые символы.
.It Fl s , Fl -skip-base
Пропускать файлы, имеющие только тривиальный ACL, как определено в
.Xr acl_is_trivial_np 3 .
В частности, будут пропущены файлы с ACL POSIX.1e, которые представляют только
владельца, группу и остальных, чтобы соответствовать режиму файла.
.It Fl v
Для ACL NFSv4 отображать маску доступа и флаги в подробной форме.
Игнорируется для ACL POSIX.1e.
.El
.Pp
Доступен следующий операнд:
.Bl -tag -width indent
.It Ar файл
Путь к файлу, ACL которого должен быть получен.
Если
.Ar файл
не указан или
.Ar файл
указан как
.Fl ,
то
.Nm
читает список путей, каждый из которых завершается символом новой строки,
из стандартного ввода.
.El
.Pp
Объяснение синтаксиса ACL см. на странице руководства
.Xr setfacl 1 .
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
.Dl getfacl /
.Pp
Получить ACL для каталога
.Pa / .
.Pp
.Dl getfacl -d /
.Pp
Получить ACL по умолчанию для каталога
.Pa / ,
если он есть.
.Sh СМ. ТАКЖЕ
.Xr setfacl 1 ,
.Xr acl 3 ,
.Xr getextattr 8 ,
.Xr setextattr 8 ,
.Xr acl 9 ,
.Xr extattr 9
.Sh СТАНДАРТЫ
Утилита
.Nm
должна быть совместима со стандартом
.Tn IEEE
Std 1003.2c.
.Sh ИСТОРИЯ
Поддержка расширенных атрибутов и списков управления доступом была разработана
в рамках проекта
.Tn TrustedBSD
и появилась в
.Fx 5.0 .
.Sh АВТОРЫ
.An Robert N M Watson
