.\" FRDP path contrib/bc/manuals/bc/HN.1
.\" FRDP githash fdc4a7c8012b214986cfa2e2fb6d99731f004b1b
.\" FRDP hash256 0d0ddf230b2cc06f64547ecc9055ab3b8349a231e0e7c74bef6998a7901d4461
.nh
.ad l
.SH ИМЯ
bc \- язык и калькулятор десятичной арифметики произвольной точности
.SH СИНТАКСИС
\f[B]bc\f[R] [\f[B]\-cCghilPqRsvVw\f[R]] [\f[B]\-\-digit\-clamp\f[R]]
[\f[B]\-\-no\-digit\-clamp\f[R]] [\f[B]\-\-global\-stacks\f[R]]
[\f[B]\-\-help\f[R]] [\f[B]\-\-interactive\f[R]] [\f[B]\-\-mathlib\f[R]]
[\f[B]\-\-no\-prompt\f[R]] [\f[B]\-\-no\-read\-prompt\f[R]]
[\f[B]\-\-quiet\f[R]] [\f[B]\-\-standard\f[R]] [\f[B]\-\-warn\f[R]]
[\f[B]\-\-version\f[R]] [\f[B]\-e\f[R] \f[I]expr\f[R]]
[\f[B]\-\-expression\f[R]=\f[I]expr\f[R]\&...]
[\f[B]\-f\f[R] \f[I]file\f[R]\&...]
[\f[B]\-\-file\f[R]=\f[I]file\f[R]\&...]
[\f[I]file\f[R]\&...]
[\f[B]\-I\f[R] \f[I]ibase\f[R]] [\f[B]\-\-ibase\f[R]=\f[I]ibase\f[R]]
[\f[B]\-O\f[R] \f[I]obase\f[R]] [\f[B]\-\-obase\f[R]=\f[I]obase\f[R]]
[\f[B]\-S\f[R] \f[I]scale\f[R]] [\f[B]\-\-scale\f[R]=\f[I]scale\f[R]]
[\f[B]\-E\f[R] \f[I]seed\f[R]] [\f[B]\-\-seed\f[R]=\f[I]seed\f[R]]
.SH ОПИСАНИЕ
bc(1) — это интерактивный процессор для языка, впервые стандартизованного
в 1991 году POSIX.
(См. раздел \f[B]СТАНДАРТЫ\f[R].)
Язык обеспечивает десятичную арифметику неограниченной точности и
несколько похож на C, но есть различия.
Такие различия будут отмечены в этом документе.
.PP
После разбора и обработки параметров этот bc(1) читает любые файлы,
заданные в командной строке, и выполняет их перед чтением из
\f[B]stdin\f[R].
.PP
Этот bc(1) является заменой \f[I]любого\f[R] bc(1), включая
(и особенно) GNU bc(1).
У него также много расширений и дополнительных возможностей по сравнению
с другими реализациями.
.PP
\f[B]Примечание\f[R]: Если запуск этого bc(1) на \f[I]любом\f[R]
сценарии, предназначенном для другого bc(1), даёт ошибку разбора, то
вероятно, это потому, что слово, которое этот bc(1) резервирует как
ключевое, используется как имя функции, переменной или массива.
Чтобы исправить это, используйте параметр командной строки \f[B]\-r\f[R]
\f[I]keyword\f[R], где \f[I]keyword\f[R] — ключевое слово, используемое
как имя в сценарии.
Для получения дополнительной информации см. раздел \f[B]ОПЦИИ\f[R].
.PP
Если разбор сценариев, предназначенных для других реализаций bc(1),
всё ещё не работает, это ошибка, и о ней следует сообщить.
См. раздел \f[B]ИЗВЕСТНЫЕ ОШИБКИ\f[R].
.SH ОПЦИИ
Далее перечислены параметры, которые принимает bc(1).
.TP
\f[B]\-C\f[R], \f[B]\-\-no\-digit\-clamp\f[R]
Отключает ограничение цифр, больших или равных текущему
\f[B]ibase\f[R], при разборе чисел.
.RS
.PP
Это означает, что значение, добавляемое к числу из цифры, всегда равно
значению этой цифры, умноженному на значение ibase в степени позиции
цифры, которая начинается с 0 у младшей значащей цифры.
.PP
Если этот и/или параметры \f[B]\-c\f[R] или \f[B]\-\-digit\-clamp\f[R]
заданы несколько раз, используется последний заданный.
.PP
Этот параметр переопределяет переменную окружения
\f[B]BC_DIGIT_CLAMP\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]) и
значение по умолчанию, которое можно узнать с помощью параметров
\f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-c\f[R], \f[B]\-\-digit\-clamp\f[R]
Включает ограничение цифр, больших или равных текущему
\f[B]ibase\f[R], при разборе чисел.
.RS
.PP
Это означает, что для цифр, значение, добавляемое к числу из цифры,
которая больше или равна ibase, равно значению ibase минус 1, умноженному
на значение ibase в степени позиции цифры, которая начинается с 0 у
младшей значащей цифры.
.PP
Если этот и/или параметры \f[B]\-C\f[R] или \f[B]\-\-no\-digit\-clamp\f[R]
заданы несколько раз, используется последний заданный.
.PP
Этот параметр переопределяет переменную окружения
\f[B]BC_DIGIT_CLAMP\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]) и
значение по умолчанию, которое можно узнать с помощью параметров
\f[B]\-h\f[R] или \f[B]\-\-help\f[R].
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-E\f[R] \f[I]seed\f[R], \f[B]\-\-seed\f[R]=\f[I]seed\f[R]
Устанавливает встроенную переменную \f[B]seed\f[R] в значение
\f[I]seed\f[R], считая, что \f[I]seed\f[R] задано по основанию 10.
Если \f[I]seed\f[R] не является допустимым числом, это фатальная ошибка.
.RS
.PP
Если задано несколько экземпляров этого параметра, используется последний.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-e\f[R] \f[I]expr\f[R], \f[B]\-\-expression\f[R]=\f[I]expr\f[R]
Вычисляет \f[I]expr\f[R].
Если задано несколько выражений, они вычисляются по порядку.
Если также заданы файлы (см. параметры \f[B]\-f\f[R] и
\f[B]\-\-file\f[R]), выражения и файлы вычисляются в заданном порядке.
Это означает, что если файл задан перед выражением, файл сначала
читается и вычисляется.
.RS
.PP
Если этот параметр задан в командной строке (т. е. не в
\f[B]BC_ENV_ARGS\f[R], см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]),
то после обработки всех выражений и файлов bc(1) завершится, если
\f[B]\-\f[R] (\f[B]stdin\f[R]) не был передан как аргумент хотя бы раз
в \f[B]\-f\f[R] или \f[B]\-\-file\f[R], будь то в командной строке или в
\f[B]BC_ENV_ARGS\f[R].
Однако если любые другие аргументы \f[B]\-e\f[R],
\f[B]\-\-expression\f[R], \f[B]\-f\f[R] или \f[B]\-\-file\f[R] заданы
после \f[B]\-f\-\f[R] или эквивалента, bc(1) выдаст фатальную ошибку и
завершится.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-f\f[R] \f[I]file\f[R], \f[B]\-\-file\f[R]=\f[I]file\f[R]
Читает \f[I]file\f[R] и вычисляет его построчно, как если бы он читался
через \f[B]stdin\f[R].
Если также заданы выражения (см. параметры \f[B]\-e\f[R] и
\f[B]\-\-expression\f[R]), выражения вычисляются в заданном порядке.
.RS
.PP
Если этот параметр задан в командной строке (т. е. не в
\f[B]BC_ENV_ARGS\f[R], см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]),
то после обработки всех выражений и файлов bc(1) завершится, если
\f[B]\-\f[R] (\f[B]stdin\f[R]) не был передан как аргумент хотя бы раз
в \f[B]\-f\f[R] или \f[B]\-\-file\f[R].
Однако если любые другие аргументы \f[B]\-e\f[R],
\f[B]\-\-expression\f[R], \f[B]\-f\f[R] или \f[B]\-\-file\f[R] заданы
после \f[B]\-f\-\f[R] или эквивалента, bc(1) выдаст фатальную ошибку и
завершится.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-g\f[R], \f[B]\-\-global\-stacks\f[R]
Превращает глобальные переменные \f[B]ibase\f[R], \f[B]obase\f[R],
\f[B]scale\f[R] и \f[B]seed\f[R] в стеки.
.RS
.PP
Это приводит к тому, что копия текущего значения всех четырёх помещается
в стек при каждом вызове функции и извлекается при каждом возврате из
функции.
Это означает, что функции могут присваивать значения любым из этих
глобальных переменных, не беспокоясь, что изменение повлияет на другие
функции.
Таким образом, гипотетическая функция с именем \f[B]output(x,b)\f[R],
которая просто печатает \f[B]x\f[R] по основанию \f[B]b\f[R], могла бы
быть написана так:
.IP
.EX
define void output(x, b) {
    obase=b
    x
}
.EE
.PP
вместо такого:
.IP
.EX
define void output(x, b) {
    auto c
    c=obase
    obase=b
    x
    obase=c
}
.EE
.PP
Это делает написание функций намного проще.
.PP
(\f[B]Примечание\f[R]: функция \f[B]output(x,b)\f[R] существует в
расширенной математической библиотеке.
См. раздел \f[B]БИБЛИОТЕКА\f[R].)
.PP
Однако, поскольку использование этого флага означает, что функции не
могут устанавливать \f[B]ibase\f[R], \f[B]obase\f[R], \f[B]scale\f[R]
или \f[B]seed\f[R] глобально, функции, созданные для этого, больше не
смогут работать.
Для этого есть два возможных варианта использования, и для каждого есть
решение.
.PP
Во-первых, если функция вызывается при запуске, чтобы превратить bc(1) в
преобразователь чисел, можно заменить эту возможность различными
псевдонимами оболочки.
Примеры:
.IP
.EX
alias d2o=\[dq]bc \-e ibase=A \-e obase=8\[dq]
alias h2b=\[dq]bc \-e ibase=G \-e obase=2\[dq]
.EE
.PP
Во-вторых, если цель функции — установить \f[B]ibase\f[R],
\f[B]obase\f[R], \f[B]scale\f[R] или \f[B]seed\f[R] глобально для любой
другой цели, её можно разделить на одну—четыре функции (в зависимости от
того, сколько глобальных переменных она устанавливает), и каждая из этих
функций может возвращать желаемое значение для глобальной переменной.
.PP
Для функций, которые устанавливают \f[B]seed\f[R], значение,
присвоенное \f[B]seed\f[R], не передаётся родительским функциям.
Это означает, что последовательность псевдослучайных чисел, которую они
видят, не будет той же последовательностью псевдослучайных чисел, которую
видит любая родительская функция.
Это имеет место только после того, как \f[B]seed\f[R] был установлен.
.PP
Если функция хочет не влиять на последовательность псевдослучайных чисел
своих родителей, но хочет использовать тот же \f[B]seed\f[R], она может
использовать следующую строку:
.IP
.EX
seed = seed
.EE
.PP
Если такое поведение этого параметра желательно для каждого запуска
bc(1), пользователи могут определить \f[B]BC_ENV_ARGS\f[R] и включить
этот параметр (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R] для
подробностей).
.PP
Если используются \f[B]\-s\f[R], \f[B]\-w\f[R] или любые эквиваленты,
этот параметр игнорируется.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-h\f[R], \f[B]\-\-help\f[R]
Печатает сообщение об использовании и завершает работу.
.TP
\f[B]\-I\f[R] \f[I]ibase\f[R], \f[B]\-\-ibase\f[R]=\f[I]ibase\f[R]
Устанавливает встроенную переменную \f[B]ibase\f[R] в значение
\f[I]ibase\f[R], считая, что \f[I]ibase\f[R] задано по основанию 10.
Если \f[I]ibase\f[R] не является допустимым числом, это фатальная ошибка.
.RS
.PP
Если задано несколько экземпляров этого параметра, используется последний.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-i\f[R], \f[B]\-\-interactive\f[R]
Принудительно включает интерактивный режим.
(См. раздел \f[B]ИНТЕРАКТИВНЫЙ РЕЖИМ\f[R].)
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-L\f[R], \f[B]\-\-no\-line\-length\f[R]
Отключает проверку длины строки и печатает числа без обратных слешей и
переводов строк.
Другими словами, этот параметр устанавливает \f[B]BC_LINE_LENGTH\f[R] в
\f[B]0\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-l\f[R], \f[B]\-\-mathlib\f[R]
Устанавливает \f[B]scale\f[R] (см. раздел \f[B]СИНТАКСИС\f[R]) в
\f[B]20\f[R] и загружает включённую математическую библиотеку и
расширенную математическую библиотеку перед запуском любого кода, включая
любые выражения или файлы, заданные в командной строке.
.RS
.PP
Чтобы узнать, что находится в библиотеках, см. раздел
\f[B]БИБЛИОТЕКА\f[R].
.RE
.TP
\f[B]\-O\f[R] \f[I]obase\f[R], \f[B]\-\-obase\f[R]=\f[I]obase\f[R]
Устанавливает встроенную переменную \f[B]obase\f[R] в значение
\f[I]obase\f[R], считая, что \f[I]obase\f[R] задано по основанию 10.
Если \f[I]obase\f[R] не является допустимым числом, это фатальная ошибка.
.RS
.PP
Если задано несколько экземпляров этого параметра, используется последний.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-P\f[R], \f[B]\-\-no\-prompt\f[R]
Отключает приглашение в режиме TTY.
(Приглашение включается только в режиме TTY.
См. раздел \f[B]РЕЖИМ TTY\f[R].)
Это в основном для тех пользователей, которые не хотят приглашения или
не привыкли к ним в bc(1).
Большинство таких пользователей захотят поместить этот параметр в
\f[B]BC_ENV_ARGS\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
.RS
.PP
Эти параметры переопределяют переменные окружения \f[B]BC_PROMPT\f[R] и
\f[B]BC_TTY_MODE\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-q\f[R], \f[B]\-\-quiet\f[R]
Этот параметр предназначен для совместимости с GNU bc(1)
(https://www.gnu.org/software/bc/); он ничего не делает.
Без этого параметра GNU bc(1) печатает заголовок об авторских правах.
Этот bc(1) печатает заголовок об авторских правах только если задан один
или несколько параметров \f[B]\-v\f[R], \f[B]\-V\f[R] или
\f[B]\-\-version\f[R], если только переменная окружения
\f[B]BC_BANNER\f[R] не установлена и не содержит ненулевое целое, или
если этот bc(1) был собран с заголовком, отображаемым по умолчанию.
Если \f[I]любой\f[R] из этих случаев имеет место, то этот параметр
\f[I]действительно\f[R] не даёт bc(1) печатать заголовок.
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-R\f[R], \f[B]\-\-no\-read\-prompt\f[R]
Отключает приглашение чтения в режиме TTY.
(Приглашение чтения включается только в режиме TTY.
См. раздел \f[B]РЕЖИМ TTY\f[R].)
Это в основном для тех пользователей, которые не хотят приглашения
чтения или не привыкли к ним в bc(1).
Большинство таких пользователей захотят поместить этот параметр в
\f[B]BC_ENV_ARGS\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
Этот параметр также полезен в строках hash bang сценариев bc(1),
которые запрашивают ввод пользователя.
.RS
.PP
Этот параметр не отключает обычное приглашение, потому что приглашение
чтения используется только при вызове встроенной функции \f[B]read()\f[R].
.PP
Эти параметры \f[I]действительно\f[R] переопределяют переменные окружения
\f[B]BC_PROMPT\f[R] и \f[B]BC_TTY_MODE\f[R] (см. раздел
\f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]), но только для приглашения чтения.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-r\f[R] \f[I]keyword\f[R], \f[B]\-\-redefine\f[R]=\f[I]keyword\f[R]
Переопределяет \f[I]keyword\f[R], чтобы его можно было использовать как
имя функции, переменной или массива.
Это полезно, когда этот bc(1) выдаёт ошибки разбора при разборе
сценариев, предназначенных для других реализаций bc(1).
.RS
.PP
Ключевые слова, которые этот bc(1) позволяет переопределять:
.IP \[bu] 2
\f[B]abs\f[R]
.IP \[bu] 2
\f[B]asciify\f[R]
.IP \[bu] 2
\f[B]continue\f[R]
.IP \[bu] 2
\f[B]divmod\f[R]
.IP \[bu] 2
\f[B]else\f[R]
.IP \[bu] 2
\f[B]halt\f[R]
.IP \[bu] 2
\f[B]irand\f[R]
.IP \[bu] 2
\f[B]last\f[R]
.IP \[bu] 2
\f[B]limits\f[R]
.IP \[bu] 2
\f[B]maxibase\f[R]
.IP \[bu] 2
\f[B]maxobase\f[R]
.IP \[bu] 2
\f[B]maxrand\f[R]
.IP \[bu] 2
\f[B]maxscale\f[R]
.IP \[bu] 2
\f[B]modexp\f[R]
.IP \[bu] 2
\f[B]print\f[R]
.IP \[bu] 2
\f[B]rand\f[R]
.IP \[bu] 2
\f[B]read\f[R]
.IP \[bu] 2
\f[B]seed\f[R]
.IP \[bu] 2
\f[B]stream\f[R]
.PP
Если любое из этих ключевых слов используется как имя функции,
переменной или массива в сценарии, используйте этот параметр с ключевым
словом в качестве аргумента.
Если используется несколько, используйте этот параметр для всех них; его
можно использовать несколько раз.
.PP
Ключевые слова \f[I]не\f[R] переопределяются при разборе встроенной
математической библиотеки (см. раздел \f[B]БИБЛИОТЕКА\f[R]).
.PP
Переопределять ключевые слова, предписанные стандартом POSIX (см. раздел
\f[B]СТАНДАРТЫ\f[R]), — фатальная ошибка.
Попытка переопределить слова, которые этот bc(1) не резервирует как
ключевые, — фатальная ошибка.
.RE
.TP
\f[B]\-S\f[R] \f[I]scale\f[R], \f[B]\-\-scale\f[R]=\f[I]scale\f[R]
Устанавливает встроенную переменную \f[B]scale\f[R] в значение
\f[I]scale\f[R], считая, что \f[I]scale\f[R] задано по основанию 10.
Если \f[I]scale\f[R] не является допустимым числом, это фатальная ошибка.
.RS
.PP
Если задано несколько экземпляров этого параметра, используется последний.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-s\f[R], \f[B]\-\-standard\f[R]
Обрабатывает точно язык, определённый стандартом (см. раздел
\f[B]СТАНДАРТЫ\f[R]), и выдаёт ошибку, если используются какие-либо
расширения.
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-v\f[R], \f[B]\-V\f[R], \f[B]\-\-version\f[R]
Печатает информацию о версии (заголовок об авторских правах) и
завершает работу.
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-w\f[R], \f[B]\-\-warn\f[R]
Как \f[B]\-s\f[R] и \f[B]\-\-standard\f[R], за исключением того, что для
нестандартных расширений печатаются предупреждения (а не ошибки), и
выполнение продолжается нормально.
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\-z\f[R], \f[B]\-\-leading\-zeroes\f[R]
Заставляет bc(1) печатать все числа больше \f[B]\-1\f[R] и меньше
\f[B]1\f[R], и не равные \f[B]0\f[R], с ведущим нулём.
.RS
.PP
Это можно задать для отдельных чисел с помощью функций \f[B]plz(x)\f[R],
\f[B]plznl(x)\f[R], \f[B]pnlz(x)\f[R] и \f[B]pnlznl(x)\f[R] в
расширенной математической библиотеке (см. раздел
\f[B]БИБЛИОТЕКА\f[R]).
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.PP
Все длинные параметры являются \f[B]непереносимыми расширениями\f[R].
.SH СТАНДАРТНЫЙ ВВОД
Если не заданы файлы или выражения с помощью параметров \f[B]\-f\f[R],
\f[B]\-\-file\f[R], \f[B]\-e\f[R] или \f[B]\-\-expression\f[R], то bc(1)
читает из \f[B]stdin\f[R].
.PP
Однако в этом есть несколько оговорок.
.PP
Во-первых, \f[B]stdin\f[R] вычисляется по одной строке за раз.
Единственное исключение — если разбор не может завершиться.
Это означает, что начало строки без её завершения или начало функции,
инструкции \f[B]if\f[R] или цикла без их завершения также заставит bc(1)
не выполнять код.
.PP
Во-вторых, после инструкции \f[B]if\f[R] bc(1) не знает, будет ли далее
инструкция \f[B]else\f[R], поэтому он не будет выполнять код, пока не
узнает, что инструкции \f[B]else\f[R] не будет.
.SH СТАНДАРТНЫЙ ВЫВОД
Любой вывод, не являющийся ошибкой, записывается в \f[B]stdout\f[R].
Кроме того, если включены история (см. раздел \f[B]ИСТОРИЯ\f[R]) и
приглашение (см. раздел \f[B]РЕЖИМ TTY\f[R]), оба выводятся в
\f[B]stdout\f[R].
.PP
\f[B]Примечание\f[R]: В отличие от других реализаций bc(1), этот bc(1)
выдаст фатальную ошибку (см. раздел \f[B]СТАТУС ВЫХОДА\f[R]), если не
сможет записать в \f[B]stdout\f[R], поэтому если \f[B]stdout\f[R] закрыт,
как в \f[B]bc  >&\-\f[R], он завершится с ошибкой.
Это сделано для того, чтобы bc(1) мог сообщать о проблемах, когда
\f[B]stdout\f[R] перенаправлен в файл.
.PP
Если есть сценарии, которые зависят от поведения других реализаций
bc(1), рекомендуется изменить эти сценарии так, чтобы перенаправлять
\f[B]stdout\f[R] в \f[B]/dev/null\f[R].
.SH СТАНДАРТНЫЙ ВЫВОД ОШИБОК
Любой вывод ошибок записывается в \f[B]stderr\f[R].
.PP
\f[B]Примечание\f[R]: В отличие от других реализаций bc(1), этот bc(1)
выдаст фатальную ошибку (см. раздел \f[B]СТАТУС ВЫХОДА\f[R]), если не
сможет записать в \f[B]stderr\f[R], поэтому если \f[B]stderr\f[R] закрыт,
как в \f[B]bc  2>&\-\f[R], он завершится с ошибкой.
Это сделано для того, чтобы bc(1) мог завершиться с кодом ошибки, когда
\f[B]stderr\f[R] перенаправлен в файл.
.PP
Если есть сценарии, которые зависят от поведения других реализаций
bc(1), рекомендуется изменить эти сценарии так, чтобы перенаправлять
\f[B]stderr\f[R] в \f[B]/dev/null\f[R].
.SH СИНТАКСИС
Синтаксис программ bc(1) в основном похож на C, с некоторыми отличиями.
Этот bc(1) следует стандарту POSIX (см. раздел \f[B]СТАНДАРТЫ\f[R]),
который является гораздо более полным источником по языку, который
принимает этот bc(1).
Этот раздел предназначен для краткого изложения и перечисления всех
расширений к стандарту.
.PP
В разделах ниже \f[B]E\f[R] означает выражение, \f[B]S\f[R] означает
инструкцию, а \f[B]I\f[R] означает идентификатор.
.PP
Идентификаторы (\f[B]I\f[R]) начинаются со строчной буквы и могут
сопровождаться любым количеством (до \f[B]BC_NAME_MAX\-1\f[R]) строчных
букв (\f[B]a\-z\f[R]), цифр (\f[B]0\-9\f[R]) и знаков подчёркивания
(\f[B]_\f[R]).
Регулярное выражение — \f[B][a\-z][a\-z0\-9_]*\f[R].
Идентификаторы длиной более одного символа (буквы) являются
\f[B]непереносимым расширением\f[R].
.PP
\f[B]ibase\f[R] — это глобальная переменная, определяющая, как
интерпретировать константные числа.
Это «входное» основание, или основание системы счисления, используемое
для интерпретации входных чисел.
Изначально \f[B]ibase\f[R] равно \f[B]10\f[R].
Если флаги \f[B]\-s\f[R] (\f[B]\-\-standard\f[R]) и \f[B]\-w\f[R]
(\f[B]\-\-warn\f[R]) не были заданы в командной строке, максимальное
допустимое значение для \f[B]ibase\f[R] — \f[B]36\f[R].
В противном случае — \f[B]16\f[R].
Минимальное допустимое значение для \f[B]ibase\f[R] — \f[B]2\f[R].
Максимальное допустимое значение для \f[B]ibase\f[R] можно узнать в
программах bc(1) с помощью встроенной функции \f[B]maxibase()\f[R].
.PP
\f[B]obase\f[R] — это глобальная переменная, определяющая, как выводить
результаты.
Это «выходное» основание, или основание системы счисления, используемое
для вывода чисел.
Изначально \f[B]obase\f[R] равно \f[B]10\f[R].
Максимальное допустимое значение для \f[B]obase\f[R] —
\f[B]BC_BASE_MAX\f[R], и его можно узнать в программах bc(1) с помощью
встроенной функции \f[B]maxobase()\f[R].
Минимальное допустимое значение для \f[B]obase\f[R] — \f[B]0\f[R].
Если \f[B]obase\f[R] равно \f[B]0\f[R], значения выводятся в научной
нотации, а если \f[B]obase\f[R] равно \f[B]1\f[R], значения выводятся в
инженерной нотации.
В противном случае значения выводятся в указанном основании.
.PP
Вывод в научной и инженерной нотации — это \f[B]непереносимые
расширения\f[R].
.PP
\f[I]scale\f[R] выражения — это количество цифр в результате выражения
справа от десятичной точки, а \f[B]scale\f[R] — глобальная переменная,
которая задаёт точность любых операций, за исключениями.
Изначально \f[B]scale\f[R] равно \f[B]0\f[R].
\f[B]scale\f[R] не может быть отрицательным.
Максимальное допустимое значение для \f[B]scale\f[R] —
\f[B]BC_SCALE_MAX\f[R], и его можно узнать в программах bc(1) с помощью
встроенной функции \f[B]maxscale()\f[R].
.PP
В bc(1) есть как \f[I]глобальные\f[R], так и \f[I]локальные\f[R]
переменные.
Все \f[I]локальные\f[R] переменные локальны для функции; они являются
параметрами или введены в списке \f[B]auto\f[R] функции (см. раздел
\f[B]ФУНКЦИИ\f[R]).
Если происходит доступ к переменной, которая не является параметром или
не находится в списке \f[B]auto\f[R], предполагается, что она
\f[I]глобальная\f[R].
Если родительская функция имеет \f[I]локальную\f[R] переменную с тем же
именем, что дочерняя функция считает \f[I]глобальной\f[R], то значение
этой \f[I]глобальной\f[R] переменной в дочерней функции — это значение
переменной в родительской функции, а не значение фактической
\f[I]глобальной\f[R] переменной.
.PP
Всё вышесказанное относится и к массивам.
.PP
Значение инструкции, являющейся выражением (т. е. любого из именованных
выражений или операндов), печатается, если только оператор с наименьшим
приоритетом не является оператором присваивания \f[I]и\f[R] выражение не
окружено скобками.
.PP
Значение, которое печатается, также присваивается специальной переменной
\f[B]last\f[R].
Одиночная точка (\f[B].\f[R]) также может использоваться как синоним
\f[B]last\f[R].
Это \f[B]непереносимые расширения\f[R].
.PP
Инструкции могут разделяться точками с запятой или переводами строк.
.SS Комментарии
Есть два вида комментариев:
Блочные комментарии заключаются в \f[B]/*\f[R] и \f[B]*/\f[R].
Строчные комментарии начинаются с \f[B]#\f[R] и продолжаются до
следующего перевода строки, не включая его.
Это \f[B]непереносимое расширение\f[R].
.SS Именованные выражения
Следующие выражения являются именованными в bc(1):
Переменные: \f[B]I\f[R]
Элементы массива: \f[B]I[E]\f[R]
\f[B]ibase\f[R]
\f[B]obase\f[R]
\f[B]scale\f[R]
\f[B]seed\f[R]
\f[B]last\f[R] или одиночная точка (\f[B].\f[R])
.PP
Числа 6 и 7 являются \f[B]непереносимыми расширениями\f[R].
.PP
Значение \f[B]seed\f[R] зависит от текущего генератора псевдослучайных
чисел, но гарантируется, что оно не изменится, кроме новых мажорных
версий.
.PP
\f[I]scale\f[R] и знак значения могут быть значимыми.
.PP
Если ранее использованное значение \f[B]seed\f[R] присваивается
\f[B]seed\f[R] и используется снова, генератор псевдослучайных чисел
гарантированно выдаст ту же последовательность псевдослучайных чисел,
что и при предыдущем использовании значения \f[B]seed\f[R].
.PP
Точное значение, присвоенное \f[B]seed\f[R], не гарантируется к
возврату, если \f[B]seed\f[R] запросить сразу же снова.
Однако если \f[B]seed\f[R] \f[I]действительно\f[R] возвращает другое
значение, оба значения при присваивании \f[B]seed\f[R] гарантированно
дают одну и ту же последовательность псевдослучайных чисел.
Это означает, что некоторые значения, присвоенные \f[B]seed\f[R],
\f[I]не\f[R] будут давать уникальные последовательности псевдослучайных
чисел.
Значение \f[B]seed\f[R] изменится после любого использования операндов
\f[B]rand()\f[R] и \f[B]irand(E)\f[R] (см. подраздел
\f[I]Операнды\f[R] ниже), кроме случая, когда параметр, переданный в
\f[B]irand(E)\f[R], равен \f[B]0\f[R], \f[B]1\f[R] или отрицателен.
.PP
Нет ограничения на длину (количество значащих десятичных цифр) или
\f[I]scale\f[R] значения, которое можно присвоить \f[B]seed\f[R].
.PP
Переменные и массивы не конфликтуют; пользователи могут иметь массивы с
тем же именем, что и переменные.
Это также относится к функциям (см. раздел \f[B]ФУНКЦИИ\f[R]), поэтому
пользователь может иметь переменную, массив и функцию с одинаковым
именем, и они не будут затенять друг друга, как внутри функций, так и
вне их.
.PP
Именованные выражения требуются как операнд операторов
\f[B]increment\f[R]/\f[B]decrement\f[R] и как левая часть операторов
\f[B]assignment\f[R] (см. подраздел \f[I]Операторы\f[R]).
.SS Операнды
Следующие операнды допустимы в bc(1):
Числа (см. подраздел \f[I]Числа\f[R] ниже).
Индексы массива (\f[B]I[E]\f[R]).
\f[B](E)\f[R]: Значение \f[B]E\f[R] (используется для изменения
приоритета).
\f[B]sqrt(E)\f[R]: Квадратный корень из \f[B]E\f[R].
\f[B]E\f[R] должен быть неотрицательным.
\f[B]length(E)\f[R]: Количество значащих десятичных цифр в \f[B]E\f[R].
Возвращает \f[B]1\f[R] для \f[B]0\f[R] без десятичных знаков.
Если передан строковый аргумент, возвращается длина строки.
Передача строки в \f[B]length(E)\f[R] — это \f[B]непереносимое
расширение\f[R].
\f[B]length(I[])\f[R]: Количество элементов в массиве \f[B]I\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]scale(E)\f[R]: \f[I]scale\f[R] выражения \f[B]E\f[R].
\f[B]abs(E)\f[R]: Абсолютное значение \f[B]E\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]is_number(E)\f[R]: \f[B]1\f[R], если заданный аргумент является
числом, \f[B]0\f[R], если это строка.
Это \f[B]непереносимое расширение\f[R].
\f[B]is_string(E)\f[R]: \f[B]1\f[R], если заданный аргумент является
строкой, \f[B]0\f[R], если это число.
Это \f[B]непереносимое расширение\f[R].
\f[B]modexp(E, E, E)\f[R]: Модульное возведение в степень, где первое
выражение — основание, второе — показатель степени, а третье — модуль.
Все три значения должны быть целыми.
Второй аргумент должен быть неотрицательным.
Третий аргумент должен быть ненулевым.
Это \f[B]непереносимое расширение\f[R].
\f[B]divmod(E, E, I[])\f[R]: Деление и взятие остатка в одной операции.
Это для оптимизации.
Первое выражение — делимое, а второе — делитель, который должен быть
ненулевым.
Возвращаемое значение — частное, а остаток сохраняется в индексе
\f[B]0\f[R] предоставленного массива (последний аргумент).
Это \f[B]непереносимое расширение\f[R].
\f[B]asciify(E)\f[R]: Если \f[B]E\f[R] — строка, возвращает строку,
состоящую из первой буквы её аргумента.
Если это число, вычисляет число по модулю \f[B]256\f[R] и возвращает это
число как односимвольную строку.
Это \f[B]непереносимое расширение\f[R].
\f[B]asciify(I[])\f[R]: Строка, состоящая из символов, которые
получились бы в результате применения \f[B]asciify(E)\f[R] к каждому
элементу массива, указанного аргументом.
Это позволяет создавать многосимвольные строки и сохранять их.
Это \f[B]непереносимое расширение\f[R].
\f[B]I()\f[R], \f[B]I(E)\f[R], \f[B]I(E, E)\f[R] и так далее, где
\f[B]I\f[R] — идентификатор функции, не являющейся \f[B]void\f[R] (см.
подраздел \f[I]Функции void\f[R] раздела \f[B]ФУНКЦИИ\f[R]).
Аргумент(ы) \f[B]E\f[R] также могут быть массивами вида \f[B]I[]\f[R],
которые автоматически превращаются в ссылки на массивы (см. подраздел
\f[I]Ссылки на массивы\f[R] раздела \f[B]ФУНКЦИИ\f[R]), если
соответствующий параметр в определении функции является ссылкой на
массив.
\f[B]read()\f[R]: Читает строку из \f[B]stdin\f[R] и использует её как
выражение.
Результат этого выражения — результат операнда \f[B]read()\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]maxibase()\f[R]: Максимально допустимое \f[B]ibase\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]maxobase()\f[R]: Максимально допустимое \f[B]obase\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]maxscale()\f[R]: Максимально допустимое \f[B]scale\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]line_length()\f[R]: Длина строки, установленная с помощью
\f[B]BC_LINE_LENGTH\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]).
Это \f[B]непереносимое расширение\f[R].
\f[B]global_stacks()\f[R]: \f[B]0\f[R], если глобальные стеки не
включены параметрами \f[B]\-g\f[R] или \f[B]\-\-global\-stacks\f[R],
иначе ненулевое значение.
См. раздел \f[B]ОПЦИИ\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]leading_zero()\f[R]: \f[B]0\f[R], если ведущие нули не включены
параметрами \f[B]\-z\f[R] или \f[B]\[en]leading\-zeroes\f[R], иначе
ненулевое значение.
См. раздел \f[B]ОПЦИИ\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]rand()\f[R]: Псевдослучайное целое между \f[B]0\f[R] (включительно)
и \f[B]BC_RAND_MAX\f[R] (включительно).
Использование этого операнда изменит значение \f[B]seed\f[R].
Это \f[B]непереносимое расширение\f[R].
\f[B]irand(E)\f[R]: Псевдослучайное целое между \f[B]0\f[R]
(включительно) и значением \f[B]E\f[R] (исключительно).
Если \f[B]E\f[R] отрицательно или не является целым (\f[I]scale\f[R]
выражения \f[B]E\f[R] не равно \f[B]0\f[R]), возникает ошибка, и bc(1)
сбрасывается (см. раздел \f[B]СБРОС\f[R]), а \f[B]seed\f[R] остаётся
без изменений.
Если \f[B]E\f[R] больше \f[B]BC_RAND_MAX\f[R], верхняя граница
обеспечивается генерацией нескольких псевдослучайных целых, умножением
их на соответствующие степени \f[B]BC_RAND_MAX+1\f[R] и сложением их
вместе.
Таким образом, размер целого, который можно сгенерировать этим
операндом, не ограничен.
Использование этого операнда изменит значение \f[B]seed\f[R], если
только значение \f[B]E\f[R] не равно \f[B]0\f[R] или \f[B]1\f[R].
В этом случае возвращается \f[B]0\f[R], и \f[B]seed\f[R] \f[I]не\f[R]
изменяется.
Это \f[B]непереносимое расширение\f[R].
\f[B]maxrand()\f[R]: Максимальное целое, возвращаемое \f[B]rand()\f[R].
Это \f[B]непереносимое расширение\f[R].
.PP
Целые, генерируемые \f[B]rand()\f[R] и \f[B]irand(E)\f[R],
гарантированно являются настолько непредвзятыми, насколько это возможно,
с учётом ограничений генератора псевдослучайных чисел.
.PP
\f[B]Примечание\f[R]: Значения, возвращаемые генератором
псевдослучайных чисел с помощью \f[B]rand()\f[R] и \f[B]irand(E)\f[R],
гарантированно \f[I]НЕ\f[R] являются криптографически стойкими.
Это следствие использования генератора псевдослучайных чисел с семенем.
Однако они \f[I]гарантированно\f[R] воспроизводимы при идентичных
значениях \f[B]seed\f[R].
Это означает, что псевдослучайные значения из bc(1) следует использовать
только там, где воспроизводимый поток псевдослучайных чисел
\f[I]КРИТИЧЕСКИ ВАЖЕН\f[R].
В любом другом случае используйте генератор псевдослучайных чисел без
семени.
.SS Числа
Числа — это строки, состоящие из цифр, заглавных букв и не более
\f[B]1\f[R] точки для разделителя дробной части.
Числа могут содержать до \f[B]BC_NUM_MAX\f[R] цифр.
Заглавные буквы равны \f[B]9\f[R] плюс их позиция в алфавите, начиная с
\f[B]1\f[R] (т. е. \f[B]A\f[R] равно \f[B]10\f[R], или \f[B]9+1\f[R]).
.PP
Если цифра или буква не имеет смысла при текущем значении
\f[B]ibase\f[R] (т. е. они больше или равны текущему значению
\f[B]ibase\f[R]), то поведение зависит от наличия параметров
\f[B]\-c\f[R]/\f[B]\-\-digit\-clamp\f[R] или
\f[B]\-C\f[R]/\f[B]\-\-no\-digit\-clamp\f[R] (см. раздел
\f[B]ОПЦИИ\f[R]), наличия и значения переменной окружения
\f[B]BC_DIGIT_CLAMP\f[R] (см. раздел \f[B]ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ\f[R]),
или значения по умолчанию, которое можно узнать с помощью параметра
\f[B]\-h\f[R]/\f[B]\-\-help\f[R].
.PP
Если ограничение отключено, то цифры или буквы, которые больше или равны
текущему значению \f[B]ibase\f[R], не изменяются.
Вместо этого их заданное значение умножается на соответствующую степень
\f[B]ibase\f[R] и добавляется к числу.
Это означает, что при \f[B]ibase\f[R] равном \f[B]3\f[R] число
\f[B]AB\f[R] равно \f[B]3\[ha]1*A+3\[ha]0*B\f[R], что равно
\f[B]3\f[R] умножить на \f[B]10\f[R] плюс \f[B]11\f[R], или
\f[B]41\f[R].
.PP
Если ограничение включено, то цифры или буквы, которые больше или равны
текущему значению \f[B]ibase\f[R], устанавливаются в значение наибольшей
допустимой цифры в \f[B]ibase\f[R] перед умножением на соответствующую
степень \f[B]ibase\f[R] и добавлением к числу.
Это означает, что при \f[B]ibase\f[R] равном \f[B]3\f[R] число
\f[B]AB\f[R] равно \f[B]3\[ha]1*2+3\[ha]0*2\f[R], что равно
\f[B]3\f[R] умножить на \f[B]2\f[R] плюс \f[B]2\f[R], или \f[B]8\f[R].
.PP
Есть одно исключение из ограничения: односимвольные числа (т. е.
\f[B]A\f[R] отдельно).
Такие числа никогда не ограничиваются и всегда принимают значение,
которое они имели бы в максимально возможном \f[B]ibase\f[R].
Это означает, что \f[B]A\f[R] отдельно всегда равно десятичному
\f[B]10\f[R], а \f[B]Z\f[R] отдельно всегда равно десятичному
\f[B]35\f[R].
Такое поведение предписано стандартом (см. раздел СТАНДАРТЫ) и
предназначено для предоставления простого способа установить текущее
\f[B]ibase\f[R] (с помощью команды \f[B]i\f[R]) независимо от текущего
значения \f[B]ibase\f[R].
.PP
Если ограничение включено, и требуется ограниченное значение символа,
используйте ведущий ноль, т. е. для \f[B]A\f[R] используйте
\f[B]0A\f[R].
.PP
Кроме того, bc(1) принимает числа в научной нотации.
Они имеют вид \f[B]<number>e<integer>\f[R].
Показатель степени (часть после \f[B]e\f[R]) должен быть целым.
Пример — \f[B]1.89237e9\f[R], что равно \f[B]1892370000\f[R].
Отрицательные показатели также допускаются, поэтому \f[B]4.2890e\-3\f[R]
равно \f[B]0.0042890\f[R].
.PP
Использование научной нотации является ошибкой или предупреждением,
если заданы параметры командной строки \f[B]\-s\f[R] или \f[B]\-w\f[R]
соответственно (или их эквиваленты).
.PP
\f[B]ПРЕДУПРЕЖДЕНИЕ\f[R]: И число, и показатель степени в научной
нотации интерпретируются согласно текущему \f[B]ibase\f[R], но число
всё равно умножается на \f[B]10\[ha]exponent\f[R] независимо от
текущего \f[B]ibase\f[R].
Например, если \f[B]ibase\f[R] равно \f[B]16\f[R] и bc(1) получает
строку числа \f[B]FFeA\f[R], результирующее десятичное число будет
\f[B]2550000000000\f[R], а если bc(1) получает строку числа
\f[B]10e\-4\f[R], результирующее десятичное число будет
\f[B]0.0016\f[R].
.PP
Приём ввода в виде научной нотации — это \f[B]непереносимое
расширение\f[R].
.SS Операторы
Можно использовать следующие арифметические и логические операторы.
Они перечислены в порядке убывания приоритета.
Операторы в одной группе имеют одинаковый приоритет.
.TP
\f[B]++\f[R] \f[B]\-\-\f[R]
Тип: Префиксный и постфиксный
.RS
.PP
Ассоциативность: Нет
.PP
Описание: \f[B]инкремент\f[R], \f[B]декремент\f[R]
.RE
.TP
\f[B]\-\f[R] \f[B]!\f[R]
Тип: Префиксный
.RS
.PP
Ассоциативность: Нет
.PP
Описание: \f[B]отрицание\f[R], \f[B]логическое НЕ\f[R]
.RE
.TP
\f[B]$\f[R]
Тип: Постфиксный
.RS
.PP
Ассоциативность: Нет
.PP
Описание: \f[B]усечение\f[R]
.RE
.TP
\f[B]\[at]\f[R]
Тип: Бинарный
.RS
.PP
Ассоциативность: Правая
.PP
Описание: \f[B]установка точности\f[R]
.RE
.TP
\f[B]\[ha]\f[R]
Тип: Бинарный
.RS
.PP
Ассоциативность: Правая
.PP
Описание: \f[B]возведение в степень\f[R]
.RE
.TP
\f[B]*\f[R] \f[B]/\f[R] \f[B]%\f[R]
Тип: Бинарный
.RS
.PP
Ассоциативность: Левая
.PP
Описание: \f[B]умножение\f[R], \f[B]деление\f[R], \f[B]остаток\f[R]
.RE
.TP
\f[B]+\f[R] \f[B]\-\f[R]
Тип: Бинарный
.RS
.PP
Ассоциативность: Левая
.PP
Описание: \f[B]сложение\f[R], \f[B]вычитание\f[R]
.RE
.TP
\f[B]<<\f[R] \f[B]>>\f[R]
Тип: Бинарный
.RS
.PP
Ассоциативность: Левая
.PP
Описание: \f[B]сдвиг влево\f[R], \f[B]сдвиг вправо\f[R]
.RE
.TP
\f[B]=\f[R] \f[B]<<=\f[R] \f[B]>>=\f[R] \f[B]+=\f[R] \f[B]\-=\f[R] \f[B]*=\f[R] \f[B]/=\f[R] \f[B]%=\f[R] \f[B]\[ha]=\f[R] \f[B]\[at]=\f[R]
Тип: Бинарный
.RS
.PP
Ассоциативность: Правая
.PP
Описание: \f[B]присваивание\f[R]
.RE
.TP
\f[B]==\f[R] \f[B]<=\f[R] \f[B]>=\f[R] \f[B]!=\f[R] \f[B]<\f[R] \f[B]>\f[R]
Тип: Бинарный
.RS
.PP
Ассоциативность: Левая
.PP
Описание: \f[B]отношение\f[R]
.RE
.TP
\f[B]&&\f[R]
Тип: Бинарный
.RS
.PP
Ассоциативность: Левая
.PP
Описание: \f[B]логическое И\f[R]
.RE
.TP
\f[B]||\f[R]
Тип: Бинарный
.RS
.PP
Ассоциативность: Левая
.PP
Описание: \f[B]логическое ИЛИ\f[R]
.RE
.PP
Операторы будут описаны подробнее ниже.
.TP
\f[B]++\f[R] \f[B]\-\-\f[R]
Префиксные и постфиксные операторы \f[B]инкремента\f[R] и
\f[B]декремента\f[R] ведут себя точно так же, как в C. Они требуют
именованное выражение (см. подраздел \f[I]Именованные выражения\f[R]) в
качестве операнда.
.RS
.PP
Префиксные версии этих операторов более эффективны; используйте их, где
возможно.
.RE
.TP
\f[B]\-\f[R]
Оператор \f[B]отрицания\f[R] возвращает \f[B]0\f[R], если пользователь
пытается отрицать любое выражение со значением \f[B]0\f[R].
В противном случае возвращается копия выражения с изменённым знаком.
.TP
\f[B]!\f[R]
Оператор \f[B]логического НЕ\f[R] возвращает \f[B]1\f[R], если выражение
равно \f[B]0\f[R], или \f[B]0\f[R] в противном случае.
.RS
.PP
\f[B]Предупреждение\f[R]: Этот оператор имеет \f[B]другой приоритет\f[R],
чем эквивалентный оператор в GNU bc(1) и других реализациях bc(1)!
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]$\f[R]
Оператор \f[B]усечения\f[R] возвращает копию заданного выражения со всем
удалённым \f[I]scale\f[R].
.RS
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\[at]\f[R]
Оператор \f[B]установки точности\f[R] принимает два выражения и
возвращает копию первого с \f[I]scale\f[R], равным значению второго
выражения.
Это может означать, что число возвращается без изменений (если
\f[I]scale\f[R] первого выражения совпадает со значением второго
выражения), расширенным (если меньше) или усечённым (если больше).
.RS
.PP
Второе выражение должно быть целым (без \f[I]scale\f[R]) и
неотрицательным.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]\[ha]\f[R]
Оператор \f[B]возведения в степень\f[R] (не оператор
\f[B]исключающего ИЛИ\f[R], как было бы в C) принимает два выражения и
возводит первое в степень значения второго.
\f[I]scale\f[R] результата равен \f[B]scale\f[R].
.RS
.PP
Второе выражение должно быть целым (без \f[I]scale\f[R]), и если оно
отрицательно, первое значение должно быть ненулевым.
.RE
.TP
\f[B]*\f[R]
Оператор \f[B]умножения\f[R] принимает два выражения, умножает их и
возвращает произведение.
Если \f[B]a\f[R] — \f[I]scale\f[R] первого выражения, а \f[B]b\f[R] —
\f[I]scale\f[R] второго выражения, \f[I]scale\f[R] результата равен
\f[B]min(a+b,max(scale,a,b))\f[R], где \f[B]min()\f[R] и
\f[B]max()\f[R] возвращают очевидные значения.
.TP
\f[B]/\f[R]
Оператор \f[B]деления\f[R] принимает два выражения, делит их и возвращает
частное.
\f[I]scale\f[R] результата должен быть значением \f[B]scale\f[R].
.RS
.PP
Второе выражение должно быть ненулевым.
.RE
.TP
\f[B]%\f[R]
Оператор \f[B]остатка\f[R] принимает два выражения, \f[B]a\f[R] и
\f[B]b\f[R], и вычисляет их так: 1) Вычисляет \f[B]a/b\f[R] с текущим
\f[B]scale\f[R] и 2) Использует результат шага 1 для вычисления
\f[B]a\-(a/b)*b\f[R] с \f[I]scale\f[R]
\f[B]max(scale+scale(b),scale(a))\f[R].
.RS
.PP
Второе выражение должно быть ненулевым.
.RE
.TP
\f[B]+\f[R]
Оператор \f[B]сложения\f[R] принимает два выражения, \f[B]a\f[R] и
\f[B]b\f[R], и возвращает сумму с \f[I]scale\f[R], равным максимуму
\f[I]scale\f[R] выражений \f[B]a\f[R] и \f[B]b\f[R].
.TP
\f[B]\-\f[R]
Оператор \f[B]вычитания\f[R] принимает два выражения, \f[B]a\f[R] и
\f[B]b\f[R], и возвращает разность с \f[I]scale\f[R], равным максимуму
\f[I]scale\f[R] выражений \f[B]a\f[R] и \f[B]b\f[R].
.TP
\f[B]<<\f[R]
Оператор \f[B]сдвига влево\f[R] принимает два выражения, \f[B]a\f[R] и
\f[B]b\f[R], и возвращает копию значения \f[B]a\f[R] с десятичной точкой,
перемещённой на \f[B]b\f[R] позиций вправо.
.RS
.PP
Второе выражение должно быть целым (без \f[I]scale\f[R]) и
неотрицательным.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]>>\f[R]
Оператор \f[B]сдвига вправо\f[R] принимает два выражения, \f[B]a\f[R] и
\f[B]b\f[R], и возвращает копию значения \f[B]a\f[R] с десятичной точкой,
перемещённой на \f[B]b\f[R] позиций влево.
.RS
.PP
Второе выражение должно быть целым (без \f[I]scale\f[R]) и
неотрицательным.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]=\f[R] \f[B]<<=\f[R] \f[B]>>=\f[R] \f[B]+=\f[R] \f[B]\-=\f[R] \f[B]*=\f[R] \f[B]/=\f[R] \f[B]%=\f[R] \f[B]\[ha]=\f[R] \f[B]\[at]=\f[R]
Операторы \f[B]присваивания\f[R] принимают два выражения, \f[B]a\f[R] и
\f[B]b\f[R], где \f[B]a\f[R] — именованное выражение (см. подраздел
\f[I]Именованные выражения\f[R]).
.RS
.PP
Для \f[B]=\f[R] \f[B]b\f[R] копируется, и результат присваивается
\f[B]a\f[R].
Для всех остальных \f[B]a\f[R] и \f[B]b\f[R] применяются как операнды к
соответствующему арифметическому оператору, и результат присваивается
\f[B]a\f[R].
.PP
Операторы \f[B]присваивания\f[R], соответствующие операторам, которые
являются расширениями, сами являются \f[B]непереносимыми
расширениями\f[R].
.RE
.TP
\f[B]==\f[R] \f[B]<=\f[R] \f[B]>=\f[R] \f[B]!=\f[R] \f[B]<\f[R] \f[B]>\f[R]
Операторы \f[B]отношения\f[R] сравнивают два выражения, \f[B]a\f[R] и
\f[B]b\f[R], и если отношение выполняется согласно семантике языка C,
результат равен \f[B]1\f[R].
В противном случае он равен \f[B]0\f[R].
.RS
.PP
Обратите внимание, что в отличие от C эти операторы имеют более низкий
приоритет, чем операторы \f[B]присваивания\f[R], что означает, что
\f[B]a=b>c\f[R] интерпретируется как \f[B](a=b)>c\f[R].
.PP
Кроме того, вопреки требованию стандарта (см. раздел
\f[B]СТАНДАРТЫ\f[R]), эти операторы могут появляться везде, где могут
использоваться любые другие выражения.
Это разрешение является \f[B]непереносимым расширением\f[R].
.RE
.TP
\f[B]&&\f[R]
Оператор \f[B]логического И\f[R] принимает два выражения и возвращает
\f[B]1\f[R], если оба выражения ненулевые, и \f[B]0\f[R] в противном
случае.
.RS
.PP
Это \f[I]не\f[R] оператор с коротким замыканием.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.TP
\f[B]||\f[R]
Оператор \f[B]логического ИЛИ\f[R] принимает два выражения и возвращает
\f[B]1\f[R], если одно из выражений ненулевое, и \f[B]0\f[R] в противном
случае.
.RS
.PP
Это \f[I]не\f[R] оператор с коротким замыканием.
.PP
Это \f[B]непереносимое расширение\f[R].
.RE
.SS Инструкции
Следующие элементы являются инструкциями:
\f[B]E\f[R]
\f[B]{\f[R] \f[B]S\f[R] \f[B];\f[R] \&...
\f[B];\f[R] \f[B]S\f[R] \f[B]}\f[R]
\f[B]if\f[R] \f[B](\f[R] \f[B]E\f[R] \f[B])\f[R] \f[B]S\f[R]
\f[B]if\f[R] \f[B](\f[R] \f[B]E\f[R] \f[B])\f[R] \f[B]S\f[R]
\f[B]else\f[R] \f[B]S\f[R]
\f[B]while\f[R] \f[B](\f[R] \f[B]E\f[R] \f[B])\f[R] \f[B]S\f[R]
\f[B]for\f[R] \f[B](\f[R] \f[B]E\f[R] \f[B];\f[R] \f[B]E\f[R]
\f[B];\f[R] \f[B]E\f[R] \f[B])\f[R] \f[B]S\f[R]
Пустая инструкция
\f[B]break\f[R]
\f[B]continue\f[R]
\f[B]quit\f[R]
\f[B]halt\f[R]
\f[B]limits\f[R]
Строка символов, заключённая в двойные кавычки
\f[B]print\f[R] \f[B]E\f[R] \f[B],\f[R] \&...
\f[B],\f[R] \f[B]E\f[R]
\f[B]stream\f[R] \f[B]E\f[R] \f[B],\f[R] \&...
\f[B],\f[R] \f[B]E\f[R]
\f[B]I()\f[R], \f[B]I(E)\f[R], \f[B]I(E, E)\f[R] и так далее, где
\f[B]I\f[R] — идентификатор \f[B]void\f[R]-функции (см. подраздел
\f[I]Функции void\f[R] раздела \f[B]ФУНКЦИИ\f[R]).
Аргумент(ы) \f[B]E\f[R] также могут быть массивами вида \f[B]I[]\f[R],
которые автоматически превращаются в ссылки на массивы (см. подраздел
\f[I]Ссылки на массивы\f[R] раздела \f[B]ФУНКЦИИ\f[R]), если
соответствующий параметр в определении функции является ссылкой на
массив.
.PP
Числа 4, 9, 11, 12, 14, 15 и 16 являются \f[B]непереносимыми
расширениями\f[R].
.PP
Кроме того, как \f[B]непереносимое расширение\f[R], любые или все
выражения в заголовке цикла for могут быть опущены.
Если условие (второе выражение) опущено, предполагается, что оно равно
константе \f[B]1\f[R].
.PP
Инструкция \f[B]break\f[R] заставляет цикл прекратить итерации и
возобновить выполнение сразу после цикла.
Это допускается только в циклах.
.PP
Инструкция \f[B]continue\f[R] заставляет итерацию цикла остановиться
раньше и возвращает к началу цикла, включая проверку условия цикла.
Это допускается только в циклах.
.PP
Инструкция \f[B]if\f[R] \f[B]else\f[R] делает то же самое, что и в C.
.PP
Инструкция \f[B]quit\f[R] заставляет bc(1) завершиться, даже если она
находится в ветви, которая не будет выполнена (это команда времени
компиляции).
.PP
\f[B]Предупреждение\f[R]: Поведение этого bc(1) при \f[B]quit\f[R]
немного отличается от других реализаций bc(1).
Другие реализации bc(1) завершатся, как только закончат разбор строки,
на которой находится команда \f[B]quit\f[R].
Этот bc(1) выполнит любые завершённые и исполняемые инструкции, которые
находятся перед инструкцией \f[B]quit\f[R], перед завершением.
.PP
Другими словами, для приведённого ниже кода bc(1):
.IP
.EX
for (i = 0; i < 3; ++i) i; quit
.EE
.PP
Другие реализации bc(1) ничего не напечатают, а этот bc(1) напечатает
\f[B]0\f[R], \f[B]1\f[R] и \f[B]2\f[R] на последовательных строках перед
завершением.
.PP
Инструкция \f[B]halt\f[R] заставляет bc(1) завершиться, если она
выполнена.
(В отличие от \f[B]quit\f[R], если она находится в ветви инструкции
\f[B]if\f[R], которая не выполняется, bc(1) не завершается.)
.PP
Инструкция \f[B]limits\f[R] печатает ограничения, которым подвержен этот
bc(1).
Это похоже на инструкцию \f[B]quit\f[R] тем, что это команда времени
компиляции.
.PP
Выражение само по себе вычисляется и печатается, за ним следует перевод
строки.
.PP
Как научная, так и инженерная нотация доступны для печати результатов
выражений.
Научная нотация активируется присваиванием \f[B]0\f[R] переменной
\f[B]obase\f[R], а инженерная нотация активируется присваиванием
\f[B]1\f[R] переменной \f[B]obase\f[R].
Чтобы отключить их, просто присвойте \f[B]obase\f[R] другое значение.
.PP
Научная и инженерная нотация отключаются, если bc(1) запущен с любым из
параметров командной строки \f[B]\-s\f[R] или \f[B]\-w\f[R] (или их
эквивалентами).
.PP
Печать чисел в научной и/или инженерной нотации — это
\f[B]непереносимое расширение\f[R].
.SS Строки
Если строки появляются как инструкция сами по себе, они печатаются без
завершающего перевода строки.
.PP
Помимо появления в виде отдельной инструкции сами по себе, строки можно
присваивать переменным и элементам массивов.
Их также можно передавать функциям в параметрах-переменных.
.PP
Если любой инструкции, ожидающей строку, передаётся переменная, которой
была присвоена строка, инструкция действует так, как если бы получила
строку.
.PP
Если над строкой или переменной или элементом массива, которым была
присвоена строка, предпринимается любая математическая операция,
возникает ошибка, и bc(1) сбрасывается (см. раздел \f[B]СБРОС\f[R]).
.PP
Присваивание строк переменным и
