.\" Licensed under the OpenIB.org BSD license (FreeBSD Variant) - See COPYING.md
.\" FRDP path ./contrib/ofed/libibverbs/man/ibv_devices.1
.\" FRDP githash d6b92ffa990dc57d8a969a98e3ca4e25ba39cbb2
.\" FRDP hash256 6e6b2397342574c8928d482cd62a5217d1f1c8b9c7c414087b815d62acea69a2
.SH ИМЯ
ibv_devices \- список устройств RDMA

.SH СИНТАКСИС
.B ibv_devices

.SH ОПИСАНИЕ
.PP
Выводит список устройств RDMA, доступных для использования из пользовательского пространства.

.SH СМ. ТАКЖЕ
.BR ibv_devinfo (1)

.SH АВТОРЫ
.TP
Roland Dreier
.RI < rolandd@cisco.com >
