.\" FRDP path usr.bin/indent/indent.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 c2bcdf967ab5040f2cedb5fb2201d19ca3d23eabcf6d91d402fccc1b27b47b20
.Dd June 28, 2023
.Dt INDENT 1
.Os
.Sh ИМЯ
.Nm indent
.Nd форматирование и выравнивание исходного кода программ на C
.Sh СИНТАКСИС
.Nm
.Op Ar input-file Op Ar output-file
.Op Fl bacc | Fl nbacc
.Op Fl bad | Fl nbad
.Op Fl badp | Fl nbadp
.Op Fl bap | Fl nbap
.Op Fl bbb | Fl nbbb
.Op Fl \&bc | Fl nbc
.Op Fl \&bl | Fl \&br
.Op Fl bs | Fl nbs
.Op Fl c Ns Ar n
.Op Fl \&cd Ns Ar n
.Bk -words
.Op Fl cdb | Fl ncdb
.Ek
.Op Fl \&ce | Fl nce
.Op Fl \&ci Ns Ar n
.Op Fl cli Ns Ar n
.Op Fl cs | Fl ncs
.Op Fl d Ns Ar n
.Op Fl \&di Ns Ar n
.Op Fl dj | Fl ndj
.Bk -words
.Op Fl ei | Fl nei
.Op Fl eei | Fl neei
.Ek
.Bk -words
.Op Fl fbs | Fl nfbs
.Op Fl fc1 | Fl nfc1
.Op Fl fcb | Fl nfcb
.Ek
.Op Fl i Ns Ar n
.Op Fl \&ip | Fl nip
.Op Fl l Ns Ar n
.Op Fl \&lc Ns Ar n
.Op Fl \&ldi Ns Ar n
.Op Fl \&lp | Fl nlp
.Op Fl \&lpl | Fl nlpl
.Op Fl npro
.Op Fl P Ns Ar file
.Op Fl pcs | Fl npcs
.Op Fl ps | Fl nps
.Op Fl psl | Fl npsl
.Op Fl \&sc | Fl nsc
.Bk -words
.Op Fl sob | Fl nsob
.Ek
.Op Fl \&st
.Op Fl \&ta
.Op Fl T Ns Ar typename
.Op Fl ts Ns Ar n
.Op Fl U Ns Ar file
.Op Fl ut | Fl nut
.Op Fl v | Fl \&nv
.Op Fl -version
.Sh ОПИСАНИЕ
Утилита
.Nm
— это
.Em C
форматтер программ.
Она переформатирует
.Em C
программу в
.Ar input-file
в соответствии с ключами.
Ключи, которые можно
указать, описаны ниже.
Они могут появляться до или после имён
файлов.
.Pp
.Sy ПРИМЕЧАНИЕ :
Если указать только
.Ar input-file ,
форматирование выполняется
«на месте», то есть отформатированный файл записывается обратно в
.Ar input-file ,
а резервная копия
.Ar input-file
записывается в текущем каталоге.
Если
.Ar input-file
называется
.Sq Pa /blah/blah/file ,
резервный файл по умолчанию называется
.Sq Pa file.BAK .
Расширение, используемое для резервного файла, можно переопределить с помощью
переменной окружения
.Ev SIMPLE_BACKUP_SUFFIX .
.Pp
Если указан
.Ar output-file ,
.Nm
проверяет, что он отличается от
.Ar input-file .
.Pp
Перечисленные ниже параметры управляют стилем форматирования, навязываемым
.Nm .
.Bl -tag -width Op
.It Fl bacc , nbacc
Если указан
.Fl bacc ,
пустая строка принудительно вставляется вокруг каждого блока условной
компиляции.
Например, перед каждым #ifdef и после каждого #endif.
Другие пустые строки, окружающие такие блоки, будут удалены.
По умолчанию:
.Fl nbacc .
.It Fl bad , nbad
Если указан
.Fl bad ,
пустая строка принудительно вставляется после каждого блока
объявлений.
По умолчанию:
.Fl nbad .
.It Fl badp , nbadp
Это отдалённо похоже на
.Fl bad ,
за исключением того, что применяется только к первому набору объявлений
в процедуре (сразу после первой `{') и вызывает генерацию пустой
строки, даже если объявлений нет.
По умолчанию
.Fl nbadp .
.It Fl bap , nbap
Если указан
.Fl bap ,
пустая строка принудительно вставляется после каждого тела процедуры.
По умолчанию:
.Fl nbap .
.It Fl bbb , nbbb
Если указан
.Fl bbb ,
пустая строка принудительно вставляется перед каждым блочным комментарием.
По умолчанию:
.Fl nbbb .
.It Fl \&bc , nbc
Если указан
.Fl \&bc ,
то после каждой запятой в объявлении принудительно вставляется символ новой строки.
.Fl nbc
отключает этот параметр.
По умолчанию:
.Fl \&nbc .
.It Fl \&bl , \&br
Указание
.Fl \&bl
выравнивает составные операторы так:
.Bd -literal -offset indent
if (...)
{
  code
}
.Ed
.Pp
Указание
.Fl \&br
(по умолчанию) заставляет их выглядеть так:
.Bd -literal -offset indent
if (...) {
  code
}
.Ed
.It Fl bs , nbs
Следует ли всегда вставлять пробел после sizeof.
По умолчанию
.Fl nbs .
.It Fl c Ns Ar n
Столбец, в котором начинаются комментарии к коду.
По умолчанию 33.
.It Fl cd Ns Ar n
Столбец, в котором начинаются комментарии к объявлениям.
По умолчанию
эти комментарии начинаются в том же столбце, что и комментарии к коду.
.It Fl cdb , ncdb
Включает (отключает) размещение разделителей комментариев на пустых строках.
При
включённом этом параметре комментарии выглядят так:
.Bd -literal -offset indent
	/*
	 * this is a comment
	 */
.Ed
.Pp
А не так:
.Bd -literal -offset indent
	/* this is a comment */
.Ed
.Pp
Это влияет только на блочные комментарии, а не на комментарии справа от
кода.
По умолчанию
.Fl cdb .
.It Fl ce , nce
Включает (отключает) принудительное размещение `else' вплотную к непосредственно предшествующей
`}'.
По умолчанию
.Fl \&ce .
.It Fl \&ci Ns Ar n
Устанавливает отступ продолжения равным
.Ar n .
Строки продолжения
будут иметь отступ настолько от начала первой строки
оператора.
Родительские выражения получают дополнительный отступ, чтобы
указать вложенность, если только не действует
.Fl \&lp
или отступ продолжения не равен ровно половине основного отступа.
.Fl \&ci
по умолчанию имеет то же значение, что и
.Fl i .
.It Fl cli Ns Ar n
Заставляет метки case иметь отступ
.Ar n
табуляций вправо от содержащего
.Ic switch
оператора.
.Fl cli0.5
заставляет метки case иметь отступ в половину табуляции.
По
умолчанию
.Fl cli0 .
.It Fl cs , ncs
Управляет тем, следует ли после имён типов в скобках при приведениях типа ставить пробел или
нет.
По умолчанию
.Fl ncs .
.It Fl d Ns Ar n
Управляет размещением комментариев, которые не находятся
справа от кода.
Например,
.Fl \&d\&1
означает, что такие комментарии размещаются на один уровень отступа
левее кода.
Указание значения по умолчанию
.Fl \&d\&0
выравнивает эти комментарии с кодом.
См. раздел об отступах
комментариев ниже.
.It Fl \&di Ns Ar n
Задаёт отступ в позициях символов
для имён глобальных переменных и всех имён членов struct/union
относительно начала их объявления типа.
По умолчанию
.Fl di16 .
.It Fl dj , ndj
.Fl \&dj
выравнивает объявления по левому краю.
.Fl ndj
делает отступ объявлений так же, как для кода.
По умолчанию
.Fl ndj .
.It Fl \&ei , nei
Включает (отключает) специальную обработку
.Ic else-if .
Если она включена,
.Ic if
после
.Ic else
будет иметь тот же отступ, что и предшествующий
.Ic \&if
оператор.
По умолчанию
.Fl ei .
.It Fl eei , neei
Включает (отключает) дополнительный отступ на строках продолжения
выражения в
.Ic if
и
.Ic while
операторах.
Эти строки продолжения получат отступ на один дополнительный уровень.
По умолчанию
.Fl neei .
.It Fl fbs , nfbs
Включает (отключает) разбиение объявления функции и открывающей скобки
на две строки.
По умолчанию
.Fl fbs .
.It Fl fc1 , nfc1
Включает (отключает) форматирование комментариев, начинающихся в столбце 1.
Часто комментарии, у которых ведущий `/` находится в столбце 1, были тщательно
отформатированы вручную программистом.
В таких случаях
следует использовать
.Fl nfc1 .
По умолчанию
.Fl fc1 .
.It Fl fcb , nfcb
Включает (отключает) форматирование блочных комментариев (тех, что начинаются
с `/*\\n').
Часто блочные комментарии были не очень тщательно отформатированы вручную
программистом, но переформатирование, которое просто изменило бы разрывы строк, не
желательно.
В таких случаях
следует использовать
.Fl nfcb .
Блочные комментарии тогда обрабатываются как комментарии-рамки.
По умолчанию
.Fl fcb .
.It Fl i Ns Ar n
Количество столбцов для одного уровня отступа.
По умолчанию 8.
.It Fl \&ip , nip
Включает (отключает) отступ объявлений параметров от левого
края.
По умолчанию
.Fl \&ip .
.It Fl l Ns Ar n
Максимальная длина выходной строки.
По умолчанию 78.
.It Fl lc Ns Ar n
Максимальная длина выходной строки в блочном комментарии.
По умолчанию 0, что означает ограничение строк блочного комментария в соответствии с
.Fl l .
.It Fl \&ldi Ns Ar n
Задаёт отступ в позициях символов
для имён локальных переменных
относительно начала их объявления типа.
По умолчанию имена локальных переменных имеют отступ
на ту же величину, что и глобальные.
.It Fl \&lp , nlp
Выравнивает код, окружённый круглыми скобками, в строках продолжения.
С
.Fl \&lp ,
если строка
имеет открывающую круглую скобку, не закрытую на этой строке, то строки продолжения
будут выровнены так, чтобы начинаться с позиции символа сразу после открывающей
скобки.
Например, вот как выглядит фрагмент продолженного кода с
.Fl nlp
:
.Bd -literal -offset indent
p1 = first_procedure(second_procedure(p2, p3),
\ \ third_procedure(p4, p5));
.Ed
.Pp
С
.Fl lp
(по умолчанию) код выглядит несколько яснее:
.Bd -literal -offset indent
p1\ =\ first_procedure(second_procedure(p2,\ p3),
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ third_procedure(p4,\ p5));
.Ed
.Pp
Вставив ещё два символа новой строки, получаем:
.Bd -literal -offset indent
p1\ =\ first_procedure(second_procedure(p2,
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ p3),
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ third_procedure(p4,
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ p5));
.Ed
.It Fl \&lpl , nlpl
С
.Fl \&lpl
код, окружённый круглыми скобками, в строках продолжения выравнивается, даже если
он выйдет за правый край.
С
.Fl \&nlpl
(по умолчанию) такая строка, которая вышла бы за правый край, сдвигается
влево, чтобы остаться в пределах края, если это не требует размещения её
левее текущего уровня отступа.
Эти ключи не имеют эффекта, если
выбран
.Fl nlp .
.It Fl npro
Заставляет файлы профиля,
.Sq Pa ./.indent.pro
и
.Sq Pa ~/.indent.pro ,
игнорироваться.
.It Fl P Ns Ar file
Читать профиль из
.Ar file .
.It Fl pcs , npcs
Если истинно
.Pq Fl pcs ,
во всех вызовах процедур между
именем и `(' будет вставлен пробел.
По умолчанию
.Fl npcs .
.It Fl ps , nps
Если истинно
.Pq Fl ps ,
оператор разыменования указателя (`->') обрабатывается как любой другой
бинарный оператор.
По умолчанию
.Fl nps .
.It Fl psl , npsl
Если истинно
.Pq Fl psl ,
имена определяемых процедур размещаются в
столбце 1 — их типы, если есть, остаются на предыдущих строках.
По
умолчанию
.Fl psl .
.It Fl \&sc , nsc
Включает (отключает) размещение звёздочек (`*') у левого края всех
комментариев.
По умолчанию
.Fl sc .
.It Fl sob , nsob
Если указан
.Fl sob ,
indent будет удалять необязательные пустые строки.
Это можно использовать, чтобы
избавиться от пустых строк после объявлений.
По умолчанию:
.Fl nsob .
.It Fl \&st
Заставляет
.Nm
брать ввод из stdin и выдавать вывод в stdout.
.It Fl ta
ключевых слов типа.
.It Fl T Ns Ar typename
Добавляет
.Ar typename
в список ключевых слов типов.
Имена накапливаются:
.Fl T
можно указывать более одного раза.
Вам нужно указать все имена типов, которые
появляются в вашей программе и определены через
.Ic typedef
— ничего не
пострадает, если вы пропустите несколько, но программа не будет отформатирована так хорошо, как
следовало бы.
Это звучит как болезненная необходимость, но на самом деле это
симптом проблемы в C:
.Ic typedef
вызывает синтаксическое изменение в
языке, и
.Nm
не может найти все
случаи
.Ic typedef .
.It Fl ts Ns Ar n
Предполагаемое расстояние между позициями табуляции.
По умолчанию 8.
.It Fl U Ns Ar file
Добавляет имена типов из
.Ar file
в список ключевых слов типов.
.It Fl ut , nut
Включает (отключает) использование символов табуляции в выводе.
По умолчанию
.Fl ut .
.It Fl v , \&nv
.Fl v
включает «подробный» режим;
.Fl \&nv
выключает его.
В подробном режиме
.Nm
сообщает, когда разбивает одну строку ввода на две или более строк вывода,
и выдаёт некоторую статистику размера по завершении.
По умолчанию
.Fl \&nv .
.It Fl -version
Заставляет
.Nm
вывести номер версии и выйти.
.El
.Pp
Вы можете настроить собственный «профиль» значений по умолчанию для
.Nm
, создав файл с именем
.Pa .indent.pro
в вашем домашнем каталоге и/или текущем каталоге и включив
в него любые желаемые ключи.
`.indent.pro' в текущем каталоге имеет
приоритет над файлом в вашем домашнем каталоге.
Если
.Nm
запускается и файл профиля существует, то он читается для установки
значений по умолчанию программы.
Однако ключи в командной строке всегда переопределяют ключи
профиля.
Ключи должны быть разделены пробелами, табуляциями или символами новой строки.
.Pp
.Ss Комментарии
.Sq Em Рамки
.Em комментариев .
Утилита
.Nm
предполагает, что любой комментарий с тире или звёздочкой сразу после начала
комментария (то есть `/*\-' или `/**') — это комментарий, окружённый рамкой из звёздочек.
Каждая строка такого комментария остаётся неизменной, за исключением того, что её отступ
может быть скорректирован с учётом изменения отступа первой строки
комментария.
.Pp
.Em Обычный текст .
Все остальные комментарии обрабатываются как обычный текст.
Утилита
.Nm
размещает как можно больше слов (разделённых пробелами, табуляциями или символами новой строки) на
строке.
Пустые строки разделяют абзацы.
.Ss Отступ комментариев
Если комментарий находится на строке с кодом, он начинается в «столбце комментариев»,
который задаётся параметром командной строки
.Fl c Ns Ns Ar n .
В противном случае комментарий начинается на
.Ar n
уровней отступа левее того места, где в данный момент размещается код, где
.Ar n
задаётся параметром командной строки
.Fl d Ns Ns Ar n .
Если код на строке выходит за столбец комментариев,
комментарий начинается дальше вправо, и правый край может быть
автоматически расширен в крайних случаях.
.Ss Строки препроцессора
В общем,
.Nm
оставляет строки препроцессора в покое.
Единственное
переформатирование, которое она выполняет, — выравнивание завершающих комментариев.
Встроенные комментарии она оставляет в покое.
Условная компиляция
.Pq Ic #ifdef...#endif
распознаётся, и
.Nm
пытается правильно
компенсировать введённые синтаксические особенности.
.Ss Синтаксис C
Утилита
.Nm
понимает значительную часть синтаксиса C, но у неё
«снисходительный» парсер.
Она пытается справляться с обычными видами
неполного и неправильно сформированного синтаксиса.
В частности, использование макросов вроде:
.Pp
.Dl #define forever for(;;)
.Pp
обрабатывается правильно.
.Sh ОКРУЖЕНИЕ
Утилита
.Nm
использует
переменную окружения
.Ev HOME .
.Sh ФАЙЛЫ
.It Pa ./.indent.pro
файл профиля
.It Pa ~/.indent.pro
файл профиля
.El
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Bx 4.2 .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
У утилиты
.Nm
даже больше ключей, чем у
.Xr ls 1 .
.Pp
Распространённая ошибка — попытаться отформатировать все
.Em C
программы в каталоге, набрав:
.Pp
.Dl indent *.c
.Pp
Вероятно, это ошибка, а не особенность.
