.\" FRDP path usr.bin/kdump/kdump.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 1d345e0b173b03cc69d9151c5c9cd5b0bc4f92d064ef4bdf88544ca21a57aff0
.Dd July 16, 2022
.Dt KDUMP 1
.Os
.Sh ИМЯ
.Nm kdump
.Nd отображение данных трассировки ядра
.Sh СИНТАКСИС
.Nm
.Op Fl dEnlHRSsTA
.Op Fl f Ar trfile
.Op Fl m Ar maxdata
.Op Fl p Ar pid
.Op Fl t Ar trstr
.Sh ОПИСАНИЕ
Команда
.Nm
отображает файлы трассировки ядра, созданные с помощью
.Xr ktrace 1 ,
в удобочитаемом формате.
По умолчанию отображается файл
.Pa ktrace.out
в текущем каталоге.
.Pp
Параметры следующие:
.Bl -tag -width Fl
.It Fl A
Отображать ABI трассируемого процесса.
.It Fl c
Отображать номер CPU с каждой записью трассировки.
.It Fl d
Отображать все числа в десятичном виде.
.It Fl E
Отображать прошедшие временные метки (время с начала трассировки).
.It Fl f Ar trfile
Отображать указанный файл вместо
.Pa ktrace.out .
.It Fl H
Выводить идентификатор потока (tid) потока с каждой записью трассировки, если он доступен.
Если идентификатор потока недоступен, будет выведено 0.
.It Fl l
Циклически читать файл трассировки, достигнув конца файла, ожидая
дополнительных данных.
.It Fl m Ar maxdata
Отображать не более
.Ar maxdata
байт при декодировании
.Tn I/O .
.It Fl n
Подавлять специальные переводы.
Обычно
.Nm
пытается декодировать многие системные вызовы в более удобочитаемый формат.
Например,
значения
.Xr ioctl 2
заменяются именем макроса, а
значения
.Va errno
заменяются строкой
.Xr strerror 3 .
Подавление этой возможности даёт более согласованный формат вывода и
легко поддаётся дальнейшей обработке.
.It Fl p Ar pid
Отображать только события трассировки, соответствующие процессу или потоку
.Ar pid .
Это может быть полезно, когда в одном файле трассировки записано несколько процессов или потоков.
.It Fl R
Отображать относительные временные метки (время с предыдущей записи).
.It Fl r
При декодировании записей STRU отображать элементы структуры, такие как UID,
GID, даты и т. д., символически, а не численно.
.It Fl S
Отображать номера системных вызовов.
.It Fl s
Подавлять отображение данных I/O.
.It Fl T
Отображать абсолютные временные метки для каждой записи (секунды с начала эпохи).
.It Fl t Ar trstr
См.
параметр
.Fl t
команды
.Xr ktrace 1 .
.El
.Pp
Формат вывода
.Nm
ориентирован на строки с несколькими полями.
В приведённом ниже примере показан фрагмент kdump, сгенерированный следующими
командами:
.Bd -literal -offset indent

?> kdump

 85045 echo     CALL  writev(0x1,0x804b030,0x2)
 85045 echo     GIO   fd 1 wrote 7 bytes
 85045 echo     RET   writev 7
.Ed
.Pp
Первое поле — PID трассируемого процесса.
Второе поле — имя трассируемой программы.
Третье поле — операция, которую ядро выполнило
от имени процесса.
Если выводятся идентификаторы потоков, то между полем PID и полем имени программы
будет добавлен дополнительный столбец идентификатора потока.
.Pp
В первой строке выше ядро выполняет
системный вызов
.Xr writev 2
от имени процесса, поэтому это операция
.Li CALL .
Четвёртое поле показывает выполненный системный вызов,
включая его аргументы.
Системный вызов
.Xr writev 2
принимает файловый дескриптор, в данном случае 1, или стандартный
вывод, затем указатель на iovector для записи и количество
iovector, которые должны быть записаны.
Во второй строке мы видим, что операция была
.Li GIO ,
для общего I/O, и что в файловый дескриптор 1 было
записано семь байт.
Далее следуют семь записанных байт — строка
.Qq Li ktrace
с символом возврата каретки и перевода строки.
Последняя строка — операция
.Li RET ,
показывающая возврат из ядра, из какого системного вызова мы
возвращаемся, и значение, которое получил процесс.
Системный вызов
.Xr writev 2
записал семь байт, поэтому 7 — это возвращаемое значение.
.Pp
Возможные операции:
.It Sy Имя Ta Sy Операция Ta Sy Четвёртое поле
.It Li CALL Ta вход в системный вызов Ta имя системного вызова и аргументы
.It Li RET Ta возврат из системного вызова Ta имя системного вызова и возвращаемое значение
.It Li NAMI Ta поиск имени файла Ta путь к файлу
.It Li GIO Ta общий I/O Ta fd, чтение/запись, количество байт
.It Li PSIG Ta сигнал Ta имя сигнала, обработчик, маска, код
.It Li CSW Ta переключение контекста Ta stop/resume user/kernel wmesg
.It Li USER Ta данные из пользовательского процесса Ta данные
.It Li STRU Ta различные системные вызовы Ta структура
.It Li SCTL Ta запросы
.Xr sysctl 3 Ta
имя MIB
.It Li PFLT Ta вход в страничную ошибку Ta адрес и тип ошибки
.It Li PRET Ta возврат из страничной ошибки Ta результат ошибки
.El
.Sh СМ. ТАКЖЕ
.Xr ktrace 1
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Bx 4.4 .
