.\" FRDP path bin/kenv/kenv.1
.\" FRDP githash 4fd518fcb2bbee4c8c41215d6993b923ef57a0e5
.\" FRDP hash256 7ad9870dc86718735906d82d9794f1eb6e7ba029b8bab1f4902ceab1a3b4938a
.Dd June 22, 2026
.Dt KENV 1
.Os
.Sh ИМЯ
.Nm kenv
.Nd "вывести список или изменить окружение ядра"
.Sh СИНТАКСИС
.Nm
.Op Fl l | s
.Op Fl hNq
.Nm
.Op Fl qv
.Ar переменная Ns Op = Ns Ar значение
.Nm
.Op Fl q
.Fl u
.Ar переменная
.Sh ОПИСАНИЕ
Утилита
.Nm
выводит список всех переменных в окружении ядра, если
запущена без аргументов.
.Pp
Если
.Fl l
указан, то вместо этого будет выведено статическое окружение,
предоставляемое
.Xr loader 8 .
Аналогично, параметр
.Fl s
выведет статическое окружение, определённое в конфигурации ядра.
Оба параметра
.Fl l
и
.Fl s
зависят от того, сконфигурировано ли ядро для сохранения ранних
окружений ядра.
Конфигурация ядра по умолчанию не сохраняет эти окружения.
.Pp
Если указан параметр
.Fl h ,
вывод будет ограничен подсказками зондирования ядра.
Если указано необязательное имя
.Ar переменной ,
.Nm
выведет только это значение.
Если указан параметр
.Fl N ,
.Nm
выведет только имена переменных, а не их значения.
Если указан параметр
.Fl u ,
.Nm
удалит указанную переменную окружения.
Если после переменной окружения указано необязательное
.Ar значение ,
.Nm
установит переменную окружения в это значение.
.Pp
Если параметр
.Fl q
установлен, предупреждения, обычно выводимые в результате
невозможности выполнить запрошенную операцию, подавляются.
.Pp
Если параметр
.Fl v
установлен, при запуске
.Nm
с именем переменной будет выведено имя переменной окружения
в дополнение к значению.
.Pp
Переменные можно добавлять в окружение ядра с помощью файла
.Pa /boot/loader.conf ,
или также статически компилировать в ядро с помощью выражения
.Pp
.Dl Ic env Ar имя_файла
.Pp
в файле конфигурации ядра.
Файл может содержать строки вида
.Pp
.Pp
где пробельные символы вокруг
.Sq name
и
.Sq = ,
а также всё после символа
.Sq #
игнорируются.
Почти любой печатный символ, кроме
.Sq = ,
допустим в составе имени.
Кавычки необязательны и необходимы только если значение содержит
пробельные символы.
.Sh ПРИМЕРЫ
Показать имена переменных подсказок зондирования ядра и отфильтровать
по устройству uart
.Bd -literal -offset indent
$ kenv -h -N | grep uart
hint.uart.0.at
hint.uart.0.flags
hint.uart.0.irq
hint.uart.0.port
hint.uart.1.at
hint.uart.1.irq
hint.uart.1.port
.Ed
.Pp
Показать значение конкретной переменной:
.Bd -literal -offset indent
$ kenv hint.uart.1.at
isa
.Ed
.Pp
То же, что выше, но с добавлением имени переменной в вывод:
.Bd -literal -offset indent
$ kenv -v hint.uart.1.at
.Ed
.Pp
Попытаться удалить переменную и подавить предупреждения, если они есть:
.Bd -literal -offset indent
$ kenv -q -u hint.uart.1.at
.Ed
.Pp
Установить значение переменной
.Ev verbose_loading
.Bd -literal -offset indent
.Ed
.Sh СМ. ТАКЖЕ
.Xr kenv 2 ,
.Xr config 5 ,
.Xr loader.conf 5 ,
.Xr loader 8
.Sh ИСТОРИЯ
Утилита
.Nm
появилась в
.Fx 4.1.1 .
.Sh ВОПРОСЫ БЕЗОПАСНОСТИ
Обратите внимание, что непривилегированным пользователям разрешено
читать из окружения ядра, если только системный параметр
.Va security.bsd.unprivileged_kenv_read
не установлен в 0.
Это включает как вывод списка окружения ядра, так и получение
конкретной
.Va переменной
из окружения.
