.\" FRDP path contrib/llvm-project/lld/docs/ld.lld.1
.\" FRDP githash 700637cbb5e582861067a11aaca4d053546871d2
.\" FRDP hash256 681677661186b6014d29a849774eeb90924ce140259ad232fd9e33ca507f1227
.Dd Jul 25, 2023
.Dt LD.LLD 1
.Os
.Sh ИМЯ
.Nm ld.lld
.Nd компоновщик ELF из проекта LLVM
.Sh СИНТАКСИС
.Nm ld.lld
.Op Ar параметры
.Ar объектный_файл ...
.Sh ОПИСАНИЕ
Компоновщик принимает один или несколько объектных файлов, архивов и файлов библиотек и объединяет
их в выходной файл (исполняемый файл, разделяемую библиотеку или другой объектный
файл).
Он перемещает код и данные из входных файлов и разрешает ссылки на символы
между ними.
.Pp
.Nm
является заменой без изменений для компоновщиков GNU BFD и gold.
Он принимает большинство тех же аргументов командной строки и сценариев компоновщика,
что и компоновщики GNU.
.Pp
.Nm
в настоящее время поддерживает целевые архитектуры i386, x86-64, ARM, AArch64, LoongArch, PowerPC32,
PowerPC64, MIPS32, MIPS64, RISC-V, AMDGPU, Hexagon и SPARC V9.
.Nm
действует как компоновщик, совместимый с Microsoft link.exe, если вызывается как
.Nm lld-link
и как ld в macOS, если вызывается как
.Nm ld.ld64.
Все эти целевые архитектуры всегда поддерживаются независимо от того, как
.Nm
был собран, поэтому вы всегда можете использовать
.Nm
как нативный компоновщик, так и кросс-компоновщик.
.Sh ОПЦИИ
Многие опции имеют однобуквенную и длинную форму.
При использовании длинных форм опций, кроме тех, что начинаются с буквы
.Cm o
можно указывать один или два дефиса перед именем опции.
Длинные опции, начинающиеся с
.Cm o
требуют двух дефисов, чтобы избежать путаницы с опцией
.Fl o Ar путь
.
.Pp
.Bl -tag -width indent
.It Fl -allow-multiple-definition
Не выдавать ошибку, если символ определён несколько раз.
Будет использовано первое определение.
.It Fl -allow-shlib-undefined
Разрешить неразрешённые ссылки в разделяемых библиотеках.
Эта опция включена по умолчанию при компоновке разделяемой библиотеки.
.It Fl -apply-dynamic-relocs
Применить значения времени компоновки для динамических перемещений.
.It Fl -as-needed
Устанавливать
.Dv DT_NEEDED
для разделяемых библиотек только если они используются.
.It Fl -auxiliary Ns = Ns Ar значение
Установить поле
.Dv DT_AUXILIARY
в указанное имя.
.It Fl -Bdynamic , Fl -dy
Компоновать с разделяемыми библиотеками.
.It Fl -Bstatic , Fl -static , Fl -dn
Не компоновать с разделяемыми библиотеками.
.It Fl Bno-symbolic
Не связывать локально определённые символы с видимостью по умолчанию для
.Fl shared
(по умолчанию).
.It Fl Bsymbolic
Связывать локально определённые символы с видимостью по умолчанию для
.Fl shared.
Также установить флаг
.Dv DF_SYMBOLIC
.
.It Fl Bsymbolic-non-weak
Связывать локально определённые символы STB_GLOBAL с видимостью по умолчанию для
.Fl shared.
.It Fl Bsymbolic-functions
Связывать локально определённые символы функций с видимостью по умолчанию для
.Fl shared.
.It Fl Bsymbolic-non-weak-functions
Связывать локально определённые символы функций STB_GLOBAL с видимостью по умолчанию для
.Fl shared.
.It Fl -be8
Записать файл ELF с Big Endian, используя формат BE8 (только AArch32)
.It Fl -branch-to-branch
Включить оптимизации branch-to-branch: ветвление, целью которого является
другая инструкция ветвления, перезаписывается так, чтобы указывать на цель
последнего ветвления (только AArch64 и X86_64). Включено по умолчанию при
.Fl O2 Ns .
.It Fl -build-id Ns = Ns Ar значение
Сгенерировать примечание build ID.
.Ar значение
может быть одним из
.Cm fast ,
.Cm md5 ,
.Cm sha1 ,
.Cm tree ,
.Cm uuid ,
.Cm 0x Ns Ar hex-string ,
и
.Cm none .
.Cm tree
является синонимом
.Cm sha1 .
Build-ID типов
.Cm fast ,
.Cm md5 ,
.Cm sha1 ,
и
.Cm tree
вычисляются из содержимого объектов.
.Cm fast
не предназначен для криптографической стойкости.
.It Fl -build-id
Синоним для
.Fl -build-id Ns = Ns Cm sha1 .
.It Fl -call-graph-profile-sort Ns = Ns Ar алгоритм
.Ar алгоритм
может быть:
.Pp
.Bl -tag -width 2n -compact
.It Cm none
Игнорировать профиль графа вызовов.
.It Cm hfsort
Использовать hfsort.
.It Cm cdsort
Использовать cdsort (по умолчанию).
.El
.Pp
.It Fl -color-diagnostics Ns = Ns Ar значение
Использовать цвета в диагностике.
.Ar значение
может быть одним из
.Cm always ,
.Cm auto ,
и
.Cm never .
.Cm auto
включает цвет тогда и только тогда, когда вывод идёт на терминал.
.It Fl -color-diagnostics
Псевдоним для
.Fl -color-diagnostics Ns = Ns Cm auto .
.It Fl -compress-debug-sections Ns = Ns Ar значение
Сжимать отладочные секции DWARF.
Секции остаются несжатыми, если сжатое содержимое оказалось бы больше.
.Cm значение
может быть
.Pp
.Bl -tag -width 2n -compact
.It Cm none
Без сжатия.
.It Cm zlib
Уровень сжатия по умолчанию — 1 (самый быстрый), так как отладочная информация обычно хорошо сжимается на этом уровне.
.It Cm zstd
Использовать уровень сжатия по умолчанию в zstd.
.El
.Pp
.It Fl -compress-sections Ns = Ns Ar section-glob={none,zlib,zstd}[:level]
Сжимать выходные секции, соответствующие glob-шаблону и не имеющие флага SHF_ALLOC.
Совпавшие секции остаются несжатыми, если сжатое содержимое оказалось бы больше.
Уровень сжатия —
.Cm уровень
(если указан) или уровень по умолчанию с ориентацией на скорость.
Это похоже на обобщённую опцию
.Cm --compress-debug-sections.
.It Fl -cref
Выводить таблицу перекрёстных ссылок. Если
.Fl Map
указана, выводить в файл карты.
.It Fl -debug-names
Генерировать объединённую секцию
.Li .debug_names
.
.It Fl -default-script Ns = Ns Ar файл , Fl dT Ar файл
При отсутствии
.Fl -script ,
читать этот сценарий компоновщика по умолчанию.
.It Fl -defsym Ns = Ns Ar символ Ns = Ns Ar выражение
Определить псевдоним символа.
.Ar выражение
может быть другим символом или выражением сценария компоновщика.
Например,
.Ql --defsym=foo=bar
или
.Ql --defsym=foo=bar+0x100 .
.It Fl -demangle
Деманглить имена символов.
.It Fl -disable-new-dtags
Отключить новые динамические теги.
.It Fl -discard-all , Fl x
Удалить все локальные символы.
.It Fl -discard-locals , Fl X
Удалить временные локальные символы.
.It Fl -discard-none
Сохранить все символы в таблице символов.
.It Fl -dynamic-linker Ns = Ns Ar значение
Указать динамический компоновщик, который будет использоваться для динамически
компонуемого исполняемого файла.
Это записывается в сегмент ELF типа
.Dv PT_INTERP .
.It Fl -dynamic-list Ns = Ns Ar файл
Аналогично
.Cm --export-dynamic-symbol-list .
При создании разделяемого объекта подразумевает
.Cm -Bsymbolic
но не устанавливает DF_SYMBOLIC
.It Fl -EB
Выбрать формат Big Endian в команде OUTPUT_FORMAT.
.It Fl -EL
Выбрать формат Little Endian в команде OUTPUT_FORMAT.
.It Fl -eh-frame-hdr
Запросить создание секции
.Li .eh_frame_hdr
и заголовка сегмента
.Dv PT_GNU_EH_FRAME .
.It Fl -emit-relocs , Fl q
Генерировать перемещения в выходном файле.
.It Fl -enable-new-dtags
Включить новые динамические теги.
.It Fl -enable-non-contiguous-regions
Вытеснять входные секции в последующие подходящие выходные секции, чтобы избежать переполнения области памяти.
.It Fl -end-lib
Завершить группировку объектов, которые должны обрабатываться так, как если бы они были вместе
в архиве.
.It Fl -entry Ns = Ns Ar entry
Имя символа точки входа.
.It Fl -error-limit Ns = Ns Ar значение
Максимальное число ошибок, выводимых перед остановкой.
Значение ноль означает отсутствие ограничения.
.It Fl -error-unresolved-symbols
Сообщать о неразрешённых символах как об ошибках.
.It Fl -error-handing-script Ns = Ns Ar script_path
Вызывать сценарий
.Ar script_path
при некоторой ошибке, с
.Ar tag
в качестве первого аргумента и дополнительным параметром в качестве второго аргумента. Ожидается, что сценарий
вернёт 0 при успехе. Любое другое значение считается общей ошибкой.
.Ar tag
может быть
.Cm missing-lib
с последующим именем отсутствующей библиотеки.
.Cm undefined-symbol
с последующим именем неопределённого символа.
.It Fl -execute-only
Пометить исполняемые секции как нечитаемые.
Эта опция в настоящее время поддерживается только на AArch64.
.It Fl -exclude-libs Ns = Ns Ar значение
Исключить статические библиотеки из автоматического экспорта.
.It Fl -export-dynamic , Fl E
Поместить символы в таблицу динамических символов.
.It Fl -export-dynamic-symbol Ns = Ns Ar glob
(исполняемый файл) Поместить совпавшие нелокальные определённые символы в таблицу динамических символов.
(разделяемый объект) Ссылки на совпавшие нелокальные символы STV_DEFAULT не должны привязываться к определениям внутри разделяемого объекта, даже если иначе они были бы привязаны из-за
.Cm -Bsymbolic
,
.Cm -Bsymbolic-functions
или
.Cm --dynamic-list
.It Fl -export-dynamic-symbol-list Ns = Ns Ar файл
Прочитать список шаблонов динамических символов из
.Ar файл .
Применить
.Cm --export-dynamic-symbol
к каждому шаблону.
.It Fl -fatal-warnings
Считать предупреждения ошибками.
.It Fl -filter Ns = Ns Ar значение , Fl F Ar значение
Установить поле
.Dv DT_FILTER
в указанное значение.
.It Fl -fini Ns = Ns Ar символ
Указать функцию финализатора.
.It Fl -force-group-allocation
Имеет смысл только для -r. Группы секций отбрасываются. Если два члена группы секций размещены в одной выходной секции, также объединить их перемещения.
.It Fl -format Ns = Ns Ar input-format , Fl b Ar input-format
Указать формат входных файлов, следующих за этой опцией.
.Ar input-format
может быть одним из
.Cm binary ,
.Cm elf ,
и
.Cm default .
.Cm default
является синонимом
.Cm elf .
.It Fl -gc-sections
Включить сборку мусора неиспользуемых секций.
.It Fl -gdb-index
Генерировать секцию
.Li .gdb_index
.
.It Fl -hash-style Ns = Ns Ar значение
Указать стиль хеша.
.Ar значение
может быть
.Cm sysv ,
.Cm gnu ,
или
.Cm both .
.Cm both
является значением по умолчанию.
.It Fl -help
Вывести справочное сообщение.
.It Fl -icf Ns = Ns Cm all
Включить сворачивание идентичного кода.
.It Fl -icf Ns = Ns Cm safe
Включить безопасное сворачивание идентичного кода.
.It Fl -icf Ns = Ns Cm none
Отключить сворачивание идентичного кода.
.It Fl -ignore-data-address-equality
Игнорировать равенство адресов данных. C/C++ требует, чтобы каждые данные имели уникальный
адрес.
Эта опция позволяет lld выполнять небезопасную оптимизацию, нарушающую это
требование: создавать копии данных только для чтения или объединять два или более фрагментов данных только для чтения,
которые случайно имеют одинаковое значение.
.It Fl -ignore-function-address-equality
Игнорировать равенство адресов функций.
Эта опция разрешает вызовы не-PIC функции с видимостью, отличной от стандартной, в
разделяемом объекте.
Функция может иметь разные адреса внутри исполняемого файла и внутри
разделяемого объекта.
.It Fl -image-base Ns = Ns Ar значение
Установить базовый адрес в
.Ar значение .
.It Fl -init Ns = Ns Ar символ
Указать функцию инициализатора.
.It Fl -keep-unique Ns = Ns Ar символ
Не сворачивать
.Ar символ
во время ICF.
.It Fl l Ar libName, Fl -library Ns = Ns Ar libName
Корневое имя используемой библиотеки.
.It Fl L Ar dir , Fl -library-path Ns = Ns Ar dir
Добавить каталог в путь поиска библиотек.
.It Fl -lto-aa-pipeline Ns = Ns Ar значение
Конвейер AA для запуска во время LTO.
Используется вместе с
.Fl -lto-newpm-passes .
.It Fl -lto-newpm-passes Ns = Ns Ar значение
Проходы для запуска во время LTO.
.It Fl -lto-O Ns Ar opt-level
Уровень оптимизации для LTO.
.It Fl -lto-partitions Ns = Ns Ar значение
Число разделов генерации кода LTO.
.It Fl m Ar значение
Установить целевую эмуляцию.
.It Fl -Map Ns = Ns Ar файл , Fl M Ar файл
Вывести карту компоновки в
.Ar файл .
.It Fl -nmagic , Fl n
Не выравнивать секции по страницам, компоновать со статическими библиотеками.
.It Fl -no-allow-shlib-undefined
Не разрешать неразрешённые ссылки в разделяемых библиотеках.
Эта опция включена по умолчанию при компоновке исполняемого файла.
.It Fl -no-as-needed
Всегда устанавливать
.Dv DT_NEEDED
для разделяемых библиотек.
.It Fl -no-color-diagnostics
Не использовать цвета в диагностике.
.It Fl -no-demangle
Не деманглить имена символов.
.It Fl -no-dynamic-linker
Запретить вывод секции
.Li .interp
.
.It Fl -no-fortran-common
Не искать в членах архива определения для переопределения COMMON-символов.
.It Fl -no-gc-sections
Отключить сборку мусора неиспользуемых секций.
.It Fl -no-gnu-unique
Отключить привязку символов STB_GNU_UNIQUE.
.It Fl -no-merge-exidx-entries
Отключить объединение записей .ARM.exidx.
.It Fl -no-nmagic
Выравнивать секции по страницам.
.It Fl -no-omagic
Не делать секции текста и данных записываемыми, выравнивать секции по страницам.
.It Fl -no-relax
Отключить целевые релаксации. Для x86-64 это отключает оптимизацию GOT R_X86_64_GOTPCRELX и R_X86_64_REX_GOTPCRELX.
.It Fl -no-rosegment
Не помещать неисполняемые секции только для чтения в отдельный сегмент.
.It Fl -undefined-version
Не сообщать о version scripts, ссылающихся на неопределённые символы.
.It Fl -no-undefined
Сообщать о неразрешённых символах, даже если компоновщик создаёт разделяемую библиотеку.
.It Fl -no-warn-mismatch
Не отклонять неизвестные типы секций.
.It Fl -no-warn-symbol-ordering
Не предупреждать о проблемах с файлом порядка символов или профилем графа вызовов.
.It Fl -no-warnings , Fl w
Подавить предупреждения и отменить
.Cm --fatal-warnings.
.It Fl -no-whole-archive
Восстанавливает поведение по умолчанию для загрузки членов архива.
.It Fl -no-pie , Fl -no-pic-executable
Не создавать позиционно-независимый исполняемый файл.
.It Fl -noinhibit-exec
Сохранять выходной исполняемый файл, когда он всё ещё пригоден для использования.
.It Fl -nostdlib
Искать только в каталогах, указанных в командной строке.
.It Fl o Ar путь
Записать выходной исполняемый файл, библиотеку или объект в
.Ar путь .
Если не указано,
.Dv a.out
используется по умолчанию.
.It Fl O Ns Ar значение
Оптимизировать выходной файл.
.Ar значение
может быть:
.Pp
.Bl -tag -width 2n -compact
.It Cm 0
Отключить объединение строк.
.It Cm 1
Включить объединение строк.
.It Cm 2
Включить объединение хвостов строк и оптимизацию branch-to-branch.
.El
.Pp
.Fl O Ns Cm 1
является значением по умолчанию.
.It Fl -oformat Ns = Ns Ar формат
Указать формат выходного объектного файла.
Единственный поддерживаемый
.Ar формат
—
.Cm binary ,
который создаёт вывод без заголовка ELF.
.It Fl -omagic , Fl N
Сделать секции текста и данных читаемыми и записываемыми, не выравнивать секции
по страницам, компоновать со статическими библиотеками.
.It Fl -opt-remarks-filename Ar файл
Записать замечания по оптимизации в формате YAML в
.Ar файл .
.It Fl -opt-remarks-passes Ar pass-regex
Фильтровать замечания по оптимизации, разрешая только проходы, соответствующие
.Ar pass-regex .
.It Fl -opt-remarks-with-hotness
Включить информацию о горячности в файл замечаний по оптимизации.
.It Fl -orphan-handling Ns = Ns Ar режим
Управлять обработкой осиротевших секций.
Осиротевшая секция — это секция, явно не упомянутая в сценарии компоновщика.
.Ar режим
может быть:
.Pp
.Bl -tag -width 2n -compact
.It Cm place
Помещать осиротевшие секции в подходящие выходные секции.
.It Cm warn
Помещать осиротевшие секции как для
.Cm place
и также выводить предупреждение.
.It Cm error
Помещать осиротевшие секции как для
.Cm place
и также выводить ошибку.
.El
.Pp
.Cm place
является значением по умолчанию.
.It Fl -pack-dyn-relocs Ns = Ns Ar формат
Упаковать динамические перемещения в заданном формате.
.Ar формат
может быть:
.Pp
.Bl -tag -width 2n -compact
.It Cm none
Не упаковывать.
Динамические перемещения кодируются в SHT_REL(A).
.It Cm android
Упаковать динамические перемещения в SHT_ANDROID_REL(A).
.It Cm relr
Упаковать относительные перемещения в SHT_RELR, а остальные динамические перемещения в
SHT_REL(A).
.It Cm android+relr
Упаковать относительные перемещения в SHT_RELR, а остальные динамические перемещения в
SHT_ANDROID_REL(A).
.El
.Pp
.Cm none
является значением по умолчанию.
Если
.Fl -use-android-relr-tags
указана, использовать SHT_ANDROID_RELR вместо SHT_RELR.
.Pp
.It Fl -package-metadata
Вывести строку в процентном кодировании в секцию
.Cm .note.package
\&. Например, %25 декодируется в один %.
.It Fl -pic-veneer
Всегда генерировать позиционно-независимые thunks.
.It Fl -pie , Fl -pic-executable
Создать позиционно-независимый исполняемый файл.
.It Fl -power10-stubs Ns = Ns Cm mode
Использовать ли инструкции Power10 в заглушках вызовов для R_PPC64_REL24_NOTOC и взаимодействия TOC/NOTOC.
.Ar режим
может быть:
.Pp
.Bl -tag -width 2n -compact
.It Cm yes
(по умолчанию) Использовать.
.It Cm auto
В настоящее время то же, что yes.
.It Cm no
Не использовать.
.El

.It Fl -print-gc-sections
Перечислить удалённые неиспользуемые секции.
.It Fl -print-icf-sections
Перечислить идентичные свёрнутые секции.
.It Fl -print-map
Вывести карту компоновки на стандартный вывод.
.It Fl -print-archive-stats Ns = Ns Ar файл
Записать статистику использования архивов в указанный файл.
Вывести число членов и извлечённых членов для каждого архива.
.It Fl -push-state
Сохранить текущее состояние
.Fl -as-needed ,
.Fl -static ,
и
.Fl -whole-archive.
.It Fl -pop-state
Восстановить состояния, сохранённые
.Fl -push-state.
.It Fl -randomize-section-padding Ns = Ns Ar зерно
Случайно вставлять заполнение между входными секциями и в начале каждого сегмента, используя заданное зерно.
Заполнение вставляется в выходные секции с именами, соответствующими следующим шаблонам:
.Cm .bss ,
.Cm .data ,
.Cm .data.rel.ro ,
.Cm .lbss ,
.Cm .ldata ,
.Cm .lrodata ,
.Cm .ltext ,
.Cm .rodata
и
.Cm .text* .
.It Fl --relax-gp
Включить релаксацию глобального указателя для RISC-V.
.It Fl -relocatable , Fl r
Создать перемещаемый объектный файл.
.It Fl -remap-inputs Ns = Ns Ar from-glob=to-file
Входные файлы, соответствующие
.Cm from-glob
сопоставляются с
.Cm to-file.
Используйте
.Cm /dev/null
чтобы игнорировать входной файл.
.It Fl -remap-inputs-file Ns = Ns Ar файл
Переназначить входные файлы на основе шаблонов в
.Ar файл .
Каждая строка в файле переназначения имеет формат
.Cm from-glob=to-file
или является комментарием, начинающимся с
.Cm # .
.It Fl -reproduce Ns = Ns Ar путь
Записать tar-файл в
.Ar путь ,
содержащий все входные файлы, необходимые для воспроизведения компоновки, текстовый файл с именем
response.txt, содержащий опции командной строки, и текстовый файл с именем
version.txt, содержащий вывод ld.lld --version.
Архив после
распаковки можно использовать для повторного запуска компоновщика с теми же опциями и входными файлами.
.It Fl -retain-symbols-file Ns = Ns Ar файл
Сохранить только символы, перечисленные в файле.
.It Fl -rpath Ns = Ns Ar значение , Fl R Ar значение
Добавить
.Dv DT_RUNPATH
в вывод.
.It Fl -rsp-quoting Ns = Ns Ar значение
Стиль кавычек для файлов ответов.
Поддерживаемые значения:
.Cm windows
и
.Cm posix .
.It Fl -script Ns = Ns Ar файл , Fl T Ar файл
Читать сценарий компоновщика из
.Ar файл .
Если задано несколько сценариев компоновщика, они обрабатываются так, как если бы
были объединены в порядке их появления в командной строке.
.It Fl -section-start Ns = Ns Ar секция Ns = Ns Ar адрес
Установить адрес секции.
.It Fl -shared , Fl -Bsharable
Собрать разделяемый объект.
.It Fl -shuffle-sections Ns = Ns Ar зерно
Перемешать совпавшие секции, используя заданное зерно, перед отображением их в выходные секции.
Если -1, обратить порядок секций. Если 0, использовать случайное зерно.
.It Fl -soname Ns = Ns Ar значение , Fl h Ar значение
Установить
.Dv DT_SONAME
в
.Ar значение .
.It Fl -sort-common
Эта опция игнорируется для совместимости с GNU.
.It Fl -sort-section Ns = Ns Ar значение
Указывает правило сортировки секций при использовании linkerscript.
.It Fl -start-lib
Начать группировку объектов, которые должны обрабатываться так, как если бы они были вместе
в архиве.
.It Fl -strip-all , Fl s
Удалить все символы.
Подразумевает
.Fl -strip-debug .
.It Fl -strip-debug , Fl S
Удалить отладочную информацию.
.It Fl -symbol-ordering-file Ns = Ns Ar файл
Разместить секции в порядке, указанном в
.Ar файл .
.It Fl -sysroot Ns = Ns Ar значение
Установить системный корень.
.It Fl -target1-abs
Интерпретировать
.Dv R_ARM_TARGET1
как
.Dv R_ARM_ABS32 .
.It Fl -target1-rel
Интерпретировать
.Dv R_ARM_TARGET1
как
.Dv R_ARM_REL32 .
.It Fl -target2 Ns = Ns Ar тип
Интерпретировать
.Dv R_ARM_TARGET2
как
.Ar тип ,
где
.Ar тип
является одним из
.Cm rel ,
.Cm abs ,
или
.Cm got-rel .
.It Fl -Tbss Ns = Ns Ar значение
То же, что
.Fl -section-start
с
.Li .bss
в качестве имени секции.
.It Fl -Tdata Ns = Ns Ar значение
То же, что
.Fl -section-start
с
.Li .data
в качестве имени секции.
.It Fl -Ttext Ns = Ns Ar значение
То же, что
.Fl -section-start
с
.Li .text
в качестве имени секции.
.It Fl -thinlto-cache-dir Ns = Ns Ar значение
Путь к каталогу кэшированных объектных файлов ThinLTO.
.It Fl -thinlto-cache-policy Ns = Ns Ar значение
Политика очистки кэша ThinLTO.
.It Fl -thinlto-jobs Ns = Ns Ar значение
Число задач ThinLTO.
.It Fl -threads Ns = Ns Ar N
Число потоков.
.Cm all
(по умолчанию) означает все поддерживаемые параллельные потоки.
.Cm 1
отключает многопоточность.
.It Fl -fat-lto-objects
Использовать секцию .llvm.lto, содержащую LLVM bitcode, в fat LTO объектных файлах для выполнения LTO.
.It Fl -no-fat-lto-objects
Игнорировать секцию .llvm.lto в перемещаемых объектных файлах (по умолчанию).
.It Fl -time-trace
Записывать временную трассировку.
.It Fl -time-trace-file Ns = Ns Ar файл
Записать вывод временной трассировки в
.Ar файл .
.It Fl -time-trace-granularity Ns = Ns Ar значение
Минимальная временная гранулярность (в микросекундах), отслеживаемая профилировщиком времени.
.It Fl -trace
Вывести имена входных файлов.
.It Fl -trace-symbol Ns = Ns Ar символ , Fl y Ar символ
Отслеживать ссылки на
.Ar символ .
.It Fl -undefined Ns = Ns Ar символ , Fl u Ar символ
Если
.Ar символ
не определён после разрешения символов, и существует статическая библиотека,
содержащая объектный файл, определяющий символ, загрузить член,
чтобы включить объектный файл в выходной файл.
.It Fl -undefined-glob Ns = Ns Ar шаблон
Синоним для
.Fl -undefined ,
за исключением того, что принимает glob-шаблон.
В glob-шаблоне
.Cm *
соответствует нулю или более символов,
.Cm ?
соответствует любому одиночному символу, а
.Cm [...]
соответствует символам в скобках.
Все символы, соответствующие
заданному шаблону, обрабатываются так, как если бы они были заданы как аргументы
.Fl -undefined .
.It Fl -unique
Создаёт отдельную выходную секцию для каждой осиротевшей входной секции.
.It Fl -unresolved-symbols Ns = Ns Ar значение
Определить, как обрабатывать неразрешённые символы.
.It Fl -use-android-relr-tags
Использовать теги SHT_ANDROID_RELR / DT_ANDROID_RELR* вместо SHT_RELR / DT_RELR*.
.It Fl v , Fl V
Показать номер версии и продолжить компоновку, если указаны объектные файлы.
.It Fl -version
Показать номер версии и выйти.
.It Fl -verbose
Подробный режим.
.It Fl -version-script Ns = Ns Ar файл
Читать version script из
.Ar файл .
.It Fl -warn-backrefs
Предупреждать об обратных или циклических зависимостях от статических архивов или между ними.
Это можно использовать, чтобы гарантировать, что вызов компоновщика остаётся совместимым с
традиционными Unix-подобными компоновщиками.
.It Fl -warn-backrefs-exclude Ns = Ns Ar glob
Glob, описывающий архив (или объектный файл внутри --start-lib),
который следует игнорировать для
.Fl -warn-backrefs
.It Fl -warn-common
Предупреждать о повторяющихся common-символах.
.It Fl -warn-ifunc-textrel
Предупреждать об использовании ifunc-символов вместе с text relocations.
Старые версии библиотеки glibc (2.28 и ранее) имеют ошибку, из-за которой
сегмент, включающий ifunc-символы, помечается как неисполняемый, когда
они перемещаются.
В результате, хотя программа успешно компилируется и компонуется,
она выдаёт ошибку сегментации, когда указатель инструкций достигает
ifunc-символа.
Используйте -warn-ifunc-textrel, чтобы lld выдавал предупреждение, если
код может включать ifunc-символы, может выполнять text relocations и компоноваться со
старой версией glibc.
Иначе нет необходимости использовать её, так как значение по умолчанию не выдаёт
предупреждение.
Этот флаг был введён в конце 2018 года, не имеет аналога в компоновщиках ld и gold
и может быть удалён в будущем.
.It Fl -warn-unresolved-symbols
Сообщать о неразрешённых символах как о предупреждениях.
.It Fl -whole-archive
Принудительно загрузить всех членов статической библиотеки.
.It Fl -why-extract Ns = Ns Ar файл
Вывести в файл, почему извлекаются члены архива.
.It Fl -why-live Ns = Ns Ar glob
Сообщать цепочку ссылок, препятствующую сборке мусора, для каждого символа, соответствующего glob.
.It Fl -wrap Ns = Ns Ar символ
Перенаправить
.Ar символ
ссылки на
.Ar __wrap_symbol
и
.Ar __real_symbol
ссылки на
.Ar символ .
.It Fl z Ar опция
Расширения опций компоновщика.
.Bl -tag -width indent -compact
.Pp
.It Cm dead-reloc-in-nonalloc Ns = Ns Ar section_glob=value
Разрешить перемещение в совпавшей секции без SHF_ALLOC, ссылающееся на отброшенный символ, в
.Ar значение
Принимает glob-шаблоны; если секция соответствует более чем одной опции, последняя
опция имеет приоритет. Рекомендуется порядок от наименее конкретного к наиболее конкретному совпадению.
.Pp
.It Cm execstack
Сделать основной стек исполняемым.
Разрешения стека записываются в сегмент
.Dv PT_GNU_STACK
.
.Pp
.It Cm bti-report Ns = Ns Ar [none|warning|error]
Указать, как сообщать об отсутствующем свойстве GNU_PROPERTY_AARCH64_FEATURE_1_BTI.
.Cm none
является значением по умолчанию; компоновщик не будет сообщать об отсутствующем свойстве, иначе оно будет сообщено как предупреждение или ошибка.
.Pp
.It Cm cet-report Ns = Ns Ar [none|warning|error]
Указать, как сообщать об отсутствующих свойствах GNU_PROPERTY_X86_FEATURE_1_IBT или GNU_PROPERTY_X86_FEATURE_1_SHSTK.
.Cm none
является значением по умолчанию; компоновщик не будет сообщать об отсутствующем свойстве, иначе оно будет сообщено как предупреждение или ошибка.
.Pp
.It Cm dynamic-undefined-weak
Делать неопределённые weak-символы динамическими, когда присутствует таблица динамических символов, если на них ссылаются из
перемещаемых объектных файлов и они не сделаны локальными из-за видимости символов или версионирования. Не делать их динамическими, когда
.Cm nodynamic-undefined-weak
указана.
.Cm dynamic-undefined-weak
является значением по умолчанию при сборке разделяемого объекта или когда присутствует входной разделяемый объект.
.Pp
.It Cm pauth-report Ns = Ns Ar [none|warning|error]
Указать, как сообщать об отсутствующем свойстве GNU_PROPERTY_AARCH64_FEATURE_PAUTH.
.Cm none
является значением по умолчанию; компоновщик не будет сообщать об отсутствующем свойстве, иначе оно будет сообщено как предупреждение или ошибка.
.Pp
.It Cm force-bti
Принудительно включить инструкцию AArch64 BTI в PLT, предупреждать, если входной ELF-файл не имеет свойства GNU_PROPERTY_AARCH64_FEATURE_1_BTI.
.Pp
.It Cm force-ibt
Принудительно включить Intel Indirect Branch Tracking в PLT, предупреждать, если входной ELF-файл
не имеет свойства GNU_PROPERTY_X86_FEATURE_1_IBT.
.Pp
.It Cm global
Устанавливает
.Dv DF_1_GLOBAL flag в
.Dv DYNAMIC
секции.
Разные загрузчики могут сами решать, как обрабатывать этот флаг.
.Pp
.It Cm ifunc-noplt
Не генерировать записи PLT для ifunc-символов.
Вместо этого генерировать text relocations, ссылающиеся на resolver.
Это экспериментальная оптимизация и подходит только для автономных
сред, где text relocations не имеют обычных недостатков.
Эта опция должна быть объединена с опцией
.Fl z Li notext
.
.Pp
.It Cm initfirst
Устанавливает флаг
.Dv DF_1_INITFIRST
чтобы указать, что модуль должен инициализироваться первым.
.Pp
.It Cm interpose
Установить флаг
.Dv DF_1_INTERPOSE
чтобы указать компоновщику времени выполнения, что объект является interposer.
Во время разрешения символов interposer-ы ищутся после приложения,
но до других зависимостей.
.Pp
.It Cm lrodata-after-bss
Поместить .lrodata после .bss.
.Pp
.It Cm muldefs
Не выдавать ошибку, если символ определён несколько раз.
Будет использовано первое определение.
Это синоним для
.Fl -allow-multiple-definition.
.Pp
.It Cm nocombreloc
Отключить объединение и сортировку нескольких секций перемещений.
.Pp
.It Cm nocopyreloc
Отключить создание copy relocations.
.Pp
.It Cm nodefaultlib
Установить флаг
.Dv DF_1_NODEFLIB
чтобы указать, что пути поиска библиотек по умолчанию следует игнорировать.
.Pp
.It Cm nodelete
Установить флаг
.Dv DF_1_NODELETE
чтобы указать, что объект нельзя выгрузить из процесса.
.Pp
.It Cm nodlopen
Установить флаг
.Dv DF_1_NOOPEN
чтобы указать, что объект не может быть открыт с помощью
.Xr dlopen 3 .
.Pp
.It Cm nognustack
Не выводить сегмент
.Dv PT_GNU_STACK
.
.Pp
.It Cm norelro
Не указывать, что части объекта должны быть отображены только для чтения
после начальной обработки перемещений.
Объект будет опускать сегмент
.Dv PT_GNU_RELRO
.
.Pp
.It Cm nosectionheader
Не генерировать таблицу заголовков секций.
.Pp
.It Cm notext
Разрешить перемещения относительно сегментов только для чтения.
Устанавливает флаг
.Dv DT_TEXTREL в
.Dv DYNAMIC
секции.
.Pp
.It Cm now
Установить флаг
.Dv DF_BIND_NOW
чтобы указать, что загрузчик времени выполнения должен выполнять всю обработку перемещений
как часть инициализации объекта.
По умолчанию перемещения могут выполняться по требованию.
.Pp
.It Cm origin
Установить флаг
.Dv DF_ORIGIN
чтобы указать, что объект требует обработки
$ORIGIN
.
.Pp
.It Cm pac-plt
Только AArch64, использовать аутентификацию указателей в PLT.
.Pp
.It Cm pack-relative-relocs
Аналогично
.Cm -pack-dyn-relocs=relr
, но синтезирует зависимость версии GLIBC_ABI_DT_RELR, если есть зависимость версии GLIBC_2.*.
glibc ld.so отклоняет загрузку динамически связанного объекта без зависимости версии GLIBC_ABI_DT_RELR.
.Pp
.It Cm rel
Использовать формат REL для динамических перемещений.
.Pp
.It Cm rela
Использовать формат RELA для динамических перемещений.
.Pp
.It Cm retpolineplt
Генерировать записи PLT формата retpoline как меру защиты от CVE-2017-5715.
.Pp
.It Cm rodynamic
Сделать секцию
.Li .dynamic
только для чтения.
Тег
.Dv DT_DEBUG
не будет выдан.
.Pp
.It Cm separate-loadable-segments
.It Cm separate-code
.It Cm noseparate-code
Указать, могут ли два смежных сегмента PT_LOAD перекрываться в страницах.
.Cm noseparate-code
(по умолчанию) допускает перекрытие.
.Cm separate-code
допускает перекрытие между двумя исполняемыми сегментами или двумя неисполняемыми сегментами.
.Cm separate-loadable-segments
не допускает перекрытие.
.Pp
.It Cm shstk
Только x86, использовать shadow stack.
.Pp
.It Cm stack-size Ns = Ns Ar размер
Установить размер стека основного потока в
.Ar размер .
Размер стека записывается как размер
.Ar размер .
.Dv PT_GNU_STACK
программного сегмента.
.Pp
.It Cm start-stop-gc
Не позволять ссылкам __start_/__stop_ сохранять связанные секции с C-идентификаторами (по умолчанию).
.Pp
.It Cm nostart-stop-gc
Позволять ссылкам __start_/__stop_ сохранять связанные секции с C-идентификаторами.
.Pp
.It Cm text
Не разрешать перемещения относительно сегментов только для чтения.
Это значение по умолчанию.
.Pp
.It Cm nobtcfi
Создать сегмент
.Dv PT_OPENBSD_NOBTCFI
.
.Pp
.It Cm wxneeded
Создать сегмент
.Dv PT_OPENBSD_WXNEEDED
.
.El
.El

.Sh ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
.Bl -tag -width LC_CTYPE
.It Ev LLD_REPRODUCE
Создать воспроизводящий tar-архив с указанным именем файла. Если
.Fl -reproduce
указана,
.Fl -reproduce
имеет приоритет.
.It Ev LLD_VERSION
ld.lld создаёт секцию с именем
.Cm .comment
содержащую строку версии LLD. Строку версии можно переопределить этой переменной окружения,
что полезно для устранения различий в двоичном файле, вызванных различиями номера версии LLD.
.El

.Sh ЗАМЕЧАНИЯ ПО РЕАЛИЗАЦИИ
.Nm Ap s
обработка архивных файлов (тех, что имеют расширение
.Pa .a
) отличается от традиционных компоновщиков, используемых в Unix-подобных
системах.
.Pp
Традиционные компоновщики поддерживают набор неопределённых символов во время компоновки.
Компоновщик обрабатывает каждый файл в порядке его появления в
командной строке, пока набор неопределённых символов не станет пустым.
Объектный файл включается в выходной объект, когда он встречается,
а его неопределённые символы добавляются в набор.
При встрече архивного файла традиционный компоновщик ищет объекты
внутри него и обрабатывает те, которые удовлетворяют символы из неразрешённого
набора.
.Pp
Обработка взаимозависимых архивов может быть неудобной при использовании традиционного
компоновщика.
Архивные файлы, возможно, придётся указывать несколько раз, или можно использовать специальные опции командной строки
.Fl -start-group
и
.Fl -end-group
чтобы заставить компоновщик перебирать файлы в группе, пока в набор не будут добавлены новые
символы.
.Pp
.Nm
записывает все символы, найденные в объектах и архивах, по мере перебора
аргументов командной строки.
Когда
.Nm
встречает неопределённый символ, который может быть разрешён объектным файлом,
содержащимся в ранее обработанном архивном файле, он немедленно извлекает
и включает его в выходной объект.
.Pp
При определённых архивных входных данных
.Nm
может давать иные результаты по сравнению с традиционными компоновщиками.
На практике большие объёмы стороннего программного обеспечения компоновались с
.Nm
без существенных проблем.
.Pp
Опцию
.Fl -warn-backrefs
можно использовать для выявления вызова компоновщика, который может быть несовместим
с поведением традиционного Unix-подобного компоновщика.
