.\" FRDP path usr.bin/ldd/ldd.1
.\" FRDP githash b2c76c41be32f904179efed29c0ca04d53f3996c
.\" FRDP hash256 5b3229930d4248b3a2b745539f73a9dbc9bbaba97aea7439bbbff4ff4dbe28ab
.Dd March 21, 2023
.Dt LDD 1
.Os
.Sh ИМЯ
.Nm ldd
.Nd список зависимостей динамических объектов
.Sh СИНТАКСИС
.Nm
.Op Fl a
.Op Fl f Ar format Op Fl f Ar format
.Ar program ...
.Sh ОПИСАНИЕ
Утилита
.Nm
отображает все разделяемые объекты, необходимые для запуска данной программы или
для загрузки данного разделяемого объекта.
В отличие от
.Xr nm 1 ,
список включает
.Dq косвенные
зависимости, которые являются результатом необходимых разделяемых объектов, самих
зависящих от других разделяемых объектов.
.Pp
Можно указать ноль, один или два
параметра
.Fl f .
Аргумент — это строка формата, передаваемая
.Xr rtld 1
и позволяющая настроить
вывод
.Nm Ns .
Если указан один, он задаёт
.Ev LD_TRACE_LOADED_OBJECTS_FMT1 .
Если указаны два, они задают
.Ev LD_TRACE_LOADED_OBJECTS_FMT1
и
.Ev LD_TRACE_LOADED_OBJECTS_FMT2
соответственно.
См.
.Xr rtld 1
для подробностей, включая список распознаваемых символов преобразования.
.Pp
Параметр
.Fl a
отображает список всех объектов, необходимых каждому загруженному
объекту.
.Sh ЗАМЕЧАНИЯ ПО РЕАЛИЗАЦИИ
.Nm
перечисляет зависимости исполняемого файла, устанавливая
переменные окружения
.Xr rtld 1
и запуская исполняемый файл в дочернем процессе.
Если исполняемый файл повреждён или недействителен,
.Nm
может поэтому завершиться с ошибкой, не предоставив никаких диагностических сообщений об ошибках.
.Sh ПРИМЕРЫ
Ниже приведён пример конвейера оболочки, использующего
параметр
.Fl f .
Он выведет отчёт обо всех ELF-двоичных файлах в текущем каталоге,
которые скомпонованы со старым libc.so.6:
.Sh СМ. ТАКЖЕ
.Xr ld 1 ,
.Xr nm 1 ,
.Xr readelf 1 ,
.Xr rtld 1
.Sh ИСТОРИЯ
Утилита
.Nm
впервые появилась в SunOS 4.0, в её текущем виде она появилась в
.Fx 1.1 .
