.\" FRDP path contrib/ldns/packaging/ldns-config.1
.\" FRDP githash d44c9549ef31884ac069b0306bad248a74bb2825
.\" FRDP hash256 5218247882ff9903273134a949c174c32b278ae673daf34edab45c8e025ffb2c
.SH ИМЯ
ldns-config \- показать флаги компилятора и компоновщика для использования ldns.
.SH СИНТАКСИС
.B ldns-config
[
.IR ОПЦИИ
]

.SH ОПИСАНИЕ
При написании программ с использованием ldns необходимо указать компилятору,
где искать заголовочные файлы и какие библиотеки из каких мест следует
компоновать. \fBldns-config\fR можно использовать, чтобы узнать, какие флаги
использовать с компилятором C и компоновщиком.

.SH ОПЦИИ
.TP
\fB--cflags\fR
Показать флаги компилятора C, необходимые для компиляции с ldns

.TP
\fB--libs\fR
Показать флаги, которые следует использовать для компоновки с ldns

.TP
\fB--version\fR
Показывает версию ldns установленной библиотеки ldns

.TP
\fB--libversion\fR
Показывает версию двоичного API установленной библиотеки ldns

.TP
\fB--help\fR
Показать описание использования \fBldns-config\fR

.SH АВТОР
Написано командой ldns.

.SH СООБЩЕНИЕ ОБ ОШИБКАХ
Сообщайте об ошибках по адресу <dns-team@nlnetlabs.nl>.

.SH АВТОРСКОЕ ПРАВО
Copyright (C) 2011 NLnet Labs. Это свободное программное обеспечение. НЕТ
гарантии; даже для КОММЕРЧЕСКОЙ ПРИГОДНОСТИ или ПРИГОДНОСТИ ДЛЯ КОНКРЕТНОЙ
ЦЕЛИ.
