.\" FRDP path bin/ls/ls.1
.\" FRDP githash 4ed2448a4f2b32d0c4055c282e4cc2b691d621ed
.\" FRDP hash256 f4a811d5c5de5d42afda3e801d0af515744aba3537f675d947df095d4987f271
.Dd January 16, 2025
.Dt LS 1
.Os
.Sh ИМЯ
.Nm ls
.Nd "выводит содержимое каталогов"
.Sh СИНТАКСИС
.Nm
.Op Fl ABCFGHILPRSTUWZabcdfghiklmnopqrstuvwxy1\&,
.Op Fl -color Ns = Ns Ar когда
.Op Fl -group-directories Ns = Ns Ar порядок
.Op Fl -group-directories-first
.Op Fl D Ar формат
.Op Ar
.Sh ОПИСАНИЕ
Для каждого операнда, который именует
.Ar файл
типа, отличного от
каталога,
.Nm
выводит его имя, а также любую запрошенную
связанную информацию.
Для каждого операнда, который именует
.Ar файл
типа каталог,
.Nm
выводит имена файлов, содержащихся
в этом каталоге, а также любую запрошенную связанную
информацию.
.Pp
Если операнды не заданы, выводится содержимое текущего
каталога.
Если задано более одного операнда,
операнды, не являющиеся каталогами, выводятся первыми; каталоги
и операнды, не являющиеся каталогами, сортируются отдельно и в
лексикографическом порядке.
.Pp
Доступны следующие параметры:
.Bl -tag -width indent
.It Fl A
Включать элементы каталога, имена которых начинаются с
точки
.Pq Sq Pa \&.
кроме
.Pa \&.
и
.Pa .. .
Автоматически устанавливается для суперпользователя, если не
указан
.Fl I .
.It Fl B
Принудительно выводить непечатаемые символы (как определено в
.Xr ctype 3
и текущих настройках локали) в именах файлов как
.Li \e Ns Va xxx ,
где
.Va xxx
— числовое значение символа в восьмеричном виде.
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl C
Принудительно выводить в несколько колонок; это значение по умолчанию, когда вывод направлен на терминал.
.It Fl D Ar формат
При выводе в длинном
.Pq Fl l
формате использовать
.Ar формат
для форматирования вывода даты и времени.
Аргумент
.Ar формат
— это строка, используемая
.Xr strftime 3 .
В зависимости от выбранной строки формата это может привести к
разному числу колонок в выводе.
Этот параметр переопределяет
.Fl T
параметр.
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl F
Отображать косую черту
.Pq Ql /
сразу после каждого имени пути, которое является каталогом,
звёздочку
.Pq Ql *
после каждого исполняемого,
знак at
.Pq Ql @
после каждой символической ссылки,
знак равенства
.Pq Ql =
после каждого сокета,
знак процента
.Pq Ql %
после каждого whiteout,
и вертикальную черту
.Pq Ql \&|
после каждого, который является
.Tn FIFO .
.It Fl G
Включить цветной вывод.
Этот параметр эквивалентен определению
.Ev CLICOLOR
или
.Ev COLORTERM
в окружении и установке
.Fl -color Ns = Ns Ar auto .
(См. ниже.)
Эта функциональность может быть исключена при компиляции удалением определения
.Ev COLORLS .
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl H
Символические ссылки в командной строке отслеживаются.
Этот параметр подразумевается, если
не указан ни один из
.Fl F , d ,
или
.Fl l
параметров.
.It Fl I
Запретить автоматическую установку
.Fl A
для суперпользователя.
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl L
Если аргумент является символической ссылкой, выводить файл или каталог, на который ссылается ссылка,
а не саму ссылку.
Этот параметр отменяет
.Fl P
параметр.
.It Fl P
Если аргумент является символической ссылкой, выводить саму ссылку, а не
объект, на который ссылается ссылка.
Этот параметр отменяет
.Fl H
и
.Fl L
параметры.
.It Fl R
Рекурсивно выводить встречающиеся подкаталоги.
.It Fl S
Сортировать по размеру (сначала самый большой файл) перед сортировкой операндов в
лексикографическом порядке.
.It Fl T
При выводе в длинном
.Pq Fl l
формате отображать полную информацию о времени для файла, включая
месяц, день, час, минуту, секунду и год.
Параметр
.Fl D
даёт ещё больший контроль над форматом вывода.
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl U
Использовать время создания файла для сортировки или вывода.
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl W
Отображать whiteout при сканировании каталогов.
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl Z
Отображать метку MAC каждого файла; см.
.Xr maclabel 7 .
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl a
Включать элементы каталога, имена которых начинаются с
точки
.Pq Sq Pa \&. .
.It Fl b
Как
.Fl B ,
но использовать
.Tn C
escape-последовательности, когда это возможно.
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl c
Использовать время последнего изменения состояния файла для сортировки или вывода.
.It Fl -color Ns = Ns Ar когда
Выводить цветные escape-последовательности в зависимости от
.Ar когда ,
которое может быть установлено в
.Cm always ,
.Cm auto ,
или
.Cm never .
.Pp
.Cm always
заставит
.Nm
всегда выводить цвет.
Если
.Ev TERM
не установлена или установлена в недопустимый терминал, то
.Nm
будет использовать явные
.Tn ANSI
escape-последовательности без помощи
.Xr termcap 5 .
.Cm always
является значением по умолчанию, если
.Fl -color
указан без аргумента.
.Pp
.Cm auto
заставит
.Nm
выводить escape-последовательности на основе
.Xr termcap 5 ,
но только если
.Dv stdout
является tty и либо указан
.Fl G
флаг, либо одна из переменных окружения
.Ev COLORTERM
или
.Ev CLICOLOR
установлена и не пуста.
.Pp
.Cm never
отключит цвет независимо от переменных окружения.
.Cm never
является значением по умолчанию, когда ни
.Fl -color ,
ни
.Fl G
не указаны.
.Pp
Для совместимости с GNU coreutils
.Nm
поддерживает
.Cm yes
или
.Cm force
как эквивалент
.Cm always ,
.Cm no
или
.Cm none
как эквивалент
.Cm never ,
и
.Cm tty
или
.Cm if-tty
как эквивалент
.Cm auto .
.It Fl d
Каталоги выводятся как обычные файлы (рекурсивно не просматриваются).
.It Fl f
Вывод не сортируется.
Этот параметр включает
.Fl a .
Он также отменяет действие
.Fl r ,
.Fl S
и
.Fl t
параметров.
Как допускается в
.St -p1003.1-2008 ,
этот параметр не влияет на
.Fl d ,
.Fl l ,
.Fl R
и
.Fl s
параметры.
.It Fl g
Отображать вывод в длинном
.Pq Fl l
формате без имени или номера владельца файла.
.It Fl -group-directories Ns = Ns Ar порядок
В результатах для каждого операнда
группировать каталоги вместе и выводить их либо
.Cm first
либо
.Cm last .
.It Fl -group-directories-first
Эквивалентно
.Fl -group-directories Ns = Ns Ar first .
Реализовано для совместимости с GNU coreutils.
.It Fl h
При использовании с
.Fl l
параметром использовать суффиксы единиц: байт, килобайт, мегабайт, гигабайт, терабайт
и петабайт, чтобы уменьшить количество цифр до четырёх или меньше,
используя основание 2 для размеров.
Этот параметр не определён в
.St -p1003.1-2008 .
.It Fl i
Для каждого файла выводить серийный номер файла (номер inode).
.It Fl k
Это имеет тот же эффект, что и установка переменной окружения
.Ev BLOCKSIZE
в 1024, за исключением того, что также обнуляет любые
.Fl h
параметры слева от него.
.It Fl l
(Строчная буква
.Dq эль . )
Выводить файлы в длинном формате, как описано в
.Sx "Длинный формат"
подразделе ниже.
.It Fl m
Потоковый формат вывода; выводить файлы по странице, разделяя запятыми.
.It Fl n
Отображать идентификаторы пользователей и групп численно, а не преобразовывать в имя пользователя
или группы в длинном
.Pq Fl l
выводе.
.It Fl o
Включать флаги файлов в длинный
.Pq Fl l
вывод.
Этот параметр несовместим с
.St -p1003.1-2008 .
См.
.Xr chflags 1
для списка флагов файлов и их значений.
.It Fl p
Записывать косую черту
.Pq Ql /
после каждого имени файла, если этот файл является каталогом.
.It Fl q
Принудительно выводить неграфические символы в именах файлов как
символ
.Ql \&? ;
это значение по умолчанию, когда вывод направлен на терминал.
.It Fl r
Обратить порядок сортировки.
.It Fl s
Отображать количество блоков, используемых в файловой системе каждым файлом.
Размеры блоков и итоги по каталогам обрабатываются, как описано в
.Sx "Длинный формат"
подразделе ниже, за исключением (если длинный формат также не запрошен)
итоги по каталогам не выводятся, когда вывод в
одну колонку, даже если запрошен многоколоночный вывод.
.It Fl t
Сортировать по убыванию времени изменения (сначала недавно изменённые).
Если два файла имеют одинаковую метку времени изменения, сортировать их имена
в возрастающем лексикографическом порядке.
Параметр
.Fl r
обращает оба этих порядка сортировки.
.Pp
Заметьте, что эти порядки сортировки противоречивы: временная последовательность идёт в
убывающем порядке, а лексикографическая сортировка — в возрастающем.
Это поведение предписано
.St -p1003.2 .
Эта особенность может вызвать проблемы при выводе файлов, сохранённых с последовательными именами на
файловых системах FAT, например, с цифровых камер, где возможно наличие
более одного изображения с одинаковой меткой времени.
В таком случае фотографии невозможно вывести в последовательности, в которой
они были сняты.
Чтобы обеспечить одинаковый порядок сортировки для времени и для лексикографической сортировки, установите
переменную окружения
.Ev LS_SAMESORT
или используйте
.Fl y
параметр.
Это заставляет
.Nm
обращать лексикографический порядок сортировки при сортировке файлов с
одинаковой меткой времени изменения.
.It Fl u
Использовать время последнего доступа,
вместо времени последнего изменения
файла для сортировки
.Pq Fl t
или вывода
.Pq Fl l .
.It Fl v
Сортировать в соответствии с естественным порядком, используя
.Xr strverscmp 3
вместо
.Xr strcoll 3
в качестве функции сравнения.
Например, файлы, упорядоченные лексикографически
.It Fl w
Принудительно выводить непечатаемые символы без обработки.
Это значение по умолчанию,
когда вывод не направлен на терминал.
Этот параметр не определён в
.St -p1003.1-2001 .
.It Fl x
То же, что и
.Fl C ,
за исключением того, что многоколоночный вывод формируется с элементами, сортированными
по строкам, а не по колонкам.
.It Fl y
Когда установлен
.Fl t
параметр, сортировать алфавитный вывод в том же порядке, что и вывод по времени.
Это имеет тот же эффект, что и установка
.Ev LS_SAMESORT .
См. описание
.Fl t
параметра для более подробной информации.
Этот параметр не определён в
.St -p1003.1-2001 .
.It Fl 1
(Цифра
.Dq один . )
Принудительно выводить
по одной записи на строку.
Это значение по умолчанию, когда
вывод не направлен на терминал.
.It Fl ,
(Запятая) Когда установлен
.Fl l
или
.Fl s
параметр, выводить размеры файлов, сгруппированные и разделённые тысячами, используя
неденежный разделитель, возвращаемый
.Xr localeconv 3 ,
обычно запятую или точку.
Если локаль не установлена или локаль не имеет неденежного разделителя, этот
параметр не имеет эффекта.
Этот параметр не определён в
.St -p1003.1-2001 .
.El
.Pp
Параметры
.Fl 1 , C , x ,
и
.Fl l
все переопределяют друг друга; последний указанный определяет
используемый формат.
.Pp
Параметры
.Fl c , u ,
и
.Fl U
все переопределяют друг друга; последний указанный определяет
используемое время файла.
.Pp
Параметры
.Fl S , t
и
.Fl v
переопределяют друг друга; последний указанный определяет
используемый порядок сортировки.
.Pp
Параметры
.Fl B , b , w ,
и
.Fl q
все переопределяют друг друга; последний указанный определяет
формат, используемый для непечатаемых символов.
.Pp
Параметры
.Fl H , L
и
.Fl P
все переопределяют друг друга (частично или полностью); они
применяются в указанном порядке.
.Pp
По умолчанию
.Nm
выводит по одной записи на строку в стандартный
вывод; исключения — терминалы или когда указаны
.Fl C
или
.Fl x
параметры.
.Pp
Информация о файле отображается с одним или несколькими
.Ao blank Ac Ns s
разделяющими информацию, связанную с
.Fl i , s ,
и
.Fl l
параметрами.
.Ss Длинный формат
Если задан
.Fl l
параметр, для каждого файла
отображается следующая информация:
режим файла,
количество ссылок, имя владельца, имя группы,
метка MAC,
количество байт в файле, сокращённое
название месяца, день месяца последнего изменения файла,
час последнего изменения файла, минута последнего
изменения файла и имя пути.
.Pp
Если время изменения файла более чем на 6 месяцев
в прошлом или будущем, и
.Fl D
или
.Fl T
не указаны,
то год последнего изменения
отображается вместо полей часа и минуты.
.Pp
Если имена владельца или группы не являются известным именем пользователя или группы,
или задан
.Fl n
параметр,
отображаются числовые ID.
.Pp
Если файл является специальным символьным или специальным блочным файлом,
номер устройства для файла отображается в поле размера.
Если файл является символической ссылкой, имени пути
файла, на который указывает ссылка, предшествует
.Dq Li -> .
.Pp
Выводу содержимого каталога предшествует
помеченное общее количество блоков, используемых в файловой системе файлами,
которые перечислены как содержимое каталога
(которые могут включать или не включать
.Pa \&.
и
.Pa ..
и другие файлы, начинающиеся с точки, в зависимости от других параметров).
Если задан
.Fl h
параметр,
общий размер отображается как количество байт.
.Pp
Размер блока по умолчанию — 512 байт.
Размер блока может быть установлен параметром
.Fl k
или переменной окружения
.Ev BLOCKSIZE .
Количество блоков в выводе будет округлено вверх, так что
количество байт будет по крайней мере таким же, как используется соответствующими
блоками файловой системы (которые могут иметь другой размер).
.Pp
Режим файла, выводимый при
.Fl l
параметре, состоит из
типа записи и прав доступа.
Символ типа записи описывает тип файла, как
следует:
.Pp
.Bl -tag -width 4n -offset indent -compact
.It Sy \-
Обычный файл.
.It Sy b
Специальный блочный файл.
.It Sy c
Специальный символьный файл.
.It Sy d
Каталог.
.It Sy l
Символическая ссылка.
.It Sy p
.Tn FIFO .
.It Sy s
Сокет.
.It Sy w
Whiteout.
.El
.Pp
Следующие три поля
состоят из трёх символов каждое:
права владельца,
права группы и
права остальных.
Каждое поле имеет три позиции символов:
.Bl -enum -offset indent
.It
Если
.Sy r ,
файл доступен для чтения; если
.Sy \- ,
он не доступен для чтения.
.It
Если
.Sy w ,
файл доступен для записи; если
.Sy \- ,
он не доступен для записи.
.It
Первое из следующего, что применимо:
.Bl -tag -width 4n -offset indent
.It Sy S
Если в правах владельца, файл не исполняемый и
установлен режим set-user-ID.
Если в правах группы, файл не исполняемый
и установлен режим set-group-ID.
.It Sy s
Если в правах владельца, файл исполняемый
и установлен режим set-user-ID.
Если в правах группы, файл исполняемый
и установлен режим setgroup-ID.
.It Sy x
Файл исполняемый или каталог
доступен для поиска.
.It Sy \-
Файл не доступен ни для чтения, ни для записи, ни исполнения,
ни установлен режим set-user-ID, ни set-group-ID, ни sticky.
(См. ниже.)
.El
.Pp
Следующие два применяются только к третьему символу в последней группе
(права остальных).
.Bl -tag -width 4n -offset indent
.It Sy T
Установлен sticky-бит
(режим
.Li 1000 ) ,
но нет права на исполнение или поиск.
(См.
.Xr chmod 1
или
.Xr sticky 7 . )
.It Sy t
Установлен sticky-бит (режим
.Li 1000 ) ,
и есть доступ для поиска или исполнения.
(См.
.Xr chmod 1
или
.Xr sticky 7 . )
.El
.El
.Pp
Следующее поле содержит
плюс
.Pq Ql +
символ, если файл имеет ACL, или
пробел
, если нет.
Утилита
.Nm
не показывает фактический ACL;
используйте
.Xr getfacl 1
для этого.
.Sh ОКРУЖЕНИЕ
Следующие переменные окружения влияют на выполнение
.Nm :
.Bl -tag -width indent
.It Ev BLOCKSIZE
Если она установлена, её значение, округлённое вверх до 512 или вниз до
кратного 512, будет использоваться как размер блока в байтах
.Fl l
и
.Fl s
параметрами.
См.
.Sx "Длинный формат"
подраздел для получения дополнительной информации.
.It Ev CLICOLOR
Использовать
.Tn ANSI
цветовые последовательности для различения типов файлов.
См.
.Ev LSCOLORS
ниже.
В дополнение к типам файлов, упомянутым в
.Fl F
параметре, также отображаются некоторые дополнительные атрибуты (установлен бит setuid и т.п.).
Цветовой вывод зависит от типа терминала с соответствующими
.Xr termcap 5
возможностями.
По умолчанию
.Dq Li cons25
консоль имеет соответствующие возможности,
но для отображения цветов в
.Xr xterm 1 Pq Pa ports/x11/xterm ,
например,
переменная
.Ev TERM
должна быть установлена в
.Dq Li xterm-color .
Другие типы терминалов могут требовать аналогичных настроек.
Цветовой вывод
тихо отключается, если вывод не направлен на терминал,
если только не определена переменная
.Ev CLICOLOR_FORCE
или
.Fl -color
не установлен в
.Dq always .
.It Ev CLICOLOR_FORCE
Цветовые последовательности обычно отключаются, если вывод не направлен на
терминал.
Это можно переопределить, установив эту переменную.
Однако переменная
.Ev TERM
всё ещё должна ссылаться на терминал, поддерживающий цвета,
иначе невозможно определить, какие цветовые последовательности
использовать.
.It Ev COLORTERM
См. описание
.Ev CLICOLOR
выше.
.It Ev COLUMNS
Если эта переменная содержит строку, представляющую
десятичное целое, она используется как
ширина позиции колонки для отображения
многоколоночного текстового вывода.
Утилита
.Nm
вычисляет, сколько текстовых колонок имён путей отображать,
на основе предоставленной ширины.
(См.
.Fl C
и
.Fl x . )
.It Ev LANG
Локаль, используемая при определении порядка дня и месяца в длинном
.Fl l
формате вывода.
См.
.Xr environ 7
для получения дополнительной информации.
.It Ev LSCOLORS
Значение этой переменной описывает, какой цвет использовать для какого
атрибута, когда цвета включены с помощью
.Ev CLICOLOR
или
.Ev COLORTERM .
Эта строка является конкатенацией пар формата
.Ar f Ns Ar b ,
где
.Ar f
— цвет переднего плана, а
.Ar b
— цвет фона.
Когда цвет фона заглавный, текст подчёркивается.
.Pp
Обозначения цветов следующие:
.Pp
.Bl -tag -width 4n -offset indent -compact
.It Sy a
чёрный
.It Sy b
красный
.It Sy c
зелёный
.It Sy d
коричневый
.It Sy e
синий
.It Sy f
пурпурный
.It Sy g
голубой
.It Sy h
светло-серый
.It Sy A
жирный или подчёркнутый чёрный, обычно выглядит как тёмно-серый
.It Sy B
жирный или подчёркнутый красный
.It Sy C
жирный или подчёркнутый зелёный
.It Sy D
жирный или подчёркнутый коричневый, обычно выглядит как жёлтый
.It Sy E
жирный или подчёркнутый синий
.It Sy F
жирный или подчёркнутый пурпурный
.It Sy G
жирный или подчёркнутый голубой
.It Sy H
жирный или подчёркнутый светло-серый; выглядит как ярко-белый
.It Sy x
цвет переднего плана или фона по умолчанию
.It Sy X
цвет переднего плана или фона по умолчанию, с подчёркиванием или жирным
.El
.Pp
Заметьте, что вышеуказанные цвета являются стандартными
.Tn ANSI
цветами.
Фактическое отображение может отличаться
в зависимости от цветовых возможностей используемого терминала.
.Pp
Порядок атрибутов следующий:
.Pp
.Bl -enum -offset indent -compact
.It
каталог
.It
символическая ссылка
.It
сокет
.It
канал
.It
исполняемый
.It
специальный блочный
.It
специальный символьный
.It
исполняемый с установленным битом setuid
.It
исполняемый с установленным битом setgid
.It
каталог, доступный для записи другим, со sticky-битом
.It
каталог, доступный для записи другим, без sticky-бита
.El
.Pp
Значение по умолчанию —
т.е. синий передний план и
фон по умолчанию для обычных каталогов, чёрный передний план и красный
фон для исполняемых файлов setuid, и т.д.
.It Ev LS_COLWIDTHS
Если эта переменная установлена, она считается
разделённым двоеточиями списком минимальных ширин колонок.
Неразумные
и недостаточные ширины игнорируются (таким образом, ноль означает
динамически изменяемую ширину колонки).
Не все колонки имеют изменяемые ширины.
Поля, по порядку: inode, количество блоков, количество ссылок, имя пользователя,
имя группы, флаги, размер файла, имя файла.
.It Ev LS_SAMESORT
Если эта переменная установлена, параметр
.Fl t
сортирует имена файлов с одинаковой меткой времени изменения в том же
смысле, что и сортировка по времени.
См. описание
.Fl t
параметра для более подробной информации.
.It Ev TERM
Функциональность
.Ev CLICOLOR
и
.Ev COLORTERM
зависит от типа терминала с цветовыми возможностями.
.It Ev TZ
Часовой пояс, используемый при отображении дат.
См.
.Xr environ 7
для получения дополнительной информации.
.El
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
Вывести содержимое текущего рабочего каталога в длинном формате:
.Pp
.Dl $ ls -l
.Pp
В дополнение к выводу содержимого текущего рабочего каталога в
длинном формате, показать номера inode, флаги файлов (см.
.Xr chflags 1 ) ,
и дополнить каждое имя файла символом, представляющим его тип файла:
.Pp
.Dl $ ls -lioF
.Pp
Вывести файлы в
.Pa /var/log ,
отсортировав вывод так, чтобы наиболее недавно изменённые записи
были напечатаны первыми:
.Pp
.Dl $ ls -lt /var/log
.Sh СОВМЕСТИМОСТЬ
Поле группы теперь автоматически включается в длинный вывод для
файлов для совместимости с
.St -p1003.2
спецификацией.
.Sh СМ. ТАКЖЕ
.Xr chflags 1 ,
.Xr chmod 1 ,
.Xr getfacl 1 ,
.Xr sort 1 ,
.Xr xterm 1 Pq Pa ports/x11/xterm ,
.Xr localeconv 3 ,
.Xr strcoll 3 ,
.Xr strftime 3 ,
.Xr strmode 3 ,
.Xr strverscmp 3 ,
.Xr termcap 5 ,
.Xr maclabel 7 ,
.Xr sticky 7 ,
.Xr symlink 7 ,
.Xr getfmac 8
.Sh СТАНДАРТЫ
За исключением параметров
.Fl g , n
и
.Fl o ,
утилита
.Nm
соответствует
.St -p1003.1-2001
и
.St -p1003.1-2008 .
Параметры
.Fl B , D , G , I , T , U , W , Z , b , h , v , w , y
,
.Fl ,
.Fl -color
и
.Fl -group-directories Ns =
(включая
.Fl -group-directories-first )
являются нестандартными расширениями.
.Pp
Поддержка ACL совместима с
.Tn IEEE
Std\~1003.2c
.Pq Dq Tn POSIX Ns .2c
Draft\~17
(отозван).
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v1 .
.Pp
Параметр
.Fl v
был добавлен в
.Fx 13.2 .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Для поддержания обратной совместимости отношения между многими
параметрами довольно сложны.
.Pp
Исключение, упомянутое в описании параметра
.Fl s ,
возможно, является особенностью, которая была
основана на том факте, что одноколоночный вывод
обычно направляется не на терминал.
Спорно, является ли это ошибкой проектирования.
.Pp
.St -p1003.2
предписывает противоположные порядки сортировки для файлов с одинаковой меткой времени при
сортировке с
.Fl t
параметром.
