.\" FRDP path contrib/lua/doc/lua.1
.\" FRDP githash 3068d706eabe99f930fb01d3cbfd74ff1f0eb5a2
.\" FRDP hash256 aba7788e9d9d3050ff57c3fc40047d46d79b83baa66507572b36c43c3b7534d5
.SH ИМЯ
lua \- интерпретатор Lua
.SH СИНТАКСИС
.B lua
[
.I параметры
]
[
.I сценарий
[
.I аргументы
]
]
.SH ОПИСАНИЕ
.B lua
является автономным интерпретатором Lua.
Он загружает и выполняет программы Lua,
либо в виде текстового исходного кода,
либо в виде предварительно скомпилированного двоичного кода.
(Предварительно скомпилированные двоичные файлы создаются
.BR luac ,
компилятором Lua.)
.B lua
можно использовать как пакетный интерпретатор, а также в интерактивном режиме.
.LP
После обработки
.IR параметров ,
программа Lua в файле
.I сценарий
загружается и выполняется.
.I аргументы
доступны
.I сценарию
как строки в глобальной таблице с именем
.B arg
а также как аргументы его главной функции.
При вызове без аргументов
.B lua
ведёт себя так,
как если бы стандартный ввод был терминалом,
а в противном случае —
иначе.
.LP
В интерактивном режиме
.B lua
выдаёт приглашение пользователю,
читает строки из стандартного ввода
и выполняет их по мере чтения.
Если строка содержит выражение,
то она вычисляется, и результат выводится.
Если строка не содержит законченного оператора,
то отображается дополнительное приглашение и
строки читаются до тех пор, пока не будет сформирован законченный оператор или
не будет обнаружена синтаксическая ошибка.
.LP
Перед обработкой параметров командной строки и сценариев
.B lua
проверяет содержимое переменных окружения
.B LUA_INIT_5_4
и
.BR LUA_INIT ,
в указанном порядке.
Если содержимое имеет вид
.RI '@ файл ',
то
.I файл
выполняется.
В противном случае предполагается, что содержимое является оператором Lua, и оно выполняется.
Когда
.B LUA_INIT_5_4
определена,
.B LUA_INIT
игнорируется.
.SH ОПЦИИ
.TP
выполнить оператор
.IR оператор .
.TP
.B \-i
войти в интерактивный режим после выполнения
.IR сценария .
.TP
подключить библиотеку
.I модуль
в глобальную
.IR модуль .
.TP
подключить библиотеку
.I модуль
в глобальную
.IR g .
.TP
.B \-v
показать информацию о версии.
.TP
.B \-E
игнорировать переменные окружения.
.TP
.B \-W
включить предупреждения.
.TP
.B \-\-
прекратить обработку параметров.
.TP
.B \-
прекратить обработку параметров и выполнить стандартный ввод как файл.
.SH ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
Следующие переменные окружения влияют на выполнение
.BR lua .
Когда они определены,
варианты для конкретной версии имеют приоритет,
а варианты без привязки к версии игнорируются.
.TP
.B LUA_INIT, LUA_INIT_5_4
Код, выполняемый перед параметрами командной строки и сценариями.
.TP
.B LUA_PATH, LUA_PATH_5_4
Начальное значение package.path,
путь, используемый require для поиска загрузчиков Lua.
.TP
.B LUA_CPATH, LUA_CPATH_5_4
Начальное значение package.cpath,
путь, используемый require для поиска загрузчиков C.
.SH СТАТУС ВЫХОДА
Если сценарий вызывает os.exit,
то
.B lua
завершается с указанным статусом выхода.
В противном случае
.B lua
завершается
с EXIT_SUCCESS (0 в POSIX-системах), если ошибок не было,
и
с EXIT_FAILURE (1 в POSIX-системах), если были ошибки.
Ошибки, возникшие в интерактивном режиме, не приводят к завершению.
.SH ДИАГНОСТИКА
Сообщения об ошибках должны быть понятны сами по себе.
.BR luac (1)
.br
Документация на lua.org,
особенно раздел 7 справочного руководства.
.SH АВТОРЫ
R. Ierusalimschy,
L. H. de Figueiredo,
W. Celes
