.\" FRDP path contrib/mandoc/man.1
.\" FRDP githash 80c12959679ab203459dc20eb9ece3a7328b7de5
.\" FRDP hash256 b7b293ddcc5e05feb5208c577a9da44ac1f76a3e19b2fc5958695496dd15a846
.Dd $Mdocdate: January 26 2025 $
.Dt MAN 1
.Os
.Sh ИМЯ
.Nm man
.Nd "отображать страницы руководства"
.Sh СИНТАКСИС
.Nm man
.Op Fl acfhklw
.Op Fl C Ar file
.Op Fl M Ar path
.Op Fl m Ar path
.Op Fl S Ar subsection
.Op Oo Fl s Oc Ar section
.Ar name ...
.Sh ОПИСАНИЕ
Утилита
.Nm
отображает
страницу руководства с заголовком
.Ar name .
Страницы можно выбирать по
определённой категории
.Pq Ar section
или
архитектуре машины
.Pq Ar subsection ,
либо искать с помощью
.Fl k ,
используя поисковые выражения
.Xr apropos 1 .
Пейджер по умолчанию,
.Xr less 1 ,
поддерживает команду
.Ic :t
для перехода к определениям конкретных терминов (см.
.Dv MANPAGER ,
ниже).
.Pp
Параметры перечислены ниже:
.Bl -tag -width Ds
.It Fl a
Отобразить все подходящие страницы руководства.
.It Fl C Ar file
Использовать указанный
.Ar file
вместо файла конфигурации по умолчанию.
Это позволяет пользователям настроить собственное окружение руководств.
См.
.Xr man.conf 5
для описания содержимого этого файла.
.It Fl c
Копировать страницу руководства в стандартный вывод вместо использования
.Xr less 1
для постраничного вывода.
Это делается по умолчанию, если стандартный вывод не является терминальным устройством.
.Pp
При использовании
.Fl c
большинство терминальных устройств не могут отобразить разметку.
Чтобы вывести результат работы
.Nm
в терминал с разметкой, но без пейджера, передайте его по конвейеру в
.Xr ul 1 .
Чтобы удалить разметку, вместо этого передайте вывод по конвейеру в
.Xr col 1
.Fl b .
.It Fl f
Синоним
.Xr whatis 1 .
Он ищет
.Ar name
среди названий страниц руководства и отображает строки заголовков всех подходящих страниц.
Поиск нечувствителен к регистру и совпадает только с целыми словами.
.It Fl h
Отображать только строки раздела СИНТАКСИС запрошенных страниц руководства.
Подразумевает
.Fl a
и
.Fl c .
.It Fl k
Синоним
.Xr apropos 1 .
Вместо
.Ar name
можно указать выражение, используя синтаксис, описанный в руководстве
.Xr apropos 1 .
По умолчанию отображает строки заголовков всех подходящих страниц.
.It Fl l
Синоним
.Xr mandoc 1 .
Аргументы
.Ar name
интерпретируются как имена файлов.
Поиск не выполняется, а
.Ar file ,
.Ar path ,
.Ar section ,
.Ar subsection
и
.Fl w
игнорируются.
Этот параметр подразумевает
.Fl a .
.It Fl M Ar path
Переопределить список каталогов для поиска страниц руководства.
Указанный
.Ar path
должен быть списком каталогов, разделённых двоеточием
.Pq Ql \&: .
Этот параметр также переопределяет переменную окружения
.Ev MANPATH
и любые каталоги, указанные в файле
.Xr man.conf 5 .
.It Fl m Ar path
Дополнить список каталогов для поиска страниц руководства.
Указанный
.Ar path
должен быть списком каталогов, разделённых двоеточием
.Pq Ql \&: .
Эти каталоги будут просмотрены перед каталогами, указанными с помощью параметра
.Fl M ,
переменной окружения
.Ev MANPATH ,
файла
.Xr man.conf 5
или каталогов по умолчанию.
.It Fl S Ar subsection
Показывать только страницы для указанной архитектуры
.Xr machine 1 .
.Ar subsection
нечувствительно к регистру.
.Pp
По умолчанию устанавливаются страницы руководства для всех архитектур.
Поэтому этот параметр можно использовать для просмотра страниц для одной
архитектуры, работая в другой.
.Pp
Этот параметр переопределяет переменную окружения
.Ev MACHINE .
.Tg s
.It Oo Fl s Oc Ar section
Выбирать руководства только из указанного
.Ar section .
В настоящее время доступны следующие разделы:
.Pp
.Bl -tag -width "1" -compact
.It 1
Общие команды
.Pq инструменты и утилиты .
.It 2
Системные вызовы и номера ошибок.
.It 3
Библиотечные функции.
.It 3p
Справочное руководство программиста
.Xr perl 1 .
.It 4
Драйверы устройств.
.It 5
Форматы файлов.
.It 6
Игры.
.It 7
Разная информация.
.It 8
Команды сопровождения и работы системы.
.It 9
Внутреннее устройство ядра.
.El
.It Fl w
Вывести пути всех подходящих страниц руководства вместо отображения
каких-либо из них.
Если
.Ar name
не указано, вывести каталоги, которые были бы просмотрены.
.El
.Pp
Параметры
.Fl IKOTW
также поддерживаются и описаны в
.Xr mandoc 1 .
Параметры
.Fl fkl
взаимно исключают друг друга и переопределяют друг друга.
.Pp
Поиск начинается с аргумента
.Fl m ,
если он указан, затем продолжается с аргументом
.Fl M ,
переменной
.Ev MANPATH ,
записями
.Ic manpath
в файле
.Xr man.conf 5
или по умолчанию с
.Pa /usr/share/man : Ns Pa /usr/X11R6/man : Ns Pa /usr/local/man .
В каждом из них каталоги просматриваются в указанном порядке.
В каждом каталоге поиск выполняется в соответствии со следующим
списком разделов: 1, 8, 6, 2, 3, 5, 7, 4, 9, 3p.
Отображается первое найденное совпадение.
.Pp
База данных
.Xr mandoc.db 5
используется для поиска записей страниц руководства.
Если база данных отсутствует, устарела или повреждена,
.Nm
переходит к поиску файлов с именем
.Ar name . Ns Ar section .
Если в одном каталоге существуют и форматированная, и неформатированная
версии одной и той же страницы руководства, например
.Pa cat1/foo.0
и
.Pa man1/foo.1 ,
используется только неформатированная версия.
База данных поддерживается в актуальном состоянии с помощью
.Xr makewhatis 8 ,
который запускается сценарием обслуживания
.Xr weekly 8 .
.Pp
Рекомендации по написанию страниц руководства можно найти в
.Xr mdoc 7 .
.Sh ОКРУЖЕНИЕ
.Bl -tag -width MANPATHX
.It Ev MACHINE
Поскольку некоторые страницы руководства предназначены только для конкретных
архитектур,
.Nm
выполняет поиск в любых подкаталогах
с тем же именем, что и текущая архитектура,
в каждом каталоге, который он просматривает.
Области, специфичные для машины, проверяются перед общими областями.
Текущий тип машины можно переопределить, установив переменную окружения
.Ev MACHINE
в имя конкретной архитектуры
или с помощью параметра
.Fl S .
.Ev MACHINE
нечувствительна к регистру.
.It Ev MANPAGER
Любое непустое значение переменной окружения
.Ev MANPAGER
используется вместо стандартной программы постраничного вывода
.Xr less 1 .
Если используется
.Xr less 1 ,
интерактивную команду
.Ic :t
можно использовать для перехода к определениям различных терминов,
например параметров командной строки, модификаторов команд, внутренних
команд, переменных окружения, имён функций, макросов препроцессора,
значений
.Xr errno 2
и некоторых других выделенных слов.
У некоторых терминов определяющий текст может находиться более чем в одном
месте.
В этом случае интерактивные команды
.Ic t
и
.Ic T
в
.Xr less 1
можно использовать для перехода к следующему и предыдущему месту,
содержащему информацию о термине, который последним искался с помощью
.Ic :t .
Параметр
.Fl O Cm tag Ns Op = Ns Ar term ,
описанный в руководстве
.Xr mandoc 1 ,
открывает страницу руководства на определении конкретного
.Ar term ,
а не в начале.
.It Ev MANPATH
Переопределить стандартный путь поиска, который либо указан в
.Xr man.conf 5 ,
либо является путём по умолчанию.
Формат
.Ev MANPATH
— список каталогов, разделённых двоеточием
.Pq Ql \&: .
Недопустимые каталоги игнорируются.
Переопределяется параметром
.Fl M ,
игнорируется, если указан
.Fl l .
.Pp
Если
.Ev MANPATH
начинается с двоеточия, он добавляется в конец стандартного пути;
если заканчивается двоеточием, добавляется в начало;
а если содержит два соседних двоеточия,
стандартный путь вставляется между двоеточиями.
.It Ev PAGER
Указывает программу постраничного вывода, используемую, когда
.Ev MANPAGER
не определена.
Если не определена ни
.Ev PAGER ,
ни
.Ev MANPAGER ,
используется
.Xr less 1 .
.El
.Sh ФАЙЛЫ
.Bl -tag -width /etc/man.conf -compact
.It Pa /etc/man.conf
файл конфигурации
.Nm
по умолчанию
.El
.Sh СТАТУС ВЫХОДА
.Ex -std man
См.
.Xr mandoc 1
для подробностей.
.Sh ПРИМЕРЫ
Показать все страницы руководства, в которых упоминается переменная окружения
.Ev PWD :
.Pp
.Dl $ man -ak Ev=PWD
.Pp
Показать руководство
.Xr ksh 1
и перейти к месту, где описана встроенная команда
.Ic pwd :
.Pp
.Dl $ man -O tag=pwd ksh
.Pp
Эквивалентно: используйте команду
.Ql man ksh ,
затем введите
.Ql :tpwd
и нажмите клавишу возврата.
.Pp
Отформатировать страницу для вставки фрагментов в сообщение электронной почты \(em
избегать вывода любых символов UTF-8, уменьшить ширину для упрощения
цитирования в ответах и удалить разметку:
.Pp
.Dl $ man -T ascii -O width=65 pledge | col -b
.Pp
Прочитать набранную страницу в программе просмотра PDF:
.Pp
.Dl $ MANPAGER=mupdf man -T pdf lpd
.Sh СМ. ТАКЖЕ
.Xr apropos 1 ,
.Xr col 1 ,
.Xr mandoc 1 ,
.Xr ul 1 ,
.Xr whereis 1 ,
.Xr man.conf 5 ,
.Xr mdoc 7
.Sh СТАНДАРТЫ
Утилита
.Nm
соответствует спецификации
.St -p1003.1-2008 .
.Pp
Флаги
.Op Fl aCcfhIKlMmOSsTWw ,
а также переменные окружения
.Ev MACHINE ,
.Ev MANPAGER
и
.Ev MANPATH ,
являются расширениями к этой спецификации.
.Sh ИСТОРИЯ
Команда
.Nm
впервые появилась в
.At v2 .
.Pp
Параметр
.Fl w
впервые появился в
.At v7 ;
.Fl f
и
.Fl k
в
.Pa /usr/usb/man
в
.Bx 4.0 ;
.Fl M
в
.Bx 4.3 ;
.Fl a
в
.Bx 4.3 Tahoe ;
.Fl c
и
.Fl m
в
.Bx 4.3 Reno ;
.Fl h
в
.Bx 4.3 Net/2 ;
.Fl C
в
.Nx 1.0 ;
.Fl s
и
.Fl S
в
.Ox 2.3 ;
и
.Fl I ,
.Fl K ,
.Fl l ,
.Fl O
и
.Fl W
в
.Ox 5.7 .
Параметр
.Fl T
впервые появился в
.At III
и также был добавлен в
.Ox 5.7 .
