.\" Copyright (c) 2009 Gabor Kovesdan <gabor@FreeBSD.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Portions of this text are reprinted and reproduced in electronic form
.\" from IEEE Std 1003.1, 2004 Edition, Standard for Information Technology --
.\" Portable Operating System Interface (POSIX), The Open Group Base
.\" Specifications Issue 6, Copyright (C) 2001-2004 by the Institute of
.\" Electrical and Electronics Engineers, Inc and The Open Group.  In the
.\" event of any discrepancy between this version and the original IEEE and
.\" The Open Group Standard, the original IEEE and The Open Group Standard is
.\" the referee document.  The original Standard can be obtained online at
.\"     http://www.opengroup.org/unix/online.html.
.\"
.\" FRDP path ./usr.bin/mkesdb/mkesdb.1
.\" FRDP githash fa9896e082a1046ff4fbc75fcba4d18d1f2efc19
.\" FRDP hash256 28583086075aa2fb30ca0166287b865ff2cbd8f19ad7baa9bff2d489b83f84bc
.Dd 1 ноября 2009
.Dt MKESDB 1
.Os
.Sh ИМЯ
.Nm mkesdb
.Nd создает каталог преобразований для
.Xr iconv 3
.Sh СИНТАКСИС
.Nm
.Op Fl md
.Fl o
.Ar outfile
.Ar infile
.Sh ОПИСАНИЕ
Утилита
.Nm
генерирует каталог преобразований для библиотеки
.Xr iconv 3 .
Сгенерированные данные включают список поддерживаемых кодировок
и их наиболее важные характеристики, такие как используемый
подключаемый модуль.
.Pp
Доступны следующие опции:
.Bl -tag -width 0123
.It Fl d
Включает режим отладки.
.It Fl m
Обрабатывает каталог директорий или файл псевдонимов.
Если не указано, входной файл рассматривается как описание кодировки.
.It Fl o Ar outfile
Поместить сгенерированные двоичные данные в
.Ar outfile .
.El
.Sh СТАТУС ВЫХОДА
.Ex -std mkesdb
.Sh СМ. ТАКЖЕ
.Xr iconv 1 ,
.Xr mkcsmapper 1 ,
.Xr iconv 3
.Sh ИСТОРИЯ
.Nm
впервые появилась в
.Nx 2.0 , и стала доступна в
.Fx 9.0 .
.Sh АВТОРЫ
Эта страница руководства была написана
.An Gabor Kovesdan Aq Mt gabor@FreeBSD.org .
