.\" FRDP path usr.bin/nl/nl.1
.\" FRDP githash b2c76c41be32f904179efed29c0ca04d53f3996c
.\" FRDP hash256 0247654ea4837c810564d93265284e416ff9fef7d2f8642bc92d01c181e29f7a
.Dd July 24, 2022
.Dt NL 1
.Os
.Sh ИМЯ
.Nm nl
.Nd фильтр нумерации строк
.Sh СИНТАКСИС
.Nm
.Op Fl p
.Bk -words
.Op Fl b Ar type
.Ek
.Bk -words
.Op Fl d Ar delim
.Ek
.Bk -words
.Op Fl f Ar type
.Ek
.Bk -words
.Op Fl h Ar type
.Ek
.Bk -words
.Op Fl i Ar incr
.Ek
.Bk -words
.Op Fl l Ar num
.Ek
.Bk -words
.Op Fl n Ar format
.Ek
.Bk -words
.Op Fl s Ar sep
.Ek
.Bk -words
.Op Fl v Ar startnum
.Ek
.Bk -words
.Op Fl w Ar width
.Ek
.Op Ar file
.Sh ОПИСАНИЕ
Утилита
.Nm
читает строки из указанного
.Ar file ,
применяет настраиваемую операцию фильтрации с нумерацией строк
и записывает результат в стандартный вывод.
Если
.Ar file
— это одиночное тире
.Pq Sq Fl
или отсутствует,
.Nm
читает из стандартного ввода.
.Pp
Утилита
.Nm
рассматривает читаемый текст в терминах логических страниц.
Если не указано иное, нумерация строк сбрасывается в начале каждой
логической страницы.
Логическая страница состоит из разделов заголовка, тела и нижнего колонтитула;
пустые разделы допустимы.
Различные параметры нумерации строк
независимо доступны для разделов заголовка, тела и нижнего колонтитула.
.Pp
Начала разделов логической страницы сигнализируются входными строками, содержащими
только одну из следующих последовательностей символов-разделителей:
.El
.Pp
Если входные данные не содержат никаких директив, сигнализирующих о разделах логической страницы,
считается, что читаемый текст состоит из единственного тела логической страницы.
.Pp
Доступны следующие параметры:
.It Fl b Ar type
Указать строки тела логической страницы, которые должны быть пронумерованы.
Распознаваемые
аргументы
.Ar type :
.Bl -tag -width indent
.It Cm a
Нумеровать все строки.
.It Cm t
Нумеровать только непустые строки.
.It Cm n
Не нумеровать строки.
.It Cm p Ns Ar expr
Нумеровать только те строки, которые содержат базовое регулярное выражение, заданное
.Ar expr .
.El
.Pp
По умолчанию
.Ar type
для строк тела логической страницы —
.Cm t .
.It Fl d Ar delim
Указать символы-разделители, используемые для обозначения начала раздела логической
страницы во входном файле.
Можно указать не более двух символов;
если указан только один символ, первый символ заменяется, а
второй символ остаётся неизменным.
По умолчанию
символы
.Ar delim
—
.Dq Li \e: .
.It Fl f Ar type
Указать то же, что и
.Fl b Ar type ,
но для строк нижнего колонтитула логической страницы.
По умолчанию
.Ar type
для строк нижнего колонтитула логической страницы —
.Cm n .
.It Fl h Ar type
Указать то же, что и
.Fl b Ar type ,
но для строк заголовка логической страницы.
По умолчанию
.Ar type
для строк заголовка логической страницы —
.Cm n .
.It Fl i Ar incr
Указать значение приращения, используемое для нумерации строк логической страницы.
По умолчанию
значение
.Ar incr
— 1.
.It Fl l Ar num
Если для текущего логического раздела указана нумерация всех строк
с помощью соответствующего параметра
.Fl b Cm a ,
.Fl f Cm a
или
.Fl h Cm a ,
указать количество соседних пустых строк, считаемых за одну.
Например,
.Fl l
2 приводит к тому, что нумеруется только вторая соседняя пустая строка.
По умолчанию
значение
.Ar num
— 1.
.It Fl n Ar format
Указать формат вывода нумерации строк.
Распознаваемые
аргументы
.Ar format :
.Bl -tag -width indent -compact
.It Cm ln
Выравнивание по левому краю.
.It Cm rn
Выравнивание по правому краю, ведущие нули подавляются.
.It Cm rz
Выравнивание по правому краю, ведущие нули сохраняются.
.El
.Pp
По умолчанию
.Ar format
—
.Cm rn .
.It Fl p
Указать, что нумерация строк не должна перезапускаться на разделителях логических страниц.
.It Fl s Ar sep
Указать символы, используемые для отделения номера строки от соответствующей
строки текста.
По умолчанию
.Ar sep
— одиночный символ табуляции.
.It Fl v Ar startnum
Указать начальное значение, используемое для нумерации строк логической страницы; см. также
описание
параметра
.Fl p .
По умолчанию
значение
.Ar startnum
— 1.
.It Fl w Ar width
Указать количество символов, занимаемых номером строки;
в случае, если
.Ar width
недостаточна для размещения номера строки, он будет усечён до своих
.Ar width
младших значащих цифр.
По умолчанию
.Ar width
— 6.
.El
.Sh ОКРУЖЕНИЕ
Переменные окружения
.Ev LANG , LC_ALL , LC_CTYPE
и
.Ev LC_COLLATE
влияют на выполнение
.Nm
как описано в
.Xr environ 7 .
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
Пронумеровать все непустые строки:
.Bd -literal -offset indent
     1  This is


     2  a simple text
.Ed
.Pp
Пронумеровать все строки, включая пустые, с выравниванием номеров строк по правому краю
с ведущими нулями, начиная с 2, с приращением 2 и настраиваемым многосимвольным
разделителем:
.Bd -literal -offset indent
000002->This
000004->is
000006->an
000008->
000010->
000012->example
.Ed
.Pp
Пронумеровать строки, соответствующие регулярному выражению для
.Em i
.No с последующим
.Em m
.No или
.Em n
.Bd -literal -offset indent
        This is
     1  a simple text
        with multiple
     2  lines
.Ed
.Sh СМ. ТАКЖЕ
.Xr jot 1 ,
.Xr pr 1
.Sh СТАНДАРТЫ
Утилита
.Nm
соответствует
.St -p1003.1-2001 .
.Sh ИСТОРИЯ
Утилита
.Nm
впервые появилась в
.At III .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Входные строки ограничены
.Dv LINE_MAX
(2048) байтами в длину.
