.\" FRDP path usr.bin/nohup/nohup.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 55602d08e0d7060ff6cadb0a908e6adaecb05fa492cdaa4c5970d3f5245dc2de
.Dd June 26, 2023
.Dt NOHUP 1
.Os
.Sh ИМЯ
.Nm nohup
.Nd вызов утилиты, невосприимчивой к разрыву связи
.Sh СИНТАКСИС
.Nm
.Op Fl Fl
.Ar utility
.Op Ar arguments
.Sh ОПИСАНИЕ
Утилита
.Nm
вызывает
.Ar utility
с его
.Ar arguments
и в этот момент устанавливает сигнал
.Dv SIGHUP
как игнорируемый.
Если стандартный вывод является терминалом, стандартный вывод
дописывается в файл
.Pa nohup.out
в текущем каталоге.
Если стандартный поток ошибок является терминалом, он направляется в то же место,
что и стандартный вывод.
.Pp
Некоторые оболочки могут предоставлять встроенную команду
.Nm
, которая похожа на эту утилиту или идентична ей.
Обратитесь к
странице руководства
.Xr builtin 1 .
.Sh ОКРУЖЕНИЕ
Следующие переменные используются
.Nm :
.Bl -tag -width flag
.It Ev HOME
Если выходной файл
.Pa nohup.out
не может быть создан в текущем каталоге, утилита
.Nm
использует каталог, указанный в
.Ev HOME ,
для создания файла.
.It Ev PATH
Используется для поиска запрошенной
.Ar utility ,
если имя не содержит
.Ql /
символов.
.El
.Sh СТАТУС ВЫХОДА
Утилита
.Nm
завершается с одним из следующих значений:
.Bl -tag -width Ds
.It 126
.Ar utility
была найдена, но не может быть вызвана.
.It 127
.Ar utility
не может быть найдена или в
.Nm
произошла ошибка.
.El
.Pp
В остальных случаях статус выхода
.Nm
будет таким же, как у
.Ar utility .
.Sh СМ. ТАКЖЕ
.Xr builtin 1 ,
.Xr csh 1 ,
.Xr timeout 1 ,
.Xr signal 3 ,
.Xr daemon 8
.Sh СТАНДАРТЫ
Ожидается, что утилита
.Nm
совместима с
.St -p1003.2 .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Два или более экземпляра
.Nm
могут дописывать в один и тот же файл, что приводит к запутанному выводу.
