.\" FRDP path usr.bin/passwd/passwd.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 2837fe0915fdb44214604c67be653b50a984335b1be614dbc3d559377faad201
.Dd February 14, 2014
.Dt PASSWD 1
.Os
.Sh ИМЯ
.Nm passwd , yppasswd
.Nd изменение пароля пользователя
.Sh СИНТАКСИС
.Nm
.Op Fl l
.Op Ar user
.Nm yppasswd
.Op Fl l
.Op Fl y
.Op Fl d Ar domain
.Op Fl h Ar host
.Op Fl o
.Sh ОПИСАНИЕ
Утилита
.Nm
изменяет локальный, Kerberos- или NIS-пароль пользователя.
Если пользователь не является суперпользователем,
.Nm
сначала запрашивает текущий пароль и не продолжит работу, пока не будет введён правильный
пароль.
.Pp
При вводе нового пароля введённые символы не отображаются, чтобы
избежать того, что пароль увидит прохожий.
Утилита
.Nm
запрашивает новый пароль дважды, чтобы обнаружить ошибки ввода.
.Pp
Общая длина пароля должна быть меньше
.Dv _PASSWORD_LEN
(в настоящее время 128 символов).
.Pp
После проверки пароля
.Nm
передаёт информацию о новом пароле
хосту аутентификации Kerberos.
.Pp
Доступен следующий параметр:
.Bl -tag -width indent
.It Fl l
Обновлять пароль только в локальном
файле паролей, а не в базе данных Kerberos.
При изменении только локального пароля
используется
.Xr pwd_mkdb 8
для обновления баз данных паролей.
.El
.Pp
При изменении локального пароля или пароля NIS следующая дата смены пароля
устанавливается в соответствии с возможностью
.Dq passwordtime
в классе входа пользователя.
.Pp
Чтобы изменить Kerberos-пароль другого пользователя, нужно сначала
запустить
.Xr kinit 1 ,
а затем
.Nm .
Суперпользователь не обязан предоставлять текущий пароль пользователя,
если изменяется только локальный пароль.
.Sh ВЗАИМОДЕЙСТВИЕ С NIS
Утилита
.Nm
имеет встроенную поддержку NIS.
Если пользователь существует в базе данных паролей NIS,
но не существует локально,
.Nm
автоматически переключается в
режим
.Nm yppasswd .
Если указанный
пользователь не существует ни в локальной базе данных паролей, ни в
картах паролей NIS,
.Nm
возвращает ошибку.
.Pp
При изменении пароля NIS непривилегированные пользователи обязаны предоставить
свой старый пароль для аутентификации (демон
.Xr rpc.yppasswdd 8
требует исходный пароль, прежде чем
разрешить любые изменения в картах паролей NIS).
Это ограничение применяется даже к
суперпользователю, с одним важным исключением: аутентификация по паролю
обходится для суперпользователя на главном сервере NIS.
Это означает, что
суперпользователь на главном сервере NIS может вносить неограниченные изменения в
любой пароль NIS.
Суперпользователь на клиентских системах NIS и подчинённых
серверах NIS всё ещё должен предоставить пароль, прежде чем обновление будет обработано.
.Pp
Следующие дополнительные параметры поддерживаются для использования с NIS:
.Bl -tag -width indent
.It Fl y
Переопределить
эвристики проверки
.Nm Ns
и принудительно
перевести её в режим NIS.
.It Fl l
Когда NIS включён, флаг
.Fl l
можно использовать, чтобы заставить
.Nm
перейти в
режим
.Dq только локально .
Этот флаг можно использовать для изменения записи
локального пользователя, когда существует пользователь NIS с тем же именем входа.
Например, иногда можно найти записи для системных
.Dq заполнителей
пользователей, таких как
.Pa bin
или
.Pa daemon ,
как в картах паролей NIS, так и в локальной базе данных пользователей.
По
умолчанию
.Nm
попытается изменить пароль NIS.
Флаг
.Fl l
можно использовать для изменения вместо этого локального пароля.
.It Fl d Ar domain
Указать, какой домен использовать при изменении пароля NIS.
По умолчанию
.Nm
предполагает, что следует использовать системный домен по умолчанию.
Этот флаг
предназначен в первую очередь для использования суперпользователем на главном сервере NIS: один
сервер NIS может поддерживать несколько доменов.
Также возможно, что
доменное имя на главном сервере NIS может быть не задано (не обязательно, чтобы
сервер NIS также был клиентом), и в этом случае
команде
.Nm
нужно сообщить, с каким доменом работать.
.It Fl h Ar host
Указать имя сервера NIS.
Этот параметр в сочетании
с параметром
.Fl d
можно использовать для изменения пароля NIS на нелокальном сервере
NIS.
Когда домен указан с помощью
параметра
.Fl d
и
.Nm
не может определить имя главного сервера NIS (возможно, потому что
локальное доменное имя не задано), предполагается, что имя главного сервера NIS —
.Dq localhost .
Это можно переопределить с помощью
флага
.Fl h .
Указанное имя хоста не обязательно должно быть именем главного сервера NIS:
имя главного сервера NIS для данной карты можно определить, запросив любой
сервер NIS (главный или подчинённый) в домене, поэтому указание имени
подчинённого сервера сработает так же хорошо.
.It Fl o
Не переопределять автоматически проверки аутентификации по паролю для
суперпользователя на главном сервере NIS; вместо этого предполагать
.Dq старый
режим.
Этот
флаг имеет ограниченное практическое применение, но полезен для тестирования.
.El
.Sh ФАЙЛЫ
.Bl -tag -width /etc/master.passwd -compact
.It Pa /etc/master.passwd
база данных пользователей
.It Pa /etc/passwd
файл паролей формата Version 7
.It Pa /etc/passwd.XXXXXX
временная копия файла паролей
.It Pa /etc/login.conf
база данных возможностей классов входа
.El
.Sh СМ. ТАКЖЕ
.Xr chpass 1 ,
.Xr kinit 1 ,
.Xr login 1 ,
.Xr login.conf 5 ,
.Xr passwd 5 ,
.Xr kerberos 8 ,
.Xr kpasswdd 8 ,
.Xr pam_passwdqc 8 ,
.Xr pw 8 ,
.Xr pwd_mkdb 8 ,
.Xr vipw 8
.Rs
.%A Robert Morris
.%A Ken Thompson
.Re
.Sh ПРИМЕЧАНИЯ
Команда
.Nm yppasswd
на самом деле является всего лишь ссылкой на
.Nm .
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v6 .
