.\" FRDP path bin/pax/pax.1
.\" FRDP githash 90aea514c6249118e880d75972d063362f4bf492
.\" FRDP hash256 bd789ca6e50eb0bc8ea656c3070270e7dfbb52d40764831631645277a3212941
.Dd October 19, 2022
.Dt PAX 1
.Os
.Sh ИМЯ
.Nm pax
.Nd читать и записывать архивы файлов и копировать иерархии каталогов
.Sh СИНТАКСИС
.Nm
.Op Fl cdnvzO
.Bk -words
.Op Fl f Ar архив
.Ek
.Bk -words
.Op Fl s Ar строка_замены
.Ar ...\&
.Ek
.Bk -words
.Op Fl U Ar пользователь
.Ar ...\&
.Ek
.Bk -words
.Op Fl G Ar группа
.Ar ...\&
.Ek
.Bk -words
.Oo
.Fl T
.Op Ar от_дата
.Op Ar ,до_дата
.Oc
.Ar ...\&
.Ek
.Op Ar шаблон ...\&
.Nm
.Fl r
.Op Fl cdiknuvzDOYZ
.Bk -words
.Op Fl f Ar архив
.Ek
.Bk -words
.Op Fl o Ar параметры
.Ar ...\&
.Ek
.Bk -words
.Op Fl p Ar строка
.Ar ...\&
.Ek
.Bk -words
.Op Fl s Ar строка_замены
.Ar ...\&
.Ek
.Op Fl E Ar предел
.Bk -words
.Op Fl U Ar пользователь
.Ar ...\&
.Ek
.Bk -words
.Op Fl G Ar группа
.Ar ...\&
.Ek
.Bk -words
.Oo
.Fl T
.Op Ar от_дата
.Op Ar ,до_дата
.Oc
.Ar ...\&
.Ek
.Op Ar шаблон ...\&
.Nm
.Fl w
.Op Fl dituvzHLOPX
.Bk -words
.Op Fl b Ar размер_блока
.Ek
.Oo
.Op Fl a
.Op Fl f Ar архив
.Oc
.Bk -words
.Op Fl x Ar формат
.Ek
.Bk -words
.Op Fl s Ar строка_замены
.Ar ...\&
.Ek
.Bk -words
.Op Fl o Ar параметры
.Ar ...\&
.Ek
.Bk -words
.Op Fl U Ar пользователь
.Ar ...\&
.Ek
.Bk -words
.Op Fl G Ar группа
.Ar ...\&
.Ek
.Bk -words
.Op Fl B Ar байты
.Ek
.Bk -words
.Oo
.Fl T
.Op Ar от_дата
.Op Ar ,до_дата
.Op Ar /[c][m]
.Oc
.Ar ...\&
.Ek
.Op Ar
.Nm
.Fl r
.Fl w
.Op Fl diklntuvDHLOPXYZ
.Bk -words
.Op Fl p Ar строка
.Ar ...\&
.Ek
.Bk -words
.Op Fl s Ar строка_замены
.Ar ...\&
.Ek
.Bk -words
.Op Fl U Ar пользователь
.Ar ...\&
.Ek
.Bk -words
.Op Fl G Ar группа
.Ar ...\&
.Ek
.Bk -words
.Oo
.Fl T
.Op Ar от_дата
.Op Ar ,до_дата
.Op Ar /[c][m]
.Oc
.Ar ...\&
.Ek
.Op Ar
.Ar каталог
.Sh ОПИСАНИЕ
Утилита
.Nm
читает, записывает и выводит список членов архивного файла,
а также копирует иерархии каталогов.
Эти операции не зависят от конкретного формата архива
и поддерживают широкий набор различных форматов архивов.
Список поддерживаемых форматов архивов можно найти в описании
опции
.Fl x .
.Pp
Наличие опций
.Fl r
и
.Fl w
определяет, в каком из следующих функциональных режимов
.Nm
будет работать:
.Em список , чтение , запись
и
.Em копирование .
.Bl -tag -width 6n
.It <none>
.Em Список .
Записывает в
.Dv стандартный вывод
таблицу содержимого членов архивного файла, читаемого из
.Dv стандартного ввода ,
чьи путевые имена соответствуют указанным
.Ar шаблонам .
Таблица содержимого содержит одно имя файла на строку
и записывается с использованием построчной буферизации.
.It Fl r
.Em Чтение .
Извлекает члены архивного файла, читаемого из
.Dv стандартного ввода ,
с путевыми именами, соответствующими указанным
.Ar шаблонам .
Формат архива и блокировка определяются автоматически при вводе.
Когда извлекаемый файл является каталогом, извлекается вся иерархия файлов,
корнем которой является этот каталог.
Все извлечённые файлы создаются относительно текущей иерархии файлов.
Установка владельца, времён доступа и модификации, а также режима файла для
извлечённых файлов подробно обсуждается в описании опции
.Fl p .
.It Fl w
.Em Запись .
Записывает архив, содержащий
.Ar файл
операнды, в
.Dv стандартный вывод
с использованием указанного формата архива.
Когда никакие
.Ar файл
операнды не указаны, из
.Dv стандартного ввода
читается список файлов для копирования по одному на строку.
Когда
.Ar файл
операнд также является каталогом, будет включена вся иерархия файлов,
корнем которой является этот каталог.
.It Fl r Fl w
.Em Копирование .
Копирует
.Ar файл
операнды в целевой
.Ar каталог .
Когда никакие
.Ar файл
операнды не указаны, из
.Dv стандартного ввода
читается список файлов для копирования по одному на строку.
Когда
.Ar файл
операнд также является каталогом, будет включена вся иерархия файлов,
корнем которой является этот каталог.
Эффект
.Em копирования
таков, как если бы скопированные файлы были записаны в архивный файл, а затем
извлечены, за исключением того, что между исходными и скопированными файлами
могут существовать жёсткие ссылки (см. опцию
.Fl l
ниже).
.Pp
.Em Предупреждение :
Целевой
.Ar каталог
не должен быть одним из
.Ar файл
операндов или членом иерархии файлов, корнем которой является один из
.Ar файл
операндов.
Результат
.Em копирования
в таких условиях непредсказуем.
.El
.Pp
При обработке повреждённого архива во время операции
.Em чтения
или
.Em списка ,
.Nm
попытается восстановиться после дефектов носителя и будет просматривать архив,
чтобы найти и обработать как можно больше членов архива (см. опцию
.Fl E
для получения дополнительных сведений об обработке ошибок).
.Sh ОПЕРАНДЫ
Операнд
.Ar каталог
задаёт путевое имя целевого каталога.
Если операнд
.Ar каталог
не существует, или не доступен пользователю для записи,
или не является каталогом,
.Nm
завершится с ненулевым статусом выхода.
.Pp
Операнд
.Ar шаблон
используется для выбора одного или нескольких путевых имён членов архива.
Члены архива выбираются с использованием нотации сопоставления с образцом,
описанной в
.Xr fnmatch 3 .
Когда операнд
.Ar шаблон
не указан, будут выбраны все члены архива.
Когда
.Ar шаблон
соответствует каталогу, будет выбрана вся иерархия файлов, корнем которой
является этот каталог.
Когда операнд
.Ar шаблон
не выбирает хотя бы один член архива,
.Nm
запишет эти операнды
.Ar шаблон
в диагностическое сообщение в
.Dv стандартный поток ошибок
и затем завершится с ненулевым статусом выхода.
.Pp
Операнд
.Ar файл
задаёт путевое имя файла, который нужно скопировать или архивировать.
Когда операнд
.Ar файл
не выбирает хотя бы один член архива,
.Nm
запишет эти путевые имена операндов
.Ar файл
в диагностическое сообщение в
.Dv стандартный поток ошибок
и затем завершится с ненулевым статусом выхода.
.Sh ОПЦИИ
Поддерживаются следующие опции:
.Bl -tag -width 4n
.It Fl r
Читает архивный файл из
.Dv стандартного ввода
и извлекает указанные
.Ar файлы .
Если для извлечения члена архива требуются промежуточные каталоги,
эти каталоги будут созданы так, как если бы
.Xr mkdir 2
был вызван с побитовым включающим
.Dv OR
из
.Dv S_IRWXU , S_IRWXG
и
.Dv S_IRWXO
в качестве аргумента режима.
Если выбранный формат архива поддерживает указание связанных файлов
и эти файлы не могут быть связаны во время извлечения архива,
.Nm
запишет диагностическое сообщение в
.Dv стандартный поток ошибок
и завершится с ненулевым статусом выхода по завершении операции.
.It Fl w
Записывает файлы в
.Dv стандартный вывод
в указанном формате архива.
Когда операнды
.Ar файл
не указаны,
.Dv стандартный ввод
читается для получения списка путевых имён по одному на строку без ведущих или
завершающих
.Aq пробелов .
.It Fl a
Добавляет
.Ar файлы
в конец архива, который был записан ранее.
Если формат архива не указан с помощью опции
.Fl x ,
будет выбран формат, используемый в архиве в данный момент.
Любая попытка добавить в архив в формате, отличном от
формата, уже используемого в архиве, заставит
.Nm
немедленно завершиться
с ненулевым статусом выхода.
Размер блокировки, используемый в томе архива, где начинается запись,
будет продолжать использоваться для остальной части этого тома архива.
.Pp
.Em Предупреждение :
Многие устройства хранения не способны поддерживать операции, необходимые
для выполнения операции добавления.
Любая попытка добавить в архив, хранящийся на таком устройстве, может повредить
архив или привести к другим непредсказуемым результатам.
В частности, ленточные накопители с большей вероятностью не поддерживают
операцию добавления.
Архив, хранящийся в обычном файле файловой системы или на дисковом устройстве,
обычно поддерживает операцию добавления.
.It Fl b Ar размер_блока
При
.Em записи
архива блокирует вывод по положительному десятичному целому числу
байтов на одну запись в архивный файл.
.Ar размер_блока
должен быть кратен 512 байтам, максимум 64512 байтов.
.Ar размер_блока
больше 32256 байтов нарушает стандарт
.Tn POSIX
и не будет переносимым на все системы.
.Ar размер_блока
может заканчиваться на
.Li k
или
.Li b
чтобы указать умножение на 1024 (1K) или 512 соответственно.
Пара
.Ar размер_блока
может быть разделена
.Li x
для указания произведения.
Конкретное устройство архива может налагать дополнительные ограничения на размер
блокировки, которую оно поддерживает.
Когда блокировка не указана, значение по умолчанию
.Ar размер_блока
зависит от используемого формата архива (см. опцию
.Fl x ).
.It Fl c
Сопоставляет все файлы или членов архива
.Em кроме
указанных операндами
.Ar шаблон
и
.Ar файл .
.It Fl d
Заставляет файлы типа каталог, копируемые или архивируемые, или члены архива
типа каталог, извлекаемые, соответствовать только файлу каталога или члену архива,
а не иерархии файлов, корнем которой является каталог.
.It Fl f Ar архив
Указывает
.Ar архив
как путевое имя входного или выходного архива, переопределяя значение по умолчанию
.Dv стандартный ввод
(для
.Em списка
и
.Em чтения )
или
.Dv стандартный вывод
(для
.Em записи ).
Один архив может занимать несколько файлов и различных устройств архива.
При необходимости
.Nm
запросит путевое имя файла или устройства следующего тома архива.
.It Fl i
Интерактивно переименовывает файлы или членов архива.
Для каждого члена архива, соответствующего операнду
.Ar шаблон ,
или каждого файла, соответствующего операнду
.Ar файл ,
.Nm
выдаст запрос в
.Pa /dev/tty
указав имя файла, его режим и время модификации.
Утилита
.Nm
затем прочитает строку из
.Pa /dev/tty .
Если эта строка пуста, файл или член архива пропускается.
Если эта строка состоит из одной точки, файл или член архива обрабатывается
без изменения его имени.
В противном случае его имя заменяется содержимым строки.
Утилита
.Nm
немедленно завершится с ненулевым статусом выхода, если
.Dv <EOF>
встретится при чтении ответа или если
.Pa /dev/tty
не может быть открыт для чтения и записи.
.It Fl k
Не перезаписывать существующие файлы.
.It Fl l
Связывать файлы.
(Буква ell).
В режиме
.Em копирования
.Pq Fl r w ,
между исходной и целевой иерархиями файлов создаются жёсткие ссылки,
когда это возможно.
.It Fl n
Выбирает первый член архива, соответствующий каждому
.Ar шаблон
операнду.
Для каждого
.Ar шаблона
сопоставляется не более одного члена архива.
Когда сопоставляются члены типа каталог, также сопоставляется иерархия файлов,
корнем которой является этот каталог (если только
.Fl d
также не указана).
.It Fl o Ar параметры
Информация для изменения алгоритма извлечения или записи архивных файлов,
специфичная для формата архива, указанного
.Fl x .
В общем случае
.Ar параметры
имеют вид:
.Cm name=value
.It Fl p Ar строка
Указывает одну или несколько опций характеристик файла (привилегий).
Аргумент-опция
.Ar строка
— это строка, задающая характеристики файла, которые следует сохранить или
отбросить при извлечении.
Строка состоит из символов спецификации
.Cm a , e , m , o ,
и
.Cm p .
Несколько характеристик можно объединить в одной строке
и можно указать несколько
.Fl p
опций.
Значения символов спецификации следующие:
.Bl -tag -width 2n
.It Cm a
Не сохранять времена доступа к файлу.
По умолчанию времена доступа к файлу сохраняются, когда это возможно.
.It Cm e
.Sq Сохранить всё ,
идентификатор пользователя, идентификатор группы, биты режима файла,
время доступа к файлу и время модификации файла.
Это предназначено для использования
.Em root ,
обладающим всеми необходимыми привилегиями, чтобы сохранить все
аспекты файлов в том виде, в каком они записаны в архиве.
Флаг
.Cm e
является суммой флагов
.Cm o
и
.Cm p .
.It Cm m
Не сохранять времена модификации файлов.
По умолчанию времена модификации файлов сохраняются, когда это возможно.
.It Cm o
Сохранять идентификатор пользователя и идентификатор группы.
.It Cm p
.Sq Сохранить
биты режима файла.
Это предназначено для использования
.Em пользователем
с обычными привилегиями, который хочет сохранить все аспекты файла, кроме
владения.
Времена файла по умолчанию сохраняются, но предлагаются два других флага,
чтобы отключить это и вместо этого использовать время извлечения.
.El
.Pp
В предыдущем списке
.Sq сохранить
означает, что атрибут, хранящийся в архиве, присваивается извлечённому файлу
с учётом разрешений вызывающего процесса.
В противном случае атрибут извлечённого файла определяется как
часть обычного действия по созданию файла.
Если не указан ни символ спецификации
.Cm e ,
ни
.Cm o ,
или идентификатор пользователя и идентификатор группы не сохраняются по какой-либо
причине,
.Nm
не будет устанавливать
.Dv S_ISUID
.Em ( setuid )
и
.Dv S_ISGID
.Em ( setgid )
биты режима файла.
Если сохранение любого из этих элементов не удаётся по какой-либо причине,
.Nm
запишет диагностическое сообщение в
.Dv стандартный поток ошибок .
Неудача сохранения этих элементов повлияет на итоговый статус выхода,
но не приведёт к удалению извлечённого файла.
Если буквы характеристик файла в любом из строковых аргументов-опций
дублируются или конфликтуют друг с другом, преимущество имеют те,
что указаны последними.
Например, если
.Dl Fl p Ar eme
указано, времена модификации файлов всё равно сохраняются.
.Pp
Флаги файлов, устанавливаемые
.Xr chflags 1
не понимаются
.Nm ,
однако
.Xr tar 1
и
.Xr dump 8
их сохраняют.
.It Fl s Ar строка_замены
Изменяет имена файлов или членов архива, указанные
.Ar шаблон
или
.Ar файл
операндами, в соответствии с выражением подстановки
.Ar строка_замены ,
используя синтаксис регулярных выражений утилиты
.Xr ed 1 .
Формат этих регулярных выражений:
.Dl /old/new/[gp]
Как и в
.Xr ed 1 ,
.Cm old
— базовое регулярное выражение, а
.Cm new
может содержать амперсанд (&), обратные ссылки \\n (где n — цифра)
или сопоставление подвиражений.
Строка
.Cm old
также может содержать
.Dv <newline>
символы.
Любой ненулевой символ может использоваться в качестве разделителя (/ показан здесь).
Несколько
.Fl s
выражений можно указать.
Выражения применяются в том порядке, в котором они указаны в
командной строке, и завершаются при первой успешной подстановке.
Необязательный завершающий
.Cm g
продолжает применять выражение подстановки к подстроке путевого имени,
которая начинается с первого символа после конца последней успешной
подстановки.
Первая неуспешная подстановка останавливает действие
.Cm g
опции.
Необязательный завершающий
.Cm p
приводит к записи окончательного результата успешной подстановки в
.Dv стандартный поток ошибок
в следующем формате:
.Dl <исходное путевое имя> >> <новое путевое имя>
Имена файлов или членов архива, которые подставляются в пустую строку,
не выбираются и пропускаются.
.It Fl t
Сбрасывает времена доступа любого файла или каталога, прочитанного или
к которому обращался
.Nm
к значениям, которые были до чтения или обращения
.Nm .
.It Fl u
Игнорирует файлы, которые старше (имеют менее позднее время модификации файла)
чем уже существующий файл или член архива с тем же именем.
Во время
.Em чтения
член архива с тем же именем, что и файл в файловой системе, будет
извлечён, если член архива новее файла.
Во время
.Em записи
элемент файловой системы с тем же именем, что и член архива, будет
записан в архив, если он новее члена архива.
Во время
.Em копирования
файл в целевой иерархии заменяется файлом в исходной иерархии
или ссылкой на файл в исходной иерархии, если файл в исходной иерархии новее.
.It Fl v
Во время операции
.Em списка
создаёт подробную таблицу содержимого, используя формат утилиты
.Xr ls 1
с опцией
.Fl l .
Для путевых имён, представляющих жёсткую ссылку на предыдущий член архива,
вывод имеет формат:
.Dl <вывод ls -l> == <имя ссылки>
Для путевых имён, представляющих символическую ссылку, вывод имеет формат:
.Dl <вывод ls -l> => <имя ссылки>
Где <вывод ls -l> — формат вывода, задаваемый утилитой
.Xr ls 1
при использовании с опцией
.Fl l .
В противном случае для всех остальных режимов работы
.Em ( чтение , запись
и
.Em копирование ) ,
путевые имена записываются и сбрасываются в
.Dv стандартный поток ошибок
без завершающего
.Dv <newline>
как только начинается обработка этого файла или члена архива.
Завершающий
.Dv <newline> ,
не буферизуется и записывается только после того, как файл был прочитан или
записан.
.It Fl x Ar формат
Указывает выходной формат архива; формат по умолчанию —
.Ar ustar .
Утилита
.Nm
в настоящее время поддерживает следующие форматы:
.Bl -tag -width 4n
.It Ar cpio
Расширенный формат обмена cpio, указанный в
.St -p1003.2
стандарте.
Размер блока по умолчанию для этого формата — 5120 байтов.
Информация об inode и устройстве файла (используемая этим форматом для
обнаружения жёстких ссылок на файлы), которая может быть усечена этим форматом,
обнаруживается
.Nm
и исправляется.
.It Ar bcpio
Старый двоичный формат cpio.
Размер блока по умолчанию для этого формата — 5120 байтов.
Этот формат не очень переносим, и его не следует использовать, когда доступны
другие форматы.
Информация об inode и устройстве файла (используемая этим форматом для
обнаружения жёстких ссылок на файлы), которая может быть усечена этим форматом,
обнаруживается
.Nm
и исправляется.
.It Ar sv4cpio
cpio из System V release 4.
Размер блока по умолчанию для этого формата — 5120 байтов.
Информация об inode и устройстве файла (используемая этим форматом для
обнаружения жёстких ссылок на файлы), которая может быть усечена этим форматом,
обнаруживается
.Nm
и исправляется.
.It Ar sv4crc
cpio из System V release 4 с контрольными суммами crc файлов.
Размер блока по умолчанию для этого формата — 5120 байтов.
Информация об inode и устройстве файла (используемая этим форматом для
обнаружения жёстких ссылок на файлы), которая может быть усечена этим форматом,
обнаруживается
.Nm
и исправляется.
.It Ar tar
Старый
.Bx
формат tar, как в
.Bx 4.3 .
Размер блока по умолчанию для этого формата — 10240 байтов.
Путевые имена, сохраняемые этим форматом, должны иметь длину 100 символов или
меньше.
Будут архивироваться только
.Em обычные
файлы,
.Em жёсткие ссылки , символические ссылки
и
.Em каталоги
(другие типы файловых систем не поддерживаются).
Для обратной совместимости с ещё более старыми форматами tar при записи архива
можно использовать опцию
.Fl o ,
чтобы опустить сохранение каталогов.
Эта опция имеет вид:
.Dl Fl o Cm write_opt=nodir
.It Ar ustar
Расширенный формат обмена tar, указанный в
.St -p1003.2
стандарте.
Размер блока по умолчанию для этого формата — 10240 байтов.
Путевые имена, сохраняемые этим форматом, должны иметь длину 255 символов или
меньше.
Часть каталога может быть не более 155 символов, а каждый компонент пути
должен быть меньше 100 символов.
.El
.Pp
Утилита
.Nm
обнаружит и сообщит о любом файле, который она не может сохранить или извлечь
в результате ограничений конкретного формата архива.
Отдельные форматы архивов могут налагать дополнительные ограничения на использование.
Типичные ограничения форматов архивов включают (но не ограничиваются):
длину путевого имени файла, размер файла, длину путевого имени ссылки и тип файла.
.It Fl z
Использовать
.Xr gzip 1
для сжатия (распаковки) архива при записи (чтении).
Несовместимо с
.Fl a .
.It Fl B Ar байты
Ограничивает количество байтов, записываемых в один том архива, значением
.Ar байты .
Предел
.Ar байты
может заканчиваться на
.Li m ,
.Li k ,
или
.Li b
чтобы указать умножение на 1048576 (1M), 1024 (1K) или 512 соответственно.
Пара пределов
.Ar байты
может быть разделена
.Li x
для указания произведения.
.Pp
Обратите внимание, что указанный размер относится к самому несжатому образу pax.
Если также используется опция
.Fl z ,
результирующий файл может содержать меньше
.Ar байтов ,
в зависимости от сжимаемости содержимого архива.
См.
.Xr zip 1 Pq Pa ports/archivers/zip
если требуются сжатые тома предсказуемого размера.
.Pp
.Em Предупреждение :
Используйте эту опцию только при записи архива на устройство, которое поддерживает
условие конца файла при чтении, основанное на последнем (или наибольшем) смещении
записи (например, обычный файл или ленточный накопитель).
Использование этой опции с гибким или жёстким диском не рекомендуется.
.It Fl D
Эта опция аналогична опции
.Fl u ,
за исключением того, что проверяется время изменения inode файла вместо
времени модификации файла.
Время изменения inode файла можно использовать для выбора файлов, информация
inode которых (например, uid, gid и т.д.) новее, чем копия файла в целевом
.Ar каталоге .
.It Fl E Ar предел
Ограничивает количество последовательных ошибок чтения при попытке прочитать
повреждённый архив значением
.Ar предел .
При положительном
.Ar пределе
.Nm
попытается восстановиться после ошибки чтения архива и будет
продолжать обработку, начиная со следующего файла, хранящегося в архиве.
.Ar предел ,
равный 0, заставит
.Nm
остановить работу после обнаружения первой ошибки чтения на томе архива.
.Ar предел ,
равный
.Li NONE ,
заставит
.Nm
пытаться восстанавливаться после ошибок чтения бесконечно.
По умолчанию
.Ar предел
— небольшое положительное число повторных попыток.
.Pp
.Em Предупреждение :
Использование этой опции с
.Li NONE
требует крайней осторожности, так как
.Nm
может застрять в бесконечном цикле на очень сильно повреждённом архиве.
.It Fl G Ar группа
Выбирает файл по его
.Ar группа
имени или, если оно начинается с
.Cm # ,
по числовому gid.
Символ '\\' можно использовать для экранирования
.Cm # .
Можно указать несколько
.Fl G
опций, и проверка останавливается при первом совпадении.
.It Fl H
Следовать только символическим ссылкам командной строки при выполнении
физического обхода файловой системы.
.It Fl L
Следовать всем символическим ссылкам для выполнения логического обхода
файловой системы.
.It Fl O
Принудительно делать архив одним томом.
Если том заканчивается преждевременно,
.Nm
не будет запрашивать новый том.
Эта опция может быть полезна для автоматизированных задач, где
восстановление после ошибок не может выполнить человек.
.It Fl P
Не следовать символическим ссылкам, выполнять физический обход файловой системы.
Это режим по умолчанию.
.It Fl T Ar [от_дата][,до_дата][/[c][m]]
Позволяет выбирать файлы на основе времени модификации файла или изменения inode,
попадающего в указанный временной диапазон от
.Ar от_дата
до
.Ar до_дата
(даты включаются).
Если указана только
.Ar от_дата ,
выбираются все файлы со временем модификации или изменения inode,
равным или более новым.
Если указана только
.Ar до_дата ,
будут выбраны все файлы со временем модификации или изменения inode,
равным или более старым.
Когда
.Ar от_дата
равна
.Ar до_дата ,
будут выбраны только файлы со временем модификации или изменения inode,
точно равным этому времени.
.Pp
Когда
.Nm
находится в режиме
.Em записи
или
.Em копирования ,
необязательное завершающее поле
.Ar [c][m]
можно использовать для определения того, какое время файла (изменение inode,
модификация файла или оба) используется при сравнении.
Если ни одно не указано, по умолчанию используется только время модификации файла.
.Ar m
задаёт сравнение времени модификации файла (времени последней записи файла).
.Ar c
задаёт сравнение времени изменения inode (времени последнего изменения inode
файла; например, смена владельца, группы, режима и т.д.).
Когда указаны и
.Ar c ,
и
.Ar m ,
сравниваются как время модификации, так и время изменения inode.
Сравнение времени изменения inode полезно для выбора файлов, атрибуты которых
были недавно изменены, или выбора файлов, которые были недавно созданы и их
время модификации было сброшено на более старое время (как происходит, когда
файл извлекается из архива и время модификации сохраняется).
Сравнение времени с использованием обоих времён файла полезно, когда
.Nm
используется для создания инкрементального архива на основе времени
(будут архивироваться только файлы, изменённые в течение указанного временного
диапазона).
.Pp
Временной диапазон состоит из шести различных полей, и каждое поле должно
содержать две цифры.
Формат:
.Pp
.Dl [[[[[cc]yy]mm]dd]HH]MM[.SS]
.Pp
Где
.Ar cc
— первые две цифры года (век),
.Ar yy
— последние две цифры года,
первые
.Ar mm
— месяц (от 01 до 12),
.Ar dd
— день месяца (от 01 до 31),
.Ar HH
— час дня (от 00 до 23),
.Ar MM
— минуты (от 00 до 59),
а
.Ar SS
— секунды (от 00 до 59).
Поле минут
.Ar MM
обязательно, остальные поля необязательны и должны добавляться в следующем
порядке:
.Ar HH , dd , mm , yy , cc .
Поле
.Cm ss
можно добавить независимо от других полей.
Временные диапазоны отсчитываются от текущего времени, поэтому
.Dl Fl T Ar 1234/cm
выберет все файлы со временем модификации или изменения inode
12:34 PM сегодня или позже.
Можно указать несколько временных диапазонов
.Fl T ,
и проверка останавливается при первом совпадении.
.It Fl U Ar пользователь
Выбирает файл по его
.Ar пользователь
имени или, если оно начинается с
.Cm # ,
по числовому uid.
Символ '\\' можно использовать для экранирования
.Cm # .
Можно указать несколько
.Fl U
опций, и проверка останавливается при первом совпадении.
.It Fl X
При обходе иерархии файлов, заданной путевым именем,
не спускаться в каталоги с другим идентификатором устройства.
См. поле
.Li st_dev
как описано в
.Xr stat 2
для получения дополнительной информации об идентификаторах устройств.
.It Fl Y
Эта опция аналогична опции
.Fl D ,
за исключением того, что время изменения inode проверяется с использованием
путевого имени, созданного после завершения всех модификаций имени файла.
.It Fl Z
Эта опция аналогична опции
.Fl u ,
за исключением того, что время модификации проверяется с использованием
путевого имени, созданного после завершения всех модификаций имени файла.
.El
.Pp
Опции, которые работают с именами файлов или членов архива
.Fl ( c ,
.Fl i ,
.Fl n ,
.Fl s ,
.Fl u ,
.Fl v ,
.Fl D ,
.Fl G ,
.Fl T ,
.Fl U ,
.Fl Y ,
и
.Fl Z )
взаимодействуют следующим образом.
.Pp
При извлечении файлов во время операции
.Em чтения
члены архива
.Sq выбираются ,
основываясь только на заданных пользователем операндах шаблона, изменённых
опциями
.Fl c ,
.Fl n ,
.Fl u ,
.Fl D ,
.Fl G ,
.Fl T ,
.Fl U .
Затем любые
.Fl s
и
.Fl i
опции изменяют в этом порядке имена этих выбранных файлов.
Затем опции
.Fl Y
и
.Fl Z
будут применены на основе окончательного путевого имени.
Наконец, опция
.Fl v
запишет имена, полученные в результате этих изменений.
.Pp
При архивации файлов во время операции
.Em записи
или копировании файлов во время операции
.Em копирования
члены архива
.Sq выбираются ,
основываясь только на заданных пользователем путевых именах, изменённых
опциями
.Fl n ,
.Fl u ,
.Fl D ,
.Fl G ,
.Fl T
и
.Fl U
(опция
.Fl D
применяется только во время операции копирования).
Затем любые
.Fl s
и
.Fl i
опции изменяют в этом порядке имена этих выбранных файлов.
Затем во время операции
.Em копирования
опции
.Fl Y
и
.Fl Z
будут применены на основе окончательного путевого имени.
Наконец, опция
.Fl v
запишет имена, полученные в результате этих изменений.
.Pp
Когда одна или обе опции
.Fl u
или
.Fl D
указаны вместе с опцией
.Fl n ,
файл не считается выбранным, если он не новее файла, с которым сравнивается.
.Sh СТАТУС ВЫХОДА
Утилита
.Nm
завершится с одним из следующих значений:
.Bl -tag -width 2n
.It 0
Все файлы успешно обработаны.
.It 1
Произошла ошибка.
.El
.Sh ПРИМЕРЫ
Команда:
копирует содержимое текущего каталога на устройство
.Pa /dev/sa0 .
.Pp
Команда:
.Dl pax -v -f filename
выдаёт подробную таблицу содержимого для архива, хранящегося в
.Pa filename .
.Pp
Следующие команды:
.Dl mkdir /tmp/to
.Dl cd /tmp/from
.Dl pax -rw .\\ /tmp/to
скопируют всю
.Pa /tmp/from
иерархию каталога в
.Pa /tmp/to .
.Pp
Команда:
.Dl pax -r -s ',^//*usr//*,,' -f a.pax
читает архив
.Pa a.pax ,
при этом все файлы с корнем ``/usr'' в архиве извлекаются относительно
текущего каталога.
.Pp
Команда:
.Dl pax -rw -i .\\ dest_dir
может использоваться для интерактивного выбора файлов для копирования из
текущего каталога в
.Pa dest_dir .
.Pp
Команда:
.Dl pax -r -pe -U root -G bin -f a.pax
извлечёт все файлы из архива
.Pa a.pax
владельцем которых является
.Em root
с группой
.Em bin ,
и сохранит все разрешения файлов.
.Pp
Команда:
.Dl pax -r -w -v -Y -Z home /backup
обновит (и выведет список) только те файлы в целевом каталоге
.Pa /backup
которые старше (менее позднее время изменения inode или модификации файла),
чем файлы с тем же именем, найденные в исходном дереве файлов
.Pa home .
.Sh ДИАГНОСТИКА
Всякий раз, когда
.Nm
не может создать файл или ссылку при чтении архива или не может
найти файл при записи архива, или не может сохранить идентификатор пользователя,
идентификатор группы или режим файла, когда указана опция
.Fl p ,
диагностическое сообщение записывается в
.Dv стандартный поток ошибок
и возвращается ненулевой статус выхода, но обработка продолжается.
В случае, когда pax не может создать ссылку на файл,
.Nm
не будет создавать вторую копию файла.
.Pp
Если извлечение файла из архива преждевременно прекращено
сигналом или ошибкой,
.Nm
может извлечь файл, который хотел пользователь, только частично.
Кроме того, режимы извлечённых файлов и каталогов
могут иметь неправильные биты файла, а времена модификации и доступа могут быть
неверными.
.Pp
Если создание архива преждевременно прекращено сигналом или ошибкой,
.Nm
может создать архив только частично, что может нарушить конкретную
спецификацию формата архива.
.Pp
Если во время
.Em копирования
.Nm
обнаружит, что файл собирается перезаписать сам себя, файл не копируется,
диагностическое сообщение записывается в
.Dv стандартный поток ошибок
и когда
.Nm
завершится, он выйдет с ненулевым статусом выхода.
.Sh СМ. ТАКЖЕ
.Xr cpio 1 ,
.Xr tar 1
.Sh СТАНДАРТЫ
Утилита
.Nm
является надмножеством стандарта
.St -p1003.2 .
Опции
.Fl z ,
.Fl B ,
.Fl D ,
.Fl E ,
.Fl G ,
.Fl H ,
.Fl L ,
.Fl O ,
.Fl P ,
.Fl T ,
.Fl U ,
.Fl Y ,
.Fl Z ,
форматы архивов
.Ar bcpio ,
.Ar sv4cpio ,
.Ar sv4crc ,
.Ar tar ,
и обработка повреждённых архивов во время
.Ar список
и
.Ar чтение
операций являются расширениями стандарта
.Tn POSIX .
.Sh ИСТОРИЯ
Утилита
.Nm
появилась в
.Bx 4.4 .
.Sh АВТОРЫ
.An Keith Muller
в Калифорнийском университете, Сан-Диего
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Утилита
.Nm
не распознаёт многобайтовые символы.
.Pp
Флаги файлов, устанавливаемые
.Xr chflags 1
не сохраняются
.Nm .
В разделе BUGS
.Xr chflags 1
есть список утилит, которые не знают о флагах.
