.\" FRDP path bin/pkill/pkill.1
.\" FRDP githash 88a2d48d39d9845e36c8e95a9204001b11e7257e
.\" FRDP hash256 c626bea9440df89a280e8ddcb51f2e8f259f83d4a23a9f1c04a9842f953c8b3d
.Dd June 24, 2025
.Dt PKILL 1
.Os
.Sh ИМЯ
.Nm pgrep , pkill
.Nd найти или послать сигнал процессам по имени
.Sh СИНТАКСИС
.Nm pgrep
.Op Fl LSafilnoqvx
.Op Fl F Ar pidfile
.Op Fl G Ar gid
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl P Ar ppid
.Op Fl U Ar uid
.Op Fl c Ar класс
.Op Fl d Ar разделитель
.Op Fl g Ar pgrp
.Op Fl j Ar клетка
.Op Fl s Ar sid
.Op Fl t Ar tty
.Op Fl u Ar euid
.Ar шаблон ...
.Nm pkill
.Op Fl Ar сигнал
.Op Fl ILafilnovx
.Op Fl F Ar pidfile
.Op Fl G Ar gid
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl P Ar ppid
.Op Fl U Ar uid
.Op Fl c Ar класс
.Op Fl g Ar pgrp
.Op Fl j Ar клетка
.Op Fl s Ar sid
.Op Fl t Ar tty
.Op Fl u Ar euid
.Ar шаблон ...
.Sh ОПИСАНИЕ
Команда
.Nm pgrep
ищет в таблице процессов работающей системы и выводит
идентификаторы процессов всех процессов, соответствующих критериям,
заданным в командной строке, исключая себя и всех прямых предков, если не
указана опция
.Fl a .
.Pp
Команда
.Nm pkill
ищет в таблице процессов работающей системы и посылает сигнал всем
процессам, соответствующим критериям, заданным в командной строке, исключая себя
и всех прямых предков, если не указана опция
.Fl a .
.Pp
Доступны следующие опции:
.Bl -tag -width indent
.It Fl F Ar pidfile
Ограничить совпадения процессом, чей PID хранится в файле
.Ar pidfile .
.It Fl G Ar gid
Ограничить совпадения процессами с реальным идентификатором группы из
разделённого запятыми списка
.Ar gid .
.It Fl I
Запрашивать подтверждение перед попыткой послать сигнал каждому процессу.
.It Fl L
Файл
.Ar pidfile ,
указанный для опции
.Fl F ,
должен быть заблокирован с помощью системного вызова
.Xr flock 2
или создан с помощью
.Xr pidfile 3 .
.It Fl M Ar core
Извлекать значения, связанные со списком имён, из указанного core-файла
вместо текущей работающей системы.
.It Fl N Ar system
Извлекать список имён из указанной системы вместо системы по умолчанию,
которая является образом ядра, загруженного системой.
.It Fl P Ar ppid
Ограничить совпадения процессами с идентификатором родительского процесса из
разделённого запятыми списка
.Ar ppid .
.It Fl S
Искать также среди системных процессов (потоков ядра).
.It Fl U Ar uid
Ограничить совпадения процессами с реальным идентификатором пользователя из
разделённого запятыми списка
.Ar uid .
.It Fl d Ar разделитель
Указать разделитель, который будет выводиться между идентификаторами процессов.
По умолчанию используется символ новой строки.
Эта опция может использоваться только с командой
.Nm pgrep .
.It Fl a
Включать предков процессов в список совпадений.
По умолчанию текущий процесс
.Nm pgrep
или
.Nm pkill
и все его предки исключаются (если не используется
.Fl v ).
Заметьте, что опция
.Fl a
не
.Dq раскрывает
сам процесс
.Nm pgrep
или
.Nm pkill ,
даже с
.Fl v .
.It Fl c Ar класс
Ограничить совпадения процессами, работающими с указанным классом входа
.Ar класс .
.It Fl f
Сопоставлять с полными списками аргументов.
По умолчанию сопоставление выполняется с именами процессов.
.It Fl g Ar pgrp
Ограничить совпадения процессами с идентификатором группы процессов из
разделённого запятыми списка
.Ar pgrp .
Значение ноль означает идентификатор группы процессов работающей команды
.Nm pgrep
или
.Nm pkill .
.It Fl i
Игнорировать регистр как в таблице процессов, так и в заданном шаблоне.
.It Fl j Ar клетка
Ограничить совпадения процессами внутри указанных клеток.
Аргумент
.Ar клетка
может быть
.Dq Li any
для совпадения с процессами в любой клетке,
.Dq Li none
для совпадения с процессами не в клетке,
или разделённым запятыми списком идентификаторов или имён клеток.
.It Fl l
Длинный вывод.
Для
.Nm pgrep
выводить имя процесса в дополнение к идентификатору процесса для каждого
совпадающего процесса.
Если используется вместе с
.Fl f ,
выводить идентификатор процесса и полный список аргументов для каждого
совпадающего процесса.
Для
.Nm pkill
отображать команду kill, использованную для каждого убитого процесса.
.It Fl n
Выбрать только самый новый (недавно запущенный) из совпадающих процессов.
.It Fl o
Выбрать только самый старый (давно запущенный) из совпадающих процессов.
.It Fl q
Для
.Nm pgrep
ничего не выводить на стандартный вывод.
.It Fl s Ar sid
Ограничить совпадения процессами с идентификатором сеанса из
разделённого запятыми списка
.Ar sid .
Значение ноль означает идентификатор сеанса работающей команды
.Nm pgrep
или
.Nm pkill .
.It Fl t Ar tty
Ограничить совпадения процессами, связанными с терминалом из
разделённого запятыми списка
.Ar tty .
Имена терминалов могут быть в форме
.Pa tty Ns Ar xx
или сокращённой форме
.Ar xx .
Одиночное тире
.Pq Ql -
совпадает с процессами, не связанными с терминалом.
.It Fl u Ar euid
Ограничить совпадения процессами с эффективным идентификатором пользователя из
разделённого запятыми списка
.Ar euid .
.It Fl v
Инвертировать смысл сопоставления; отображать процессы, не соответствующие
заданным критериям.
.It Fl x
Требовать точного совпадения имени процесса или списка аргументов, если
указана
.Fl f .
По умолчанию совпадает любая подстрока.
.It Fl Ns Ar сигнал
Неотрицательное десятичное число или символическое имя сигнала, задающее сигнал,
который будет послан вместо сигнала по умолчанию
.Dv TERM .
Эта опция допустима только когда задана в качестве первого аргумента для
.Nm pkill .
.El
.Pp
Если указаны какие-либо операнды
.Ar шаблон ,
они используются как расширенные регулярные выражения для сопоставления
имени команды или полного списка аргументов каждого процесса.
Если опция
.Fl f
не указана, то
.Ar шаблон
будет пытаться сопоставиться с именем команды.
Однако в настоящее время
.Fx
отслеживает только первые 19 символов имени команды
для каждого процесса.
Попытки сопоставить любые символы после первых 19 символов имени команды
будут молча завершаться неудачей.
.Pp
Заметьте, что работающий процесс
.Nm pgrep
или
.Nm pkill
никогда не рассматривает себя или системные процессы (потоки ядра) как
потенциальное совпадение.
.Sh ЗАМЕЧАНИЯ ПО РЕАЛИЗАЦИИ
В реализации Sun Solaris использовался procfs для получения информации о процессах.
В данной реализации вместо этого используется
.Xr kvm 3 .
В работающей системе
.Xr kvm 3
использует
.Va kern.proc
MIB для получения списка процессов, доступ к памяти ядра через
.Pa /dev/kmem
не производится.
.Sh СТАТУС ВЫХОДА
Утилиты
.Nm pgrep
и
.Nm pkill
возвращают одно из следующих значений при выходе:
.Bl -tag -width indent
.It 0
Совпал один или несколько процессов.
.It 1
Не совпало ни одного процесса.
.It 2
В командной строке указаны недопустимые опции.
.It 3
Произошла внутренняя ошибка.
.El
.Sh ПРИМЕРЫ
Показать pid процесса, удерживающего pid-файл
.Pa /tmp/.X0-lock :
.Bd -literal -offset indent
$ pgrep -F /tmp/.X0-lock
1211
.Ed
.Pp
Показать pid и имя процесса, включая потоки ядра, в поиске:
.Bd -literal -offset indent
$ pgrep -lS vnlru
37 vnlru
.Ed
.Pp
Искать процессы, включая потоки ядра, соответствующие шаблону расширенного
регулярного выражения:
.Bd -literal -offset indent
$ pgrep -S 'crypto.*[2-3]'
20
19
6
5
.Ed
.Pp
Показать длинный вывод для процессов firefox:
.Bd -literal -offset indent
$ pgrep -l firefox
1312 firefox
1309 firefox
1288 firefox
1280 firefox
1279 firefox
1278 firefox
1277 firefox
1264 firefox
.Ed
.Pp
То же, что выше, но показан только pid самого последнего процесса:
.Bd -literal -offset indent
$ pgrep -n firefox
1312
.Ed
.Pp
Искать процессы vim.
Сопоставлять с полным списком аргументов:
.Bd -literal -offset indent
$ pgrep -f vim
44968
30790
.Ed
.Pp
То же, что выше, но с сопоставлением по слову
.Ql list
и показом полного списка аргументов:
.Bd -literal -offset indent
$ pgrep -f -l list
30790 vim list.txt
.Ed
.Pp
Послать сигнал
.Va SIGSTOP
процессам, которые точно совпадают:
.Bd -literal -offset indent
.Ed
.Pp
Без
.Fl f
имена длиннее 19 символов будут молча завершаться неудачей:
.Bd -literal -offset indent
$ vim this_is_a_very_long_file_name &
[1] 36689
$

[1]+  Stopped                 vim this_is_a_very_long_file_name
$
.Ed
.Pp
То же, что выше, с использованием флага
.Fl f :
.Bd -literal -offset indent
36689
.Ed
.Pp
Найти команду
.Xr top 1
работающую в любой клетке:
.Bd -literal -offset indent
$ pgrep -j any top
34498
.Ed
.Pp
Показать все процессы, работающие в клетке с ID 58:
.Bd -literal -offset indent
$ pgrep -l -j58 '.*'
28397 pkg-static
28396 pkg-static
28255 sh
28254 make
.Ed
.Sh СОВМЕСТИМОСТЬ
Исторически опция
.Dq Fl j Li 0
означает любую клетку, хотя в других утилитах, таких как
.Xr ps 1 ,
идентификатор клетки
.Li 0
имеет противоположное значение — не в клетке.
Поэтому
.Dq Fl j Li 0
устарела, и её использование не рекомендуется в пользу
.Dq Fl j Li any .
.Sh СМ. ТАКЖЕ
.Xr kill 1 ,
.Xr killall 1 ,
.Xr ps 1 ,
.Xr flock 2 ,
.Xr kill 2 ,
.Xr sigaction 2 ,
.Xr kvm 3 ,
.Xr pidfile 3 ,
.Xr re_format 7
.Sh ИСТОРИЯ
Утилиты
.Nm pkill
и
.Nm pgrep
впервые появились в
.Nx 1.6 .
Они созданы по образцу утилит с теми же именами, появившихся в Sun
Solaris 7.
Они впервые появились в
.Fx 5.3 .
.Sh АВТОРЫ
.An Andrew Doran Aq Mt ad@NetBSD.org
