.\" FRDP path bin/ps/ps.1
.\" FRDP githash 759ce9a2b38e1de70c14c81dee7e245bf0bc6b94
.\" FRDP hash256 36900c14bd8cd408422acbc2b8ee67b41f9501a432c2def37b94e9a8b50b1c03
.Dd July 16, 2025
.Dt PS 1
.Os
.Sh ИМЯ
.Nm ps
.Nd состояние процессов
.Sh СИНТАКСИС
.Nm
.Op Fl -libxo
.Op Fl AaCcdefHhjlmrSTuvwXxZ
.Op Fl O Ar fmt
.Op Fl o Ar fmt
.Op Fl D Ar up | down | both
.Op Fl G Ar gid Ns Op , Ns Ar gid Ns Ar ...
.Op Fl J Ar jid Ns Op , Ns Ar jid Ns Ar ...
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl p Ar pid Ns Op , Ns Ar pid Ns Ar ...
.Op Fl t Ar tty Ns Op , Ns Ar tty Ns Ar ...
.Op Fl U Ar user Ns Op , Ns Ar user Ns Ar ...
.Nm
.Op Fl -libxo
.Fl L
.Sh ОПИСАНИЕ
Утилита
.Nm
отображает информацию о выбранных процессах.
Её традиционный текстовый вывод состоит из строки заголовка, за которой следует по одной строке
информации на каждый выбранный процесс, или, возможно, несколько, если используется
.Fl H
.Pq по одной на лёгкий процесс .
Другие стили вывода можно запросить через
.Fl -libxo .
.Pp
По умолчанию показываются только процессы вызывающего пользователя, определяемые путём сопоставления их
эффективного идентификатора пользователя с идентификатором процесса
.Nm ,
имеющие управляющие терминалы.
Другой набор процессов можно выбрать для отображения с помощью комбинаций
.Fl A , a , D , G , J , p , T , t , U , X ,
и
.Fl x
опций.
За исключением опций
.Fl X
и
.Fl x ,
как только появляется одна из них, она отменяет выбор процессов по умолчанию, т.е.
процессы вызывающего пользователя показываются только по запросу.
Если появляется более одной из них
.Pq с теми же исключениями ,
.Nm
будет выбирать процессы, как только они будут соответствовать хотя бы одной из них
.Pq включающее ИЛИ .
Опция
.Fl X
может независимо использоваться для дальнейшей фильтрации перечисленных процессов, оставляя только
те, которые имеют управляющий терминал
.Po
кроме выбранных с помощью
.Fl p
.Pc .
Её противоположность,
.Fl x ,
принудительно удаляет этот фильтр.
Если ни
.Fl X
ни
.Fl x
не указаны, подразумеваемое поведение по умолчанию такое же, как у
.Fl X ,
если не используется другая опция, описание которой явно говорит, что
.Fl x
подразумевается.
.Pp
Для каждого выбранного процесса отображаемая по умолчанию информация состоит из
идентификатора процесса, управляющего терминала, состояния, времени CPU
.Pq включая как пользовательское, так и системное время
и связанной команды
.Po
см. документацию для ключевого слова
.Cm command
ниже
.Pc .
Эту информацию можно настроить с помощью двух групп опций, которые можно
комбинировать по мере необходимости.
Во-первых, опции
.Fl o
и
.Fl O
добавляют столбцы с данными, соответствующими явно переданным ключевым словам.
Доступные ключевые слова описаны в разделе
.Sx КЛЮЧЕВЫЕ СЛОВА
ниже.
Их можно перечислить с помощью опции
.Fl L .
Во-вторых, опции
.Fl j , l , u ,
и
.Fl v
задают определённые предопределённые группы столбцов, также называемые готовыми представлениями.
Наличие любой из этих опций отменяет отображение по умолчанию, полностью заменяя его
запрошенными столбцами, в порядке передачи опций.
Отдельные столбцы, запрошенные через опцию готового представления, которые имеют то же
ключевое слово или псевдоним к нему, что и некоторый столбец, добавленный более ранней опцией готового представления
или явной опцией
.Fl O
или
.Fl o
где-либо в командной строке, подавляются.
Это автоматическое удаление дублирующихся данных в готовых представлениях полезно для
небольшой настройки этих представлений и/или объединения нескольких из них без
необходимости собирать варианты с нуля, например, используя только
.Fl o
опции.
.Pp
Строки с информацией о выводе по умолчанию сортируются сначала по управляющему терминалу,
затем по идентификатору процесса, а затем, если
.Fl H
была указана, по идентификатору лёгкого процесса (потока).
Опции
.Fl m , r , u ,
и
.Fl v
изменяют порядок сортировки.
Если задано более одной опции сортировки, то выбранные процессы
будут отсортированы по последней указанной опции сортировки.
.Pp
Если используется традиционный текстовый вывод (по умолчанию), ширина вывода по умолчанию — та, что запрошена
переменной окружения
.Ev COLUMNS
если она присутствует, иначе ширина строки терминала, связанного с
процессом
.Nm ,
если таковой имеется.
Во всех остальных ситуациях ширина вывода не ограничена.
См. также
.Fl w
опцию и раздел
.Sx ИЗВЕСТНЫЕ ОШИБКИ .
.Pp
Для обратной совместимости
.Nm
пытается интерпретировать любой позиционный аргумент как идентификатор процесса, как если бы он был указан
опцией
.Fl p .
Неудача при этом вызовет ошибку.
.Nm
также принимает устаревшие BSD-опции, формат и действие которых намеренно оставлены
недокументированными.
.Pp
Опции следующие:
.Bl -tag -width indent
.It Fl -libxo
Создавать вывод через
.Xr libxo 3
в одном из различных человекочитаемых и машиночитаемых форматов.
См.
.Xr xo_options 7
для подробностей об аргументах командной строки.
По умолчанию используется традиционный текстовый стиль вывода.
.It Fl A
Отображать информацию обо всех процессах в системе.
Использование этой опции строго эквивалентно указанию обеих
.Fl a
и
.Fl x .
Пожалуйста, см. их описание для дополнительной информации.
.It Fl a
Отображать информацию обо всех пользовательских процессах.
Однако она не перечисляет все процессы
.Po
см.
.Fl A
и
.Fl x
.Pc .
Если
.Va security.bsd.see_other_uids
sysctl установлен в ноль, эта опция соблюдается только если реальный идентификатор пользователя
процесса
.Nm
равен 0.
.It Fl C
Изменить способ вычисления процента CPU, используя
.Dq сырое
вычисление CPU, которое игнорирует
.Dq резидентное
время (обычно это не имеет эффекта).
.It Fl c
Изменить вывод столбца
.Dq команда
так, чтобы он содержал только имя исполняемого файла,
а не полную командную строку.
.It Fl D
Расширить список выбранных процессов на основе дерева процессов.
.Dq UP
добавит процессы-предки,
.Dq DOWN
добавит процессы-потомки, а
.Dq BOTH
добавит как процессы-предки, так и процессы-потомки.
.Fl D
не подразумевает
.Fl d ,
но хорошо работает с ней.
.It Fl d
Упорядочить процессы в порядке потомков и предварять каждую команду
текстом отступа, показывающим отношения братьев и родитель/потомок в виде дерева.
Если также используются опции
.Fl m
и
.Fl r ,
они управляют тем, как сортируются процессы-братья
относительно друг друга.
Обратите внимание, что эта опция не имеет эффекта, если последний столбец не имеет
.Cm comm ,
.Cm command
или
.Cm ucomm
в качестве ключевого слова.
.It Fl e
Также отображать окружение.
.It Fl f
Указывает выводить полную команду и аргументы в
.Cm command
столбцах.
Это поведение по умолчанию в
.Fx .
См.
.Fl c
чтобы отключить это.
.It Fl G
Отображать информацию о процессах, чей реальный идентификатор группы совпадает с указанными
идентификаторами или именами групп.
Подразумевает
.Fl x
по умолчанию.
.It Fl H
Показывать все потоки, связанные с каждым процессом.
.It Fl h
Повторять заголовок информации так часто, как необходимо, чтобы гарантировать один
заголовок на страницу информации.
.It Fl J
Отображать информацию о процессах, соответствующих указанным идентификаторам клеток.
Это может быть либо
.Cm jid
либо
.Cm name
клетки.
Используйте
.Fl J
.Sy 0
чтобы запросить отображение процессов хоста.
Подразумевает
.Fl x
по умолчанию.
.It Fl j
Печатать информацию, связанную со следующими ключевыми словами:
.Cm user , pid , ppid , pgid , sid , jobc , state , tt , time ,
и
.Cm command .
.It Fl L
Перечислить набор ключевых слов, доступных для опций
.Fl O
и
.Fl o .
.It Fl l
Отображать информацию, связанную со следующими ключевыми словами:
.Cm uid , pid , ppid , cpu , pri , nice , vsz , rss , mwchan , state ,
.Cm tt , time ,
и
.Cm command .
.It Fl M
Извлекать значения, связанные со списком имён, из указанного
файла core
вместо текущей работающей системы.
.It Fl m
Сортировать по использованию памяти вместо комбинации управляющего
терминала и идентификатора процесса.
.It Fl N
Извлекать список имён из указанной системы вместо значения по умолчанию,
которое является образом ядра, из которого загружена система.
.It Fl O
Сохранить переданные столбцы в отдельном списке, который в конце прикрепляется сразу после
первого вхождения в отображении столбца идентификатора процесса, указанного другими
опциями, или отображения по умолчанию, если такового нет.
Если отображение, подготовленное другими опциями, не включает столбец идентификатора процесса,
список вставляется в начало отображения.
Дальнейшие вхождения
.Fl O
добавляются к списку столбцов, которые должны быть прикреплены.
Эта опция принимает список ключевых слов, разделённых пробелами или запятыми.
Последнее ключевое слово в списке может быть дополнено знаком равенства
.Pq Ql =
как объяснено для опции
.Fl o
и с тем же эффектом.
.It Fl o
Отображать информацию, связанную с указанным списком ключевых слов, разделённых пробелами или запятыми.
Последнее ключевое слово в списке может быть дополнено знаком равенства
.Pq Ql =
и строкой, которая занимает остаток аргумента и может содержать
пробелы и запятые.
Это заставляет выводимый заголовок использовать указанную строку вместо
стандартного заголовка.
Несколько ключевых слов также могут быть заданы в виде более чем одной
.Fl o
опции.
Таким образом, тексты заголовков для нескольких ключевых слов могут быть изменены.
Если все ключевые слова имеют пустые тексты заголовков, строка заголовка не выводится.
.It Fl p
Отображать информацию о процессах, соответствующих указанным идентификаторам процессов.
Процессы, выбранные этой опцией, не подвергаются фильтрации
.Fl X .
.It Fl r
Сортировать по текущему использованию CPU вместо комбинации управляющего
терминала и идентификатора процесса.
.It Fl S
Изменить способ вычисления времён процесса, а именно cputime, systime и usertime,
путём суммирования всех завершившихся дочерних процессов с их родительским процессом.
.It Fl T
Отображать информацию о процессах, привязанных к устройству, связанному
со стандартным вводом.
.It Fl t
Отображать информацию о процессах, привязанных к указанным терминальным
устройствам.
Можно указывать полные пути, а также сокращения (см. объяснение
.Cm tt
ключевого слова).
Подразумевает
.Fl x
по умолчанию.
.It Fl U
Отображать информацию о процессах, чей реальный идентификатор пользователя совпадает с указанными
идентификаторами или именами пользователей.
Подразумевает
.Fl x
по умолчанию.
.It Fl u
Отображать информацию, связанную со следующими ключевыми словами:
.Cm user , pid , %cpu , %mem , vsz , rss , tt , state , start , time ,
и
.Cm command .
Опция
.Fl u
подразумевает опцию
.Fl r .
.It Fl v
Отображать информацию, связанную со следующими ключевыми словами:
.Cm pid , state , time , sl , re , pagein , vsz , rss , lim , tsiz ,
.Cm %cpu , %mem ,
и
.Cm command .
Опция
.Fl v
подразумевает опцию
.Fl m .
.It Fl w
Использовать не менее 131 столбца для отображения информации.
Если
.Fl w
указана более одного раза,
.Nm
будет использовать столько столбцов, сколько необходимо.
Пожалуйста, см. преамбулу этой страницы руководства о том, как изначально определяется ширина вывода.
В частности, если начальная ширина вывода не ограничена, указание
.Fl w
не имеет эффекта.
Пожалуйста, также обратитесь к разделу
.Sx ИЗВЕСТНЫЕ ОШИБКИ .
.It Fl X
При отображении процессов, выбранных другими опциями, пропускать любые процессы, которые
не имеют управляющего терминала, кроме выбранных через
.Fl p .
Это поведение по умолчанию, если не используется другая опция, описание которой
явно говорит, что
.Fl x
подразумевается.
.It Fl x
При отображении процессов, выбранных другими опциями, включать процессы, которые
не имеют управляющего терминала.
Эта опция имеет противоположное поведение по отношению к
.Fl X .
Если указаны и
.Fl X
и
.Fl x ,
.Nm
будет следовать последнему вхождению.
.It Fl Z
Добавить
.Xr mac 4
метку в список ключевых слов, для которых
.Nm
будет отображать информацию.
.El
.Sh КЛЮЧЕВЫЕ СЛОВА
Ниже приведён полный список доступных ключевых слов и их значений.
Некоторые из них имеют псевдонимы (ключевые слова, являющиеся синонимами).
Подробные описания некоторых из них можно найти после этого списка.
.Pp
.Bl -tag -width indent -compact
.It Cm %cpu
процент использования CPU (псевдоним
.Cm pcpu )
.It Cm %mem
процент использования памяти (псевдоним
.Cm pmem )
.It Cm acflag
флаг учёта (псевдоним
.Cm acflg )
.It Cm args
команда и аргументы
.It Cm class
класс входа
.It Cm comm
команда
.It Cm command
команда и аргументы
.It Cm cow
количество ошибок copy-on-write
.It Cm cpu
Номер процессора, на котором выполняется процесс (виден только в SMP
системах).
.It Cm dsiz
размер данных в KiB
.It Cm emul
среда эмуляции системных вызовов (ABI)
.It Cm etime
прошедшее время работы, формат
.Do
.Op days- Ns
.Op hours\&: Ns
minutes:seconds
.Dc
.It Cm etimes
прошедшее время работы, в десятичных целых секундах
.It Cm fib
номер FIB по умолчанию, см.
.Xr setfib 1
.It Cm flags
флаги процесса, в шестнадцатеричном виде (псевдоним
.Cm f )
.It Cm flags2
дополнительный набор флагов процесса, в шестнадцатеричном виде (псевдоним
.Cm f2 )
.It Cm gid
эффективный идентификатор группы (псевдоним
.Cm egid )
.It Cm group
имя группы (из egid) (псевдоним
.Cm egroup )
.It Cm inblk
всего блоков прочитано (псевдоним
.Cm inblock )
.It Cm jail
имя клетки
.It Cm jid
идентификатор клетки
.It Cm jobc
счётчик управления заданиями
.It Cm ktrace
флаги трассировки
.It Cm label
метка MAC
.It Cm lim
предел использования памяти
.It Cm lockname
блокировка, на которой в данный момент заблокирован процесс (как символьное имя)
.It Cm logname
имя входа пользователя, запустившего сессию
.It Cm lstart
время запуска
.It Cm lwp
идентификатор потока (лёгкого процесса) (псевдоним
.Cm tid )
.It Cm majflt
всего ошибок страниц
.It Cm minflt
всего возвратов страниц
.It Cm msgrcv
всего полученных сообщений (чтений из каналов/сокетов)
.It Cm msgsnd
всего отправленных сообщений (записей в каналы/сокеты)
.It Cm mwchan
канал ожидания или блокировка, на которой в данный момент заблокирован процесс
.It Cm nice
значение nice (псевдоним
.Cm ni )
.It Cm nivcsw
всего непроизвольных переключений контекста
.It Cm nlwp
количество потоков (лёгких процессов), привязанных к процессу
.It Cm nsigs
всего принятых сигналов (псевдоним
.Cm nsignals )
.It Cm nswap
всего swap in/out
.It Cm nvcsw
всего произвольных переключений контекста
.It Cm nwchan
канал ожидания (как адрес)
.It Cm oublk
всего блоков записано (псевдоним
.Cm oublock )
.It Cm paddr
указатель процесса
.It Cm pagein
страничные включения (то же, что majflt)
.It Cm pgid
номер группы процессов
.It Cm pid
идентификатор процесса
.It Cm ppid
идентификатор родительского процесса
.It Cm pri
приоритет планирования
.It Cm re
время резидентности в ядре (в секундах; 127 = бесконечность)
.It Cm rgid
реальный идентификатор группы
.It Cm rgroup
имя группы (из rgid)
.It Cm rss
размер резидентного набора в KiB
.It Cm rtprio
приоритет реального времени (см.
.Xr rtprio 1 )
.It Cm ruid
реальный идентификатор пользователя
.It Cm ruser
имя пользователя (из ruid)
.It Cm sid
идентификатор сессии
.It Cm sig
ожидающие сигналы (псевдоним
.Cm pending )
.It Cm sigcatch
перехваченные сигналы (псевдоним
.Cm caught )
.It Cm sigignore
игнорируемые сигналы (псевдоним
.Cm ignored )
.It Cm sigmask
заблокированные сигналы (псевдоним
.Cm blocked )
.It Cm sl
время сна (в секундах; 127 = бесконечность)
.It Cm ssiz
размер стека в KiB
.It Cm start
время запуска
.It Cm state
символическое состояние процесса (псевдоним
.Cm stat )
.It Cm svgid
сохранённый gid из исполняемого файла setgid
.It Cm svuid
сохранённый UID из исполняемого файла setuid
.It Cm systime
накопленное системное время CPU
.It Cm tdaddr
адрес потока
.It Cm tdname
имя потока
.It Cm tdev
номер устройства управляющего терминала
.It Cm time
накопленное время CPU, пользовательское + системное (псевдоним
.Cm cputime )
.It Cm tpgid
идентификатор группы процессов управляющего терминала
.It Cm tracer
идентификатор процесса трассировщика
.It Cm tsid
идентификатор сессии управляющего терминала
.It Cm tsiz
размер текста в KiB
.It Cm tt
имя управляющего терминала (двухбуквенное сокращение)
.It Cm tty
полное имя управляющего терминала
.It Cm ucomm
имя процесса, используемое для учёта
.It Cm uid
эффективный идентификатор пользователя (псевдоним
.Cm euid )
.It Cm upr
приоритет планирования при возврате из системного вызова (псевдоним
.Cm usrpri )
.It Cm uprocp
указатель процесса
.It Cm user
имя пользователя (из UID)
.It Cm usertime
накопленное пользовательское время CPU
.It Cm vmaddr
указатель vmspace
.It Cm vsz
виртуальный размер в KiB (псевдоним
.Cm vsize )
.It Cm wchan
канал ожидания (как символьное имя)
.It Cm xstat
статус выхода или остановки (действителен только для остановленного или зомби-процесса)
.El
.Pp
Некоторые из этих ключевых слов дополнительно описаны ниже:
.Bl -tag -width lockname
.It Cm %cpu
Использование CPU процессом; это затухающее среднее за период до
одной минуты предыдущего (реального) времени.
Поскольку временная база, по которой это вычисляется, варьируется (так как процессы могут
быть очень молодыми), сумма всех
.Cm %cpu
полей может превышать 100%.
.It Cm %mem
Процент реальной памяти, используемой этим процессом.
.It Cm class
Класс входа, связанный с процессом.
.It Cm command
Выводимая команда и аргументы определяются следующим образом.
Процесс, который завершился и имеет родителя, который ещё не ждал
процесс (другими словами, зомби), отображается как
.Dq Li <defunct>.
Если аргументы не могут быть найдены
.Po
обычно потому, что они не были установлены, как в случае системных процессов
и/или потоков ядра
.Pc ,
имя команды выводится в квадратных скобках.
Утилита
.Nm
сначала пытается получить аргументы, кэшированные ядром
.Po
если они были короче значения
.Va kern.ps_arg_cache_limit
sysctl
.Pc .
Процесс может изменить отображаемые аргументы с помощью
.Xr setproctitle 3 .
В противном случае
.Nm
делает обоснованное предположение об имени файла и аргументах, заданных при
создании процесса, путём исследования памяти или области подкачки.
Метод по своей сути несколько ненадёжен, и в любом случае процесс
имеет право уничтожить эту информацию.
Однако на ключевое слово
.Cm ucomm
.Pq учёт
можно положиться.
Если аргументы недоступны или не согласуются с
.Cm ucomm
ключевым словом, значение для
.Cm ucomm
ключевого слова добавляется к аргументам в круглых скобках.
.It Cm flags
Флаги, связанные с процессом, как в
включаемом файле
.In sys/proc.h :
.Bl -column P_SINGLE_BOUNDARY 0x40000000
.El
.It Cm flags2
Флаги, хранящиеся в
.Va p_flag2
связанные с процессом, как в
включаемом файле
.In sys/proc.h :
.Bl -column P2_INHERIT_PROTECTED 0x00000001
.El
.It Cm label
Метка MAC процесса.
.It Cm lim
Мягкий предел используемой памяти, задаваемый через вызов
.Xr setrlimit 2 .
.It Cm lstart
Точное время запуска команды, использующее
.Ql %c
формат, описанный в
.Xr strftime 3 .
.It Cm lockname
Имя блокировки, на которой в данный момент заблокирован процесс.
Если имя недействительно или неизвестно, то
.Dq ???\&
отображается.
.It Cm logname
Имя входа, связанное с сессией, в которой находится процесс (см.
.Xr getlogin 2 ) .
.It Cm mwchan
Имя события, если процесс заблокирован нормально, или имя блокировки, если
процесс заблокирован на блокировке.
См. ключевые слова wchan и lockname
для подробностей.
.It Cm nice
Приращение планирования процесса (см.
.Xr setpriority 2 ) .
.It Cm rss
размер реальной памяти (резидентного набора) процесса в KiB.
.It Cm start
Время запуска команды.
Если команда запущена менее 24 часов назад, время запуска
отображается с использованием
.Dq Li %H:%M
формата, описанного в
.Xr strftime 3 .
Если команда запущена менее 7 дней назад, время запуска
отображается с использованием
.Dq Li %a%H
формата.
В противном случае время запуска отображается с использованием
.Dq Li %e%b%y
формата.
.It Cm sig
Битовая маска сигналов, ожидающих в очереди процесса, если опция
.Fl H
не была указана, иначе очередь ожидающих сигналов на поток.
.It Cm state
Состояние задаётся последовательностью символов, например,
.Dq Li RWNA .
Первый символ указывает состояние выполнения процесса:
.Pp
.Bl -tag -width indent -compact
.It Li D
Обозначает процесс в дисковом (или другом кратковременном, непрерываемом) ожидании.
.It Li I
Обозначает процесс, который бездействует (спит дольше примерно 20 секунд).
.It Li L
Обозначает процесс, который ожидает получения блокировки.
.It Li R
Обозначает процесс, готовый к выполнению.
.It Li S
Обозначает процесс, который спит менее примерно 20 секунд.
.It Li T
Обозначает остановленный процесс.
.It Li W
Обозначает бездействующий поток прерывания.
.It Li Z
Обозначает мёртвый процесс (
.Dq зомби ) .
.El
.Pp
Дополнительные символы после них, если есть, указывают дополнительную информацию
о состоянии:
.Pp
.Bl -tag -width indent -compact
.It Li +
Процесс находится в группе процессов переднего плана своего управляющего терминала.
.It Li <
Процесс повысил приоритет планирования CPU.
.It Li C
Процесс находится в
.Xr capsicum 4
режиме возможностей.
.It Li E
Процесс пытается завершиться.
.It Li J
Обозначает процесс, который находится в
.Xr jail 2 .
Имя хоста клетки можно найти в
.Pa /proc/ Ns Ao Ar pid Ac Ns Pa /status .
.It Li L
Процесс имеет страницы, заблокированные в ядре (например, для raw I/O).
.It Li N
Процесс понизил приоритет планирования CPU (см.
.Xr setpriority 2 ) .
.It Li s
Процесс является лидером сессии.
.It Li V
Родитель процесса приостановлен во время
.Xr vfork 2 ,
ожидая, пока процесс выполнит exec или завершится.
.It Li X
Процесс трассируется или отлаживается.
.El
.It Cm tt
Сокращение для пути управляющего терминала, если таковой имеется.
Сокращение состоит из трёх букв, следующих за
.Pa /dev/tty ,
или, для псевдотерминалов, соответствующей записи в
.Pa /dev/pts .
За ним следует
.Ql -
если процесс больше не может достичь этого
управляющего терминала (т.е. он был отозван).
.Ql -
без предшествующего двухбуквенного сокращения или номера устройства псевдотерминала
указывает на процесс, который никогда не имел управляющего терминала.
Полный путь управляющего терминала доступен через
.Cm tty
ключевое слово.
.It Cm wchan
Событие (адрес в системе), на котором ожидает процесс.
При выводе в числовом виде начальная часть адреса
отбрасывается, и результат выводится в шестнадцатеричном виде, например, 0x80324000 выводится
как 324000.
.El
.Sh ОКРУЖЕНИЕ
Следующие переменные окружения влияют на выполнение
.Nm :
.Bl -tag -width indent
.It Ev COLUMNS
Если установлена, задаёт предпочтительную ширину вывода пользователя в позициях столбцов.
Влияет только на традиционный текстовый стиль вывода.
Пожалуйста, см. преамбулу этой страницы руководства о том, как определяется итоговая ширина вывода.
.El
.Sh ФАЙЛЫ
.Bl -tag -width ".Pa /boot/kernel/kernel" -compact
.It Pa /boot/kernel/kernel
системный список имён по умолчанию
.El
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
Показать информацию обо всех системных процессах:
.Pp
.Dl $ ps -auxw
.Sh СМ. ТАКЖЕ
.Xr kill 1 ,
.Xr pgrep 1 ,
.Xr pkill 1 ,
.Xr procstat 1 ,
.Xr w 1 ,
.Xr kvm 3 ,
.Xr libxo 3 ,
.Xr strftime 3 ,
.Xr xo_options 7 ,
.Xr mac 4 ,
.Xr procfs 4 ,
.Xr pstat 8 ,
.Xr sysctl 8 ,
.Xr mutex 9
.Sh СТАНДАРТЫ
По историческим причинам утилита
.Nm
под
.Fx
поддерживает другой набор опций, отличный от описанного
.St -p1003.1-2008
и поддерживаемого в
.No non- Ns Bx
операционных системах.
.Pp
В частности, и в отличие от этой реализации, POSIX определяет, что опция
.Fl d
должна служить для выбора всех процессов, кроме лидеров сессий, опция
.Fl e
для выбора всех процессов
.Po
эквивалентно
.Fl A
.Pc ,
и опция
.Fl u
для выбора процессов по эффективному идентификатору пользователя.
.Pp
Однако опции
.Fl A , a , G , l , o , p , U ,
и
.Fl t
ведут себя так, как предписано
.St -p1003.1-2008 .
Опции
.Fl f
и
.Fl w
в настоящее время нет, но могут быть изменены в будущем.
.Pp
Опция POSIX
.Fl g ,
для выбора процессов, имеющих указанные процессы в качестве лидера сессии, не
реализована.
Однако другие системы UNIX, предоставляющие эту функциональность, делают это через опцию
.Fl s
вместо этого, резервируя
.Fl g
для запроса по лидерам групп.
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v3
в разделе 8 руководства.
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Поскольку
.Nm
не может работать быстрее системы и запускается как любой другой планируемый
процесс, информация, которую она отображает, никогда не может быть точной.
.Pp
.Nm ps
в настоящее время не ограничивает ширину вывода корректно и в большинстве случаев не
ограничивает её вообще, когда должна.
Независимо от целевой ширины, запрошенные столбцы всегда выводятся полностью и
с ширинами, позволяющими полностью вывести их самые длинные значения, за исключением столбцов
с ключевым словом
.Cm command
или
.Cm args
, которые не являются последними в отображении
.Pq они обрезаются до 16 байт ,
и для последнего столбца в отображении, если его ключевое слово запрашивает текстовую
информацию переменной длины, как это делают ключевые слова
.Cm command , jail ,
и
.Cm user .
Это значительно ограничивает влияние и полезность ширины терминала на
вывод, и, следовательно, переменной окружения
.Ev COLUMNS
и опции
.Fl w
.Pq если указана только один раз .
.Pp
Утилита
.Nm
не отображает корректно списки аргументов, содержащие многобайтовые
символы.
