.\" FRDP path bin/pwd/pwd.1
.\" FRDP githash 586a5bc03541397c432ce98a1551ebeee7c04ef2
.\" FRDP hash256 d5f4021aa589bf8364a08536538c433b238a97cf2d863ce5c02c25949b58101e
.Dd February 6, 2026
.Dt PWD 1
.Os
.Sh ИМЯ
.Nm pwd
.Nd вывести имя текущего рабочего каталога
.Sh СИНТАКСИС
.Nm
.Op Fl L | P
.Sh ОПИСАНИЕ
Утилита
.Nm
записывает абсолютное имя пути текущего рабочего каталога в
стандартный вывод.
.Pp
Некоторые оболочки могут предоставлять встроенную команду
.Nm ,
которая похожа на эту утилиту или идентична ей.
Обратитесь к странице руководства
.Xr builtin 1 .
.Pp
Параметры следующие:
.Bl -tag -width indent
.It Fl L
Выводить логический текущий рабочий каталог.
.It Fl P
Выводить физический текущий рабочий каталог (все символические ссылки разрешены).
.El
.Pp
Если параметры не указаны, подразумевается параметр
.Fl L .
.Sh ОКРУЖЕНИЕ
Переменные окружения, используемые
.Nm :
.Bl -tag -width "PWD"
.It Ev PWD
Логический текущий рабочий каталог.
.El
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
Показать текущий рабочий каталог с разрешёнными символическими ссылками:
.Bd -literal -offset indent
$ /bin/pwd
/usr/src/sys/kern
.Ed
.Pp
Показать логический текущий каталог.
Затем используйте
.Xr file 1 ,
чтобы просмотреть каталог
.Pa /sys :
.Bd -literal -offset indent
$ /bin/pwd -L
/sys/kern
$ file /sys
/sys: symbolic link to usr/src/sys
.Ed
.Sh СМ. ТАКЖЕ
.Xr builtin 1 ,
.Xr cd 1 ,
.Xr csh 1 ,
.Xr realpath 1 ,
.Xr sh 1 ,
.Xr getcwd 3
.Sh СТАНДАРТЫ
Утилита
.Nm
соответствует
.St -p1003.1-2001 .
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v5 .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
В
.Xr csh 1
команда
.Ic dirs
всегда быстрее, потому что она встроена в эту оболочку.
Однако она может дать другой ответ в редком случае,
когда текущий каталог или содержащий его каталог были перемещены после
того, как оболочка перешла в него.
.Pp
Параметр
.Fl L
не работает, если переменная окружения
.Ev PWD
не экспортирована оболочкой.
