.\" FRDP path sys/contrib/openzfs/man/man1/raidz_test.1
.\" FRDP githash 22649d4dba730d46244fd2dff4fd174903c8379f
.\" FRDP hash256 0e98bf2b3c984917336deea5b918f93f21ea97bf85759ef9120d4da744464451
.Dd May 26, 2021
.Dt RAIDZ_TEST 1
.Os
.
.Sh ИМЯ
.Nm raidz_test
.Nd инструмент проверки и бенчмаркинга реализации raidz
.Sh СИНТАКСИС
.Nm
.Op Fl StBevTD
.Op Fl a Ar ashift
.Op Fl o Ar zio_off_shift
.Op Fl d Ar raidz_data_disks
.Op Fl s Ar zio_size_shift
.Op Fl r Ar reflow_offset
.
.Sh ОПИСАНИЕ
Назначение этого инструмента — запустить все поддерживаемые реализации raidz и проверить
результаты всех методов.
Он также содержит опцию перебора параметров, при которой проверяются все
параметры, влияющие на блок RAID-Z (такие как размер ashift, смещение данных,
размер данных и т. д.).
Инструмент также поддерживает режим бенчмаркинга с использованием
параметра
.Fl B .
.
.Sh ПАРАМЕТРЫ
.It Fl h
Вывести краткую справку.
.It Fl a Ar ashift Pq по умолчанию: Sy 9
Значение ashift.
.It Fl o Ar zio_off_shift Pq по умолчанию: Sy 0
Смещение ZIO для каждого блока raidz.
Значение смещения —
.Em 2^zio_off_shift .
.It Fl d Ar raidz_data_disks Pq по умолчанию: Sy 8
Количество используемых дисков данных raidz.
Дополнительные диски будут использоваться для чётности.
.It Fl s Ar zio_size_shift Pq по умолчанию: Sy 19
Размер данных для блока raidz.
Реальный размер —
.Em 2^zio_size_shift .
.It Fl r Ar reflow_offset Pq по умолчанию: Sy uint max
Задать смещение расширения raidz.
Функция выделения расширенной карты raidz будет
создавать различные конфигурации карты в зависимости от этого значения.
.It Fl S Ns Pq перебор
Перебирать пространство параметров при проверке реализаций raidz.
Этот параметр
исчерпает почти все допустимые значения для
параметров
.Fl aods .
Время работы с этим параметром будет большим.
.It Fl t Ns Pq тайм-аут
Астрономическое время для теста перебора в секундах.
Фактическое время работы может быть больше.
.It Fl B Ns Pq бенчмарк
Все реализации тестируются с использованием увеличивающегося размера данных на диск.
Результаты приводятся как пропускная способность на диск, измеряемая в МиБ/с.
.It Fl e Ns Pq расширение
Использовать функцию выделения расширенной карты raidz.
.It Fl v Ns Pq подробно
Увеличить подробность вывода.
.It Fl T Ns Pq тест теста
Отладочный параметр: провалить все тесты.
Это для проверки того, будут ли тесты должным образом проверять побитовую точность.
.It Fl D Ns Pq отладка
Отладочный параметр: подключить
.Xr gdb 1
при получении
.Sy SIGSEGV
или
.Sy SIGABRT .
.El
.
.Xr ztest 1
