.\" Licensed under the OpenIB.org BSD license (FreeBSD Variant) - See COPYING.md
.\" FRDP path ./contrib/ofed/librdmacm/man/rcopy.1
.\" FRDP githash d6b92ffa990dc57d8a969a98e3ca4e25ba39cbb2
.\" FRDP hash256 eca91a28d7507d540e15ad6dc4962d337a320157e5eef2bde1a1d972ae4899b8
.SH ИМЯ
rcopy \- простая копия файлов через RDMA.
.SH СИНТАКСИС
.sp
.nf
\fIrcopy\fR исходный_файл сервер[:приёмник] [-p порт]
\fIrcopy\fR [-p порт]
.fi
Использует сокеты через интерфейс RDMA для копирования исходного файла в указанный приёмник.
.TP
исходный_файл
Имя и путь к исходному файлу для копирования.
.TP
сервер
Имя или адрес сервера-приёмника.
.TP
:приёмник
Необязательное имя и путь файла-приёмника. Если не указано, имя файла-приёмника будет совпадать с именем исходного файла.
.TP
\-p порт_сервера
Номер порта сервера.
.TP
Базовое использование: запустить rcopy на серверной системе, затем выполнить
rcopy исходный_файл имя_сервера. Серверное приложение продолжит работу после копирования файла, но в настоящее время является однопоточным.
.P
Поскольку этот тест отображает ресурсы RDMA в пользовательское пространство, пользователи должны убедиться, что у них есть доступные системные ресурсы и разрешения. Дополнительные подробности см. в файле README libibverbs.
rdma_cm(7)
