.\" FRDP path usr.bin/rusers/rusers.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 3005d3e74dadcf60da02a763aa05a0abb668e90140ffdbf2342d23433d08f773
.Dd April 23, 1991
.Dt RUSERS 1
.Os
.Sh ИМЯ
.Nm rusers
.Nd кто вошёл в систему на машинах локальной сети
.Sh СИНТАКСИС
.Nm
.Op Fl al
.Op Ar host ...
.Sh ОПИСАНИЕ
Команда
.Nm
выдаёт вывод, аналогичный
.Xr who 1 ,
но для списка
.Ar host Ns s
или всех машин в локальной
сети.
Для каждого
.Ar host ,
ответившего на
запрос
.Nm ,
на каждой строке выводится имя хоста с именами пользователей, которые в данный момент
вошли в систему.
Команда
.Nm
будет ждать
одну минуту, чтобы уловить поздние ответы.
.Pp
Доступны следующие параметры:
.Bl -tag -width indent
.It Fl a
Выводить все машины, которые ответили, даже если в данный момент никто не вошёл в систему.
.It Fl l
Выводить длинный формат списка.
Он включает имя пользователя, имя хоста,
tty, в который вошёл пользователь, дату и время, когда пользователь
вошёл в систему, количество времени с момента, когда пользователь печатал на клавиатуре,
и удалённый хост, с которого он вошёл (если применимо).
.El
.Sh ДИАГНОСТИКА
.Bl -diag
.It rusers: RPC: Program not registered
Демон
.Xr rpc.rusersd 8
не был запущен на удалённом хосте.
.It rusers: RPC: Timed out
Произошла ошибка связи.
Либо сеть
чрезмерно перегружена, либо
демон
.Xr rpc.rusersd 8
завершился на удалённом хосте.
Удалённый хост не запускает portmapper (см.
.Xr rpcbind 8 )
и не может обслуживать какие-либо службы на основе RPC.
Хост может быть недоступен.
.El
.Sh СМ. ТАКЖЕ
.Xr rwho 1 ,
.Xr users 1 ,
.Xr who 1 ,
.Xr rpc.rusersd 8 ,
.Xr rpcbind 8
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Em Sun-OS .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Параметры сортировки не реализованы.
