.\" FRDP path bin/setfacl/setfacl.1
.\" FRDP githash fa9896e082a1046ff4fbc75fcba4d18d1f2efc19
.\" FRDP hash256 1a2d2fb9ee3d81621b3b0953d77af982de4de6a69c30a79add5c5743b2d8ecff
.Dd April 29, 2023
.Dt SETFACL 1
.Os
.Sh ИМЯ
.Nm setfacl
.Nd установить информацию ACL
.Sh СИНТАКСИС
.Nm
.Op Fl R Op Fl H | L | P
.Op Fl bdhkn
.Op Fl a Ar позиция записи
.Op Fl m Ar записи
.Op Fl M Ar файл
.Op Fl x Ar записи | позиция
.Op Fl X Ar файл
.Op Ar
.Sh ОПИСАНИЕ
Утилита
.Nm
устанавливает информацию дискреционного управления доступом для указанных
файлов.
Если файлы не указаны или список состоит только из
.Sq Fl ,
имена файлов берутся из стандартного ввода.
.Pp
Доступны следующие параметры:
.Bl -tag -width indent
.It Fl a Ar позиция записи
Изменить ACL указанных файлов, вставив новые
записи ACL,
указанные в
.Ar записи ,
начиная с позиции
.Ar позиция ,
отсчет от нуля.
Этот параметр применим только к ACL NFSv4.
.It Fl b
Удалить все записи ACL, кроме синтезированных
из режима файла — трех обязательных записей в случае POSIX.1e ACL.
Если POSIX.1e ACL содержит запись
.Dq Li mask ,
права доступа записи
.Dq Li group
в результирующем ACL будут установлены в значение, связанное с записями
.Dq Li group
и
.Dq Li mask
текущего ACL.
.It Fl d
Операции применяются к записям ACL по умолчанию, а не к записям ACL доступа.
В настоящее время только каталоги могут иметь
ACL по умолчанию.
Этот параметр не применим к ACL NFSv4.
.It Fl h
Если целью операции является символическая ссылка, выполнить операцию
над самой символической ссылкой, а не следовать по ссылке.
.It Fl H
Если указан параметр
.Fl R ,
символические ссылки в командной строке прослеживаются
и, следовательно, на них команда не влияет.
(Символические ссылки, встречающиеся при обходе дерева, не прослеживаются.)
.It Fl k
Удалить все записи ACL по умолчанию на указанных файлах.
Не считается ошибкой, если указанные файлы не имеют
записей ACL по умолчанию.
Ошибка будет выдана, если какой-либо из
указанных файлов не может иметь запись по умолчанию (т. е.
не каталог).
Этот параметр не применим к ACL NFSv4.
.It Fl L
Если указан параметр
.Fl R ,
прослеживаются все символические ссылки.
.It Fl m Ar записи
Изменить ACL указанного файла.
Новые записи будут добавлены, а существующие записи изменены
в соответствии с аргументом
.Ar записи .
Для ACL NFSv4 вместо этого рекомендуется использовать параметры
.Fl a
и
.Fl x .
.It Fl M Ar файл
Изменить записи ACL указанных файлов, добавив новые
записи ACL и изменив существующие записи ACL с помощью записей ACL,
указанных в файле
.Ar файл .
Если
.Ar файл
— это
.Fl ,
ввод берется из стандартного ввода.
.It Fl n
Не пересчитывать права доступа, связанные с записью маски ACL.
Этот параметр не применим к ACL NFSv4.
.It Fl P
Если указан параметр
.Fl R ,
символические ссылки не прослеживаются.
Это значение по умолчанию.
.It Fl R
Выполнить действие рекурсивно для всех указанных каталогов.
При изменении или добавлении записей ACL NFSv4 флаги наследования
применяются только к каталогам.
.It Fl x Ar записи | позиция
Если указаны
.Ar записи ,
удалить указанные там записи ACL
из ACL доступа или ACL по умолчанию указанных файлов.
В противном случае удалить запись с индексом
.Ar позиция ,
отсчет от нуля.
.It Fl X Ar файл
Удалить записи ACL, указанные в файле
.Ar файл ,
из ACL доступа или ACL по умолчанию указанных файлов.
.El
.Pp
Вышеуказанные параметры обрабатываются в порядке, указанном
в командной строке.
.Sh ЗАПИСИ POSIX.1e ACL
Запись POSIX.1E ACL содержит три разделенных двоеточиями поля:
тег ACL, квалификатор ACL и права дискреционного доступа:
.Bl -tag -width indent
Тег ACL указывает тип записи ACL и состоит из
одного из следующего:
.Dq Li user
или
.Ql u
указывает доступ,
предоставленный владельцу файла или указанному пользователю;
.Dq Li group
или
.Ql g
указывает доступ, предоставленный группе-владельцу файла
или указанной группе;
.Dq Li other
или
.Ql o
указывает доступ,
предоставленный любому процессу, который не соответствует ни одной записи ACL
пользователя или группы;
.Dq Li mask
или
.Ql m
указывает максимальный доступ,
предоставленный любой записи ACL, кроме записи
.Dq Li user
ACL для владельца файла и записи
.Dq Li other
ACL.
Поле квалификатора ACL описывает пользователя или группу, связанных с
записью ACL.
Оно может состоять из одного из следующего: uid или
имя пользователя, gid или имя группы, либо быть пустым.
Для
.Dq Li user
записей ACL пустое поле указывает доступ, предоставленный
владельцу файла.
Для
.Dq Li group
записей ACL пустое поле указывает доступ, предоставленный
группе-владельцу файла.
Записи
.Dq Li mask
и
.Dq Li other
ACL не используют это поле.
Поле прав доступа содержит не более одного из каждого из
следующего:
.Ql r ,
.Ql w ,
и
.Ql x
для установки прав на чтение, запись и
выполнение соответственно.
Каждое из них может отсутствовать
или быть заменено символом
.Ql -
для указания отсутствия доступа.
.El
.Pp
Запись
.Dq Li mask
ACL требуется для файла с любыми записями ACL, отличными от
записей по умолчанию
.Dq Li user ,
.Dq Li group ,
и
.Dq Li other
ACL.
Если параметр
.Fl n
не указан и запись
.Dq Li mask
ACL не была указана, утилита
.Nm
применит запись
.Dq Li mask
ACL, состоящую из объединения прав, связанных
со всеми записями
.Dq Li group
ACL в результирующем ACL.
.Pp
Традиционные интерфейсы POSIX, действующие на режимы объектов файловой системы, имеют
измененную семантику при наличии расширенных ACL POSIX.1e.
Когда запись маски присутствует в ACL доступа объекта, запись маски
подставляется вместо битов группы; это происходит в таких программах,
как
.Xr stat 1
или
.Xr ls 1 .
Когда режим изменяется у объекта, имеющего запись маски,
изменения, применяемые к битам группы, фактически будут применены к
записи маски.
Эта семантика обеспечивает большую совместимость приложений:
приложения, изменяющие режим вместо ACL, будут видеть
консервативное поведение, ограничивающее действующие права, предоставленные всеми
дополнительными записями пользователей и групп; это происходит в таких программах,
как
.Xr chmod 1 .
.Pp
Записи ACL, применяемые из файла с помощью параметров
.Fl M
или
.Fl X ,
должны быть следующей формы: одна запись ACL на строку, как
указано ранее; пробелы игнорируются; любой текст после
.Ql #
игнорируется (комментарии).
.Pp
Когда вычисляются записи POSIX.1e ACL, алгоритм проверки доступа проверяет
записи ACL в следующем порядке: владелец файла,
записи
.Dq Li user
ACL, группа-владелец файла,
записи
.Dq Li group
ACL и запись
.Dq Li other
ACL.
.Pp
Несколько записей ACL, указанных в командной строке,
разделяются запятыми.
.Pp
Файлы и каталоги могут наследовать записи ACL от своего
родительского каталога.
Это достигается с помощью ACL по умолчанию.
Следует отметить, что прежде чем можно будет указать ACL по умолчанию, должны быть установлены обязательные
записи ACL для user, group, other и mask.
Более подробную информацию см. в примерах ниже.
ACL по умолчанию можно создать с помощью
.Fl d .
.Sh ЗАПИСИ NFSv4 ACL
Запись NFSv4 ACL содержит четыре или пять разделенных двоеточиями полей: тег ACL,
квалификатор ACL (только для тегов
.Dq Li user
и
.Dq Li group ),
права дискреционного доступа, флаги наследования ACL и тип ACL:
.Bl -tag -width indent
Тег ACL указывает тип записи ACL и состоит из
одного из следующего:
.Dq Li user
или
.Ql u
указывает доступ,
предоставленный указанному пользователю;
.Dq Li group
или
.Ql g
указывает доступ, предоставленный указанной группе;
.Dq Li owner@
указывает доступ, предоставленный владельцу файла;
.Dq Li group@
указывает доступ, предоставленный группе-владельцу файла;
.Dq Li everyone@
указывает всем.
Обратите внимание, что
.Dq Li everyone@
не то же самое, что традиционный Unix
.Dq Li other
— это означает,
буквально, всех, включая владельца файла и группу-владельца.
Поле квалификатора ACL описывает пользователя или группу, связанных с
записью ACL.
Оно может состоять из одного из следующего: uid или
имя пользователя, либо gid или имя группы.
В записях, чей тип тега — один из
.Dq Li owner@ ,
.Dq Li group@ ,
или
.Dq Li everyone@ ,
это поле опускается полностью, включая завершающее двоеточие.
Права доступа могут быть указаны либо в краткой, либо в длинной форме.
Краткая и длинная формы не могут смешиваться.
Права в длинной форме разделяются символом
.Ql / ;
в краткой форме они объединяются вместе.
Допустимые права:
.Bl -tag -width ".It Short" -compact
.It Краткая
Длинная
.It r
read_data
.It w
write_data
.It x
execute
.It p
append_data
.It D
delete_child
.It d
delete
.It a
read_attributes
.It A
write_attributes
.It R
read_xattr
.It W
write_xattr
.It c
read_acl
.It C
write_acl
.It o
write_owner
.It s
synchronize
.El
.Pp
Кроме того, могут использоваться следующие наборы прав:
.Bl -tag -width ".It Set" -compact
.It Набор
Права
.It full_set
все права, как показано выше
.It modify_set
все права, кроме write_acl и write_owner
.It read_set
read_data, read_attributes, read_xattr и read_acl
.It write_set
write_data, append_data, write_attributes и write_xattr
.El
Флаги наследования могут быть указаны либо в краткой, либо в длинной форме.
Краткая и длинная формы не могут смешиваться.
Флаги наследования в длинной форме разделяются символом
.Ql / ;
в краткой форме они объединяются вместе.
Допустимые флаги наследования:
.Bl -tag -width ".It Short" -compact
.It Краткая
Длинная
.It f
file_inherit
.It d
dir_inherit
.It i
inherit_only
.It n
no_propagate
.It I
inherited
.El
.Pp
Поле типа ACL — это либо
.Dq Li allow
либо
.Dq Li deny .
.El
.Pp
Записи ACL, применяемые из файла с помощью параметров
.Fl M
или
.Fl X ,
должны быть следующей формы: одна запись ACL на строку, как
указано ранее; пробелы игнорируются; любой текст после
.Ql #
игнорируется (комментарии).
.Pp
Записи NFSv4 ACL вычисляются в их видимом порядке.
.Pp
Несколько записей ACL, указанных в командной строке,
разделяются запятыми.
.Pp
Обратите внимание, что владельцу файла всегда предоставляются права read_acl, write_acl,
read_attributes и write_attributes, даже если ACL
отказывает в них.
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
.Dl setfacl -d -m u::rwx,g::rx,o::rx,mask::rwx dir
.Dl setfacl -d -m g:admins:rwx dir
.Pp
Первая команда задает обязательные элементы POSIX.1e ACL по умолчанию.
Вторая команда указывает, что пользователи в группе admins могут наследовать эти ACL по умолчанию при создании с правами на чтение, запись и выполнение.
.Pp
.Dl setfacl -m u::rwx,g:mail:rw file
.Pp
Устанавливает права на чтение, запись и выполнение для
записи POSIX.1e ACL владельца
.Pa file
и права на чтение и запись для группы mail на
.Pa file .
.Pp
.Dl setfacl -m owner@:rwxp::allow,g:mail:rwp::allow file
.Pp
Семантически равно примеру выше, но для NFSv4 ACL.
.Pp
.Dl setfacl -M file1 file2
.Pp
Устанавливает/обновляет записи ACL, содержащиеся в
.Pa file1
на
.Pa file2 .
.Pp
.Dl setfacl -x g:mail:rw file
.Pp
Удалить запись POSIX.1e ACL группы mail, содержащую права на чтение/запись,
из
.Pa file .
.Pp
.Dl setfacl -x0 file
.Pp
Удалить первую запись из NFSv4 ACL файла
.Pa file .
.Pp
.Dl setfacl -bn file
.Pp
Удалить все
.Dq Li access
записи ACL, кроме трех обязательных, из
.Pa file .
.Pp
.Dl getfacl file1 | setfacl -b -n -M - file2
.Pp
Скопировать записи ACL из
.Pa file1
в
.Pa file2 .
.Sh СМ. ТАКЖЕ
.Xr getfacl 1 ,
.Xr acl 3 ,
.Xr getextattr 8 ,
.Xr setextattr 8 ,
.Xr acl 9 ,
.Xr extattr 9
.Sh СТАНДАРТЫ
Ожидается, что утилита
.Nm
соответствует
.Tn IEEE
Std 1003.2c.
.Sh ИСТОРИЯ
Поддержка расширенных атрибутов и списков управления доступом была разработана
как часть проекта
.Tn TrustedBSD
и представлена в
.Fx 5.0 .
Поддержка NFSv4 ACL была представлена в
.Fx 8.1 .
.Sh АВТОРЫ
.An -nosplit
Утилита
.Nm
была написана
.An Chris D. Faulhaber Aq Mt jedgar@fxp.org .
Поддержка NFSv4 ACL была реализована
.An Edward Tomasz Napierala Aq Mt trasz@FreeBSD.org .
