.\" FRDP path bin/sleep/sleep.1
.\" FRDP githash 24983c4e9f9934282e8d81381095da819ad97c63
.\" FRDP hash256 e84d7fac0ff2372acfc3f87844fd6a108e16c9b36947308097ce00913eee37f5
.Dd July 27, 2026
.Dt SLEEP 1
.Os
.Sh ИМЯ
.Nm sleep
.Nd приостановить выполнение на заданный интервал времени
.Sh СИНТАКСИС
.Nm
.Ar число Ns Op Ar единица
.Op ...
.Sh ОПИСАНИЕ
Команда
.Nm
приостанавливает выполнение как минимум на
.Ar число
секунд (по умолчанию, или единица
.Li s ) ,
минут (единица
.Li m ) ,
часов (единица
.Li h ) ,
или дней (единица
.Li d ) .
Интервалы могут быть записаны в любой форме, допустимой
.Xr strtod 3 .
Если задано несколько интервалов, они складываются.
Если итоговая сумма равна нулю или отрицательна,
.Nm
немедленно завершается.
.Pp
Если команда
.Nm
получает сигнал, она выполняет стандартное действие.
При получении сигнала
.Dv SIGINFO
на стандартный поток ошибок выводится оценка количества секунд, оставшихся до
завершения.
.Sh ПРИМЕЧАНИЯ ПО РЕАЛИЗАЦИИ
Сигнал
.Dv SIGALRM
не обрабатывается этой реализацией особым образом.
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
Чтобы запустить команду через полчаса:
.Pp
.Dl (sleep 0.5h; sh command_file >out 2>err)&
.Pp
Это заклинание будет ждать полчаса, прежде чем
запустить сценарий
.Pa command_file .
См. утилиту
.Xr at 1
для другого способа сделать это.
.Pp
Чтобы повторно запускать команду:
.Pp
.Bd -literal -offset indent -compact
while :; do
	if ! [ -r zzz.rawdata ] ; then
		sleep 5m
	else
		for i in *.rawdata ; do
			sleep 70
		done >results
		break
	fi
done
.Ed
.Pp
Сценарий для такого скрипта может быть таким: программа, работающая в данный момент, обрабатывает серию файлов дольше, чем ожидалось, и было бы неплохо, чтобы другая программа начала обработку файлов, созданных первой программой, как только она завершится (когда
.Pa zzz.rawdata
будет создан).
Скрипт проверяет каждые пять минут наличие файла
.Pa zzz.rawdata ,
и когда файл найден, очередная часть обработки выполняется с вежливыми паузами по 70 секунд между каждым
.Xr awk 1
заданием.
.Sh СМ. ТАКЖЕ
.Xr nanosleep 2 ,
.Xr sleep 3
.Sh СТАНДАРТЫ
Ожидается, что команда
.Nm
совместима с
.St -p1003.2 .
.Pp
Поддержка нецелых интервалов, единиц, отличных от секунд, и
нескольких интервалов, которые складываются, представляет собой непереносимые
расширения, впервые появившиеся в GNU sh-utils 2.0a (выпущено в 2002 году).
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v4 .
