.\" FRDP path bin/stty/stty.1
.\" FRDP githash da8b3e70abecdb038eac87086748899a04b29636
.\" FRDP hash256 e940e79e1b27d1c80ddef4522004df880fb7c8660daaad158612efd695344919
.Dd September 27, 2022
.Dt STTY 1
.Os
.Sh ИМЯ
.Nm stty
.Nd "установить параметры интерфейса терминального устройства"
.Sh СИНТАКСИС
.Nm
.Op Fl a | e | g
.Op Fl f Ar файл
.Op Ar аргументы
.Sh ОПИСАНИЕ
Утилита
.Nm
устанавливает или выводит характеристики терминала
для устройства, которое является её стандартным вводом.
Если не указаны параметры или аргументы, она выводит настройки подмножества
характеристик, а также дополнительные, если они отличаются от значений
по умолчанию.
В противном случае она изменяет состояние терминала в соответствии с указанными аргументами.
Некоторые комбинации аргументов взаимно исключают друг друга на некоторых типах терминалов.
.Pp
Далее перечислены доступные параметры:
.Bl -tag -width indent
.It Fl a
Показать все текущие настройки терминала в стандартный вывод
в соответствии с
.St -p1003.2 .
.It Fl e
Показать все текущие настройки терминала в стандартный вывод
в традиционных форматах
.Bx
``all'' и ``everything''.
.It Fl f
Открыть и использовать терминал, указанный в
.Ar файл
вместо стандартного ввода.
Файл открывается
с использованием флага
.Dv O_NONBLOCK
функции
.Fn open ,
что позволяет
устанавливать или отображать настройки на терминале, который иначе
может блокироваться при открытии.
.It Fl g
Показать все текущие настройки терминала в стандартный вывод
в форме, которая может быть использована в качестве аргумента для последующего вызова
.Nm
для восстановления текущего состояния терминала в соответствии с
.St -p1003.2 .
.El
.Pp
Следующие аргументы доступны для установки характеристик
терминала:
.Ss Режимы управления:
Флаги режима управления влияют на аппаратные характеристики, связанные с
терминалом.
Это соответствует c_cflag в структуре termios.
.Bl -tag -width Fl
.It Cm parenb Pq Fl parenb
Включить (выключить) генерацию и обнаружение
чётности.
.It Cm parodd Pq Fl parodd
Выбрать нечётную (чётную) чётность.
.It Cm cs5 cs6 cs7 cs8
Выбрать размер символа, если возможно.
.It Ar number
Установить скорость передачи терминала в
указанное число, если возможно.
Если
скорость передачи установлена в ноль, управление модемом
больше не
подаётся.
.It Cm ispeed Ar number
Установить входную скорость передачи терминала в
указанное число, если возможно.
Если
входная скорость передачи установлена в ноль,
входная скорость передачи устанавливается в
значение выходной скорости
передачи.
.It Cm ospeed Ar number
Установить выходную скорость передачи терминала в
указанное число, если возможно.
Если
выходная скорость передачи установлена в
ноль, управление модемом
больше не подаётся.
.It Cm speed Ar number
Это устанавливает как
.Cm ispeed
так и
.Cm ospeed
в
.Ar number .
.It Cm hupcl Pq Fl hupcl
Прекратить подачу управления модемом
(не прекращать подачу управления модемом) при последнем закрытии.
.It Cm hup Pq Fl hup
То же, что и hupcl
.Pq Fl hupcl .
.It Cm cstopb Pq Fl cstopb
Использовать два (один) стоповых бита на символ.
.It Cm cread Pq Fl cread
Включить (выключить) приёмник.
.It Cm clocal Pq Fl clocal
Предполагать линию без (с) управлением
модемом.
.It Cm crtscts Pq Fl crtscts
Включить (выключить) управление потоком RTS/CTS.
.It Cm rtsdtr Pq Fl rtsdtr
Включить (выключить) подачу RTS/DTR при открытии.
.El
.Ss Режимы ввода:
Это соответствует c_iflag в структуре termios.
.Bl -tag -width Fl
.It Cm ignbrk Pq Fl ignbrk
Игнорировать (не игнорировать) break на
входе.
.It Cm brkint Pq Fl brkint
Сигнализировать (не сигнализировать)
.Dv INTR
при
break.
.It Cm ignpar Pq Fl ignpar
Игнорировать (не игнорировать) символы с ошибками
чётности.
.It Cm parmrk Pq Fl parmrk
Помечать (не помечать) символы с ошибками чётности.
.It Cm inpck Pq Fl inpck
Включить (выключить) проверку чётности
на входе.
.It Cm istrip Pq Fl istrip
Обрезать (не обрезать) входные символы
до семи бит.
.It Cm inlcr Pq Fl inlcr
Преобразовывать (не преобразовывать)
.Dv NL
в
.Dv CR
на входе.
.It Cm igncr Pq Fl igncr
Игнорировать (не игнорировать)
.Dv CR
на входе.
.It Cm icrnl Pq Fl icrnl
Преобразовывать (не преобразовывать)
.Dv CR
в
.Dv NL
на входе.
.It Cm ixon Pq Fl ixon
Включить (выключить)
управление выводом
.Dv START/STOP .
Вывод из системы
останавливается, когда система получает
.Dv STOP
и запускается, когда система
получает
.Dv START ,
или, если
.Cm ixany
установлен, любой символ возобновляет вывод.
.It Cm ixoff Pq Fl ixoff
Запрашивать, чтобы система отправляла (не
отправляла)
символы
.Dv START/STOP ,
когда
очередь ввода почти
пуста/полна.
.It Cm ixany Pq Fl ixany
Разрешить любому символу (разрешить только
.Dv START )
возобновлять вывод.
.It Cm imaxbel Pq Fl imaxbel
Система накладывает ограничение в
.Dv MAX_INPUT
(в настоящее время 255) символов в очереди ввода.
Если
.Cm imaxbel
установлен и достигнут предел очереди ввода,
последующий ввод заставляет систему отправить символ ASCII BEL
в очередь вывода (терминал издаёт звуковой сигнал).
В противном случае,
если
.Cm imaxbel
снят и очередь ввода заполнена, следующий входной символ вызывает
отбрасывание всей очереди ввода и вывода.
.It Cm iutf8 Pq Fl iutf8
Предполагать, что входные символы закодированы в UTF-8. Установка этого флага
позволяет backspace корректно удалять многобайтовые символы в каноническом режиме.
.El
.Ss Режимы вывода:
Это соответствует c_oflag структуры termios.
.Bl -tag -width Fl
.It Cm opost Pq Fl opost
Постобрабатывать вывод (не
постобрабатывать вывод; игнорировать все другие
режимы вывода).
.It Cm onlcr Pq Fl onlcr
Преобразовывать (не преобразовывать)
.Dv NL
в
.Dv CR-NL
на выходе.
.It Cm ocrnl Pq Fl ocrnl
Преобразовывать (не преобразовывать)
.Dv CR
в
.Dv NL
на выходе.
.It Cm tab0 tab3
Выбрать политику расширения табуляции.
.Cm tab0
отключает расширение табуляции, а
.Cm tab3
включает его.
.It Cm onocr Pq Fl onocr
Не выводить (выводить) CR в нулевой колонке.
.It Cm onlret Pq Fl onlret
На терминале NL выполняет (не выполняет) функцию CR.
.El
.Ss Локальные режимы:
Флаги локального режима (lflags) влияют на различные характеристики обработки терминала.
реализованы Джимом Кулпом на
.Tn Pdp 11/70
в
.Tn IIASA .
Позже драйвер работал на первом
.Tn VAX
в Evans Hall, UC Berkeley, где детали управления заданиями
были сильно изменены, но определения структур и имена
остались практически неизменными.
Вторая интерпретация буквы 'l' в lflag
— ``line discipline flag'' (флаг дисциплины линии), который соответствует
.Ar c_lflag
структуры
.Ar termios .
.Bl -tag -width Fl
.It Cm isig Pq Fl isig
Включить (выключить) проверку
символов на специальные управляющие
символы
.Dv INTR , QUIT ,
и
.Dv SUSP .
.It Cm icanon Pq Fl icanon
Включить (выключить) канонический ввод
.Pf ( Dv ERASE
и
.Dv KILL
обработка).
.It Cm iexten Pq Fl iexten
Включить (выключить) любые
определённые реализацией специальные управляющие символы,
не управляемые в настоящее время icanon,
isig или ixon.
.It Cm echo Pq Fl echo
Отображать (не отображать) каждый
введённый символ.
.It Cm echoe Pq Fl echoe
Символ
.Dv ERASE
должен (не должен) визуально стирать последний символ
в текущей строке с
дисплея, если возможно.
.It Cm echok Pq Fl echok
Отображать (не отображать)
.Dv NL
после символа
.Dv KILL .
.It Cm echoke Pq Fl echoke
Символ
.Dv KILL
должен (не должен) визуально стирать
текущую строку с
дисплея, если возможно.
.It Cm echonl Pq Fl echonl
Отображать (не отображать)
.Dv NL ,
даже если эхо
отключено.
.It Cm echoctl Pq Fl echoctl
Если
.Cm echoctl
установлен, отображать управляющие символы как ^X.
В противном случае управляющие символы
отображаются как есть.
.It Cm echoprt Pq Fl echoprt
Для печатающих терминалов.
Если установлен, отображать стёртые символы в обратном порядке между ``\\\\''
и ``/''.
В противном случае отключить эту функцию.
.It Cm noflsh Pq Fl noflsh
Отключить (включить) сброс после
.Dv INTR , QUIT , SUSP .
.It Cm tostop Pq Fl tostop
Отправлять (не отправлять)
.Dv SIGTTOU
для фонового вывода.
Это заставляет фоновые задания останавливаться, если они пытаются
выводить на терминал.
.It Cm altwerase Pq Fl altwerase
Использовать (не использовать) альтернативный алгоритм стирания слова при обработке
символов
.Dv WERASE .
Этот альтернативный алгоритм рассматривает последовательности
алфавитно-цифровых символов/подчёркиваний как слова.
Он также пропускает первый предшествующий символ в своей классификации
(для удобства, так как один предшествующий символ мог быть
стёрт просто символом
.Dv ERASE .)
.It Cm mdmbuf Pq Fl mdmbuf
Если установлен, управлять потоком вывода на основе состояния Carrier Detect.
В противном случае
запись возвращает ошибку, если Carrier Detect низкий (и Carrier не
игнорируется флагом
.Dv CLOCAL .)
.It Cm flusho Pq Fl flusho
Указывает, что вывод (не) отбрасывается.
.It Cm pendin Pq Fl pendin
Указывает, что ввод (не) ожидает после переключения из неканонического
в канонический режим и будет повторно введён, когда чтение станет ожидающим
или поступит больше ввода.
.El
.Ss Управляющие символы:
.Bl -tag -width Fl
.It Ar control-character Ar string
Установить
.Ar control-character
в
.Ar string .
Если строка является единственным символом,
управляющий символ устанавливается в
этот символ.
Если строка является
отключён (т.е. установлен в
.Pf { Dv _POSIX_VDISABLE Ns } . )
.Pp
Распознаваемые управляющие символы:
.Bd -ragged -offset indent
.Bl -column символ Индекс Описание
.It control- Ta \& Ta \&
.It символ Ta Индекс Ta Описание
.It _________ Ta _________ Ta _______________
.It eof Ta Tn VEOF Ta EOF No символ
.It eol Ta Tn VEOL Ta EOL No символ
.It eol2 Ta Tn VEOL2 Ta EOL2 No символ
.It erase Ta Tn VERASE Ta ERASE No символ
.It erase2 Ta Tn VERASE2 Ta ERASE2 No символ
.It werase Ta Tn VWERASE Ta WERASE No символ
.It intr Ta Tn VINTR Ta INTR No символ
.It kill Ta Tn VKILL Ta KILL No символ
.It quit Ta Tn VQUIT Ta QUIT No символ
.It susp Ta Tn VSUSP Ta SUSP No символ
.It start Ta Tn VSTART Ta START No символ
.It stop Ta Tn VSTOP Ta STOP No символ
.It discard Ta Tn VDISCARD Ta DISCARD No символ
.It dsusp Ta Tn VDSUSP Ta DSUSP No символ
.It lnext Ta Tn VLNEXT Ta LNEXT No символ
.It reprint Ta Tn VREPRINT Ta REPRINT No символ
.It status Ta Tn VSTATUS Ta STATUS No символ
.El
.Ed
.It Cm min Ar number
.It Cm time Ar number
Установить значение min или time в
число.
.Dv MIN
и
.Dv TIME
используются в
неканоническом режиме обработки ввода
(-icanon).
.El
.Ss Комбинированные режимы:
.Bl -tag -width Fl
.It Ar сохранённые настройки
Установить текущие характеристики терминала
в сохранённые настройки,
созданные параметром
.Fl g .
.It Cm evenp No или Cm parity
Включить parenb и cs7; выключить
parodd.
.It Cm oddp
Включить parenb, cs7 и parodd.
.It Fl parity , evenp , oddp
Выключить parenb и установить cs8.
.It Cm \\&nl Pq Fl \\&nl
Включить (выключить) icrnl.
Кроме того,
-nl снимает inlcr и igncr.
.It Cm ek
Сбросить
.Dv ERASE ,
.Dv ERASE2
и
.Dv KILL
символы
к системным значениям по умолчанию.
.It Cm sane
Сбросить все режимы к разумным значениям для интерактивного использования терминала.
.It Cm tty
Установить дисциплину линии в стандартную терминальную дисциплину
.Dv TTYDISC .
.It Cm crt Pq Fl crt
Установить (выключить) все режимы, подходящие для устройства отображения CRT.
.It Cm kerninfo Pq Fl kerninfo
Включить (выключить) генерируемую системой строку состояния, связанную с
обработкой символа
.Dv STATUS
(обычно устанавливается в ^T).
Строка состояния состоит из
средней загрузки системы, имени текущей команды, её идентификатора процесса,
события, которого ожидает процесс (или статуса процесса), пользовательского
и системного времени, процента загрузки ЦП и текущего использования памяти.
.Pp
Если
.Xr sysctl 8
переменная
.Va kern.tty_info_kstacks
установлена в ненулевое значение, сообщение о состоянии также включает стек программы ядра
потока переднего плана.
.It Cm columns Ar number
Размер терминала записывается как имеющий
.Ar number
колонок.
.It Cm cols Ar number
является псевдонимом для
.Cm columns .
.It Cm rows Ar number
Размер терминала записывается как имеющий
.Ar number
строк.
.It Cm dec
Установить режимы, подходящие для пользователей систем Digital Equipment Corporation
.Dv ( ERASE ,
.Dv KILL
и
.Dv INTR
символы устанавливаются в ^?, ^U и ^C;
.Dv ixany
выключен, а
.Dv crt
включён.)
.It Cm extproc Pq Fl extproc
Если установлен, этот флаг указывает, что некоторая часть обработки терминала
выполняется либо аппаратным обеспечением терминала, либо удалённой стороной, подключённой
к pty.
.It Cm raw Pq Fl raw
Если установлен, изменить режимы терминала так, чтобы не выполнялась
никакая обработка ввода или вывода.
Если снят, изменить режимы терминала в некоторое разумное
состояние, которое выполняет обработку ввода и вывода.
Обратите внимание, что поскольку
драйвер терминала больше не имеет единого
.Dv RAW
бита, невозможно определить, какие флаги были установлены до установки
.Cm raw .
Это означает, что снятие
.Cm raw
может не восстановить все настройки, которые были ранее в силе.
Чтобы перевести терминал в raw-состояние и затем точно его восстановить, рекомендуется
следующий код оболочки:
.Bd -literal
save_state=$(stty -g)
stty raw
\\&...
.Ed
.It Cm size
Размер терминала выводится как два числа в одной строке,
сначала строки, затем колонки.
.El
.Ss Режимы совместимости:
Эти режимы сохранены для совместимости с предыдущей версией
команды
.Nm .
.Bl -tag -width Fl
.It Cm all
Сообщает все режимы терминала, как с
.Cm stty Fl a ,
за исключением того, что управляющие символы выводятся в табличном формате.
.It Cm everything
То же, что и
.Cm all .
.It Cm cooked
То же, что и
.Cm sane .
.It Cm cbreak
Если установлен, включает
.Cm brkint , ixon , imaxbel , opost ,
.Cm isig , iexten
и
.Fl icanon .
Если снят, то же, что и
.Cm sane .
.It Cm new
То же, что и
.Cm tty .
.It Cm old
То же, что и
.Cm tty .
.It Cm newcrt Pq Fl newcrt
То же, что и
.Cm crt .
.It Cm pass8
Обратное к
.Cm parity .
.It Cm tandem Pq Fl tandem
То же, что и
.Cm ixoff .
.It Cm decctlq Pq Fl decctlq
Обратное к
.Cm ixany .
.It Cm crterase Pq Fl crterase
То же, что и
.Cm echoe .
.It Cm crtbs Pq Fl crtbs
То же, что и
.Cm echoe .
.It Cm crtkill Pq Fl crtkill
То же, что и
.Cm echoke .
.It Cm ctlecho Pq Fl ctlecho
То же, что и
.Cm echoctl .
.It Cm prterase Pq Fl prterase
То же, что и
.Cm echoprt .
.It Cm litout Pq Fl litout
Обратное к
.Cm opost .
.It Cm oxtabs Pq Fl oxtabs
Расширять (не расширять) табуляции в пробелы на выводе.
.It Cm tabs Pq Fl tabs
Обратное к
.Cm oxtabs .
.It Cm brk Ar value
То же, что и управляющий символ
.Cm eol .
.It Cm flush Ar value
То же, что и управляющий символ
.Cm discard .
.It Cm rprnt Ar value
То же, что и управляющий символ
.Cm reprint .
.El
.Sh ВЗАИМОДЕЙСТВИЕ С УПРАВЛЕНИЕМ ЗАДАНИЯМИ
Модификации настроек терминала обрабатываются управлением заданиями
(см.
.Xr termios 4 )
так же, как и записи.
Когда
.Nm
выполняется в фоновой группе процессов,
такие попытки приводят к тому, что ядро посылает сигнал
.Dv SIGTTOU
и останавливает процесс до тех пор, пока его группа не будет возвращена
на передний план.
Неблокирующее открытие терминального устройства с
опцией
.Fl f
для
.Nm
не влияет на это поведение.
Если желательно изменить настройки из фона,
пользователи
.Xr sh 1
могут использовать следующую идиому:
.Bd -literal
(trap '' TTOU; stty -f /dev/tty sane)
.Ed
.Pp
Обратите внимание, что изменение настроек терминала для работающего задания переднего плана,
которое к этому не готово, может вызвать несоответствия.
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh СМ. ТАКЖЕ
.Xr resizewin 1 ,
.Xr termios 4 ,
.Xr pstat 8
.Sh СТАНДАРТЫ
Утилита
.Nm
должна быть
совместима с
.St -p1003.2 .
Флаги
.Fl e
и
.Fl f
являются
расширениями стандарта.
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v2 .
