.\" FRDP path usr.bin/systat/systat.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 4a406704de0da95bef670e44c96179b3f7d427f1f976d4d8b77f4ab1368f9573
.Dd April 1, 2022
.Dt SYSTAT 1
.Os
.Sh ИМЯ
.Nm systat
.Nd отображение системной статистики
.Sh СИНТАКСИС
.Nm
.Op Fl Ar display
.Op Ar display-commands
.Op Ar refresh-interval
.Sh ОПИСАНИЕ
Утилита
.Nm
отображает различную системную статистику в экранно-ориентированном стиле
с использованием библиотеки экранного отображения curses,
.Xr ncurses 3 .
.Pp
Пока
.Nm
работает, экран обычно разделён на два окна (исключение —
отображение vmstat, которое использует весь экран).
Верхнее окно отображает текущее среднее значение загрузки системы.
Информация, отображаемая в нижнем окне, может различаться в зависимости от
пользовательских команд.
Последняя строка на экране зарезервирована для пользовательского
ввода и сообщений об ошибках.
.Pp
По умолчанию
.Nm
отображает в нижнем окне процессы, получающие наибольший процент процессора.
Другие отображения показывают использование пространства подкачки, статистику дискового I/O (в стиле
.Xr iostat 8 ) ,
статистику виртуальной памяти (в стиле
.Xr vmstat 8 ) ,
статистику TCP/IP
и сетевые соединения (в стиле
.Xr netstat 1 ) .
.Pp
Ввод интерпретируется на двух разных уровнях.
«Глобальный» интерпретатор команд обрабатывает весь ввод с клавиатуры.
Если этому интерпретатору команд не удаётся распознать команду,
строка ввода передаётся интерпретатору команд конкретного отображения.
Это
позволяет каждому отображению иметь определённые команды, специфичные для отображения.
.Pp
Параметры командной строки:
.It Fl Ns Ar display
Флаг
.Fl
ожидает, что
.Ar display
будет одним из:
.Ic icmp ,
.Ic icmp6 ,
.Ic ifstat ,
.Ic iolat ,
.Ic iostat ,
.Ic ip ,
.Ic ip6 ,
.Ic netstat ,
.Ic pigs ,
.Ic sctp ,
.Ic swap ,
.Ic tcp ,
.Ic vmstat ,
или
.Ic zarc ,
Эти отображения также можно запросить интерактивно (без
.Dq Fl )
и они подробно описаны ниже.
.It Ar refresh-interval
.Ar refresh-value
задаёт интервал времени обновления экрана в секундах.
Интервал времени может быть дробным.
.It Ar display-commands
Список команд, специфичных для этого отображения.
Эти команды также можно вводить интерактивно, и они описаны для
каждого отображения отдельно ниже.
Если команда требует аргументов, их можно указать как отдельные
аргументы командной строки.
Аргумент командной строки
.Fl -
завершит команды отображения.
Например:
.Pp
.Dl Nm Fl ifstat Fl match Ar bge0,em1 Fl pps
.Pp
Это отобразит статистику пакетов в секунду для сетевых интерфейсов
с именами bge0 и em1.
.Pp
.Dl Nm Fl iostat Fl numbers Fl - Ar 2.1
.Pp
Это отобразит всю статистику IO в числовом формате, и информация
будет обновляться каждые 2.1 секунды.
.El
.Pp
Определённые символы вызывают немедленное действие
.Nm .
Это:
.Bl -tag -width Fl
.It Ic \&^L
Обновить экран.
.It Ic \&^G
Вывести имя текущего «отображения», показываемого в
нижнем окне, и интервал обновления.
.It Ic \&:
Переместить курсор в командную строку и интерпретировать введённую
строку как команду.
Во время ввода команды
можно использовать текущие символы стирания символа, стирания слова и уничтожения строки.
.El
.Pp
Следующие команды интерпретируются «глобальным»
интерпретатором команд.
.Bl -tag -width Fl
.It Ic help
Вывести имена доступных отображений в командной строке.
.It Ic load
Вывести среднее значение загрузки за последние 1, 5 и 15 минут
в командной строке.
.It Ic stop
Остановить обновление экрана.
.It Xo
.Op Ic start
.Op Ar number
.Xc
Начать (продолжить) обновление экрана.
Если предоставлен второй, числовой,
аргумент, он интерпретируется как интервал обновления
(в секундах).
Указание только числа установит интервал обновления в это
значение.
.It Ic quit
Выйти из
.Nm .
(Это можно сократить до
.Ic q . )
.El
.Pp
Доступные отображения:
.Bl -tag -width Ic
.It Ic pigs
Отображать в нижнем окне те процессы, которые находятся в основной
памяти и получают
наибольшую часть процессора (отображение по умолчанию).
Когда менее 100% процессора
запланировано для пользовательских процессов, оставшееся время
относится на процесс «idle».
.It Ic icmp
Отображать в нижнем окне статистику о сообщениях, принятых и
переданных протоколом управляющих сообщений Интернета
.Pq Dq ICMP .
Левая половина экрана отображает информацию о принятых
пакетах, а правая половина отображает информацию о переданных
пакетах.
.Pp
Отображение
.Ic icmp
понимает две команды:
.Ic mode
и
.Ic reset .
Команда
.Ic mode
используется для выбора одного из четырёх режимов отображения, задаваемого её аргументом:
.Bl -tag -width absoluteXX -compact
.It Ic rate :
показывать скорость изменения каждого значения в пакетах (по умолчанию)
в секунду
.It Ic delta :
показывать скорость изменения каждого значения в пакетах за интервал обновления
.It Ic since :
показывать общее изменение каждого значения с момента последнего сброса отображения
.It Ic absolute :
показывать абсолютное значение каждой статистики
.El
.Pp
Команда
.Ic reset
сбрасывает базовую линию для
режима
.Ic since .
Команда
.Ic mode
без аргумента отобразит текущий режим в командной
строке.
.It Ic icmp6
Это отображение похоже на
отображение
.Ic icmp ,
но отображает статистику для IPv6 ICMP.
.It Ic ip
В остальном идентично
отображению
.Ic icmp ,
за исключением того, что отображает статистику IP и UDP.
.It Ic ip6
Подобно
отображению
.Ic ip ,
за исключением того, что отображает статистику IPv6.
Оно не отображает статистику UDP.
.It Ic sctp
Подобно
.Ic icmp ,
но со статистикой SCTP.
.It Ic tcp
Подобно
.Ic icmp ,
но со статистикой TCP.
.It Ic iolat
Отображать статистику, описывающую аппаратные задержки операций I/O, вычисленные
опцией
.Va CAM_IOSCHED_DYNAMIC .
Эта опция должна быть в файле конфигурации ядра работающего ядра, чтобы это
отображение работало.
Все устройства отображаются, так как в настоящее время нет способа их фильтровать.
Статистика, отображаемая для задержек I/O, — это процентили с
достаточными данными в течение интервала опроса для вычисления.
Если значение не может быть оценено, отображается «-».
Значения P50 (также известное как медиана), P90, P99 и P99.9 вычисляются, если
за интервал опроса произошло более 2, 10, 100 или 1000 операций.
Задержка — это значения аппаратной задержки, и она не включает никакого программного
времени очереди.
Задержки оцениваются на основе данных гистограммы, вычисленных планировщиком I/O
CAM, и представляют оценки фактического значения, которые хороши только
до двух или трёх значащих цифр.
Отображение задержки изменяется в зависимости от масштаба задержки, чтобы отразить
точность оценок и уместиться в доступном экранном пространстве.
Все задержки сообщаются в миллисекундах.
Когда цвет включён
.Bl -bullet
.It
Значения ниже среднего порога задержки отображаются зелёным.
.It
Значения между минимальным и высоким порогами задержки отображаются
пурпурным.
.It
Значения выше высоких порогов задержки отображаются красным.
.Pp
Когда цвет отключён, всегда используются цвета переднего плана и фона по умолчанию.
.Pp
Следующие команды специфичны для
отображения
.Ic iolat ;
можно указывать минимальный однозначный префикс.
.Pp
.Bl -tag -width Fl -compact
.It Cm color
Переключить использование цвета в отображении.
По умолчанию включено.
.It Cm hi=XXX
Установить высокий порог задержки в XXX миллисекунд.
.It Cm med=XXX
Установить средний порог задержки в XXX миллисекунд.
.It Cm read
Переключить отображение статистики об операциях чтения.
По умолчанию включено.
.It Cm write
Переключить отображение статистики об операциях записи.
По умолчанию включено.
.It Cm trim
Переключить отображение статистики об операциях trim.
По умолчанию включено.
.El
.El
.It Ic iostat
Отображать в нижнем окне статистику об использовании процессора
и пропускной способности диска.
Статистика использования процессора отображается в виде
столбчатых диаграмм количества времени выполнения в пользовательском режиме («user»),
в пользовательском режиме выполнения низкоприоритетных процессов («nice»), в
системном режиме («system»), в режиме прерываний («interrupt»)
и в режиме простоя («idle»).
Статистика
пропускной способности диска показывает для каждого диска мегабайты в секунду,
среднее количество дисковых транзакций в секунду и
среднее количество килобайт данных на транзакцию.
Эта информация может
отображаться в виде столбчатых диаграмм или в виде строк чисел, прокручивающихся вниз.
Столбчатые
диаграммы отображаются по умолчанию.
.Pp
Следующие команды специфичны для
отображения
.Ic iostat ;
можно указывать минимальный однозначный префикс.
.Pp
.Bl -tag -width Fl -compact
.It Cm numbers
Показывать статистику дискового I/O в числовой форме.
Значения
отображаются в числовых столбцах, которые прокручиваются вниз.
.It Cm bars
Показывать статистику дискового I/O в виде столбчатой диаграммы (по умолчанию).
.It Cm kbpt
Переключить отображение килобайт на транзакцию.
(по умолчанию —
не отображать килобайты на транзакцию).
.El
.It Ic swap
Показывать информацию об использовании пространства подкачки во всех
областях подкачки, скомпилированных в ядро, и процессах, которые выгружены,
а также сводку дисков активности.
.Pp
Области подкачки отображаются первыми с их именем, размерами и
процентом использования.
Столбец
.Ar Used
указывает общее количество использованных на данный момент блоков;
график показывает процент используемого пространства в каждом разделе.
Если используется более одного раздела подкачки,
также показывается итоговая строка.
Области, известные ядру, но не используемые, отображаются как недоступные.
.Pp
Ниже статистики пространства подкачки
процессы перечислены в порядке большего использования области подкачки.
Для каждого процесса показаны Pid, имя пользователя, часть командной строки, общее использование пространства подкачки
в байтах, размер процесса, а также процент использования подкачки на процесс и
процент пространства подкачки на систему.
.Pp
Внизу слева находится отображение использования диска.
Оно сообщает количество
килобайт на транзакцию, транзакций в секунду, мегабайт
в секунду и процент времени, в течение которого диск был занят, усреднённый
за период обновления отображения (по умолчанию пять секунд).
Система ведёт статистику почти по каждому устройству хранения.
Как правило,
отображается до семи устройств.
Устройства, отображаемые по умолчанию, — это
первые устройства в списке устройств ядра.
См.
.Xr devstat 3
и
.Xr devstat 9
для подробностей о системе devstat.
.It Ic vmstat
Занять весь экран и показать (довольно переполненный) компендиум
статистики, связанной с использованием виртуальной памяти, планированием процессов,
прерываниями устройств, кэшированием трансляции системных имён, дисковым I/O и т. д.
.Pp
Верхний левый квадрант экрана показывает количество
пользователей, вошедших в систему, и среднее значение загрузки за последние одну, пять
и пятнадцать минут.
Ниже этой строки находится статистика использования памяти.
Первая строка таблицы сообщает об использовании памяти только среди
активных процессов, то есть процессов, которые выполнялись в течение предыдущих
двадцати секунд.
Вторая строка сообщает об использовании памяти всеми процессами.
Первый столбец сообщает о количестве килобайт в физических страницах,
занятых процессами.
Второй столбец сообщает количество килобайт в физических страницах, которые
отведены под страницы текста только для чтения.
Третий и четвёртый столбцы сообщают те же две цифры для
виртуальных страниц, то есть количество килобайт в страницах, которые были бы
нужны, если бы все процессы имели все свои страницы.
Наконец, последний столбец показывает количество килобайт в физических страницах
в списке свободных.
.Pp
Ниже отображения памяти находится список
среднего количества потоков (за последний интервал обновления),
которые являются исполняемыми (`r'), находятся в ожидании страницы (`p'),
в дисковом ожидании, отличном от подкачки (`d'),
спящими (`s'), и выгруженными, но желающими выполняться (`w').
Строка также показывает среднее количество переключений контекста
(`Csw'), ловушек (`Trp'; включает страничные ошибки), системных вызовов (`Sys'),
прерываний (`Int'), программных прерываний сети (`Sof') и страничных
ошибок (`Flt').
.Pp
Ниже списка длины очереди процессов находится числовой список и
столбчатая диаграмма, показывающая количество
системного (показано как `='), прерываний (показано как `+'), пользовательского (показано как `>'),
nice (показано как `-') и времени простоя (показано как ` ').
.Pp
Ниже отображения процессов находится статистика по трансляциям имён.
Она перечисляет количество имён, транслированных за предыдущий интервал,
количество и процент трансляций, которые были
обработаны общесистемным кэшем трансляции имён, и
количество и процент трансляций, которые были
обработаны кэшем трансляции имён на процесс.
.Pp
Справа от отображения трансляций имён находятся строки, показывающие
количество грязных буферов в кэше буферов (`dtbuf'),
желаемый максимальный размер кэша vnode (`desvn'),
количество фактически выделенных vnode (`numvn')
и
количество выделенных vnode, которые свободны (`frevn').
.Pp
Внизу слева находится отображение использования диска.
Оно сообщает количество
килобайт на транзакцию, транзакций в секунду, мегабайт
в секунду и процент времени, в течение которого диск был занят, усреднённый
за период обновления отображения (по умолчанию пять секунд).
Система ведёт статистику почти по каждому устройству хранения.
Как правило,
отображается до семи устройств.
Устройства, отображаемые по умолчанию, — это
первые устройства в списке устройств ядра.
См.
.Xr devstat 3
и
.Xr devstat 9
для подробностей о системе devstat.
.Pp
Под датой в верхнем правом квадранте находится статистика
активности подкачки и свопинга.
Первые два столбца сообщают среднее количество страниц,
введённых и выведенных в секунду за последний интервал обновления,
из-за страничных ошибок и демона подкачки.
Третий и четвёртый столбцы сообщают среднее количество страниц,
введённых и выведенных в секунду за последний интервал обновления,
из-за запросов свопинга, инициированных планировщиком.
Первая строка отображения показывает среднее
количество дисковых передач в секунду за последний интервал обновления;
вторая строка отображения показывает среднее
количество переданных страниц в секунду за последний интервал обновления.
.Pp
Ниже статистики подкачки находится столбец строк, касающихся системы
виртуальной памяти.
Первые несколько строк описывают
в единицах (кроме отмеченных ниже)
страниц в секунду, усреднённых за интервал выборки,
страницы, скопированные при записи (`cow'),
страницы, заполненные нулями по требованию (`zfod'),
страницы, оптимально заполненные нулями по требованию (`ozfod'),
отношение (среднего) ozfod / zfod в процентах (`%ozfod'),
страницы, освобождённые демоном страниц (`daefr'),
страницы, освобождённые завершающимися процессами (`prcfr'),
всего освобождённых страниц (`totfr'),
страницы, реактивированные из списка свободных (`react'),
среднее количество
раз в секунду, когда демон страниц был разбужен (`pdwak'),
страницы, проанализированные демоном страниц (`pdpgs'),
и
блокирующие страничные ошибки в пути (`intrn').
Обратите внимание, что единицы особые для `%ozfod' и `pdwak'.
Следующие несколько строк описывают
как объёмы памяти в килобайтах
страницы, закреплённые в памяти (`wire'),
активные страницы (`act'),
неактивные страницы (`inact'),
грязные страницы, поставленные в очередь на очистку (`laund'),
и
свободные страницы (`free').
Обратите внимание, что отображаемые значения — текущие мгновенные;
они не являются средними.
.Pp
Внизу этого столбца находится строка, показывающая
объём виртуальной памяти в килобайтах, отображённой в кэш буферов (`buf').
Эта статистика не полезна.
Она существует только как заполнитель для соответствующей полезной статистики
(объём реальной памяти, используемой для кэширования дисков).
Наиболее важный компонент последней (объём реальной памяти,
используемой системой vm для кэширования дисков) недоступен,
но может быть оценён по значению `inact' при некоторых системных нагрузках.
.Pp
Вдоль правой стороны отображения находится разбивка
прерываний, обрабатываемых системой.
В верхней части списка — общее количество прерываний в секунду
за интервал времени.
Остальная часть столбца разбивает общее количество по устройствам
по каждому устройству.
Показаны только устройства, которые прерывались хотя бы один раз с момента загрузки.
.Pp
Следующие команды специфичны для
отображения
.Ic vmstat ;
можно указывать минимальный однозначный префикс.
.Pp
.Bl -tag -width Ar -compact
.It Cm boot
Отображать накопленную статистику с момента загрузки системы.
.It Cm run
Отображать статистику как текущий итог с момента, когда
была дана эта команда.
.It Cm time
Отображать статистику, усреднённую за интервал обновления (по умолчанию).
.It Cm zero
Сбросить текущую статистику в ноль.
.El
.It Ic zarc
отображать использование кэша arc и статистику попаданий/промахов.
.It Ic netstat
Отображать в нижнем окне сетевые соединения.
По умолчанию
сетевые серверы, ожидающие запросов, не отображаются.
Каждый адрес
отображается в формате «host.port», при этом каждый показывается символически,
когда это возможно.
Можно отображать адреса численно,
ограничить отображение набором портов, хостов и/или протоколов
(можно указывать минимальный однозначный префикс):
.Pp
.Bl -tag -width Ar -compact
.It Cm all
Переключить отображение серверных процессов, ожидающих запросов (это
эквивалентно флагу
.Fl a
для
.Xr netstat 1 ) .
.It Cm numbers
Отображать сетевые адреса численно.
.It Cm names
Отображать сетевые адреса символически.
.It Cm proto Ar protocol
Отображать только сетевые соединения, использующие указанный
.Ar protocol .
Поддерживаемые протоколы: «tcp», «udp» и «all».
.It Cm ignore Op Ar items
Не отображать информацию о соединениях, связанных с
указанными хостами или портами.
Хосты и порты можно указывать
по имени («vangogh», «ftp») или численно.
Адреса хостов
используют интернет-нотацию с точками («128.32.0.9»).
Несколько элементов
можно указать одной командой, разделив их
пробелами.
.It Cm display Op Ar items
Отображать информацию о соединениях, связанных с
указанными хостами или портами.
Как и для
.Ar ignore ,
.Op Ar items
могут быть именами или числами.
.It Cm show Op Ar ports\&|hosts
Показать в командной строке текущие выбранные протоколы,
хосты и порты.
Хосты и порты, которые игнорируются,
предваряются `!'.
Если
.Ar ports
или
.Ar hosts
указаны как аргумент
.Cm show ,
то будет отображена только запрошенная информация.
.It Cm reset
Сбросить механизмы сопоставления портов, хостов и протоколов к значениям по умолчанию
(любой протокол, порт или хост).
.El
.It Ic ifstat
Отображать сетевой трафик, проходящий через активные интерфейсы
системы.
Простаивающие интерфейсы не будут отображаться, пока они не получат некоторый
трафик.
.Pp
Для каждого отображаемого интерфейса отображаются текущая, пиковая и общая
статистика для входящего и исходящего трафика.
По умолчанию
отображение
.Ic ifstat
автоматически масштабирует используемые единицы так, чтобы они были
в удобочитаемом формате.
Единицы масштабирования, используемые для столбцов текущего и
пикового
трафика, можно изменить командой
.Ic scale .
.It Cm scale Op Ar units
Изменить масштаб, используемый для отображения текущего и пикового трафика по всем
интерфейсам.
Распознаются следующие единицы: kbit, kbyte, mbit,
mbyte, gbit, gbyte и auto.
.It Cm pps
Показывать статистику в пакетах в секунду вместо байт/бит в секунду.
Последующий вызов
.Ic pps
выключает этот режим.
.It Cm match Op Ar patterns
Отображать только интерфейсы, соответствующие шаблону, указанному как аргумент.
Шаблоны должны быть в синтаксисе оболочки, разделённые пробелами или запятыми.
Если эта команда вызвана без аргументов, отображаются все интерфейсы.
Например:
.Pp
.Dl match em0, bge1
.Pp
Это отобразит интерфейсы em0 и bge1.
.Pp
.Dl match em*, bge*, lo0
.Pp
Это отобразит все интерфейсы
.Ic em ,
все интерфейсы
.Ic bge
и интерфейс loopback.
.El
.El
.Pp
Команды для переключения между отображениями можно сокращать до
минимального однозначного префикса; например, «io» для «iostat».
Определённая информация может быть отброшена, когда размер экрана
недостаточен для отображения.
Например, на машине с 10
дисками столбчатая диаграмма
.Ic iostat
отображает только 3 диска на 24-строчном терминале.
Когда
столбчатая диаграмма переполнила бы отведённое экранное пространство, она
усекается, и фактическое значение выводится «поверх» столбца.
.Pp
Следующие команды являются общими для каждого отображения, которое показывает
информацию о дисковых накопителях.
Эти команды используются для
выбора набора накопителей для отчёта, если в вашей системе
настроено больше накопителей, чем обычно может быть отображено на
экране.
.Pp
.Bl -tag -width Ar -compact
.It Cm ignore Op Ar drives
Не отображать информацию об указанных накопителях.
Можно указать несколько
накопителей, разделив их пробелами.
.It Cm display Op Ar drives
Отображать информацию об указанных накопителях.
Можно указать несколько накопителей,
разделив их пробелами.
.It Cm only Op Ar drives
Отображать только указанные накопители.
Можно указать несколько накопителей,
разделив их пробелами.
.It Cm drives
Отобразить список доступных устройств.
.It Cm match Xo
.Ar type , Ns Ar if , Ns Ar pass
.Op | Ar ...
.Xc
Отображать устройства, соответствующие заданному шаблону.
Базовые выражения
сопоставления такие же, как используемые в
.Xr iostat 8 ,
с одним отличием.
Вместо указания нескольких
аргументов
.Fl t ,
которые затем объединяются по ИЛИ, пользователь вместо этого указывает несколько
выражений сопоставления, соединённых символом
.Pq Ql \&|
конвейера.
Разделённые запятыми аргументы внутри каждого выражения сопоставления объединяются по И,
а затем разделённые конвейером выражения сопоставления объединяются по ИЛИ.
Любое
устройство, соответствующее комбинированному выражению, будет отображено, если есть место
для его отображения.
Например:
.Pp
.Dl match da,scsi | cd,ide
.Pp
Это отобразит все устройства SCSI Direct Access и все устройства IDE CDROM.
.Pp
.Dl match da | sa | cd,pass
.Pp
Это отобразит все устройства Direct Access, все устройства Sequential Access
и все passthrough-устройства, обеспечивающие доступ к приводам CDROM.
.El
.Sh ФАЙЛЫ
.Bl -tag -width /boot/kernel/kernel -compact
.It Pa /boot/kernel/kernel
Для списка имён.
.It Pa /dev/kmem
Для информации в основной памяти.
.It Pa /etc/hosts
Для имён хостов.
.It Pa /etc/networks
Для имён сетей.
.It Pa /etc/services
Для имён портов.
.El
.Sh СМ. ТАКЖЕ
.Xr netstat 1 ,
.Xr kvm 3 ,
.Xr icmp 4 ,
.Xr icmp6 4 ,
.Xr ip 4 ,
.Xr ip6 4 ,
.Xr tcp 4 ,
.Xr udp 4 ,
.Xr gstat 8 ,
.Xr iostat 8 ,
.Xr vmstat 8
.Sh ИСТОРИЯ
Программа
.Nm
появилась в
.Bx 4.3 .
Отображения
.Ic icmp ,
.Ic ip
и
.Ic tcp
появились в
.Fx 3.0 ;
идея иметь разные режимы отображения для статистики
ICMP, IP, TCP и UDP была позаимствована из
параметра
.Fl C
для
.Xr netstat 1
в системе IRIX компании Silicon Graphics.
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Некоторые отображения предполагают минимум 80 символов в строке.
Ifstat не обнаруживает новые интерфейсы.
Отображение
.Ic vmstat
выглядит неуместно, потому что оно такое и есть (оно было добавлено как
отдельное отображение, а не создано как новая программа).
Команда
.Ic iolat
не реализует общие команды устройств, включая
фильтрацию, так как она не использует механизм
.Xr devstat 3
для получения своей статистики.
