.\" FRDP path contrib/telnet/telnet/telnet.1
.\" FRDP githash d2e0204ec0ace5a65e688a35a960e949624f3cb2
.\" FRDP hash256 aa6c0de0d7ebb1f5a39c55b0d39712c338a63027baeaaded6e88381acc5d7fef
.Dd September 29, 2022
.Dt TELNET 1
.Os
.Sh ИМЯ
.Nm telnet
.Nd пользовательский интерфейс к протоколу
.Tn TELNET
.Sh СИНТАКСИС
.Nm
.Op Fl 468EFKLNQacdfruxy
.Op Fl B Ar baudrate
.Op Fl S Ar tos
.Op Fl X Ar authtype
.Op Fl e Ar escapechar
.Op Fl k Ar realm
.Op Fl l Ar user
.Op Fl n Ar tracefile
.Op Fl s Ar src_addr
.Op Fl P Ar policy
.Oo
.Ar host
.Op Ar port
.Oc
.Sh ОПИСАНИЕ
Команда
.Nm
используется для связи с другим хостом по протоколу
.Tn TELNET .
Если
.Nm
вызвана без аргумента
.Ar host ,
она входит в режим команд,
обозначаемый приглашением
.Pq Dq Li telnet\&> .
В этом режиме она принимает и выполняет перечисленные ниже команды.
Если она вызвана с аргументами, она выполняет
команду
.Ic open
с этими аргументами.
.Pp
Параметры:
.Bl -tag -width indent
.It Fl 4
Заставляет
.Nm
использовать только адреса IPv4.
.It Fl 6
Заставляет
.Nm
использовать только адреса IPv6.
.It Fl 8
Указывает 8-битный путь данных.
Это вызывает попытку
согласовать опцию
.Dv TELNET BINARY
как для ввода, так и для вывода.
.It Fl B Ar baudrate
Устанавливает скорость передачи в бодах в
.Ar baudrate .
.It Fl E
Запрещает распознавание любого символа как символа экранирования.
.It Fl F
Если используется аутентификация Kerberos V5, параметр
.Fl F
позволяет переслать локальные учётные данные
на удалённую систему, включая любые учётные данные,
которые уже были пересланы в локальное окружение.
.It Fl K
Указывает на отсутствие автоматического входа в удалённую систему.
.It Fl L
Указывает 8-битный путь данных на выводе.
Это вызывает согласование
опции
.Dv BINARY
на выводе.
.It Fl N
Предотвращает преобразование IP-адреса в имя, когда целевой хост задан
как IP-адрес.
.It Fl Q
Тихий режим.
Это подавляет сообщения, которые
.Nm
обычно выводит при подключении или отключении.
.It Fl S Ar tos
Устанавливает опцию IP type-of-service (TOS) для соединения
telnet в значение
.Ar tos ,
которое может быть числовым значением TOS
или, в системах, которые это поддерживают, символическим
именем TOS, найденным в файле
.Pa /etc/iptos .
.It Fl X Ar atype
Отключает
.Ar atype
тип аутентификации.
.It Fl a
Попытаться выполнить автоматический вход.
Теперь это значение по умолчанию, поэтому этот параметр игнорируется.
В настоящее время это отправляет имя пользователя через переменную
.Ev USER
опции
.Ev ENVIRON ,
если она поддерживается удалённой системой.
Используется имя текущего пользователя, возвращаемое
.Xr getlogin 2 ,
если оно совпадает с текущим идентификатором пользователя,
в противном случае используется имя, связанное с идентификатором пользователя.
.It Fl c
Отключает чтение пользовательского файла
.Pa \&.telnetrc .
(См. команду
.Ic toggle skiprc
на этой странице руководства.)
.It Fl d
Устанавливает начальное значение переключателя
.Ic debug
в
.Dv TRUE .
.It Fl e Ar escapechar
Устанавливает начальный
символ экранирования
.Nm
в
.Ar escapechar .
Если
.Ar escapechar
опущен, то
символа экранирования не будет.
.It Fl f
Если используется аутентификация Kerberos V5, параметр
.Fl f
позволяет переслать локальные учётные данные на удалённую систему.
.It Fl k Ar realm
Если используется аутентификация Kerberos, параметр
.Fl k
запрашивает, чтобы
.Nm
получила билеты для удалённого хоста в
области
.Ar realm
вместо области удалённого хоста, определяемой
.Xr krb_realmofhost 3 .
.It Fl l Ar user
При подключении к удалённой системе, если удалённая система
понимает
опцию
.Ev ENVIRON ,
то
.Ar user
будет отправлен удалённой системе как значение переменной
.Ev USER .
Этот параметр подразумевает
параметр
.Fl a .
Этот параметр также можно использовать с
командой
.Ic open .
.It Fl n Ar tracefile
Открывает
.Ar tracefile
для записи информации трассировки.
См.
команду
.Ic set tracefile
ниже.
.It Fl P Ar policy
Использовать строку спецификации политики IPsec
.Ar policy
для соединений.
См.
.Xr ipsec_set_policy 3
для подробностей.
.It Fl r
Указывает пользовательский интерфейс, подобный
.Xr rlogin 1 .
В этом
режиме символ экранирования устанавливается в символ тильды (~),
если он не изменён
параметром
.Fl e .
.It Fl s Ar src_addr
Установить исходный IP-адрес для
соединения
.Nm
в
.Ar src_addr ,
который может быть IP-адресом или именем хоста.
.It Fl u
Заставляет
.Nm
использовать только адреса
.Dv AF_UNIX
(например,
сокеты домена
.Ux ,
доступные по пути к файлу).
.It Fl x
Включает шифрование потока данных, если возможно.
Теперь это значение по умолчанию, поэтому этот параметр игнорируется.
.It Fl y
Подавляет шифрование потока данных.
.It Ar host
Указывает официальное имя, псевдоним или интернет-адрес
удалённого хоста.
Если
.Ar host
начинается с
.Ql / ,
.Nm
устанавливает соединение с соответствующим именованным сокетом.
.It Ar port
Указывает номер порта (адрес приложения).
Если номер
не указан, используется порт
.Nm
по умолчанию.
.El
.Pp
В режиме rlogin строка вида ~.\& отключает от
удалённого хоста; ~ — это
символ экранирования
.Nm .
Аналогично, строка ~^Z приостанавливает
сеанс
.Nm .
Строка ~^] переходит к обычному
приглашению экранирования
.Nm .
.Pp
После открытия соединения
.Nm
попытается включить
опцию
.Dv TELNET LINEMODE .
Если это не удастся, то
.Nm
вернётся к одному из двух режимов ввода:
либо \*(Lqпо одному символу\*(Rq,
либо \*(Lqстарый построчный\*(Rq
в зависимости от того, что поддерживает удалённая система.
.Pp
Когда
.Dv LINEMODE
включён, обработка символов выполняется на
локальной системе под управлением удалённой системы.
Когда
редактирование ввода или эхо символов должно быть отключено, удалённая система
передаст эту информацию.
Удалённая система также передаст
изменения любых специальных символов, происходящие на удалённой
системе, чтобы они могли вступить в силу на локальной системе.
.Pp
В режиме \*(Lqпо одному символу\*(Rq большая часть
вводимого текста немедленно отправляется на удалённый хост для обработки.
.Pp
В режиме \*(Lqстарый построчный\*(Rq весь текст эхируется локально,
и (обычно) на удалённый хост отправляются только завершённые строки.
\*(LqСимвол локального эха\*(Rq (изначально \*(Lq^E\*(Rq) можно использовать
для выключения и включения локального эха
(в основном это использовалось бы для ввода паролей
без эха пароля).
.Pp
Если
опция
.Dv LINEMODE
включена, или если переключатель
.Ic localchars
равен
.Dv TRUE
(значение по умолчанию для \*(Lqстарый построчный\*(Rq; см. ниже),
символы пользователя
.Ic quit ,
.Ic intr
и
.Ic flush
перехватываются локально и отправляются как
последовательности протокола
.Tn TELNET
на удалённую сторону.
Если
.Dv LINEMODE
когда-либо был включён, то пользовательские
.Ic susp
и
.Ic eof
также отправляются как
последовательности протокола
.Tn TELNET ,
а
.Ic quit
отправляется как
.Dv TELNET ABORT
вместо
.Dv BREAK .
Есть параметры (см.
.Ic toggle
.Ic autoflush
и
.Ic toggle
.Ic autosynch
ниже),
которые заставляют это действие сбрасывать последующий вывод на терминал
(пока удалённый хост не подтвердит
последовательность
.Tn TELNET )
и сбрасывать предыдущий ввод терминала
(в случае
.Ic quit
и
.Ic intr ) .
.Pp
Пока соединение с удалённым хостом установлено,
режим команд
.Nm
можно войти, набрав
\*(Lqсимвол экранирования\*(Rq
.Nm
(изначально \*(Lq^]\*(Rq).
Находясь в режиме команд, доступны обычные соглашения редактирования терминала.
.Pp
Доступны следующие
команды
.Nm .
Нужно набирать лишь столько символов каждой команды, сколько необходимо для её однозначной идентификации
(это также верно для аргументов команд
.Ic mode ,
.Ic set ,
.Ic toggle ,
.Ic unset ,
.Ic slc ,
.Ic environ
и
.Ic display ).
.It Ic auth Ar argument ...
Команда auth управляет информацией, отправляемой через
опцию
.Dv TELNET AUTHENTICATE .
Допустимые аргументы для
команды
.Ic auth :
.It Ic disable Ar type
Отключает указанный тип аутентификации.
Чтобы
получить список доступных типов, используйте
команду
.Ic auth disable ?\& .
.It Ic enable Ar type
Включает указанный тип аутентификации.
Чтобы
получить список доступных типов, используйте
команду
.Ic auth enable ?\& .
.It Ic status
Перечисляет текущее состояние различных типов
аутентификации.
.El
.It Ic close
Закрыть сеанс
.Tn TELNET
и вернуться в режим команд.
.It Ic display Ar argument ...
Отображает все или некоторые значения
.Ic set
и
.Ic toggle
(см. ниже).
.It Ic encrypt Ar argument ...
Команда encrypt управляет информацией, отправляемой через
опцию
.Dv TELNET ENCRYPT .
.Pp
Допустимые аргументы для
команды
.Ic encrypt :
.Bl -tag -width Ar
.It Ic disable Ar type Xo
.Op Cm input | output
.Xc
Отключает указанный тип шифрования.
Если вы
опустите input и output, будут отключены как ввод, так и вывод.
Чтобы получить список доступных
типов, используйте
команду
.Ic encrypt disable ?\& .
.It Ic enable Ar type Xo
.Op Cm input | output
.Xc
Включает указанный тип шифрования.
Если вы
опустите input и output, будут включены как ввод, так и вывод.
Чтобы получить список доступных типов, используйте
команду
.Ic encrypt enable ?\& .
.It Ic input
Это то же самое, что и
команда
.Ic encrypt start input .
.It Ic -input
Это то же самое, что и
команда
.Ic encrypt stop input .
.It Ic output
Это то же самое, что и
команда
.Ic encrypt start output .
.It Ic -output
Это то же самое, что и
команда
.Ic encrypt stop output .
.It Ic start Op Cm input | output
Пытается начать шифрование.
Если вы опустите
.Ic input
и
.Ic output ,
будут включены как ввод, так и вывод.
Чтобы
получить список доступных типов, используйте
команду
.Ic encrypt enable ?\& .
.It Ic status
Перечисляет текущее состояние шифрования.
.It Ic stop Op Cm input | output
Останавливает шифрование.
Если вы опустите input и output,
шифрование будет и на вводе, и на выводе.
.It Ic type Ar type
Устанавливает тип шифрования по умолчанию для использования
с последующими
командами
.Ic encrypt start
или
.Ic encrypt stop .
.El
.It Ic environ Ar arguments ...
Команда
.Ic environ
используется для управления
переменными, которые могут быть отправлены через
опцию
.Dv TELNET ENVIRON .
Начальный набор переменных берётся из окружения
пользователя, при этом по умолчанию экспортируются только
переменные
.Ev DISPLAY
и
.Ev PRINTER .
Переменная
.Ev USER
также экспортируется, если используются
параметры
.Fl a
или
.Fl l .
.Pp
Допустимые аргументы для
команды
.Ic environ :
.Bl -tag -width Fl
.It Ic define Ar variable value
Определить переменную
.Ar variable
со значением
.Ar value .
Любые переменные, определённые этой командой, автоматически экспортируются.
.Ar value
может быть заключено в одинарные или двойные кавычки, чтобы
можно было включить табуляции и пробелы.
.It Ic undefine Ar variable
Удалить
.Ar variable
из списка переменных окружения.
.It Ic export Ar variable
Пометить переменную
.Ar variable
для экспорта на удалённую сторону.
.It Ic unexport Ar variable
Пометить переменную
.Ar variable
как не экспортируемую, если только
удалённая сторона явно не запросит её.
.It Ic list
Перечислить текущий набор переменных окружения.
Те, что помечены
.Cm * ,
будут отправлены автоматически,
остальные переменные будут отправлены только при явном запросе.
.It Ic ?\&
Выводит справочную информацию для
команды
.Ic environ .
.El
.It Ic logout
Отправляет
опцию
.Dv TELNET LOGOUT
на удалённую сторону.
Эта команда похожа на
команду
.Ic close ;
однако если удалённая сторона не поддерживает
опцию
.Dv LOGOUT ,
ничего не происходит.
Если же удалённая сторона поддерживает
опцию
.Dv LOGOUT ,
эта команда должна заставить удалённую сторону закрыть
соединение
.Tn TELNET .
Если удалённая сторона также поддерживает концепцию
приостановки сеанса пользователя для последующего повторного подключения,
аргумент logout указывает, что вы
должны немедленно завершить сеанс.
.It Ic mode Ar type
.Ar Type
— одна из нескольких опций, в зависимости от состояния
сеанса
.Tn TELNET .
У удалённого хоста запрашивается разрешение перейти в запрошенный режим.
Если удалённый хост способен войти в этот режим, запрошенный
режим будет выбран.
.Bl -tag -width Ar
.It Ic character
Отключить
опцию
.Dv TELNET LINEMODE
или, если удалённая сторона не понимает
опцию
.Dv LINEMODE ,
войти в режим \*(Lqпо одному символу\*(Rq.
.It Ic line
Включить
опцию
.Dv TELNET LINEMODE
или, если удалённая сторона не понимает
опцию
.Dv LINEMODE ,
попытаться войти в режим \*(Lqстарый построчный\*(Rq.
.It Ic isig Pq Ic \-isig
Попытаться включить (отключить) режим
.Dv TRAPSIG
опции
.Dv LINEMODE .
Это требует, чтобы
опция
.Dv LINEMODE
была включена.
.It Ic edit Pq Ic \-edit
Попытаться включить (отключить) режим
.Dv EDIT
опции
.Dv LINEMODE .
Это требует, чтобы
опция
.Dv LINEMODE
была включена.
.It Ic softtabs Pq Ic \-softtabs
Попытаться включить (отключить) режим
.Dv SOFT_TAB
опции
.Dv LINEMODE .
Это требует, чтобы
опция
.Dv LINEMODE
была включена.
.It Ic litecho Pq Ic \-litecho
Попытаться включить (отключить) режим
.Dv LIT_ECHO
опции
.Dv LINEMODE .
Это требует, чтобы
опция
.Dv LINEMODE
была включена.
.It Ic ?\&
Выводит справочную информацию для
команды
.Ic mode .
.El
.It Xo
.Ic open
.Op Fl l Ar user
.Op Ar host
.Op Oo Fl /+ Oc Ns Ar port
.Xc
Открыть соединение с указанным хостом.
Если номер порта
не указан,
.Nm
попытается связаться с сервером
.Tn TELNET
на порту по умолчанию.
Спецификация хоста может быть либо именем хоста (см.
.Xr hosts 5 ) ,
интернет-адресом, указанным в \*(Lqточечной нотации\*(Rq (см.
.Xr inet 3 ) ,
либо именем хоста IPv6 или адресом IPv6 в шестнадцатеричной записи с двоеточиями.
Параметр
.Fl l
можно использовать для указания имени пользователя,
которое будет передано удалённой системе через
опцию
.Ev ENVIRON .
При подключении к нестандартному порту
.Nm
пропускает любую автоматическую инициализацию
опций
.Tn TELNET .
Когда номер порта предваряется знаком минус,
выполняется начальное согласование опций.
Когда же номер порта
предваряется знаком плюс,
любое согласование и понимание опций запрещается,
что делает telnet немым клиентом для протоколов типа POP3/SMTP/NNTP/HTTP
с любыми данными, включая
символ
.Tn TELNET
IAC (0xff).
После установления соединения открывается файл
.Pa \&.telnetrc
в домашнем каталоге пользователя.
Строки, начинающиеся с #, —
это строки комментариев.
Пустые строки игнорируются.
Строки, которые начинаются
без пробела, — это начало записи машины.
Первое, что находится в строке, — это имя машины, к которой
выполняется подключение.
Это может быть имя хоста или числовой адрес, указанный как аргумент
.Ar host ,
каноническое имя этой строки, определённое
.Xr getaddrinfo 3 ,
или строка
.Dq Li DEFAULT ,
указывающая все хосты.
Остальная часть строки и последующие
строки, которые начинаются с пробела, считаются
командами
.Nm
и обрабатываются так, как если бы они были набраны
вручную в приглашении
.Nm .
.It Ic quit
Закрыть любой открытый сеанс
.Tn TELNET
и выйти из
.Nm .
Конец файла (в режиме команд) также закроет сеанс и выполнит выход.
.It Ic send Ar arguments
Отправляет одну или несколько последовательностей специальных символов на удалённый хост.
Ниже перечислены аргументы, которые можно указать
(одновременно можно указать более одного аргумента):
.Bl -tag -width escape
.It Ic abort
Отправляет
последовательность
.Dv TELNET ABORT
(прервать
процессы).
.It Ic ao
Отправляет
последовательность
.Dv TELNET AO
(Abort Output), которая должна заставить удалённую систему сбросить
весь вывод
.Em от
удалённой системы
.Em к
терминалу пользователя.
.It Ic ayt
Отправляет
последовательность
.Dv TELNET AYT
(Are You There), на которую удалённая система может ответить или не ответить.
.It Ic brk
Отправляет
последовательность
.Dv TELNET BRK
(Break), которая может иметь значение для удалённой
системы.
.It Ic ec
Отправляет
последовательность
.Dv TELNET EC
(Erase Character), которая должна заставить удалённую систему стереть последний введённый
символ.
.It Ic el
Отправляет
последовательность
.Dv TELNET EL
(Erase Line), которая должна заставить удалённую систему стереть строку, которая в данный момент
вводится.
.It Ic eof
Отправляет
последовательность
.Dv TELNET EOF
(End Of File).
.It Ic eor
Отправляет
последовательность
.Dv TELNET EOR
(End of Record).
.It Ic escape
Отправляет текущий
символ экранирования
.Nm
(изначально \*(Lq^\*(Rq).
.It Ic ga
Отправляет
последовательность
.Dv TELNET GA
(Go Ahead), которая, вероятно, не имеет значения для удалённой системы.
.It Ic getstatus
Если удалённая сторона поддерживает команду
.Dv TELNET STATUS ,
.Ic getstatus
отправит субсогласование с запросом к серверу отправить
его текущее состояние опций.
.It Ic ip
Отправляет
последовательность
.Dv TELNET IP
(Interrupt Process), которая должна заставить удалённую
систему прервать текущий выполняющийся процесс.
.It Ic nop
Отправляет
последовательность
.Dv TELNET NOP
(No OPeration).
.It Ic susp
Отправляет
последовательность
.Dv TELNET SUSP
(SUSPend process).
.It Ic synch
Отправляет
последовательность
.Dv TELNET SYNCH .
Эта последовательность заставляет удалённую систему отбросить весь ранее введённый
(но ещё не прочитанный) ввод.
Эта последовательность отправляется как
срочные данные
.Tn TCP
(и может не работать, если удалённая система —
система
.Bx 4.2
— если
она не работает, на терминале может эхироваться строчная буква \*(Lqr\*(Rq).
.It Ic do Ar cmd
.It Ic dont Ar cmd
.It Ic will Ar cmd
.It Ic wont Ar cmd
Отправляет
последовательность
.Dv TELNET DO
.Ar cmd .
.Ar Cmd
может быть либо десятичным числом от 0 до 255,
либо символическим именем конкретной
команды
.Dv TELNET .
.Ar Cmd
также может быть
.Ic help
или
.Ic ?\& ,
чтобы вывести справочную информацию, включая
список известных символических имён.
.It Ic ?\&
Выводит справочную информацию для
команды
.Ic send .
.El
.It Ic set Ar argument value
.It Ic unset Ar argument value
Команда
.Ic set
устанавливает любую из ряда
переменных
.Nm
в конкретное значение или в
.Dv TRUE .
Специальное значение
.Ic off
выключает функцию, связанную с
переменной; это эквивалентно использованию
команды
.Ic unset .
Команда
.Ic unset
отключает или устанавливает в
.Dv FALSE
любую из указанных функций.
Значения переменных можно запросить с помощью
команды
.Ic display .
Переменные, которые можно установить или снять, но не переключать, перечислены
здесь.
Кроме того, любую из переменных для
команды
.Ic toggle
можно явно установить или снять с помощью
команд
.Ic set
и
.Ic unset .
.Bl -tag -width escape
.It Ic ayt
Если
.Tn TELNET
находится в режиме localchars или
.Dv LINEMODE
включён, и введён символ состояния, на
удалённый хост отправляется
последовательность
.Dv TELNET AYT
(см.
.Ic send ayt
выше).
Начальное значение для символа \*(LqAre You There\*(Rq —
это символ состояния терминала.
.It Ic echo
Это значение (изначально \*(Lq^E\*(Rq), которое в режиме
\*(Lqпострочном\*(Rq переключает между выполнением локального эха
введённых символов (для нормальной обработки) и подавлением
эха введённых символов (для ввода, скажем, пароля).
.It Ic eof
Если
.Nm
работает в
.Dv LINEMODE
или в режиме \*(Lqстарый построчный\*(Rq, ввод этого символа
как первого символа в строке заставит отправить этот символ
удалённой системе.
Начальное значение символа eof берётся как
символ
.Ic eof
терминала.
.It Ic erase
Если
.Nm
находится в режиме
.Ic localchars
(см.
.Ic toggle
.Ic localchars
ниже),
.Sy и
если
.Nm
работает в режиме \*(Lqпо одному символу\*(Rq, то когда вводится этот
символ, на удалённую систему отправляется
последовательность
.Dv TELNET EC
(см.
.Ic send
.Ic ec
выше).
Начальное значение для символа erase берётся как
символ
.Ic erase
терминала.
.It Ic escape
Это
символ экранирования
.Nm
(изначально \*(Lq^[\*(Rq), который вызывает вход
в режим команд
.Nm
(при подключении к удалённой системе).
.It Ic flushoutput
Если
.Nm
находится в режиме
.Ic localchars
(см.
.Ic toggle
.Ic localchars
ниже)
и введён символ
.Ic flushoutput ,
на удалённый хост отправляется
последовательность
.Dv TELNET AO
(см.
.Ic send
.Ic ao
выше).
Начальное значение для символа flush берётся как
символ
.Ic flush
терминала.
.It Ic forw1
.It Ic forw2
Если
.Nm
работает в
.Dv LINEMODE ,
это символы, которые при вводе вызывают пересылку частичных строк
удалённой системе.
Начальные значения для
символов пересылки берутся из символов
eol и eol2 терминала.
.It Ic interrupt
Если
.Nm
находится в режиме
.Ic localchars
(см.
.Ic toggle
.Ic localchars
ниже)
и введён символ
.Ic interrupt ,
на удалённый хост отправляется
последовательность
.Dv TELNET IP
(см.
.Ic send
.Ic ip
выше).
Начальное значение для символа interrupt берётся как
символ
.Ic intr
терминала.
.It Ic kill
Если
.Nm
находится в режиме
.Ic localchars
(см.
.Ic toggle
.Ic localchars
ниже),
.Ic и
если
.Nm
работает в режиме \*(Lqпо одному символу\*(Rq, то когда вводится этот
символ, на удалённую систему отправляется
последовательность
.Dv TELNET EL
(см.
.Ic send
.Ic el
выше).
Начальное значение для символа kill берётся как
символ
.Ic kill
терминала.
.It Ic lnext
Если
.Nm
работает в
.Dv LINEMODE
или в режиме \*(Lqстарый построчный\*(Rq, то этот символ считается
символом
.Ic lnext
терминала.
Начальное значение для символа lnext берётся как
символ
.Ic lnext
терминала.
.It Ic quit
Если
.Nm
находится в режиме
.Ic localchars
(см.
.Ic toggle
.Ic localchars
ниже)
и введён символ
.Ic quit ,
на удалённый хост отправляется
последовательность
.Dv TELNET BRK
(см.
.Ic send
.Ic brk
выше).
Начальное значение для символа quit берётся как
символ
.Ic quit
терминала.
.It Ic reprint
Если
.Nm
работает в
.Dv LINEMODE
или в режиме \*(Lqстарый построчный\*(Rq, то этот символ считается
символом
.Ic reprint
терминала.
Начальное значение для символа reprint берётся как
символ
.Ic reprint
терминала.
.It Ic rlogin
Это символ экранирования rlogin.
Если установлен, обычный
символ экранирования
.Nm
игнорируется, если только он не
предваряется этим символом в начале строки.
Этот символ в начале строки, за которым следует
приостанавливает
команду
.Nm .
Начальное состояние — отключённый
символ экранирования
.Nm rlogin .
.It Ic start
Если
опция
.Dv TELNET TOGGLE-FLOW-CONTROL
была включена,
то этот символ считается
символом
.Ic start
терминала.
Начальное значение для символа start берётся как
символ
.Ic start
терминала.
.It Ic stop
Если
опция
.Dv TELNET TOGGLE-FLOW-CONTROL
была включена,
то этот символ считается
символом
.Ic stop
терминала.
Начальное значение для символа stop берётся как
символ
.Ic stop
терминала.
.It Ic susp
Если
.Nm
находится в режиме
.Ic localchars
или
.Dv LINEMODE
включён, и введён символ
.Ic suspend ,
на удалённый хост отправляется
последовательность
.Dv TELNET SUSP
(см.
.Ic send
.Ic susp
выше).
Начальное значение для символа suspend берётся как
символ
.Ic suspend
терминала.
.It Ic tracefile
Это файл, в который будет записываться вывод, вызванный
трассировкой
.Ic netdata
или
.Ic option ,
если она равна
.Dv TRUE .
Если он установлен в
.Dq Fl ,
то информация трассировки будет записываться в стандартный вывод (по умолчанию).
.It Ic worderase
Если
.Nm
работает в
.Dv LINEMODE
или в режиме \*(Lqстарый построчный\*(Rq, то этот символ считается
символом
.Ic worderase
терминала.
Начальное значение для символа worderase берётся как
символ
.Ic worderase
терминала.
.It Ic ?\&
Отображает допустимые
команды
.Ic set
.Pq Ic unset .
.El
.It Ic slc Ar state
Команда
.Ic slc
(Set Local Characters) используется для установки
или изменения состояния специальных
символов, когда
опция
.Dv TELNET LINEMODE
была включена.
Специальные символы — это символы, которые
отображаются на последовательности команд
.Tn TELNET
(такие как
.Ic ip
или
.Ic quit )
или символы редактирования строки (такие как
.Ic erase
и
.Ic kill ) .
По умолчанию локальные специальные символы экспортируются.
.Bl -tag -width Fl
.It Ic check
Проверить текущие настройки для текущих специальных символов.
Удалённой стороне отправляется запрос на отправку всех текущих настроек специальных
символов, и если есть какие-либо расхождения с
локальной стороной, локальная сторона переключится на удалённое значение.
.It Ic export
Переключиться на локальные значения по умолчанию для специальных символов.
Локальные символы по умолчанию — это символы локального терминала на
момент запуска
.Nm .
.It Ic import
Переключиться на удалённые значения по умолчанию для специальных символов.
Удалённые символы по умолчанию — это символы удалённой системы
на момент установления
соединения
.Tn TELNET .
.It Ic ?\&
Выводит справочную информацию для
команды
.Ic slc .
.El
.It Ic status
Показать текущее состояние
.Nm .
Это включает партнёра, к которому выполнено подключение, а также
текущий режим.
.It Ic toggle Ar arguments ...
Переключить (между
.Dv TRUE
и
.Dv FALSE )
различные флаги, которые управляют тем, как
.Nm
реагирует на события.
Эти флаги можно явно установить в
.Dv TRUE
или
.Dv FALSE
с помощью
команд
.Ic set
и
.Ic unset ,
перечисленных выше.
Можно указать более одного аргумента.
Состояние этих флагов можно запросить с помощью
команды
.Ic display .
Допустимые аргументы:
.Bl -tag -width Ar
.It Ic authdebug
Включает отладочную информацию для кода аутентификации.
.It Ic autoflush
Если
.Ic autoflush
и
.Ic localchars
оба равны
.Dv TRUE ,
то когда
распознаются символы
.Ic ao
или
.Ic quit
(и преобразуются в
последовательности
.Tn TELNET ;
см.
.Ic set
выше для подробностей),
.Nm
отказывается отображать какие-либо данные на терминале пользователя,
пока удалённая система не подтвердит (через
опцию
.Dv TELNET TIMING MARK ),
что она обработала эти
последовательности
.Tn TELNET .
Начальное значение для этого переключателя —
.Dv TRUE ,
если пользователь терминала не имел
.Dv FALSE
(см.
.Xr stty 1 ) .
.It Ic autodecrypt
Когда
опция
.Dv TELNET ENCRYPT
согласована, по
умолчанию фактическое шифрование (дешифрование) потока
данных не начинается автоматически.
Команда autoencrypt
(autodecrypt) указывает, что шифрование
выходного (входного) потока должно быть включено как можно
скорее.
.It Ic autologin
Если удалённая сторона поддерживает
опцию
.Dv TELNET AUTHENTICATION ,
.Nm
пытается использовать её для выполнения автоматической аутентификации.
Если
опция
.Dv AUTHENTICATION
не поддерживается, имя входа пользователя
передаётся через
опцию
.Dv TELNET ENVIRON .
Эта команда эквивалентна указанию
параметра
.Fl a
в
команде
.Ic open .
.It Ic autosynch
Если
.Ic autosynch
и
.Ic localchars
оба равны
.Dv TRUE ,
то когда введён либо символ
.Ic intr ,
либо
.Ic quit
(см.
.Ic set
выше для описаний символов
.Ic intr
и
.Ic quit ),
результирующая отправленная
последовательность
.Tn TELNET
сопровождается
последовательностью
.Dv TELNET SYNCH .
Эта процедура
.Ic должна
заставить удалённую систему начать отбрасывать весь ранее
введённый ввод, пока обе
последовательности
.Tn TELNET
не будут прочитаны и обработаны.
Начальное значение этого переключателя —
.Dv FALSE .
.It Ic binary
Включить или отключить
опцию
.Dv TELNET BINARY
как на вводе, так и на выводе.
.It Ic inbinary
Включить или отключить
опцию
.Dv TELNET BINARY
на вводе.
.It Ic outbinary
Включить или отключить
опцию
.Dv TELNET BINARY
на выводе.
.It Ic crlf
Если это
.Dv TRUE ,
то символы возврата каретки будут отправляться как
.Li <CR><LF> .
Если это
.Dv FALSE ,
то символы возврата каретки будут отправляться как
.Li <CR><NUL> .
Начальное значение для этого переключателя —
.Dv FALSE .
.It Ic crmod
Переключить режим возврата каретки.
Когда этот режим включён, большинство символов возврата каретки, полученных от
удалённого хоста, будут отображаться в возврат каретки, за которым следует
перевод строки.
Этот режим не влияет на символы, введённые пользователем, только
на полученные от удалённого хоста.
Этот режим не очень полезен, если удалённый хост
отправляет только возврат каретки, но никогда перевод строки.
Начальное значение для этого переключателя —
.Dv FALSE .
.It Ic debug
Переключает отладку на уровне сокета (полезно только
.Ic суперпользователю ) .
Начальное значение для этого переключателя —
.Dv FALSE .
.It Ic encdebug
Включает отладочную информацию для кода шифрования.
.It Ic localchars
Если это
.Dv TRUE ,
то символы
.Ic flush ,
.Ic interrupt ,
.Ic quit ,
.Ic erase
и
.Ic kill
(см.
.Ic set
выше) распознаются локально и преобразуются в (надеемся) подходящие
управляющие последовательности
.Tn TELNET
(соответственно
.Ic ao ,
.Ic ip ,
.Ic brk ,
.Ic ec
и
.Ic el ;
см.
.Ic send
выше).
Начальное значение для этого переключателя —
.Dv TRUE
в режиме \*(Lqстарый построчный\*(Rq
и
.Dv FALSE
в режиме \*(Lqпо одному символу\*(Rq.
Когда
опция
.Dv LINEMODE
включена, значение
.Ic localchars
игнорируется и считается всегда равным
.Dv TRUE .
Если
.Dv LINEMODE
когда-либо был включён, то
.Ic quit
отправляется как
.Ic abort ,
а
.Ic eof
и
.Ic suspend
отправляются как
.Ic eof
и
.Ic susp
(см.
.Ic send
выше).
.It Ic netdata
Переключает отображение всех сетевых данных (в шестнадцатеричном формате).
Начальное значение для этого переключателя —
.Dv FALSE .
.It Ic options
Переключает отображение некоторой внутренней
обработки протокола
.Nm
(связанной с
опциями
.Tn TELNET ).
Начальное значение для этого переключателя —
.Dv FALSE .
.It Ic prettydump
Когда переключатель
.Ic netdata
включён, если
.Ic prettydump
включён, вывод команды
.Ic netdata
будет отформатирован в более удобочитаемом для пользователя формате.
Между каждым символом в выводе ставятся пробелы, а
начало любой
последовательности экранирования
.Nm
предваряется символом '*', чтобы помочь в их поиске.
.It Ic skiprc
Когда переключатель skiprc равен
.Dv TRUE ,
.Nm
пропускает чтение файла
.Pa \&.telnetrc
в домашнем каталоге пользователя
при открытии соединений.
Начальное
значение для этого переключателя —
.Dv FALSE .
.It Ic termdata
Переключает отображение всех данных терминала (в шестнадцатеричном формате).
Начальное значение для этого переключателя —
.Dv FALSE .
.It Ic verbose_encrypt
Когда переключатель
.Ic verbose_encrypt
равен
.Dv TRUE ,
.Nm
выводит сообщение каждый раз, когда шифрование включается или
отключается.
Начальное значение для этого переключателя —
.Dv FALSE .
.It Ic ?\&
Отображает допустимые
команды
.Ic toggle .
.El
.It Ic z
Приостановить
.Nm .
Эта команда работает только когда пользователь использует
.Xr csh 1 .
.It Ic \&! Op Ar command
Выполнить одну команду в подоболочке на локальной
системе.
Если
.Ar command
опущена, то вызывается интерактивная
подоболочка.
.It Ic ?\& Op Ar command
Получить справку.
Без аргументов
.Nm
выводит краткую справку.
Если
.Ar command
указана,
.Nm
выведет справочную информацию только для этой команды.
.El
.Sh ОКРУЖЕНИЕ
.Nm
использует по крайней мере переменные окружения
.Ev HOME ,
.Ev SHELL ,
.Ev DISPLAY
и
.Ev TERM .
Другие переменные окружения могут быть переданы
на другую сторону через
опцию
.Dv TELNET ENVIRON .
.Sh ФАЙЛЫ
.Bl -tag -width ~/.telnetrc -compact
.It Pa ~/.telnetrc
пользовательские настройки запуска telnet
.El
.Sh СМ. ТАКЖЕ
.Xr rlogin 1 ,
.Xr rsh 1 ,
.Xr hosts 5 ,
.Xr nologin 5 ,
.Xr telnetd 8 Pq Pa ports/net/freebsd-telnetd
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Bx 4.2 .
.Pp
Поддержка IPv6 была добавлена проектом WIDE/KAME.
.Sh ПРИМЕЧАНИЯ
В некоторых удалённых системах эхо приходится отключать вручную при работе в
режиме \*(Lqстарый построчный\*(Rq.
.Pp
В режиме \*(Lqстарый построчный\*(Rq или
.Dv LINEMODE
символ
.Ic eof
терминала распознаётся (и отправляется удалённой системе)
только когда он является первым символом в строке.
