.\" FRDP path sys/contrib/openzfs/man/man1/test-runner.1
.\" FRDP githash 22649d4dba730d46244fd2dff4fd174903c8379f
.\" FRDP hash256 6c2483f2c2362bc426d90f464f0eabfe633cea721a100e62d5a8fe2f594255af
.Dd May 26, 2021
.Dt RUN 1
.Os
.
.Sh ИМЯ
.Nm run
.Nd поиск, выполнение и протоколирование результатов тестов
.Sh СИНТАКСИС
.Nm
.Op Fl dgq
.Op Fl o Ar outputdir
.Op Fl pP Ar script
.Op Fl t seconds
.Op Fl uxX Ar username
.Ar pathname Ns No …
.Pp
.Nm
.Fl w Ar runfile
.Op Fl gq
.Op Fl o Ar outputdir
.Op Fl pP Ar script
.Op Fl t seconds
.Op Fl uxX Ar username
.Ar pathname Ns No …
.Pp
.Nm
.Fl c Ar runfile
.Op Fl dq
.Pp
.Nm
.Op Fl h
.
.Sh ОПИСАНИЕ
Команда
.Nm
имеет три основных режима работы.
Без
.Fl c
и
.Fl w
.Nm
обрабатывает аргументы, предоставленные в
командной строке, добавляя их в список для этого запуска.
Если указанный
.Ar pathname
является исполняемым файлом, он добавляется как тест.
Если указанный
.Ar pathname
является каталогом, поведение зависит от наличия
.Fl g .
Если
.Fl g
указан, каталог рассматривается как группа тестов.
См. раздел о
.Sy Группах тестов
ниже.
Без
.Fl g
.Nm
просто спускается в каталог в поисках исполняемых файлов.
Затем тесты выполняются, и результаты протоколируются.
.Pp
С
.Fl w
.Nm
находит тесты описанным выше способом.
Вместо выполнения тестов и протоколирования результатов конфигурация тестов
сохраняется в
.Ar runfile ,
который можно использовать в будущих вызовах или отредактировать,
чтобы изменить, какие тесты выполняются и какие параметры применяются.
Параметры, указанные в командной строке с
.Fl w ,
становятся значениями по умолчанию в
.Ar runfile .
.Pp
С
.Fl c
.Nm
разбирает
.Ar runfile ,
который может задавать серию тестов и групп тестов для выполнения.
Затем тесты выполняются, и результаты протоколируются.
.
.Ss Группы тестов
Группа тестов состоит из набора исполняемых файлов, все из которых находятся в
одном каталоге.
Параметры, указанные в командной строке или в
.Ar runfile ,
применяются к отдельным тестам в группе.
Исключение составляют параметры, относящиеся к пред- и пост-скриптам, которые действуют на все
тесты как на группу.
Вместо запуска до и после каждого теста
эти скрипты запускаются только один раз каждый в начале и в конце группы тестов.
.Ss Выполнение тестов
Указанные тесты выполняются последовательно и обычно получают результаты в соответствии
со значениями выхода.
Тесты, завершающиеся с нулём и не с нулём, помечаются
.Sy PASS
и
.Sy FAIL
соответственно.
Когда пред-скрипт завершается с ошибкой для группы тестов, выполняется только пост-скрипт,
а остальные тесты помечаются
.Sy SKIPPED .
Любой тест, превышающий
свой
.Ar timeout ,
завершается и помечается
.Sy KILLED .
.Pp
По умолчанию тесты выполняются с учётными данными
скрипта
.Nm .
Выполнение тестов с другими учётными данными выполняется через
.Xr sudo 1m ,
который должен
быть настроен на разрешение выполнения без запроса пароля.
Переменные окружения из вызывающей оболочки доступны отдельным тестам.
Во время выполнения тестов рабочий каталог изменяется на
.Ar outputdir .
.
.Ss Протоколирование вывода
По умолчанию
.Nm
выводит одну строку в стандартный вывод по завершении
каждого теста, указывая имя теста, результат и затраченное время.
Кроме того, для каждого вызова
.Nm
создаётся каталог с использованием формата даты ISO 8601.
Внутри этого каталога находится файл с именем
.Sy log ,
содержащий весь
вывод тестов с временными метками, и каталог для каждого теста.
Внутри каталогов тестов находится по одному файлу для стандартного вывода,
стандартного потока ошибок и объединённого вывода.
Расположение по умолчанию для
.Ar outputdir
—
.Pa /var/tmp/test_results .
.Ar runfile
— это конфигурационный файл в стиле INI, который описывает запуск тестов.
Файл имеет одну секцию с именем
.Sy DEFAULT ,
которая содержит имена
параметров конфигурации и их значения в
формате
.Sy name No = Ar value .
Значения в этой секции применяются ко всем последующим секциям,
если они не указаны там же, и в этом случае значение по умолчанию переопределяется.
Остальные имена секций — это абсолютные пути к файлам и каталогам,
описывающие тесты и группы тестов соответственно.
Допустимые имена параметров:
.It Sy outputdir No = Ar pathname
Имя каталога, в котором хранятся протоколы тестов.
.It Sy pre No = Ar script
Запустить
.Ar script
перед тестом или группой тестов.
.It Sy pre_user No = Ar username
Выполнить пред-скрипт от имени
.Ar username .
.It Sy post No = Ar script
Запустить
.Ar script
после теста или группы тестов.
.It Sy post_user No = Ar username
Выполнить пост-скрипт от имени
.Ar username .
.It Sy quiet No = Sy True Ns | Ns Sy False
Если
.Sy True ,
в стандартный вывод печатается только сводка результатов.
.It Sy tests No = [ Ns Ar 'filename' , No … ]
Указать список
.Ar filenames
для этой группы тестов.
Требуется только базовое имя абсолютного пути.
Этот параметр допустим только для групп тестов, и каждое
.Ar filename
должно быть заключено в одинарные кавычки.
.It Sy timeout No = Ar n
Значение тайм-аута в
.Ar n
секунд.
.It Sy user No = Ar username
Выполнить тест или группу тестов от имени
.Ar username .
.El
.
.Sh ПАРАМЕТРЫ
.It Fl c Ar runfile
Указать
.Ar runfile ,
который должен быть использован командой run.
.It Fl d
Режим пробного запуска.
Не выполнять тесты, а вывести описание каждого теста, который был бы выполнен.
.It Fl m
Включить отчётность kmemleak (только Linux)
.It Fl g
Создавать группы тестов из любых каталогов, найденных при поиске тестов.
.It Fl o Ar outputdir
Указать каталог, в который записывать результаты тестов.
.It Fl p Ar script
Запустить
.Ar script
перед любым тестом или группой тестов.
.It Fl P Ar script
Запустить
.Ar script
после любого теста или группы тестов.
.It Fl q
Печатать в стандартный вывод только сводку результатов.
.It Fl s Ar script
Запустить
.Ar script
как аварийный скрипт после завершения любого теста.
.It Fl S Ar username
Выполнить аварийный скрипт от имени
.Ar username .
.It Fl t Ar n
Указать значение тайм-аута в
.Ar n
секунд на тест.
.It Fl u Ar username
Выполнять тесты или группы тестов от имени
.Ar username .
.It Fl w Ar runfile
Указать имя
.Ar runfile
для создания.
.It Fl x Ar username
Выполнить пред-скрипт от имени
.Ar username .
.It Fl X Ar username
Выполнить пост-скрипт от имени
.Ar username .
.El
.
.Sh ПРИМЕРЫ
.It Sy Пример 1 : No Запуск специальных тестов .
Этот пример демонстрирует простейший вызов
.Nm .
.Bd -literal
.No % Nm run Ar my-tests
Test: /home/jkennedy/my-tests/test-01                    [00:02] [PASS]
Test: /home/jkennedy/my-tests/test-02                    [00:04] [PASS]
Test: /home/jkennedy/my-tests/test-03                    [00:01] [PASS]

Results Summary
PASS       3

Running Time:   00:00:07
Percent passed: 100.0%
Log directory:  /var/tmp/test_results/20120923T180654
.Ed
.It Sy Пример 2 : No Создание Ar runfile No для будущего использования .
Этот пример демонстрирует создание
.Ar runfile
с нестандартными параметрами.
.Bd -literal
.No % Nm run Fl p Ar setup Fl x Ar root Fl g Fl w Ar new-tests.run Ar new-tests
.No % Nm cat Pa new-tests.run
[DEFAULT]
pre = setup
post_user =
quiet = False
user =
timeout = 60
post =
pre_user = root
outputdir = /var/tmp/test_results

[/home/jkennedy/new-tests]
tests = ['test-01', 'test-02', 'test-03']
.Ed
.El
.
.Sh СМ. ТАКЖЕ
.Xr sudo 1m
