.\" FRDP path usr.bin/usbhidaction/usbhidaction.1
.\" FRDP githash b2c76c41be32f904179efed29c0ca04d53f3996c
.\" FRDP hash256 31f671384863ecad9681e157fb4ae5d27423c267c37ddec67569ad8c147b05fb
.Dd March 14, 2022
.Dt USBHIDACTION 1
.Os
.Sh ИМЯ
.Nm usbhidaction
.Nd выполнение действий в соответствии с элементами управления USB HID
.Sh СИНТАКСИС
.Nm
.Op Fl diev
.Fl c Ar config-file
.Fl f Ar device
.Op Fl p Ar pidfile
.Op Fl t Ar tablefile
.Ar arg ...
.Sh ОПИСАНИЕ
Утилиту
.Nm
можно использовать для выполнения команд, когда на элементах управления HID
появляются определённые значения.
Обычный режим работы этой программы — прочитать файл конфигурации,
а затем стать демоном и выполнять команды, как указано в элементах HID.
Если чтение с устройства HID завершается ошибкой, программа завершается; это заставит её
завершиться, когда USB-устройство будет отключено.
.Pp
Параметры следующие:
.Bl -tag -width indent
.It Fl d
Переключить флаг демона.
.It Fl e
Указать
.Nm
завершиться рано.
Полезно при указании с несколькими подробными параметрами, чтобы увидеть, как разбираются файлы.
.It Fl i
Игнорировать элементы HID в файле конфигурации, которых нет на устройстве.
.It Fl v
Быть подробной и не становиться демоном.
.It Fl c Ar config-file
Указать путь к файлу конфигурации.
.It Fl t Ar tablefile
Указать путь к файлу таблицы использования HID.
.It Fl f Ar device
Указать путь к устройству, с которым работать.
Если
.Ar device
является числом, оно принимается как номер USB HID-устройства.
Если это относительный
путь, он принимается как имя устройства в
.Pa /dev .
Абсолютный путь принимается как буквальный путь устройства.
.It Fl p Ar pidfile
Указать альтернативный файл для хранения идентификатора процесса.
.El
.Pp
Файл конфигурации будет перечитан, если процесс получит
сигнал
.Dv SIGHUP .
.Sh КОНФИГУРАЦИЯ
Файл конфигурации имеет очень простой формат.
Каждая строка описывает
действие; если строка начинается с пробела, она считается продолжением
предыдущей строки.
Строки, начинающиеся с
.Ql #
считаются комментариями.
.Pp
Каждая строка имеет четыре части: имя элемента USB HID, значение для этого элемента,
значение устранения дребезга и действие.
Между частями должен быть пробел.
.Pp
Имена элементов похожи на используемые
.Xr usbhidctl 1 .
.Pp
Значение — это просто числовое значение.
Когда элемент сообщает это значение,
будет выполнено действие.
Если значение —
.Ql * ,
оно будет соответствовать любому значению.
.Pp
Значение устранения дребезга — целое число не меньше 0.
Значение 0 указывает, что устранение дребезга не должно выполняться.
Значение 1 выполнит действие только при изменении состояния.
Значения больше единицы указывают, что действие должно выполняться
только когда значение изменяется на эту величину.
.Pp
Действие — это обычная команда, которая выполняется с помощью
.Xr system 3 .
Перед её выполнением выполняется некоторая подстановка:
.Ql $n
будет заменено на
.Ar n Ns -й
аргумент в командной строке,
.Ql $V
будет заменено на числовое значение элемента HID,
.Ql $N
будет заменено на имя элемента управления, а
.Ql $H
будет заменено на имя устройства HID.
.Sh ФАЙЛЫ
.It Pa /usr/share/misc/usb_hid_usages
Таблица использования HID.
.It Pa /var/run/usbaction.pid
Расположение файла PID по умолчанию.
.El
.Sh ПРИМЕРЫ
Следующий файл конфигурации можно использовать для управления парой
USB-колонок Philips с помощью элементов управления HID на колонках.
.Bd -literal -offset indent
# Configuration for various Philips USB speakers
Consumer:Volume_Increment		 1 0 mixer -f $1 vol.volume=+1%
Consumer:Volume_Decrement		 1 0 mixer -f $1 vol.volume=-1%
Consumer:Mute				 1 0 mixer -f $1 vol.mute=^
Consumer:Channel_Top.Microsoft:Base_Up	 1 0 mixer -f $1 bass.volume=+1%
Consumer:Channel_Top.Microsoft:Base_Down 1 0 mixer -f $1 bass.volume=-1%
.Ed
.Pp
Пример вызова с использованием этой конфигурации:
.Pp
.Pp
Следующий пример управляет громкостью микшера с помощью Logitech Wingman.
Обратите внимание на устранение дребезга 1 для кнопок и 5 для ползунка.
.Bd -literal -offset indent
Button:Button_1	  1 1	mixer vol.volume=+10%
Button:Button_2	  1 1	mixer vol.volume=-10%
.Ed
.Sh СМ. ТАКЖЕ
.Xr usbhidctl 1 ,
.Xr usbhid 3 ,
.Xr uhid 4 ,
.Xr usb 4
.Sh ИСТОРИЯ
Команда
.Nm
впервые появилась в
.Nx 1.6 .
Команда
.Nm
появилась в
.Fx 5.1 .
