.\" FRDP path contrib/vis/vis.1
.\" FRDP githash 15fccd86b9dd17ca2cc1a70b060a2b1a1bf8470b
.\" FRDP hash256 0af94f81c763940599fe6fd63f277b89e16f98617c51ab906dc54dce7cf41d13
.Dd February 18, 2021
.Dt VIS 1
.Os
.Sh ИМЯ
.Nm vis
.Nd отображение непечатаемых символов в визуальном формате
.Sh СИНТАКСИС
.Nm
.Op Fl bcfhlMmNnoSstw
.Op Fl e Ar extra
.Op Fl F Ar foldwidth
.Op Ar file ...
.Sh ОПИСАНИЕ
.Nm
— это фильтр для преобразования непечатаемых символов
в визуальное представление.
Он отличается от
.Ql cat -v
тем, что
форма уникальна и обратима.
По умолчанию кодируются все неграфические
символы, кроме пробела, табуляции и символа новой строки.
Подробное описание
различных визуальных форматов приведено в
.Xr vis 3 .
.Pp
Параметры следующие:
.Bl -tag -width Ds
.It Fl b
Отключает добавление обратной косой черты перед управляющими последовательностями
со стрелкой вверх и метасимволами, а также отключает удвоение обратных косых черт.
Это
даёт вывод, который не является ни обратимым, ни точным, но представляет
минимальное изменение входных данных.
Это похоже на
.Dq Li cat -v .
.Pq Dv VIS_NOSLASH
.It Fl c
Запросить формат, который отображает небольшое подмножество
непечатаемых символов с использованием escape-последовательностей в стиле C.
.Pq Dv VIS_CSTYLE
.It Fl e Ar extra
Также кодировать символы в
.Ar extra ,
согласно
.Xr svis 3 .
.It Fl F Ar foldwidth
Заставляет
.Nm
сворачивать строки вывода до foldwidth столбцов (по умолчанию 80), как
.Xr fold 1 ,
за исключением
того, что используется скрытая последовательность новой строки (которая удаляется
при обратном преобразовании файла в его исходную форму с помощью
.Xr unvis 1 ) .
Если последний символ в закодированном файле не заканчивается символом новой строки,
в вывод добавляется скрытая последовательность новой строки.
Это делает
вывод пригодным для использования с различными редакторами и другими утилитами, которые
обычно не работают с частичными строками.
.It Fl f
То же, что и
.Fl F .
.It Fl h
Кодировать с использованием кодирования URI из RFC 1808.
.Pq Dv VIS_HTTPSTYLE
.It Fl l
Помечать символы новой строки видимой последовательностью
.Ql \e$ ,
за которой следует символ новой строки.
.It Fl M
Кодировать все метасимволы оболочки (подразумевает
.Fl S ,
.Fl w ,
.Fl g )
.Pq Dv VIS_META
.It Fl m
Кодировать с использованием кодирования MIME Quoted-Printable из RFC 2045.
.Pq Dv VIS_MIMESTYLE
.It Fl N
Включить флаг
.Dv VIS_NOLOCALE ,
который выполняет кодирование с использованием локали
.Dq C ,
устраняя любые зависимости кодирования, вызванные текущими
настройками локали, указанными в окружении.
.It Fl n
Отключает любое кодирование, за исключением того, что обратные косые черты
по-прежнему удваиваются, а скрытые последовательности новой строки вставляются, если
выбран
.Fl f
или
.Fl F .
В сочетании с
флагом
.Fl f
.Nm
становится подобной
обратимой версии утилиты
.Xr fold 1 .
То есть вывод можно развернуть, пропустив его через
.Xr unvis 1 .
.It Fl o
Запросить формат, который отображает непечатаемые символы как
восьмеричное число, \eddd.
.Pq Dv VIS_OCTAL
.It Fl S
Кодировать метасимволы оболочки, которые не являются пробельными или подстановочными.
.Pq Dv VIS_SHELL
.It Fl s
Кодируются только символы, считающиеся небезопасными для отправки на терминал.
Этот флаг допускает backspace, bell и возврат каретки в дополнение
к пробелу, табуляции и новой строке по умолчанию.
.Pq Dv VIS_SAFE
.It Fl t
Табуляции также кодируются.
.Pq Dv VIS_TAB
.It Fl w
Пробельные символы (пробел-табуляция-новая строка) также кодируются.
.Pq Dv VIS_WHITE
.El
.Sh ПОДДЕРЖКА МНОГОБАЙТОВЫХ СИМВОЛОВ
.Nm
поддерживает ввод многобайтовых символов.
На преобразование кодирования влияет настройка
переменной окружения
.Ev LC_CTYPE ,
которая определяет набор символов, которые можно
копировать без кодирования.
.Pp
Когда во входных данных присутствуют 8-битные данные,
.Ev LC_CTYPE
должна быть установлена в правильную локаль или в локаль C.
Если локали данных и преобразования не совпадают, распознавание многобайтовых
символов может не сработать, и кодирование будет выполняться побайтово
вместо этого.
.Sh ОКРУЖЕНИЕ
.It Ev LC_CTYPE
Указать локаль входных данных.
Установите в C, если локаль входных данных неизвестна.
.El
.Sh ПРИМЕРЫ
Визуализировать символы, кодируя пробельные символы и табуляции:
.Bd -literal -offset indent
\\^P\\012\\011\\012
.Ed
.Pp
То же, что и выше, но с использованием `\\$' для новой строки, за которым следует настоящая новая строка:
.Bd -literal -offset indent
\\^P\\$
\\011\\$
.Ed
.Pp
Визуализировать строку с использованием кодирования URI:
.Bd -literal -offset indent
$ echo http://www.freebsd.org | vis -h
http%3a%2f%2fwww.freebsd.org%0a
.Ed
.Sh СМ. ТАКЖЕ
.Xr unvis 1 ,
.Xr svis 3 ,
.Xr vis 3
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Bx 4.4 .
Поддержка многобайтовых символов была добавлена в
.Nx 7.0
и
.Fx 9.2 .
