.\" FRDP path usr.bin/write/write.1
.\" FRDP githash bdcbfde31e8e9b343f113a1956384bdf30d1ed62
.\" FRDP hash256 d1e2c1af04df74658ced36fe258d5161d4f740a928b941dfc43dcde5febaca12
.Dd February 13, 2012
.Dt WRITE 1
.Os
.Sh ИМЯ
.Nm write
.Nd отправить сообщение другому пользователю
.Sh СИНТАКСИС
.Nm
.Ar user
.Op Ar tty
.Sh ОПИСАНИЕ
Утилита
.Nm
позволяет общаться с другими пользователями, копируя строки с
вашего терминала на их.
.Pp
Когда вы запускаете команду
.Nm ,
пользователь, которому вы пишете, получает сообщение вида:
.Pp
.Dl Message from yourname@yourhost on yourtty at hh:mm ...
.Pp
Любые дальнейшие строки, которые вы вводите, будут скопированы на терминал указанного
пользователя.
Если другой пользователь хочет ответить, он также должен запустить
.Nm .
.Pp
Когда вы закончите, введите символ конца файла или прерывания.
Другой пользователь увидит сообщение
.Ql EOF ,
указывающее, что
разговор окончен.
.Pp
Вы можете запретить людям (кроме суперпользователя) писать вам
с помощью команды
.Xr mesg 1 .
.Pp
Если пользователь, которому вы хотите написать, вошёл в систему более чем на одном терминале,
вы можете указать, на какой терминал писать, указав имя терминала
как второй операнд команды
.Nm .
В качестве альтернативы вы можете позволить
.Nm
выбрать один из терминалов — она выберет тот, у которого наименьшее
время простоя.
Это делается для того, чтобы если пользователь вошёл в систему на работе и также дозвонился
из дома, сообщение пошло в нужное место.
.Pp
Традиционный протокол для общения с кем-либо состоит в том, что строка
.Ql \-o ,
либо в конце строки, либо в отдельной строке, означает, что сейчас
очередь говорить другого человека.
Строка
.Ql oo
означает, что человек считает разговор
оконченным.
.Sh СМ. ТАКЖЕ
.Xr mesg 1 ,
.Xr talk 1 ,
.Xr wall 1 ,
.Xr who 1
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v1 .
.Sh ИЗВЕСТНЫЕ ОШИБКИ
Настройка
.Ev LC_CTYPE
отправителя используется для определения того, какие символы безопасно писать на
терминал, а не получателя (о которой
.Nm
не имеет способа узнать).
