.\" FRDP path contrib/expat/doc/xmlwf.1
.\" FRDP githash c7b67985633c408cae69703ca443cbfd84d326a8
.\" FRDP hash256 d0c7006ad0ac5689a36f36a14ee2b0df0d5297bd48c5aded708b085fe476c87d
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.SH ИМЯ
xmlwf \- Определяет, является ли XML-документ корректно сформированным
.SH СИНТАКСИС
'nh
.fi
.ad l
\fBxmlwf\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[\fIПАРАМЕТРЫ\fR] [\fIФАЙЛ\fR ...]
'in \n(.iu-\nxu
.ad b
'hy
'nh
.fi
.ad l
\fBxmlwf\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
\fB-h\fR | \fB--help\fR
'in \n(.iu-\nxu
.ad b
'hy
'nh
.fi
.ad l
\fBxmlwf\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
\fB-v\fR | \fB--version\fR
'in \n(.iu-\nxu
.ad b
'hy
.SH ОПИСАНИЕ
\fBxmlwf\fR использует библиотеку Expat, чтобы
определить, является ли XML-документ корректно сформированным. Он
невалидирующий.
.PP
Если вы не указали файлы в командной строке, и у вас
есть свежая версия \fBxmlwf\fR,
входной файл будет прочитан из стандартного ввода.
Корректно сформированный документ должен следовать
следующим правилам:
.TP 0.2i
\(bu
Файл начинается с XML-декларации. Например,
\fIПРИМЕЧАНИЕ\fR:
\fBxmlwf\fR в настоящее время не
проверяет допустимость XML-декларации.
.TP 0.2i
\(bu
Каждый начальный тег либо пуст (<tag/>),
либо имеет соответствующий конечный тег.
.TP 0.2i
\(bu
Существует ровно один корневой элемент. Этот элемент должен содержать
все остальные элементы документа. После закрытия
корневого элемента могут следовать только комментарии, пробельные
символы и инструкции обработки.
.TP 0.2i
\(bu
Все элементы правильно вложены.
.TP 0.2i
\(bu
Все значения атрибутов заключены в кавычки (одинарные
или двойные).
.PP
Если документ имеет DTD и строго соответствует этому
DTD, то документ также считается \fIдействительным\fR.
\fBxmlwf\fR — невалидирующий анализатор:
он не проверяет DTD. Однако он поддерживает
внешние сущности (см. параметр \*(T<\fB\-x\fR\*(T>).
.SH ОПЦИИ
Когда параметр включает аргумент, вы можете указать аргумент либо
поддерживаются оба.
.TP 
\*(T<\fB\-a\fR\*(T> \fIкоэффициент\fR
Устанавливает максимально допустимый коэффициент усиления
для защиты от атак усиления,
таких как атака «миллиард смехов»
(по умолчанию: 100.0
для суммы прямого и косвенного вывода, а также
для выделения динамической памяти).
Коэффициент усиления вычисляется как ..

.nf

    amplification := (direct + indirect) / direct
          
.fi

\&.. с учётом использования сущностей и ..

.nf

    amplification := allocated / direct
          
.fi

\&.. с учётом динамической памяти во время разбора.
<direct> — это количество байтов, прочитанных
из основного документа при разборе,
<indirect> — это количество байтов,
добавленных при раскрытии сущностей и чтении внешних DTD-файлов,
в сумме, и
<allocated> — это общее количество байтов динамической памяти,
выделенных (и не освобождённых) на иерархию анализаторов.

\fIПРИМЕЧАНИЕ\fR:
Если вам когда-либо понадобится увеличить это значение для не-атакующей нагрузки,
пожалуйста, сообщите об ошибке.
.TP 
\*(T<\fB\-b\fR\*(T> \fIбайты\fR
Устанавливает количество выходных байтов (включая усиление),
необходимое для активации защиты от атак усиления,
таких как «миллиард смехов»
(по умолчанию: 8 MiB для суммы прямого и косвенного вывода,
и 64 MiB для выделения динамической памяти).

\fIПРИМЕЧАНИЕ\fR:
Если вам когда-либо понадобится увеличить это значение для не-атакующей нагрузки,
пожалуйста, сообщите об ошибке.
.TP 
\*(T<\fB\-c\fR\*(T>
Если входной файл корректно сформирован и \fBxmlwf\fR
не обнаруживает ошибок, входной файл просто копируется в
выходной каталог без изменений.
Это подразумевает отсутствие пространств имён (отключает \*(T<\fB\-n\fR\*(T>) и
требует \*(T<\fB\-d\fR\*(T> для указания выходного каталога.
.TP 
\*(T<\fB\-d\fR\*(T> \fIвыходной_каталог\fR
Указывает каталог для хранения преобразованных
представлений входных файлов.
По умолчанию \*(T<\fB\-d\fR\*(T> выводит каноническое представление
(описано ниже).
Вы можете выбрать другие форматы вывода с помощью \*(T<\fB\-c\fR\*(T>,
\*(T<\fB\-m\fR\*(T> и \*(T<\fB\-N\fR\*(T>.

Имена выходных файлов будут
поступать из стандартного ввода. Поэтому вы должны быть осторожны, чтобы
выходной файл не попал в тот же каталог, что и входной
файл. Иначе \fBxmlwf\fR удалит
входной файл перед созданием выходного файла (так же, как выполнение
\*(T<cat < file > file\*(T> в большинстве оболочек).

Два структурно эквивалентных XML-документа имеют побайтово
идентичное каноническое XML-представление.
Обратите внимание, что игнорируемые пробельные символы считаются значимыми и
обрабатываются эквивалентно данным.
Подробнее о каноническом XML можно узнать по адресу
http://www.jclark.com/xml/canonxml.html .
.TP 
\*(T<\fB\-e\fR\*(T> \fIкодировка\fR
Указывает кодировку символов для документа, переопределяя
любое объявление кодировки документа. \fBxmlwf\fR
поддерживает четыре встроенные кодировки:
\*(T<US\-ASCII\*(T>,
\*(T<UTF\-8\*(T>,
\*(T<UTF\-16\*(T>, и
\*(T<ISO\-8859\-1\*(T>.
См. также параметр \*(T<\fB\-w\fR\*(T>.
.TP 
\*(T<\fB\-g\fR\*(T> \fIбайты\fR
Устанавливает размер буфера, запрашиваемого на пару вызовов
\*(T<\fBXML_GetBuffer\fR\*(T> и \*(T<\fBread\fR\*(T>
(по умолчанию: 8 KiB).
.TP 
\*(T<\fB\-h\fR\*(T>, \*(T<\fB\-\-help\fR\*(T>
Выводит краткую информацию об использовании команды \fBxmlwf\fR,
а затем завершает работу.
Похоже на эту страницу man, но более кратко.
.TP 
\*(T<\fB\-k\fR\*(T>
При обработке нескольких файлов \fBxmlwf\fR
по умолчанию останавливается после первого файла с ошибкой.
Это указывает \fBxmlwf\fR сообщить об ошибке,
но продолжить обработку.
Это может быть полезно, например, при тестировании фильтра, который преобразует
многие файлы в XML, и вы хотите быстро выяснить, какие преобразования
не удались.
.TP 
\*(T<\fB\-m\fR\*(T>
Выводит какой-то странный XML-файл, который полностью
описывает входной файл, включая позиции символов.
Требует \*(T<\fB\-d\fR\*(T> для указания выходного файла.
.TP 
\*(T<\fB\-n\fR\*(T>
Включает обработку пространств имён. (описать пространства имён)
\*(T<\fB\-c\fR\*(T> отключает пространства имён.
.TP 
\*(T<\fB\-N\fR\*(T>
Добавляет объявления doctype и notation в канонический XML-вывод.
Это соответствует примеру вывода, используемому в официальных XML-тестах.
Требует \*(T<\fB\-d\fR\*(T> для указания выходного файла.
.TP 
\*(T<\fB\-p\fR\*(T>
Указывает \fBxmlwf\fR обрабатывать внешние DTD и параметрические
сущности.

Обычно \fBxmlwf\fR никогда не разбирает параметрические
сущности. \*(T<\fB\-p\fR\*(T> указывает всегда разбирать их.
\*(T<\fB\-p\fR\*(T> подразумевает \*(T<\fB\-x\fR\*(T>.
.TP 
\*(T<\fB\-q\fR\*(T>
Отключает отложенный повторный разбор и допускает квадратичное время разбора
на больших токенах (по умолчанию: отложенный повторный разбор включён).
.TP 
\*(T<\fB\-r\fR\*(T>
Обычно \fBxmlwf\fR отображает XML-файл в память
перед разбором; это может ускорить разбор на многих
платформах.
\*(T<\fB\-r\fR\*(T> отключает отображение в память и использует обычные
вызовы файлового ввода-вывода.
Конечно, отображение в память автоматически отключается
при чтении из стандартного ввода.

Использование отображения в память может привести к тому, что некоторые платформы будут сообщать
существенно больший объём памяти, используемый
\fBxmlwf\fR, но это, похоже, связано с тем, что
операционная система странно сообщает о памяти; утечки в \fBxmlwf\fR
нет.
.TP 
\*(T<\fB\-s\fR\*(T>
Выводит ошибку, если документ не является автономным.
Документ является автономным, если у него нет внешнего подмножества и нет
ссылок на параметрические сущности.
.TP 
\*(T<\fB\-t\fR\*(T>
Включает измерение времени. Это указывает Expat разобрать весь файл,
но не выполнять никакой обработки.
Это даёт довольно точное представление о чистой скорости самого Expat
без накладных расходов клиента.
\*(T<\fB\-t\fR\*(T> отключает большинство опций вывода
(\*(T<\fB\-d\fR\*(T>, \*(T<\fB\-m\fR\*(T>, \*(T<\fB\-c\fR\*(T>, ...).
.TP 
\*(T<\fB\-v\fR\*(T>, \*(T<\fB\-\-version\fR\*(T>
Выводит версию используемой библиотеки Expat, включая некоторую
информацию о конфигурации библиотеки во время компиляции, и
затем завершает работу.
.TP 
\*(T<\fB\-w\fR\*(T>
Включает поддержку кодовых страниц Windows.
Обычно \fBxmlwf\fR выдаёт ошибку, если
встречает кодировку, которую он не в состоянии обработать сам. С
\*(T<\fB\-w\fR\*(T>, \fBxmlwf\fR попытается использовать кодовую
страницу Windows. См. также \*(T<\fB\-e\fR\*(T>.
.TP 
\*(T<\fB\-x\fR\*(T>
Включает разбор внешних сущностей.
(ОСТОРОЖНО! Это делает xmlwf уязвимым для атак внешних сущностей (XXE).)

Невалидирующие анализаторы не обязаны разрешать внешние
сущности или вообще раскрывать сущности.
Expat всегда раскрывает внутренние сущности (?),
но разбор внешних сущностей должен быть включён явно.

Внешние сущности — это просто сущности, которые получают свои
данные извне XML-файла, разбираемого в данный момент.

Это пример внутренней сущности:

.nf

<!ENTITY vers '1.0.2'>
            
.fi

А вот несколько примеров внешних сущностей:

.nf

            
.fi
.TP 
\*(T<\fB\-\-\fR\*(T>
(Два дефиса.)
Завершает список параметров. Это нужно только если имя файла
начинается с дефиса. Например:

.nf

xmlwf \-\- \-myfile.xml
          
.fi

выполнит \fBxmlwf\fR для файла
\*(T<\fI\-myfile.xml\fR\*(T>.
.PP
Старые версии \fBxmlwf\fR не поддерживают
чтение из стандартного ввода.
.SH ВЫВОД
\fBxmlwf\fR ничего не выводит для файлов без проблем.
Если какой-либо входной файл не является корректно сформированным, или если вывод для любого
входного файла не может быть открыт, \fBxmlwf\fR печатает одну
строку с описанием проблемы в стандартный вывод.
.PP
Если параметр \*(T<\fB\-k\fR\*(T> не указан, \fBxmlwf\fR
останавливается при обнаружении ошибки корректности формата или ошибки выходного файла.
Если \*(T<\fB\-k\fR\*(T> указан, \fBxmlwf\fR продолжает
обработку оставшихся входных файлов, описывая найденные проблемы с любым из них.
Для параметров \*(T<\fB\-v\fR\*(T>|\*(T<\fB\-\-version\fR\*(T> или \*(T<\fB\-h\fR\*(T>|\*(T<\fB\-\-help\fR\*(T>, \fBxmlwf\fR всегда завершается с кодом состояния 0. В остальных случаях возвращаются следующие коды состояния выхода:
.TP 
\*(T<\fB0\fR\*(T>
Входные файлы корректно сформированы, и вывод (если запрошен) успешно записан.
.TP 
\*(T<\fB1\fR\*(T>
Произошла внутренняя ошибка.
.TP 
\*(T<\fB2\fR\*(T>
Один или несколько входных файлов не были корректно сформированы или не могли быть разобраны.
.TP 
\*(T<\fB3\fR\*(T>
При использовании параметра \*(T<\fB\-d\fR\*(T> произошла ошибка при открытии выходного файла.
.TP 
\*(T<\fB4\fR\*(T>
Была ошибка аргумента командной строки в способе вызова \fBxmlwf\fR.
.SH ИЗВЕСТНЫЕ ОШИБКИ
Ошибки должны выводиться в стандартный поток ошибок, а не в стандартный вывод.
.PP
Должен быть способ заставить \*(T<\fB\-d\fR\*(T> отправлять
вывод в стандартный вывод, вместо того чтобы заставлять пользователя отправлять
его в файл.
.PP
Я понятия не имею, зачем кому-то может понадобиться использовать
параметры \*(T<\fB\-d\fR\*(T>, \*(T<\fB\-c\fR\*(T>, и
\*(T<\fB\-m\fR\*(T>. Если бы кто-то мог объяснить это
мне, я хотел бы добавить эту информацию в эту страницу man.
.nf

Домашняя страница Expat:                            https://libexpat.github.io/
Спецификация W3 XML 1.0 (четвёртое издание):  https://www.w3.org/TR/2006/REC\-xml\-20060816/
Атака «миллиард смехов»:                          https://en.wikipedia.org/wiki/Billion_laughs_attack
      
.fi
.SH АВТОР
Эта страница man была изначально написана Скоттом Бронсоном <\*(T<bronson@rinspin.com\*(T>>
в декабре 2001 года для
системы Debian GNU/Linux (но может использоваться другими). Разрешается
копировать, распространять и/или изменять этот документ на
условиях GNU Free Documentation
License, Version 1.1.
