.\" FRDP path contrib/libxo/xo/xo.1
.\" FRDP githash 34b867ca30479cec104fd069178df294f8ea35f1
.\" FRDP hash256 0fd51437369d2addbf4ab36b0e2141cf4451a8ec1a89f22f7a10152e843daea1
.Dd December 4, 2014
.Dt XO 1
.Os
.Sh ИМЯ
.Nm xo
.Nd выводить форматированный вывод на основе строки формата и аргументов
.Sh СИНТАКСИС
.Nm
.Op Fl options
.Op Ar аргумент...
.Sh ОПИСАНИЕ
Утилита
.Nm
предоставляет доступ из командной строки к функциональности
библиотеки
.Nm libxo .
Используя
.Nm ,
сценарии командной оболочки могут выдавать
.Em XML ,
.Em JSON
или
.Em HTML
с помощью тех же команд, которые выводят текст.
.Pp
.Bl -tag -width indent
.It Ic --close Ar путь
Закрыть теги для заданного пути
.It Ic -C | Ic --continuation
Указывает, что этот вывод является продолжением предыдущих выходных данных
и должен находиться на той же строке.
Это позволяет корректно формировать вывод HTML.
.It Ic --depth Ar число
Установить глубину для форматированного вывода
.It Ic --help
Показать текст справки
.It Ic -H | Ic --html
Генерировать вывод HTML
.It Ic -J | Ic --json
Генерировать вывод JSON
.It Ic --leading-xpath Ar путь
Добавить префикс к создаваемым XPath (HTML)
.It Ic --not-first
Указывает, что это содержимое не первое в ряду родственных объектов;
между такими объектами ставится запятая.
.It Ic --open Ar путь
Открыть теги для заданного пути
.It Ic -p | Ic --pretty
Создавать 'pretty' вывод (добавлять отступы, переводы строк)
.It Ic --style Ar стиль
Генерировать заданный стиль (xml, json, text, html)
.It Ic -T | Ic --text
Генерировать текстовый вывод (стиль по умолчанию)
.It Ic --top-warp
Указывает, что весь объект должен быть помещён внутрь оболочки объекта
верхнего уровня, особенно при генерации вывода JSON.
.It Ic --version
Показать информацию о версии
.It Ic -W | Ic --warn
Выводить предупреждения в текстовом виде в stderr
.It Ic --warn-xml
Выводить предупреждения в xml в stdout
.It Ic --wrap Ar путь
Обернуть вывод в набор контейнеров
.It Ic -X | Ic --xml
Генерировать вывод XML
.It Ic --xpath
Добавить данные XPath в вывод HTML
.El
.Pp
Утилита
.Nm
принимает строку формата, подходящую для
.Xr xo_emit 3 ,
и набор из нуля или более аргументов, используемых для предоставления данных
для этой строки.
.Pp
Кроме того,
.Nm
принимает любые из параметров
.Nm libxo ,
перечисленных в
.Xr xo_options 7 .
.Sh ПРИМЕРЫ
В этом примере
.Nm
используется для вывода одних и тех же данных в текстовом виде, а затем в XML с помощью
.Bd -literal -offset indent
  The stereo is in route
  <product>stereo</product>
  <status>in route</status>
.Ed
.Pp
В этом примере вывод команды
.Nm
показан в нескольких стилях:
.Bd -literal -offset indent
.Pp
  TEXT:
    The fish weighs 6 pounds.
  XML:
    <name>fish</name>
    <weight>6</weight>
  JSON:
  HTML:
    </div>
.Ed
.Pp
Параметр может использоваться для обёртывания выводимого содержимого в
определённую иерархию.
Путь — это набор иерархических имён, разделённых символом '/'.
.Bd -literal -offset indent
  xo --wrap top/a/b/c '{:tag}' value
.Pp
  XML:
    <top>
      <a>
        <b>
          <c>
            <tag>value</tag>
          </c>
        </b>
      </a>
    </top>
  JSON:
          }
        }
      }
    }
.Ed
.Pp
Параметры могут использоваться для вывода
иерархической информации без соответствующих закрывающего и открывающего
тегов.
Это позволяет сценарию командной оболочки выводить открывающие теги, данные,
а затем закрывающие теги.
Параметр
.Fl \-depth
может использоваться для установки
глубины отступов.
Параметр может использоваться для
добавления данных в начало значений XPath, используемых для стиля вывода HTML.
.Bd -literal -offset indent
  #!/bin/sh
  xo --open top/data
  xo --depth 2 '{:tag}' value
  xo --close top/data
.Pp
  XML:
    <top>
      <data>
        <tag>value</tag>
      </data>
    </top>
  JSON:
      }
    }
.Ed
.Sh СМ. ТАКЖЕ
.Xr libxo 3 ,
.Xr xo_emit 3 ,
.Xr xo_options 7
.Sh ИСТОРИЯ
Библиотека
.Nm libxo
впервые появилась в
.Fx 11.0 .
.Sh АВТОРЫ
.Nm libxo
была написана
.An Phil Shafer Aq Mt phil@freebsd.org .
