.\" FRDP path contrib/byacc/yacc.1
.\" FRDP githash 822ca3276345b4a67ccbc9b54616d8b205fd37f2
.\" FRDP hash256 22de5f75cadccb46c93f41ee2c1edab7a7e7b81051334257e005fbbbfee8a4da
.
.ds N Yacc
.ds n yacc
.
.ie n .ds CW R
.el   \{
.ie \n(.g .ds CW CR
.el       .ds CW CW
.\}
.
.de Ex
.RS +7
.PP
.nf
.ft \*(CW
..
.de Ee
.fi
.ft R
.RE
..
.ie \n(.g \{
.ds `` \(lq
.ds '' \(rq
.ds '  \(aq
.\}
.el \{
.ie t .ds `` ``
.ie t .ds '' ''
.ie t .ds '  \(aq
.el   .ds '  '
.\}
.de bP
.ie n  .IP \(bu 4
.el    .IP \(bu 2
..
.SH ИМЯ
\*N \-
генератор LALR(1)-анализаторов
.SH СИНТАКСИС
.B \*n [ \-BdghilLPrtvVy ] [ \-b
.I file_prefix
.B ] [ \-H
.I defines_file
.B ] [ \-o
.I output_file
.B ] [ \-p
.I symbol_prefix
.B ]
.I filename
.SH ОПИСАНИЕ
.B \*N
читает спецификацию грамматики из файла
.I filename
и генерирует для неё LALR(1)-анализатор.
Анализаторы состоят из набора LALR(1)-таблиц разбора и управляющей программы
(драйвера), написанной на языке программирования C.
.B \*N
обычно записывает таблицы разбора и управляющую программу в файл
.IR  y.tab.c .
.PP
Доступны следующие параметры:
.TP 5
\fB\-b \fIfile_prefix\fR
Параметр
.B \-b
изменяет префикс, добавляемый к именам выходных файлов, на
строку, задаваемую
.I file_prefix.
Префикс по умолчанию — символ
.I y.
.TP
.B \-B
создать анализатор с возвратами (конфигурация времени компиляции для \fBbtyacc\fP).
.TP
.B \-d
вызывает запись заголовочного файла
.B y.tab.h
Он содержит директивы #define для идентификаторов токенов.
.TP
.B \-h
вывести сообщение об использовании в стандартный поток ошибок.
.TP
\fB\-H \fIdefines_file\fR
вызывает запись директив #define для идентификаторов токенов
в заданный \fIdefines_file\fP вместо
файла \fBy.tab.h\fP, используемого параметром \fB\-d\fP.
.TP
.B \-g
Параметр
.B \-g
вызывает запись графического описания сгенерированного LALR(1)-анализатора
в файл
.B y.dot
в формате graphviz, готовом для обработки программой
.BR dot (1).
.TP
.B \-i
Параметр \fB\-i\fR вызывает запись дополнительного заголовочного файла
.B y.tab.i
Он содержит объявления extern
и дополнительные директивы #define, необходимые для отображения обычных
имён с префиксом \fByy\fP, используемых \fIyacc\fP,
в то, что может задать параметр \fB\-p\fP.
Файл кода, например \fBy.tab.c\fP, изменяется для #include этого файла,
а также файла \fBy.tab.h\fP, что обеспечивает согласованное использование
символов, определённых в этих файлах.
.IP
Дополнительный заголовочный файл упрощает раздельную компиляцию
lex- и yacc-файлов.
.TP
.B \-l
Если параметр
.B \-l
не задан,
.B \*n
вставит директивы \fI#line\fP в сгенерированный код.
Директивы \fI#line\fP позволяют компилятору C соотносить ошибки в
сгенерированном коде с исходным кодом пользователя.
Если параметр \fB\-l\fR задан,
.B \*n
не будет вставлять директивы \fI#line\fP.
\&\fI#line\fP директивы, заданные пользователем, будут сохранены.
.TP
.B \-L
включить обработку позиций,
например, \*(``%locations\*('' (конфигурация времени компиляции для \fBbtyacc\fP).
.TP
\fB\-o \fIoutput_file\fR
задать имя файла для файла анализатора.
Если этот параметр не указан, имя выходного файла —
префикс файла, соединённый с суффиксом файла, например, \fBy.tab.c\fP.
Это переопределяет параметр \fB\-b\fP.
.TP
\fB\-p \fIsymbol_prefix\fR
Параметр
.B \-p
изменяет префикс, добавляемый к символам, генерируемым yacc, на
строку, задаваемую
.I symbol_prefix.
Префикс по умолчанию — строка
.B yy.
.TP
.B \-P
создать повторно входимый анализатор, например, \*(``%pure\-parser\*(''.
.TP
.B \-r
Параметр
.B \-r
заставляет
.B \*n
создавать отдельные файлы для кода и таблиц.
Файл кода называется
.IR y.code.c ,
а файл таблиц называется
.IR y.tab.c .
Префикс \*(``\fIy.\fP\*('' можно переопределить с помощью параметра \fB\-b\fP.
.TP
.B \-s
подавить директивы \*(``\fB#define\fP\*('', генерируемые для строковых литералов в
директиве \*(``\fB%token\fP\*('',
чтобы более точно соответствовать поведению оригинального \fByacc\fP.
.IP
Обычно, когда \fB\*n\fP видит строку, например
.Ex
.Ee
.IP
он замечает, что взятое в кавычки \*(``ADD\*('' является допустимым идентификатором C,
и генерирует #define не только для OP_ADD,
но и для ADD,
например,
.Ex
#define OP_ADD 257
.br
#define ADD 258
.Ee
.IP
Оригинальный \fByacc\fP не генерирует второй \*(``\fB#define\fP\*(''.
Параметр \fB\-s\fP подавляет эту \*(``\fB#define\fP\*(''.
.IP
POSIX (IEEE 1003.1 2004) документирует только имена и числа
для \*(``\fB%token\fP\*('',
хотя оригинальный \fByacc\fP и bison также принимают строковые литералы.
.TP
.B \-t
Параметр
.B \-t
изменяет директивы препроцессора, генерируемые
.B \*n
так, чтобы отладочные операторы включались в скомпилированный код.
.IP
\fB\*N\fR отправляет отладочный вывод в стандартный поток вывода
(совместимо как с оригинальным \fByacc\fP, так и с \fBbtyacc\fP),
тогда как \fBbtyacc\fP записывает отладочный вывод в стандартный поток ошибок
(как \fBbison\fP).
.TP
.B \-v
Параметр
.B \-v
вызывает запись удобочитаемого описания сгенерированного анализатора
в файл
.I y.output.
.TP
.B \-V
вывести номер версии в стандартный поток вывода.
.TP
.B \-y
\fB\*n\fP игнорирует этот параметр,
который bison поддерживает для мнимой совместимости с POSIX.
.PP
Параметр \fIfilename\fP не является необязательным.
Однако \fB\*n\fP принимает одиночный \*(``\-\*('' для чтения грамматики
из стандартного ввода.
Двойной маркер \*(``\-\-\*('' обозначает конец параметров.
После маркера \*(``\-\-\*('' ожидается один параметр \fIfilename\fP.
.
.SH ДИАГНОСТИКА
Если есть правила, которые никогда не сводятся, количество таких правил
сообщается в стандартный поток ошибок.
Если есть какие-либо LALR(1)-конфликты, количество конфликтов сообщается
в стандартный поток ошибок.

.SH РАСШИРЕНИЯ
.B \*N
предоставляет некоторые расширения для
совместимости с bison и другими реализациями yacc.
Он принимает несколько \fIдлинных параметров\fP, имеющих эквиваленты в \*n.
Возможности \fB%destructor\fP и \fB%locations\fP доступны
только если \fB\*n\fP был сконфигурирован и скомпилирован с поддержкой
функциональности возвратов (\fBbtyacc\fP).
Остальные возможности доступны всегда:
.TP
\fB %code\fP \fIkeyword\fP { \fIcode\fP }
Добавляет указанный исходный \fIкод\fP в заданной точке выходного файла.
Необязательный \fIkeyword\fP указывает \fB\*n\fP, куда вставлять \fIкод\fP:
.RS 7
.TP 5
\fBtop\fP
сразу после определения версии в сгенерированном файле кода.
.TP 5
\fBrequires\fP
сразу после объявления публичных переменных анализатора.
Если задан параметр \fB\-d\fP, код вставляется в
начало файла определений.
.TP 5
\fBprovides\fP
сразу после объявления приватных переменных анализатора.
Если задан параметр \fB\-d\fP, код вставляется в
конец файла определений.
.RE
.IP
Если \fIkeyword\fP не задан, код вставляется в
начало раздела кода, скопированного дословно из исходного файла.
Можно задать несколько директив \fB%code\fP;
\fB\*n\fP вставляет их в соответствующий файл кода или определений
в том порядке, в котором они появляются в исходном файле.
.TP
\fB %debug\fP
Это имеет тот же эффект, что и параметр командной строки \*(``\-t\*(''.
.TP
\fB %destructor\fP { \fIcode\fP } \fIsymbol+\fP
определяет код, который вызывается, когда символ автоматически
отбрасывается во время восстановления после ошибки.
Этот код можно использовать для
освобождения динамически выделенной памяти, связанной с соответствующим
семантическим значением, в случаях, когда пользовательские действия не могут
управлять памятью явно.
.IP
При обнаружении ошибки разбора сгенерированный анализатор
отбрасывает символы в стеке и входные токены, пока не достигнет состояния,
позволяющего продолжить разбор.
Такой подход к восстановлению после ошибки приводит к утечке памяти,
если значение \fBYYSTYPE\fP является указателем на динамически выделенную
память или содержит такие указатели.
.IP
Код в скобках \fIcode\fP вызывается всякий раз, когда анализатор отбрасывает
один из символов.
Внутри \fIcode\fP \*(``\fB$$\fP\*('' или
\*(``\fB$<\fItag\fB>$\fR\*('' обозначает семантическое значение, связанное с
отброшенным символом, а \*(``\fB@$\fP\*('' обозначает его местоположение (см.
директиву \fB%locations\fP).
.IP
Деструктор для отдельного символа определяется указанием грамматического
символа в \fIsymbol+\fP.  Деструктор для типа определяется указанием
тега семантического типа (например, \*(``<some_tag>\*('') в \fIsymbol+\fP; в этом
случае анализатор будет вызывать \fIcode\fP всякий раз, когда он отбрасывает
любой грамматический символ с этим тегом семантического типа, если только у
этого символа нет собственного деструктора для отдельного символа.
.IP
Поддерживаются две категории деструкторов по умолчанию, которые
вызываются при отбрасывании любого грамматического символа, не имеющего
ни деструктора для отдельного символа, ни деструктора для типа:
.RS
.bP
код для \*(``\fB<*>\fP\*('' используется
для грамматических символов, имеющих явно объявленный тег семантического типа
(через \*(``\fB%type\fP\*('');
.bP
код для \*(``\fB<>\fP\*('' используется
для грамматических символов без объявленного тега семантического типа.
.RE
.TP
\fB %empty\fP
игнорируется \fB\*n\fP.
.TP
\fB %expect\fP \fInumber\fP
сообщает \fB\*n\fP ожидаемое число shift/reduce-конфликтов.
Благодаря этому число сообщается только если оно отличается.
.TP
\fB %expect\-rr\fP \fInumber\fP
сообщает \fB\*n\fP ожидаемое число reduce/reduce-конфликтов.
Благодаря этому число сообщается только если оно отличается.
Это (в отличие от bison) допустимо в LALR-анализаторах.
.TP
\fB %locations\fP
указывает \fB\*n\fP включить управление информацией о позиции, связанной
с каждым токеном, предоставляемой лексером в глобальной переменной \fByylloc\fP,
подобно управлению информацией о семантическом значении, предоставляемой в \fByylval\fP.
.IP
Как и для семантических значений, местоположения можно указывать внутри
действий с помощью \fB@$\fP для ссылки на местоположение символа левой части, и \fB@\fIN\fR
(\fIN\fP — целое) для ссылки на местоположение одного из символов правой части.
Также как и для семантических значений, при сопоставлении правила
по умолчанию действие используется для вычисления местоположения,
представляемого \fB@$\fP, как начала первого символа и конца последнего символа в правой
части правила.
Это вычисление по умолчанию можно переопределить
явным присваиванием \fB@$\fP в действии правила.
.IP
Тип \fByylloc\fP — \fBYYLTYPE\fP, который по умолчанию определён так:
.Ex
typedef struct YYLTYPE {
    int first_line;
    int first_column;
    int last_line;
    int last_column;
} YYLTYPE;
.Ee
.IP
\fBYYLTYPE\fP может быть переопределён пользователем
(\fBYYLTYPE_IS_DEFINED\fP должен быть определён, чтобы отключить значение по умолчанию)
в разделе объявлений файла спецификации.
Как в bison, макрос \fBYYLLOC_DEFAULT\fP вызывается
каждый раз при сопоставлении правила для вычисления позиции левой части
правила, перед выполнением связанного действия; этот макрос может быть
переопределён пользователем.
.IP
Эта директива добавляет параметр \fBYYLTYPE\fP к \fByyerror()\fP.
Если присутствует директива \fB%pure\-parser\fP,
параметр \fBYYLTYPE\fP добавляется к вызовам \fByylex()\fP.
.TP
\fB %lex\-param\fP { \fIargument-declaration\fP }
По умолчанию лексер не принимает параметров, например, \fByylex()\fP.
Используйте эту директиву, чтобы добавить объявления параметров для вашего
настроенного лексера.
.TP
\fB %parse\-param\fP { \fIargument-declaration\fP }
По умолчанию анализатор не принимает параметров, например, \fByyparse()\fP.
Используйте эту директиву, чтобы добавить объявления параметров для вашего
настроенного анализатора.
.TP
\fB %pure\-parser\fP
Большинство переменных (кроме \fByydebug\fP и \fByynerrs\fP)
размещаются в стеке внутри \fByyparse\fP, что делает анализатор достаточно
повторно входимым.
.TP
\fB %token\-table\fP
Сделать имена токенов анализатора доступными в массиве \fByytname\fP.
Однако
.B \*n
не предопределяет \*(``$end\*('', \*(``$error\*(''
или \*(``$undefined\*('' в этом массиве.
.
.SH ПЕРЕНОСИМОСТЬ
Согласно Robert Corbett,
.Ex
Berkeley Yacc — это генератор LALR(1)-анализаторов.  Berkeley Yacc
был сделан настолько совместимым с AT&T Yacc, насколько это возможно.
Berkeley Yacc может принимать любую входную спецификацию,
соответствующую документации AT&T Yacc.  Спецификации,
использующие недокументированные возможности AT&T Yacc,
вероятно, будут отклонены.
.Ee
.PP
Обоснование в
.Ex
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/yacc.html
.Ee
.PP
документирует некоторые возможности AT&T yacc, которые больше не требуются
для соответствия POSIX.
.PP
Тем не менее, вам может быть интересно повторно использовать файлы грамматик
с некоторой другой реализацией, которая не является строго совместимой с
AT&T yacc.
Например, есть bison.
Вот несколько различий:
.bP
\fBYacc\fP принимает знак равенства перед левой фигурной скобкой
действия (как в оригинальном файле грамматики \fBftp.y\fP):
.Ex
    |   STAT CRLF
        = {
                statcmd();
        }
.Ee
.bP
\fBYacc\fP и bison выдают код в разном порядке, и в частности bison
делает прямые ссылки на общие функции, такие как yylex, yyparse и
yyerror, не предоставляя прототипов.
.bP
Поддержка bison для \*(``%expect\*('' сломана более чем в одном выпуске.
Для лучших результатов при использовании bison удалите эту директиву.
.bP
В bison нет эквивалента для некоторых параметров командной строки \fB\*n\fP,
он полагается на директивы, встроенные в файл грамматики.
.bP
Параметр \*(``\fB\-y\fP\*('' в bison не влияет на отсутствие в bison поддержки
возможностей AT&T yacc, которые были признаны устаревающими.
.bP
\fBYacc\fP принимает несколько параметров
с \fB%lex\-param\fP и \fB%parse\-param\fP в двух формах
.Ex
{type1 name1} {type2 name2} ...
{type1 name1,  type2 name2 ...}
.Ee
.IP
Bison принимает последнюю (хотя и недокументированную), но в зависимости от
выпуска может генерировать плохой код.
.bP
Как и bison, \fB\*n\fP добавит параметры, указанные через \fB%parse\-param\fP,
к \fByyparse\fP, \fByyerror\fP и (если сконфигурирован для возвратов)
к деструктору, объявленному с помощью \fB%destructor\fP.
Bison размещает дополнительные параметры \fIfirst\fP для
\fByyparse\fP и \fByyerror\fP, но \fIlast\fP для деструкторов.
\fBYacc\fP соответствует этому поведению.
.
.SH СМ. ТАКЖЕ
\fBbison\fP(1),
\fBbtyacc\fP(1),
\fBlex\fP(1),
\fBflex\fP(1),
\fByacc\fP(1)
