#!/usr/bin/env sh
#
# Copyright (c) 2026 FreeBSD Russian Documentation Project
# Copyright (c) 2026 Vladlen Popolitov
#
# SPDX-License-Identifier: BSD-2-Clause
#
# man-tr-scan.sh -- scan a FreeBSD source tree and generate a metadata file.
#
# Walks the given source tree recursively, finds regular files whose
# name ends with one of the configured suffixes (default: .1), verifies
# that they are man pages, computes the SHA-256 hash of the file with
# comment lines removed, and writes a metadata file with four fields
# per line:
#
#   src_path|target_path|orig_hash|last_existed_orig_hash
#
# The first three fields come from the scan.  The fourth field is
# carried over from the previous version of the metadata file: if the
# previous file contains a line with the same (src_path, target_path),
# its fourth field is copied into the new line unchanged.  Otherwise
# the fourth field is set to orig_hash.
#
# Lines present in the previous file but absent from the new scan are
# not carried over.
#
# src_path is the path relative to the root of the source tree,
# without a leading "./".  target_path is "man<N>/<basename>", where
# <N> is the section number taken from the file suffix.
#
# Symlinks are ignored.  Only regular files are considered.
#
# Usage:
#   man-tr-scan.sh [-q] [-v] [-s <suffixes>] <src-dir> <meta-file>
#
# Options:
#   -q              Quiet: print nothing on success.
#   -v              Verbose: print each file as it is processed.
#   -s <suffixes>   Comma-separated list of section numbers to scan.
#                   Default: 1
#                   Example: -s 1,8
#
# Exit status:
#   0   success
#   1   usage error, missing source directory, or missing meta directory
#   2   one or more files could not be processed
#

set -u

usage() {
    cat <<EOF
Usage: $0 [-q] [-v] [-s <suffixes>] <src-dir> <meta-file>

Options:
  -q              Quiet: print nothing on success.
  -v              Verbose: print each file as it is processed.
  -s <suffixes>   Comma-separated list of section numbers to scan.
                  Default: 1

Only regular files are scanned.  Symlinks are ignored.
EOF
    exit 1
}

quiet=0
verbose=0
suffixes="1"

while [ $# -gt 0 ]; do
    case "$1" in
        -q)
            quiet=1
            shift
            ;;
        -v)
            verbose=1
            shift
            ;;
        -s)
            [ $# -ge 2 ] || usage
            suffixes=$2
            shift 2
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "$0: unknown option: $1" >&2
            usage
            ;;
        *)
            break
            ;;
    esac
done

if [ $# -ne 2 ]; then
    usage
fi

src_dir=$1
meta_file=$2

if [ ! -d "$src_dir" ]; then
    echo "$0: source directory does not exist: $src_dir" >&2
    exit 1
fi

meta_dir=$(dirname "$meta_file")
if [ ! -d "$meta_dir" ]; then
    echo "$0: meta directory does not exist: $meta_dir" >&2
    exit 1
fi

# Validate suffixes and build a find expression matching any of them.
save_ifs=$IFS
IFS=','
find_name_expr=""
for s in $suffixes; do
    case "$s" in
        [1-9]) ;;
        *)
            IFS=$save_ifs
            echo "$0: invalid suffix: $s (expected a single digit 1..9)" >&2
            exit 1
            ;;
    esac
    if [ -z "$find_name_expr" ]; then
        find_name_expr="-name *.$s"
    else
        find_name_expr="$find_name_expr -o -name *.$s"
    fi
done
IFS=$save_ifs

# Number of leading lines to inspect when checking for a man page.
header_lines=100

tmp_list=$(mktemp) || exit 1
tmp_old=$(mktemp) || exit 1
tmp_new=$(mktemp) || exit 1
trap 'rm -f "$tmp_list" "$tmp_old" "$tmp_new"' EXIT HUP INT TERM

# Snapshot of the previous metadata, used for the fourth-field merge.
# If the previous file does not exist, the snapshot stays empty, which
# is equivalent to "all lines are new".
if [ -f "$meta_file" ]; then
    cp -p "$meta_file" "$tmp_old"
fi

# Collect candidate files first, so that the processing loop runs in the
# main shell and the counters remain visible afterwards.
# shellcheck disable=SC2086
find "$src_dir" -type f \( $find_name_expr \) | LC_ALL=C sort > "$tmp_list"

found=0
written=0
failed=0

{
    echo "# Generated by man-tr-scan.sh. Do not edit manually."
    echo "# Format: src_path|target_path|orig_hash|last_existed_orig_hash|git_commit_hash"
} > "$tmp_new"

while IFS= read -r file; do
    found=$((found + 1))

    # Check that this is a man page: the first non-empty, non-comment
    # line must start with .Dd or .TH. or .nr 
    # Recognized starting macros:
    #   .Dd   -- mdoc (semantic markup)
    #   .TH   -- man (appearance-based markup)
    #   .nr   -- roff preamble (variable/macro definitions, e.g. from rst2man)
first_real=$(sed -n '
    1,'"$header_lines"'{
        /^\.TH[[:space:]]/p
        /^\.Dd[[:space:]]/p
    }
' "$file" 2>/dev/null | head -n 1)

    case "$first_real" in
        .Dd*|.TH*) ;;
        *)
            [ "$verbose" -eq 1 ] && echo "skip (not a man page): $file" >&2
            failed=$((failed + 1))
            continue
            ;;
    esac

    # Compute SHA-256 with comment lines removed.
    orig_hash=$(sed '/^\.\\"/d' "$file" | openssl dgst -sha256 | sed 's/^.*= //')

    if [ -z "$orig_hash" ]; then
        echo "$0: failed to compute hash for $file" >&2
        failed=$((failed + 1))
        continue
    fi

    # src_path: relative to src_dir, without a leading "./".
    rel=${file#"$src_dir"}
    rel=${rel#/}

    # target_path: man<N>/<basename>, N from the suffix.
    base=$(basename "$file")
    suffix=${base##*.}
    target="man$suffix/$base"

    # Fourth field: carry over from the previous metadata, if present.
    last=$(awk -F'|' -v s="$rel" -v t="$target" '
        $1 == s && $2 == t { print $4; exit }
    ' "$tmp_old")

    if [ -z "$last" ]; then
        last=$orig_hash
    fi

    git_hash=$(git -C "$src_dir" log -1 --pretty=format:%H -- "$rel" 2>/dev/null)
    printf '%s|%s|%s|%s|%s\n' "$rel" "$target" "$orig_hash" "$last" "$git_hash" >> "$tmp_new"
    written=$((written + 1))

    [ "$verbose" -eq 1 ] && echo "$rel -> $target"
done < "$tmp_list"

# Sort by src_path (field 1).
LC_ALL=C sort -t'|' -k1,1 "$tmp_new" -o "$tmp_new"

# Backup existing meta file, if any.
backup_made=0
if [ -e "$meta_file" ]; then
    rm -f "$meta_file.bak"
    cp -p "$meta_file" "$meta_file.bak"
    backup_made=1
fi

# Replace meta file atomically.
mv "$tmp_new" "$meta_file"

if [ "$quiet" -eq 0 ]; then
    echo "Scanning: $src_dir"
    echo "Suffixes: $suffixes"
    echo "Found:    $found files matching suffix"
    echo "Written:  $written lines to $meta_file"
    if [ "$backup_made" -eq 1 ]; then
        echo "Backup:   $meta_file.bak"
    fi
fi

if [ "$failed" -gt 0 ]; then
    exit 2
fi

exit 0
